In [3]:
# Importing relevant packages, modules, and functions

import KTBoost.KTBoost as KTBoost
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.optimize import minimize, BFGS
from numpy.polynomial.hermite import hermgauss
from scipy.special import logsumexp
from scipy.stats import chi2, norm
from numpy.linalg import inv, pinv
import time
import copy
from joblib import Parallel, delayed
import warnings
from sklearn.exceptions import ConvergenceWarning
from collections import Counter

# 1. Code for frailty models (time-independent frailties) and simulation study

###  1.1. Implementation of the objective function (negative marginal log-likelihood) using GHQ integration: Case of time-independent frailties
- See section 2.5.2.3
- In the codes 'individual' and 'group' mean the same thing
- We minimise the negatove log-likelihood, hence the minus at in front of the negative log-likelihood

In [2]:
def loglik_glmm_ghq_vectorized(params, X, y, groups, n_individuals, n_quad=20):

    beta = params[:-1]       # Extracting fixed effects
    log_sigma_u = params[-1]        # Taking log of frailty (i.e., std dev of frailty variance) - 
                                    # We use log(sigma_u) as input as it helps with unconstrained optimisation
    
    sigma_u = np.exp(log_sigma_u)       # Taking log back to make positive

    # Gauss-Hermite quadrature
    ghq_points, ghq_weights = hermgauss(n_quad)
    ghq_points = ghq_points[:, None] * np.sqrt(2) * sigma_u
    ghq_weights = ghq_weights / np.sqrt(np.pi)  # Normalisation

    # Linear predictors and response
    eta_fixed = np.asarray(X @ beta)[:, None]         # Shape (n_obs, 1)
    y = np.asarray(y)

    # Broadcast quadrature points
    eta_all = eta_fixed + ghq_points.T                # Shape (n_obs, n_quad)
    p_all = 1 / (1 + np.exp(-np.clip(eta_all, -30, 30)))  # Sigmoid function (clipped to avoid numerical problems)

    # vectorised log-likelihoods
    log_likelihoods = y[:, None] * np.log(p_all + 1e-8) + (1 - y[:, None]) * np.log(1 - p_all + 1e-8)

    # Safety check
    if np.max(groups) >= n_individuals:
        raise ValueError("Group indices exceed declared number of individuals. Check group encoding.")

    # Aggregating per group (i.e. individual)
    loglik_per_observation = np.zeros((n_individuals, n_quad))
    np.add.at(loglik_per_observation, groups, log_likelihoods)

    # Integrating with log-sum-exp
    loglik_per_individual = logsumexp(loglik_per_observation, b=ghq_weights, axis=1)

    return -np.sum(loglik_per_individual)

###  1.2.  Implementation of the objective function (expected complete-data negative log-likelihood) using the an adaptation of the EM algorithm  (see section 2.5.3.3.1) of my thesis

In [3]:
# def em_logistic_glmm(X, y, groups, n_quad=20, max_iter=1000, tol=1e-5, verbose=True):
def em_logistic_glmm_check(X, y, groups, n_quad=20, max_iter=1000, tol=1e-5, verbose=False):

    # Initialisation of dimensions
    n_obs, p = X.shape
    unique_groups, group_idx = np.unique(groups, return_inverse=True)
    n_groups = len(unique_groups)

    # Setting Initial values of beta through logistic regression (LLink)
    init_model = LogisticRegression(penalty=None, solver='lbfgs', max_iter=1000)
    init_model.fit(X, y)
    beta = init_model.coef_.flatten()

    # Initialising sigma_u using residual values
    eta = X @ beta
    sigma_u = np.std(eta - eta.mean())

    # Gauss-Hermite quadrature nodes and weights
    gh_x, gh_w = hermgauss(n_quad)
    gh_x = gh_x * np.sqrt(2)
    gh_w = gh_w / np.sqrt(np.pi)

    loglik_trace = []
    start_time = time.time()
    

    for iteration in range(max_iter):
        # ----- E-Step -----
        # Computing linear predictors (vectorised)
        eta_fixed = X @ beta
        eta_fixed_q = np.repeat(eta_fixed[:, None], n_quad, axis=1)  # (n_obs, n_quad)
        u_q = sigma_u * gh_x  # (n_quad,)
        eta_all = eta_fixed_q + u_q  # vectorising to (n_obs, n_quad)
        eta_all = np.clip(eta_all, -30, 30)

        # Computing probabilities with LLink 
        p_all = 1 / (1 + np.exp(-eta_all))  # (n_obs, n_quad)

        # Compute log-likelihood contributions: (n_obs, n_quad)
        ll_obs_q = y[:, None] * np.log(p_all + 1e-8) + (1 - y[:, None]) * np.log(1 - p_all + 1e-8)

        # Suming within each group
        ll_group_q = np.zeros((n_groups, n_quad))
        np.add.at(ll_group_q, group_idx, ll_obs_q)

        # Computing log p(y_i | u_q) + log g(u_q)
        
        log_weights = ll_group_q + (-0.5 * (u_q**2))[None, :]  # (n_groups, n_quad) | This computes the numerator in log-space
        log_weights = log_weights - logsumexp(log_weights, axis=1, keepdims=True)  # normalisation | This line subtracts the 
#         log-sum-exp over quadrature nodes q for each individual i
        weights = np.exp(log_weights)  # posterior weights w_{iq} | In general this is what is being computed :
#          exp(log(x) - logsumexp(x)). This helps with numerical stability

        # ----- M-Step -----
        # Setting up the objective function for the expected complete-data negative log-likelihood
        def mstep_objective(params):
            beta_new = params[:-1]
            sigma_log = params[-1]
            sigma_new = np.exp(sigma_log)

            eta = X @ beta_new
            eta_q = eta[:, None] + sigma_new * gh_x[None, :]
            eta_q = np.clip(eta_q, -30, 30)
            p_q = 1 / (1 + np.exp(-eta_q))

            ll_obs_q = y[:, None] * np.log(p_q + 1e-8) + (1 - y[:, None]) * np.log(1 - p_q + 1e-8)

            ll_group_q = np.zeros((n_groups, n_quad)) 
            np.add.at(ll_group_q, group_idx, ll_obs_q)  

            # Expected log-likelihood
            expected_ll = np.sum(weights * ll_group_q) # First part of integral 
            # Adding E[log g(u)] term
            expected_ll += -0.5 * np.sum(weights * (gh_x[None, :]**2)) # Adding first to second part of integral 

            return -expected_ll  # minimising expected complete-data negative log-likelihood

        # Optimisation of the parameters in the M-step
        res = minimize(
            mstep_objective,
            x0=np.append(beta, np.log(sigma_u)),
            method='L-BFGS-B',
            options={'verbose':1}
        )

        # Updating parameters
        beta_new = res.x[:-1]
        sigma_new = np.exp(res.x[-1])
        loglik_trace.append(-res.fun)

        # Convergence check
        if iteration > 0:
            if np.linalg.norm(beta_new - beta) < tol and abs(sigma_new - sigma_u) < tol:
                if verbose:
                    print(f"✅ Converged at iteration {iteration}")
                break

        beta = beta_new
        sigma_u = sigma_new
        if verbose:
            print(f"Iter {iteration}: sigma_u = {sigma_u:.4f}, loglik = {loglik_trace[-1]:.4f}")
            
        if time.time() - start_time > 120:  # every 2 minutes
            print(f"Iteration {iteration}: beta norm = {np.linalg.norm(beta)}, sigma_u = {sigma_u:.4f}")
            start_time = time.time()

    return beta, sigma_u, loglik_trace, res

### 1.3 Code for simulation study

In [4]:
# List to save final estimates from the simulation study below
B_Res_simul_synth3 = []


# Setting up the list of (true) fixed effects parameters
vec_beta_true=[np.array([0.5, 0.5, -1.2]), np.array([1.5, -0.8, 1.3]), np.array([-1.438,  4.847, -0.444]),
               np.array([ 1.476, -0.151, -1.735]),np.array([2.5, 0.45,  0.25, -1.2]),
               np.array([0.8, -0.9 , 0.5, -1.7]),
              np.array([1.8, -2.1 , -0.5, -1.7]), np.array([-1.24,  1.17, -1.04,  0.97])]



for sigmm in [0.25, 0.8, 1.2, 2.5]: # Set of true Frailty standard deviation 
    
    Res_simul_synth3=[]
    
    for beta_true in vec_beta_true[:]: # Loop over set fixed parameters


        tstart = time.time()


        print('Initial sigma:',sigmm)
        
#  ---------------------------------- PART 1 : Data genertating process ---------------------------
        

        # Simulate data in a longitudinal format
        np.random.seed(42)

        n_individuals = 10000
        obs_per_individual = np.random.randint(1, 6, size=n_individuals)  # Individuals may have between 1 and
#         6 observations (number of observation are assigned randomly per individual)
        n_obs = np.sum(obs_per_individual)  

        # True random effect standard deviation (frailty)
        sigma_u_true = sigmm

        # Generate random effects (frailty) per individual
        u = np.random.normal(0, sigma_u_true, size=n_individuals)

        # Generate fixed covariates
        
        if len(beta_true)==3:
            X1 = np.random.uniform(-2, 2, size=n_obs)  
            X2 = np.random.choice([0, 1], size=n_obs)
            
        elif len(beta_true)==4:
            X1 = np.random.uniform(-2, 2, size=n_obs)  
            X2 = np.random.choice([0, 1], size=n_obs) 
            X3 = np.random.gamma(1.2, .6, size=n_obs)

        # Assign ids to individuals to be able to track them
        individual_ids = np.repeat(np.arange(n_individuals), obs_per_individual)

        
        # Generate linear predictor and probabilities
        if len(beta_true)==3:
        
            eta = beta_true[0] + beta_true[1] * X1 + beta_true[2] * X2 + u[individual_ids] 
            p = 1 / (1 + np.exp(-eta))  
            
        elif len(beta_true)==4:
            eta = beta_true[0] + beta_true[1] * X1 + beta_true[2] * X2 + beta_true[3] * X3 + u[individual_ids] 
            p = 1 / (1 + np.exp(-eta))  

        



        # Generate binary responses
        y = np.random.binomial(1, p, size=n_obs)

        # Create DataFrame
        # 
        

        # Step 2: Prepare data for optimization
        if len(beta_true)==3:
            df = pd.DataFrame({'y': y, 'X1': X1, 'X2': X2, 'individual': individual_ids})
            X = sm.add_constant(df[['X1', 'X2']])  
            
        elif len(beta_true)==4:
            df = pd.DataFrame({'y': y, 'X1': X1, 'X2': X2, 'X3': X3, 'individual': individual_ids})
            X = sm.add_constant(df[['X1', 'X2', 'X3']])
            
            
        else:
            print("Issue for beta",beta_true)
            
        y = df['y'].values
        # Ensure individual IDs are mapped to sequential indices
        unique_ids, groups = np.unique(df['individual'].values, return_inverse=True)

        # Update n_individuals based on unique IDs
        n_individuals = len(unique_ids)




# -------------------------------- End of part 1 (ata genertating process) ---------------------------
        
        
# ------------------------------------ Part 2: Recovering the true parameters using GHQ/EM ------------------
        
#  Fitting a fixed effects LLink model to the data (i.e. X)

        model_logis = LogisticRegression(penalty="none")
        model_logis.fit(X.values,y)

        init_model = LogisticRegression(penalty=None, solver='lbfgs', max_iter=1000)
        init_model.fit(X, y)
        
#         Extracting the parameters estimates (i.e. fixed effects) of the model 
        init_params_better = init_model.coef_.flatten()

        # Extracting predicted probabilities on the train set to generate some statistics 
        predicted_probs = model_logis.predict_proba(X)[:,1]

        # Log-likelihood
        loglik_reduced = np.sum(y * np.log(predicted_probs + 1e-8) + (1 - y) * np.log(1 - predicted_probs + 1e-8))


        # Extract initial estimates for fixed effects
        beta_init = model_logis.coef_[0]


        # Step 5: Initialize sigma_u using residual standard deviation from the fixed effects model
        residuals = y - predicted_probs
        sigma_u_init = np.std(residuals)
        log_sigma_u_init = np.log(sigma_u_init + 1e-4)

        init_params_better = np.append(beta_init, log_sigma_u_init) 

        # ------------------------------ Optimisation time-independent frailty model ---------------------


        # RUnning GHQ optimisation
        result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals), 
                                method="L-BFGS-B", options={'maxiter': 1000,  'verbose': 1},
                               jac='2-point')

        loglik_full = -result_full.fun  

        # Step 6: Compute LRT and RLRT for sigma_u
        num_fixed_params = len(result_full.x) - 1
        p_values_fixed = np.full(num_fixed_params + 1, np.nan)  

        # Extracting hessian
        hessian = sm.tools.numdiff.approx_hess(result_full.x, loglik_glmm_ghq_vectorized, args=(X, y, groups,
                                                                                               n_individuals))
        
        # Extracting standard error if scalar
        if np.linalg.matrix_rank(hessian) == hessian.shape[0]:
            se_glmm = np.sqrt(np.diag(inv(hessian)))[:-1]  
        else:
            se_glmm = np.sqrt(np.diag(pinv(hessian)))[:-1]

        # Computing pvalues
        if n_individuals > 100:
            p_values_fixed[:-1] = 2 * (1 - norm.cdf(np.abs(result_full.x[:-1] / se_glmm)))  # Wald test
        else:
            p_values_fixed[:-1] = np.nan  # Placeholder for small samples


        # Displaying some results ()
        dataframe_synth = pd.DataFrame({
            'Parameter': list(df.columns[1:]) + ['Sigma_u'],
            'Estimate (LLink_with_GHQ)': np.append(result_full.x[:-1], np.exp(result_full.x[-1]))
        })
#         print(dataframe_synth,'\n')

        #  Running EM optimisation
        
        tp_beta_hat_EM_ori_singl, tp_sigma_u_hat_EM_ori_singl, tp_vec_ll_trace_EM_ori_singl, tp_res_ =\
        em_logistic_glmm_check(X.values, y, groups, n_quad=20, verbose=True)

        dataframe_synth_EM = pd.DataFrame({
            'Parameter': list(df.columns[1:]) + ['Sigma_u'],
            'Estimate (LLink_with_EM)': np.append(tp_beta_hat_EM_ori_singl, tp_sigma_u_hat_EM_ori_singl)
        })
    
        
        
#         print(dataframe_synth_EM,'\n')

        dataframe_synth_f = pd.DataFrame([np.append(beta_true,sigmm),
                                          dataframe_synth['Estimate (LLink_with_GHQ)'],
                                          dataframe_synth_EM['Estimate (LLink_with_EM)']]).T

        dataframe_synth_f.columns = ['True parameters','Estimates GHQ', 'Estimate EM']

        print('Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):\n')
        
        print(dataframe_synth_f,'\n\n\n')
    
        Res_simul_synth3.append([dataframe_synth_f, result_full, tp_res_])

        tstop = time.time()

        print('Time taken', (tstop-tstart)/60., 'minutes\n\n\n')
        
    B_Res_simul_synth3.append(Res_simul_synth3)

Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.6405, loglik = -24091.2405
Iter 1: sigma_u = 0.5106, loglik = -27968.6120
Iter 2: sigma_u = 0.4081, loglik = -33878.2678
Iter 3: sigma_u = 0.3278, loglik = -42458.4074
Iter 4: sigma_u = 0.2657, loglik = -53702.4883
Iter 5: sigma_u = 0.2190, loglik = -66086.0503
Iter 6: sigma_u = 0.1848, loglik = -77271.0626
Iter 7: sigma_u = 0.1602, loglik = -85886.3326
Iter 8: sigma_u = 0.1423, loglik = -91969.0863
Iter 9: sigma_u = 0.1290, loglik = -96161.1492
Iter 10: sigma_u = 0.1189, loglik = -99084.8627
Iter 11: sigma_u = 0.1110, loglik = -101176.4496
Iter 12: sigma_u = 0.1047, loglik = -102717.4256
Iter 13: sigma_u = 0.0996, loglik = -103884.0169
Iter 14: sigma_u = 0.0954, loglik = -104788.8208
Iter 15: sigma_u = 0.0919, loglik = -105505.5209
Iter 16: sigma_u = 0.0889, loglik = -106083.6375
Iter 17: sigma_u = 0.0864, loglik = -106557.2567
Iter 18: sigma_u = 0.0842, loglik = -106950.4936
Iter 19: sigma_u = 0.0823, loglik = -107281.1429
Iter 20: sigma_u = 0.0806, loglik = -107561.7988
Iter 21: sigma_u = 0.0792, loglik = -107801.8066
Iter 22: sigma_u = 0.0779, loglik = -108008.7503
Iter 23: sigma_u = 0.0767, loglik = -108188.3057
Iter 24: sigma_u = 0.0757, loglik = -108345.1214
Iter 25: sigma_u = 0.0748, loglik = -108482.8453
Iter 26: sigma_u = 0.0740, loglik = -108603.8867
Iter 27: sigma_u = 0.0733, loglik = -108711.5931
Iter 28: sigma_u = 0.0726, loglik = -108807.0298
Iter 29: sigma_u = 0.0720, loglik = -108892.4214
Iter 30: sigma_u = 0.0715, loglik = -108968.9569
Iter 31: sigma_u = 0.0710, loglik = -109038.5095
Iter 32: sigma_u = 0.0706, loglik = -109100.8416
Iter 33: sigma_u = 0.0702, loglik = -109156.3907
Iter 34: sigma_u = 0.0698, loglik = -109206.3849
Iter 35: sigma_u = 0.0695, loglik = -109251.6026
Iter 36: sigma_u = 0.0692, loglik = -109292.5687
Iter 37: sigma_u = 0.0688, loglik = -109329.7631
Iter 38: sigma_u = 0.0686, loglik = -109373.2801
Iter 39: sigma_u = 0.0683, loglik = -109403.2463
Iter 40: sigma_u = 0.0681, loglik = -109437.8486
Iter 41: sigma_u = 0.0679, loglik = -109467.6380
Iter 42: sigma_u = 0.0677, loglik = -109492.9587
Iter 43: sigma_u = 0.0676, loglik = -109513.2947
Iter 44: sigma_u = 0.0674, loglik = -109528.6951
Iter 45: sigma_u = 0.0673, loglik = -109545.9889
Iter 46: sigma_u = 0.0672, loglik = -109561.4356
Iter 47: sigma_u = 0.0671, loglik = -109573.3684
Iter 48: sigma_u = 0.0670, loglik = -109586.7537
Iter 49: sigma_u = 0.0669, loglik = -109597.8665
Iter 50: sigma_u = 0.0668, loglik = -109607.1289
Iter 51: sigma_u = 0.0668, loglik = -109616.5111
Iter 52: sigma_u = 0.0667, loglik = -109624.7891
Iter 53: sigma_u = 0.0666, loglik = -109632.5092
Iter 54: sigma_u = 0.0666, loglik = -109638.6695
Iter 55: sigma_u = 0.0666, loglik = -109639.2591
Iter 56: sigma_u = 0.0666, loglik = -109640.9125
Iter 57: sigma_u = 0.0666, loglik = -109641.4824
Iter 58: sigma_u = 0.0666, loglik = -109643.4335
Iter 59: sigma_u = 0.0666, loglik = -109643.9772
Iter 60: sigma_u = 0.0666, loglik = -109646.1881
Iter 61: sigma_u = 0.0666, loglik = -109646.7027
Iter 62: sigma_u = 0.0666, loglik = -109649.2466
Iter 63: sigma_u = 0.0665, loglik = -109649.7339
Iter 64: sigma_u = 0.0665, loglik = -109652.5301
Iter 65: sigma_u = 0.0665, loglik = -109652.9921
Iter 66: sigma_u = 0.0665, loglik = -109655.9641
Iter 67: sigma_u = 0.0665, loglik = -109656.4011
Iter 68: sigma_u = 0.0665, loglik = -109659.4063
Iter 69: sigma_u = 0.0664, loglik = -109659.8194
Iter 70: sigma_u = 0.0664, loglik = -109663.0433
Iter 71: sigma_u = 0.0664, loglik = -109663.4343
Iter 72: sigma_u = 0.0664, loglik = -109666.5152
Iter 73: sigma_u = 0.0664, loglik = -109666.8844
Iter 74: sigma_u = 0.0664, loglik = -109669.9120
Iter 75: sigma_u = 0.0664, loglik = -109670.2593
Iter 76: sigma_u = 0.0663, loglik = -109673.2483
Iter 77: sigma_u = 0.0663, loglik = -109673.5790
Iter 78: sigma_u = 0.0663, loglik = -109676.3767
Iter 79: sigma_u = 0.0663, loglik = -109676.6888
Iter 80: sigma_u = 0.0663, loglik = -109679.2945
Iter 81: sigma_u = 0.0663, loglik = -109679.5886
Iter 82: sigma_u = 0.0663, loglik = -109682.1059
Iter 83: sigma_u = 0.0663, loglik = -109682.3839
Iter 84: sigma_u = 0.0663, loglik = -109684.7710
Iter 85: sigma_u = 0.0662, loglik = -109685.0347
Iter 86: sigma_u = 0.0662, loglik = -109687.1890
Iter 87: sigma_u = 0.0662, loglik = -109687.4400
Iter 88: sigma_u = 0.0662, loglik = -109689.4435
Iter 89: sigma_u = 0.0662, loglik = -109689.6796
Iter 90: sigma_u = 0.0662, loglik = -109691.7296
Iter 91: sigma_u = 0.0662, loglik = -109691.9543
Iter 92: sigma_u = 0.0662, loglik = -109693.9020
Iter 93: sigma_u = 0.0662, loglik = -109694.1130
Iter 94: sigma_u = 0.0662, loglik = -109695.9897
Iter 95: sigma_u = 0.0661, loglik = -109696.1879
Iter 96: sigma_u = 0.0661, loglik = -109697.9091
Iter 97: sigma_u = 0.0661, loglik = -109698.0972
Iter 98: sigma_u = 0.0661, loglik = -109699.6865
Iter 99: sigma_u = 0.0661, loglik = -109699.8650
Iter 100: sigma_u = 0.0661, loglik = -109701.4419
Iter 101: sigma_u = 0.0661, loglik = -109701.6086
Iter 102: sigma_u = 0.0661, loglik = -109703.1687
Iter 103: sigma_u = 0.0661, loglik = -109703.3256
Iter 104: sigma_u = 0.0661, loglik = -109704.6607
Iter 105: sigma_u = 0.0661, loglik = -109704.8095
Iter 106: sigma_u = 0.0661, loglik = -109706.0000
Iter 107: sigma_u = 0.0661, loglik = -109706.1414
Iter 108: sigma_u = 0.0661, loglik = -109707.3346
Iter 109: sigma_u = 0.0661, loglik = -109707.4674
Iter 110: sigma_u = 0.0661, loglik = -109708.7281
Iter 111: sigma_u = 0.0660, loglik = -109708.8559
Iter 112: sigma_u = 0.0660, loglik = -109709.9803
Iter 113: sigma_u = 0.0660, loglik = -109710.0995
Iter 114: sigma_u = 0.0660, loglik = -109711.1418
Iter 115: sigma_u = 0.0660, loglik = -109711.2543
Iter 116: sigma_u = 0.0660, loglik = -109712.2436
Iter 117: sigma_u = 0.0660, loglik = -109712.3483
Iter 118: sigma_u = 0.0660, loglik = -109713.2966
Iter 119: sigma_u = 0.0660, loglik = -109713.3953
Iter 120: sigma_u = 0.0660, loglik = -109714.3172
Iter 121: sigma_u = 0.0660, loglik = -109714.4118
Iter 122: sigma_u = 0.0660, loglik = -109715.3147
Iter 123: sigma_u = 0.0660, loglik = -109715.4034
Iter 124: sigma_u = 0.0660, loglik = -109716.1417
Iter 125: sigma_u = 0.0660, loglik = -109716.2252
Iter 126: sigma_u = 0.0660, loglik = -109716.9763
Iter 127: sigma_u = 0.0660, loglik = -109717.0582
Iter 128: sigma_u = 0.0660, loglik = -109717.6590
Iter 129: sigma_u = 0.0660, loglik = -109717.7368
Iter 130: sigma_u = 0.0660, loglik = -109718.3950
Iter 131: sigma_u = 0.0660, loglik = -109718.4673
Iter 132: sigma_u = 0.0660, loglik = -109719.0297
Iter 133: sigma_u = 0.0660, loglik = -109719.0967
Iter 134: sigma_u = 0.0660, loglik = -109719.7968
Iter 135: sigma_u = 0.0660, loglik = -109719.8618
Iter 136: sigma_u = 0.0660, loglik = -109720.4262
Iter 137: sigma_u = 0.0660, loglik = -109720.4882
Iter 138: sigma_u = 0.0659, loglik = -109720.9412
Iter 139: sigma_u = 0.0659, loglik = -109721.0005
Iter 140: sigma_u = 0.0659, loglik = -109721.4077
Iter 141: sigma_u = 0.0659, loglik = -109721.4646
Iter 142: sigma_u = 0.0659, loglik = -109721.8642
Iter 143: sigma_u = 0.0659, loglik = -109721.9156
Iter 144: sigma_u = 0.0659, loglik = -109722.4257
Iter 145: sigma_u = 0.0659, loglik = -109722.4761
Iter 146: sigma_u = 0.0659, loglik = -109722.8632
Iter 147: sigma_u = 0.0659, loglik = -109722.9098
Iter 148: sigma_u = 0.0659, loglik = -109723.3951
Iter 149: sigma_u = 0.0659, loglik = -109723.4402
Iter 150: sigma_u = 0.0659, loglik = -109723.8283
Iter 151: sigma_u = 0.0659, loglik = -109723.8693
Iter 152: sigma_u = 0.0659, loglik = -109724.2312
Iter 153: sigma_u = 0.0659, loglik = -109724.2721
Iter 154: sigma_u = 0.0659, loglik = -109724.6575
Iter 155: sigma_u = 0.0659, loglik = -109724.6916
✅ Converged at iteration 156
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             0.50       0.483874     0.483761
1             0.50       0.480457     0.480386
2            -1.20      -1.199890    -1.199755
3             0.25       0.283866     0.065916



Time taken 1.8138797481854756 minutes



Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.9962, loglik = -13205.1841
Iter 1: sigma_u = 0.8433, loglik = -14473.0465
Iter 2: sigma_u = 0.7131, loglik = -16357.5773
Iter 3: sigma_u = 0.6032, loglik = -18947.7470
Iter 4: sigma_u = 0.5107, loglik = -22480.5329
Iter 5: sigma_u = 0.4331, loglik = -27237.0999
Iter 6: sigma_u = 0.3683, loglik = -33478.2192
Iter 7: sigma_u = 0.3145, loglik = -41251.6431
Iter 8: sigma_u = 0.2706, loglik = -50103.6407
Iter 9: sigma_u = 0.2352, loglik = -59081.2511
Iter 10: sigma_u = 0.2071, loglik = -67219.1726
Iter 11: sigma_u = 0.1848, loglik = -74003.2714
Iter 12: sigma_u = 0.1670, loglik = -79394.7274
Iter 13: sigma_u = 0.1525, loglik = -83595.7500
Iter 14: sigma_u = 0.1407, loglik = -86863.6691
Iter 15: sigma_u = 0.1309, loglik = -89426.1501
Iter 16: sigma_u = 0.1226, loglik = -91459.9992
Iter 17: sigma_u = 0.1155, loglik = -93096.0639
Iter 18: sigma_u = 0.1094, loglik = -94428.9435
Iter 19: sigma_u = 0.1041, loglik = -95531.4434
Iter 20: sigma_u = 0.0994, loglik = -96454.2994
Iter 21: sigma_u = 0.0952, loglik = -97235.3424
Iter 22: sigma_u = 0.0915, loglik = -97903.1073
Iter 23: sigma_u = 0.0882, loglik = -98479.1493
Iter 24: sigma_u = 0.0852, loglik = -98980.3971
Iter 25: sigma_u = 0.0824, loglik = -99419.7986
Iter 26: sigma_u = 0.0799, loglik = -99807.7015
Iter 27: sigma_u = 0.0776, loglik = -100152.2913
Iter 28: sigma_u = 0.0755, loglik = -100460.1482
Iter 29: sigma_u = 0.0735, loglik = -100736.6932
Iter 30: sigma_u = 0.0717, loglik = -100986.2592
Iter 31: sigma_u = 0.0700, loglik = -101212.5290
Iter 32: sigma_u = 0.0684, loglik = -101418.5126
Iter 33: sigma_u = 0.0669, loglik = -101606.7298
Iter 34: sigma_u = 0.0655, loglik = -101779.3649
Iter 35: sigma_u = 0.0642, loglik = -101938.1736
Iter 36: sigma_u = 0.0629, loglik = -102086.6229
Iter 37: sigma_u = 0.0618, loglik = -102223.7025
Iter 38: sigma_u = 0.0606, loglik = -102350.7891
Iter 39: sigma_u = 0.0596, loglik = -102468.8069
Iter 40: sigma_u = 0.0586, loglik = -102578.8283
Iter 41: sigma_u = 0.0576, loglik = -102681.4628
Iter 42: sigma_u = 0.0567, loglik = -102777.5257
Iter 43: sigma_u = 0.0559, loglik = -102867.5960
Iter 44: sigma_u = 0.0550, loglik = -102952.0969
Iter 45: sigma_u = 0.0542, loglik = -103031.7189
Iter 46: sigma_u = 0.0535, loglik = -103106.7038
Iter 47: sigma_u = 0.0528, loglik = -103177.5566
Iter 48: sigma_u = 0.0521, loglik = -103244.5233
Iter 49: sigma_u = 0.0514, loglik = -103307.8063
Iter 50: sigma_u = 0.0508, loglik = -103367.9597
Iter 51: sigma_u = 0.0502, loglik = -103424.9258
Iter 52: sigma_u = 0.0496, loglik = -103476.7699
Iter 53: sigma_u = 0.0490, loglik = -103528.9166
Iter 54: sigma_u = 0.0485, loglik = -103578.1680
Iter 55: sigma_u = 0.0479, loglik = -103623.9330
Iter 56: sigma_u = 0.0474, loglik = -103667.8842
Iter 57: sigma_u = 0.0469, loglik = -103710.4656
Iter 58: sigma_u = 0.0464, loglik = -103751.5964
Iter 59: sigma_u = 0.0459, loglik = -103792.7643
Iter 60: sigma_u = 0.0455, loglik = -103830.2044
Iter 61: sigma_u = 0.0451, loglik = -103866.4566
Iter 62: sigma_u = 0.0447, loglik = -103899.6498
Iter 63: sigma_u = 0.0443, loglik = -103931.8995
Iter 64: sigma_u = 0.0439, loglik = -103962.7932
Iter 65: sigma_u = 0.0436, loglik = -103988.3586
Iter 66: sigma_u = 0.0432, loglik = -104016.4721
Iter 67: sigma_u = 0.0428, loglik = -104045.1109
Iter 68: sigma_u = 0.0425, loglik = -104072.1907
Iter 69: sigma_u = 0.0421, loglik = -104097.0314
Iter 70: sigma_u = 0.0418, loglik = -104123.2941
Iter 71: sigma_u = 0.0414, loglik = -104148.4355
Iter 72: sigma_u = 0.0410, loglik = -104180.3351
Iter 73: sigma_u = 0.0406, loglik = -104203.5864
Iter 74: sigma_u = 0.0403, loglik = -104232.6859
Iter 75: sigma_u = 0.0403, loglik = -104254.5548
Iter 76: sigma_u = 0.0403, loglik = -104255.6961
Iter 77: sigma_u = 0.0400, loglik = -104256.0826
Iter 78: sigma_u = 0.0396, loglik = -104276.8168
Iter 79: sigma_u = 0.0394, loglik = -104303.3951
Iter 80: sigma_u = 0.0391, loglik = -104322.6262
Iter 81: sigma_u = 0.0389, loglik = -104340.4854
Iter 82: sigma_u = 0.0389, loglik = -104351.4767
Iter 83: sigma_u = 0.0387, loglik = -104352.0672
Iter 84: sigma_u = 0.0384, loglik = -104370.4696
Iter 85: sigma_u = 0.0382, loglik = -104385.9493
Iter 86: sigma_u = 0.0379, loglik = -104402.9305
Iter 87: sigma_u = 0.0377, loglik = -104419.4440
Iter 88: sigma_u = 0.0374, loglik = -104435.6814
Iter 89: sigma_u = 0.0371, loglik = -104451.3311
Iter 90: sigma_u = 0.0371, loglik = -104471.4820
Iter 91: sigma_u = 0.0371, loglik = -104472.2936
Iter 92: sigma_u = 0.0371, loglik = -104472.5063
Iter 93: sigma_u = 0.0371, loglik = -104474.0534
Iter 94: sigma_u = 0.0369, loglik = -104474.2188
Iter 95: sigma_u = 0.0366, loglik = -104488.7608
Iter 96: sigma_u = 0.0366, loglik = -104503.5788
Iter 97: sigma_u = 0.0366, loglik = -104503.8164
Iteration 97: beta norm = 2.178953470287349, sigma_u = 0.0366
Iter 98: sigma_u = 0.0366, loglik = -104504.4916
Iter 99: sigma_u = 0.0366, loglik = -104504.6983
Iter 100: sigma_u = 0.0366, loglik = -104505.8030
Iter 101: sigma_u = 0.0364, loglik = -104505.9680
Iter 102: sigma_u = 0.0361, loglik = -104519.7330
Iter 103: sigma_u = 0.0361, loglik = -104537.6079
Iter 104: sigma_u = 0.0361, loglik = -104538.7750
Iter 105: sigma_u = 0.0361, loglik = -104538.9418
Iter 106: sigma_u = 0.0361, loglik = -104540.5014
Iter 107: sigma_u = 0.0359, loglik = -104540.6373
Iter 108: sigma_u = 0.0356, loglik = -104553.5436
Iter 109: sigma_u = 0.0356, loglik = -104570.2999
Iter 110: sigma_u = 0.0356, loglik = -104572.0384
Iter 111: sigma_u = 0.0356, loglik = -104572.2349
Iter 112: sigma_u = 0.0356, loglik = -104572.7125
Iter 113: sigma_u = 0.0355, loglik = -104572.9002
Iter 114: sigma_u = 0.0355, loglik = -104573.5959
Iter 115: sigma_u = 0.0355, loglik = -104573.7487
Iter 116: sigma_u = 0.0355, loglik = -104575.3442
Iter 117: sigma_u = 0.0353, loglik = -104575.4611
Iter 118: sigma_u = 0.0352, loglik = -104591.6008
Iter 119: sigma_u = 0.0352, loglik = -104592.2402
Iter 120: sigma_u = 0.0352, loglik = -104592.3863
Iter 121: sigma_u = 0.0352, loglik = -104593.7711
Iter 122: sigma_u = 0.0350, loglik = -104593.8837
Iter 123: sigma_u = 0.0350, loglik = -104609.0362
Iter 124: sigma_u = 0.0349, loglik = -104610.1922
Iter 125: sigma_u = 0.0349, loglik = -104610.3730
Iter 126: sigma_u = 0.0349, loglik = -104611.1855
Iter 127: sigma_u = 0.0349, loglik = -104611.3777
Iter 128: sigma_u = 0.0349, loglik = -104612.0579
Iter 129: sigma_u = 0.0349, loglik = -104612.2496
Iter 130: sigma_u = 0.0349, loglik = -104612.8378
Iter 131: sigma_u = 0.0349, loglik = -104613.0355
Iter 132: sigma_u = 0.0349, loglik = -104613.5634
Iter 133: sigma_u = 0.0349, loglik = -104613.7652
Iter 134: sigma_u = 0.0349, loglik = -104614.2294
Iter 135: sigma_u = 0.0349, loglik = -104614.4376
Iter 136: sigma_u = 0.0349, loglik = -104614.8563
Iter 137: sigma_u = 0.0349, loglik = -104615.0713
Iter 138: sigma_u = 0.0349, loglik = -104615.4466
Iter 139: sigma_u = 0.0349, loglik = -104615.6742
Iter 140: sigma_u = 0.0349, loglik = -104616.0038
Iter 141: sigma_u = 0.0348, loglik = -104616.2463
Iter 142: sigma_u = 0.0348, loglik = -104616.5332
Iter 143: sigma_u = 0.0348, loglik = -104616.7999
Iter 144: sigma_u = 0.0348, loglik = -104617.0483
Iter 145: sigma_u = 0.0348, loglik = -104617.3493
Iter 146: sigma_u = 0.0348, loglik = -104617.5628
Iter 147: sigma_u = 0.0348, loglik = -104617.9212
Iter 148: sigma_u = 0.0348, loglik = -104618.1021
Iter 149: sigma_u = 0.0348, loglik = -104618.5764
Iter 150: sigma_u = 0.0348, loglik = -104618.7262
Iter 151: sigma_u = 0.0348, loglik = -104619.5321
Iter 152: sigma_u = 0.0346, loglik = -104619.6514
Iter 153: sigma_u = 0.0344, loglik = -104630.6867
Iter 154: sigma_u = 0.0344, loglik = -104645.0213
Iter 155: sigma_u = 0.0344, loglik = -104646.4062
Iter 156: sigma_u = 0.0343, loglik = -104646.6000
Iter 157: sigma_u = 0.0343, loglik = -104646.8836
Iter 158: sigma_u = 0.0343, loglik = -104647.0723
Iter 159: sigma_u = 0.0343, loglik = -104647.4205
Iter 160: sigma_u = 0.0343, loglik = -104647.5798
Iter 161: sigma_u = 0.0343, loglik = -104648.0527
Iter 162: sigma_u = 0.0343, loglik = -104648.1836
Iter 163: sigma_u = 0.0343, loglik = -104649.0647
Iter 164: sigma_u = 0.0341, loglik = -104649.1679
Iter 165: sigma_u = 0.0339, loglik = -104659.5431

Iter 166: sigma_u = 0.0339, loglik = -104673.1129
Iter 167: sigma_u = 0.0339, loglik = -104675.7183
Iter 168: sigma_u = 0.0339, loglik = -104675.7983
Iter 169: sigma_u = 0.0339, loglik = -104676.3099
Iter 170: sigma_u = 0.0339, loglik = -104676.4837
Iter 171: sigma_u = 0.0338, loglik = -104676.7894
Iter 172: sigma_u = 0.0338, loglik = -104676.9386
Iter 173: sigma_u = 0.0338, loglik = -104677.3441
Iter 174: sigma_u = 0.0338, loglik = -104677.4673
Iter 175: sigma_u = 0.0338, loglik = -104678.1757
Iter 176: sigma_u = 0.0337, loglik = -104678.2733
Iter 177: sigma_u = 0.0334, loglik = -104688.0029
Iter 178: sigma_u = 0.0333, loglik = -104700.7373
Iter 179: sigma_u = 0.0333, loglik = -104707.4997
Iter 180: sigma_u = 0.0333, loglik = -104708.3535
Iter 181: sigma_u = 0.0333, loglik = -104708.4552
Iter 182: sigma_u = 0.0333, loglik = -104708.8223
Iter 183: sigma_u = 0.0333, loglik = -104708.9344
Iter 184: sigma_u = 0.0333, loglik = -104709.5398
Iter 185: sigma_u = 0.0333, loglik = -104709.6295
Iter 186: sigma_u = 0.0333, loglik = -104711.9167
Iter 187: sigma_u = 0.0332, loglik = -104711.9816
Iter 188: sigma_u = 0.0332, loglik = -104713.5348
Iter 189: sigma_u = 0.0332, loglik = -104713.6640
Iter 190: sigma_u = 0.0332, loglik = -104714.4339
Iter 191: sigma_u = 0.0332, loglik = -104714.5748
Iter 192: sigma_u = 0.0332, loglik = -104715.0286
Iter 193: sigma_u = 0.0332, loglik = -104715.1693
Iter 194: sigma_u = 0.0332, loglik = -104715.5536
Iter 195: sigma_u = 0.0332, loglik = -104715.6997
Iter 196: sigma_u = 0.0332, loglik = -104716.0413
Iter 197: sigma_u = 0.0332, loglik = -104716.1924
Iter 198: sigma_u = 0.0332, loglik = -104716.4964
Iter 199: sigma_u = 0.0332, loglik = -104716.6546
Iter 200: sigma_u = 0.0332, loglik = -104716.9175
Iter 201: sigma_u = 0.0332, loglik = -104717.0840
Iter 202: sigma_u = 0.0332, loglik = -104717.3173
Iter 203: sigma_u = 0.0332, loglik = -104717.4961
Iter 204: sigma_u = 0.0332, loglik = -104717.6985
Iter 205: sigma_u = 0.0332, loglik = -104717.8950
Iter 206: sigma_u = 0.0331, loglik = -104718.0698
Iter 207: sigma_u = 0.0331, loglik = -104718.2953
Iter 208: sigma_u = 0.0331, loglik = -104718.4444
Iter 209: sigma_u = 0.0331, loglik = -104718.7245
Iter 210: sigma_u = 0.0331, loglik = -104718.8494
Iter 211: sigma_u = 0.0331, loglik = -104719.2417
Iter 212: sigma_u = 0.0331, loglik = -104719.3444
Iter 213: sigma_u = 0.0331, loglik = -104720.0768
Iter 214: sigma_u = 0.0330, loglik = -104720.1575
Iter 215: sigma_u = 0.0328, loglik = -104729.0086
Iter 216: sigma_u = 0.0328, loglik = -104740.3997
Iter 217: sigma_u = 0.0328, loglik = -104740.7464
Iter 218: sigma_u = 0.0327, loglik = -104740.8472
Iter 219: sigma_u = 0.0327, loglik = -104741.3991
Iter 220: sigma_u = 0.0327, loglik = -104741.4793
Iter 221: sigma_u = 0.0327, loglik = -104743.6978
Iter 222: sigma_u = 0.0327, loglik = -104743.7563
Iter 223: sigma_u = 0.0327, loglik = -104745.0605
Iter 224: sigma_u = 0.0327, loglik = -104745.1773
Iter 225: sigma_u = 0.0327, loglik = -104745.6476
Iter 226: sigma_u = 0.0327, loglik = -104745.7804
Iter 227: sigma_u = 0.0327, loglik = -104746.1060
Iter 228: sigma_u = 0.0327, loglik = -104746.2397
Iter 229: sigma_u = 0.0327, loglik = -104746.5246
Iter 230: sigma_u = 0.0327, loglik = -104746.6634
Iter 231: sigma_u = 0.0327, loglik = -104746.9168
Iter 232: sigma_u = 0.0326, loglik = -104747.0622
Iter 233: sigma_u = 0.0326, loglik = -104747.2866
Iter 234: sigma_u = 0.0326, loglik = -104747.4421
Iter 235: sigma_u = 0.0326, loglik = -104747.6397
Iter 236: sigma_u = 0.0326, loglik = -104747.8075
Iter 237: sigma_u = 0.0326, loglik = -104747.9792
Iter 238: sigma_u = 0.0326, loglik = -104748.1658
Iter 239: sigma_u = 0.0326, loglik = -104748.3137
Iter 240: sigma_u = 0.0326, loglik = -104748.5360
Iter 241: sigma_u = 0.0326, loglik = -104748.6612
Iter 242: sigma_u = 0.0326, loglik = -104748.9476
Iter 243: sigma_u = 0.0326, loglik = -104749.0515
Iter 244: sigma_u = 0.0326, loglik = -104749.4979
Iter 245: sigma_u = 0.0326, loglik = -104749.5819
Iter 246: sigma_u = 0.0326, loglik = -104750.8205
Iter 247: sigma_u = 0.0324, loglik = -104750.8824
Iter 248: sigma_u = 0.0323, loglik = -104759.1461
Iter 249: sigma_u = 0.0322, loglik = -104769.7616
Iter 250: sigma_u = 0.0322, loglik = -104771.2534
Iter 251: sigma_u = 0.0322, loglik = -104771.3440
Iter 252: sigma_u = 0.0322, loglik = -104771.5321
Iter 253: sigma_u = 0.0322, loglik = -104771.6358
Iter 254: sigma_u = 0.0322, loglik = -104771.9337
Iter 255: sigma_u = 0.0322, loglik = -104772.0224
Iter 256: sigma_u = 0.0322, loglik = -104772.5561
Iter 257: sigma_u = 0.0322, loglik = -104772.6267
Iter 258: sigma_u = 0.0322, loglik = -104775.0692
Iter 259: sigma_u = 0.0321, loglik = -104775.1169
Iter 260: sigma_u = 0.0321, loglik = -104775.8556
Iter 261: sigma_u = 0.0321, loglik = -104775.9621
Iter 262: sigma_u = 0.0321, loglik = -104776.5920
Iter 263: sigma_u = 0.0321, loglik = -104776.6982
Iter 264: sigma_u = 0.0321, loglik = -104777.2535
Iter 265: sigma_u = 0.0321, loglik = -104777.3610
Iter 266: sigma_u = 0.0321, loglik = -104777.8469
Iter 267: sigma_u = 0.0321, loglik = -104777.9547
Iter 268: sigma_u = 0.0321, loglik = -104778.3866
Iter 269: sigma_u = 0.0321, loglik = -104778.4963
Iter 270: sigma_u = 0.0321, loglik = -104778.8885
Iter 271: sigma_u = 0.0321, loglik = -104778.9999
Iter 272: sigma_u = 0.0321, loglik = -104779.3487
Iter 273: sigma_u = 0.0321, loglik = -104779.4617
Iter 274: sigma_u = 0.0321, loglik = -104779.7692
Iter 275: sigma_u = 0.0321, loglik = -104779.8856
Iter 276: sigma_u = 0.0321, loglik = -104780.1627
Iter 277: sigma_u = 0.0321, loglik = -104780.2830
Iter 278: sigma_u = 0.0321, loglik = -104780.5285
Iter 279: sigma_u = 0.0321, loglik = -104780.6539
Iter 280: sigma_u = 0.0321, loglik = -104780.8719
Iter 281: sigma_u = 0.0321, loglik = -104781.0028
Iter 282: sigma_u = 0.0320, loglik = -104781.1957
Iter 283: sigma_u = 0.0320, loglik = -104781.3353
Iter 284: sigma_u = 0.0320, loglik = -104781.5046
Iter 285: sigma_u = 0.0320, loglik = -104781.6557
Iter 286: sigma_u = 0.0320, loglik = -104781.8052
Iter 287: sigma_u = 0.0320, loglik = -104781.9726
Iter 288: sigma_u = 0.0320, loglik = -104782.1029
Iter 289: sigma_u = 0.0320, loglik = -104782.3017
Iter 290: sigma_u = 0.0320, loglik = -104782.4117
Iter 291: sigma_u = 0.0320, loglik = -104782.6633
Iter 292: sigma_u = 0.0320, loglik = -104782.7555
Iter 293: sigma_u = 0.0320, loglik = -104783.1501
Iter 294: sigma_u = 0.0320, loglik = -104783.2250
Iter 295: sigma_u = 0.0320, loglik = -104784.2560
Iter 296: sigma_u = 0.0318, loglik = -104784.3119
Iter 297: sigma_u = 0.0318, loglik = -104793.0071
Iter 298: sigma_u = 0.0318, loglik = -104793.0849
Iter 299: sigma_u = 0.0318, loglik = -104793.7281
Iter 300: sigma_u = 0.0317, loglik = -104793.7882
Iter 301: sigma_u = 0.0317, loglik = -104801.7049
Iter 302: sigma_u = 0.0317, loglik = -104802.1290
Iter 303: sigma_u = 0.0317, loglik = -104802.2603
Iter 304: sigma_u = 0.0317, loglik = -104802.3854
Iter 305: sigma_u = 0.0317, loglik = -104802.5508
Iter 306: sigma_u = 0.0317, loglik = -104802.6620
Iter 307: sigma_u = 0.0317, loglik = -104802.8662
Iter 308: sigma_u = 0.0317, loglik = -104802.9597
Iter 309: sigma_u = 0.0317, loglik = -104803.2375
Iter 310: sigma_u = 0.0316, loglik = -104803.3155
Iter 311: sigma_u = 0.0316, loglik = -104803.8362
Iter 312: sigma_u = 0.0316, loglik = -104803.8977
Iter 313: sigma_u = 0.0316, loglik = -104807.1947
Iter 314: sigma_u = 0.0316, loglik = -104807.2331
Iter 315: sigma_u = 0.0316, loglik = -104807.6284
Iter 316: sigma_u = 0.0316, loglik = -104807.7270
Iter 317: sigma_u = 0.0316, loglik = -104808.0925
Iter 318: sigma_u = 0.0316, loglik = -104808.1922
Iter 319: sigma_u = 0.0316, loglik = -104808.5156
Iter 320: sigma_u = 0.0316, loglik = -104808.6175
Iter 321: sigma_u = 0.0316, loglik = -104808.9029
Iter 322: sigma_u = 0.0315, loglik = -104809.0069
Iter 323: sigma_u = 0.0315, loglik = -104809.2646
Iter 324: sigma_u = 0.0315, loglik = -104809.3721
Iter 325: sigma_u = 0.0315, loglik = -104809.6024
Iter 326: sigma_u = 0.0315, loglik = -104809.7129
Iter 327: sigma_u = 0.0315, loglik = -104809.9223
Iter 328: sigma_u = 0.0315, loglik = -104810.0368
Iter 329: sigma_u = 0.0315, loglik = -104810.2223

Iter 330: sigma_u = 0.0315, loglik = -104810.3432
Iter 331: sigma_u = 0.0315, loglik = -104810.5074
Iter 332: sigma_u = 0.0315, loglik = -104810.6358
Iter 333: sigma_u = 0.0315, loglik = -104810.7815
Iter 334: sigma_u = 0.0315, loglik = -104810.9234
Iter 335: sigma_u = 0.0315, loglik = -104811.0489
Iter 336: sigma_u = 0.0315, loglik = -104811.2099
Iteration 336: beta norm = 2.176662610263306, sigma_u = 0.0315
Iter 337: sigma_u = 0.0315, loglik = -104811.3181
Iter 338: sigma_u = 0.0315, loglik = -104811.5118
Iter 339: sigma_u = 0.0315, loglik = -104811.6044
Iter 340: sigma_u = 0.0315, loglik = -104811.8675
Iter 341: sigma_u = 0.0315, loglik = -104811.9439
Iter 342: sigma_u = 0.0315, loglik = -104812.4294
Iter 343: sigma_u = 0.0314, loglik = -104812.4895
Iter 344: sigma_u = 0.0314, loglik = -104815.0783
Iter 345: sigma_u = 0.0314, loglik = -104815.1173
Iter 346: sigma_u = 0.0314, loglik = -104815.5986
Iter 347: sigma_u = 0.0314, loglik = -104815.6923
Iter 348: sigma_u = 0.0314, loglik = -104816.1174
Iter 349: sigma_u = 0.0314, loglik = -104816.2113
Iter 350: sigma_u = 0.0314, loglik = -104816.6001
Iter 351: sigma_u = 0.0314, loglik = -104816.6952
Iter 352: sigma_u = 0.0314, loglik = -104817.0449
Iter 353: sigma_u = 0.0314, loglik = -104817.1406
Iter 354: sigma_u = 0.0314, loglik = -104817.4530
Iter 355: sigma_u = 0.0314, loglik = -104817.5508
Iter 356: sigma_u = 0.0314, loglik = -104817.8267
Iter 357: sigma_u = 0.0314, loglik = -104817.9275
Iter 358: sigma_u = 0.0314, loglik = -104818.1740
Iter 359: sigma_u = 0.0314, loglik = -104818.2769
Iter 360: sigma_u = 0.0314, loglik = -104818.4985
Iter 361: sigma_u = 0.0314, loglik = -104818.6064
Iter 362: sigma_u = 0.0314, loglik = -104818.8035
Iter 363: sigma_u = 0.0314, loglik = -104818.9155
Iter 364: sigma_u = 0.0314, loglik = -104819.0905
Iter 365: sigma_u = 0.0314, loglik = -104819.2093
Iter 366: sigma_u = 0.0314, loglik = -104819.3631
Iter 367: sigma_u = 0.0314, loglik = -104819.4930
Iter 368: sigma_u = 0.0314, loglik = -104819.6254
Iter 369: sigma_u = 0.0314, loglik = -104819.7708
Iter 370: sigma_u = 0.0314, loglik = -104819.8837
Iter 371: sigma_u = 0.0314, loglik = -104820.0537
Iter 372: sigma_u = 0.0313, loglik = -104820.1504
Iter 373: sigma_u = 0.0313, loglik = -104820.3657
Iter 374: sigma_u = 0.0313, loglik = -104820.4465
Iter 375: sigma_u = 0.0313, loglik = -104820.7694
Iter 376: sigma_u = 0.0313, loglik = -104820.8359
Iter 377: sigma_u = 0.0313, loglik = -104821.6347
Iter 378: sigma_u = 0.0312, loglik = -104821.6844
Iter 379: sigma_u = 0.0312, loglik = -104829.5828
Iter 380: sigma_u = 0.0312, loglik = -104829.8599
Iter 381: sigma_u = 0.0312, loglik = -104829.9281
Iter 382: sigma_u = 0.0312, loglik = -104830.4801
Iter 383: sigma_u = 0.0310, loglik = -104830.5330
Iter 384: sigma_u = 0.0310, loglik = -104838.8941
Iter 385: sigma_u = 0.0310, loglik = -104838.9768
Iter 386: sigma_u = 0.0310, loglik = -104839.4374
Iter 387: sigma_u = 0.0310, loglik = -104839.5307
Iter 388: sigma_u = 0.0310, loglik = -104839.7755
Iter 389: sigma_u = 0.0310, loglik = -104839.8696
Iter 390: sigma_u = 0.0310, loglik = -104840.0801
Iter 391: sigma_u = 0.0310, loglik = -104840.1774
Iter 392: sigma_u = 0.0310, loglik = -104840.3670
Iter 393: sigma_u = 0.0310, loglik = -104840.4673
Iter 394: sigma_u = 0.0310, loglik = -104840.6370
Iter 395: sigma_u = 0.0310, loglik = -104840.7443
Iter 396: sigma_u = 0.0310, loglik = -104840.8926
Iter 397: sigma_u = 0.0310, loglik = -104841.0080
Iter 398: sigma_u = 0.0310, loglik = -104841.1369
Iter 399: sigma_u = 0.0310, loglik = -104841.2619
Iter 400: sigma_u = 0.0310, loglik = -104841.3748
Iter 401: sigma_u = 0.0310, loglik = -104841.5170
Iter 402: sigma_u = 0.0310, loglik = -104841.6146
Iter 403: sigma_u = 0.0310, loglik = -104841.7871
Iter 404: sigma_u = 0.0310, loglik = -104841.8697
Iter 405: sigma_u = 0.0310, loglik = -104842.1057
Iter 406: sigma_u = 0.0309, loglik = -104842.1736
Iter 407: sigma_u = 0.0309, loglik = -104842.6003
Iter 408: sigma_u = 0.0309, loglik = -104842.6539
Iter 409: sigma_u = 0.0309, loglik = -104844.8883
Iter 410: sigma_u = 0.0309, loglik = -104844.9230
Iter 411: sigma_u = 0.0309, loglik = -104845.3395
Iter 412: sigma_u = 0.0309, loglik = -104845.4233
Iter 413: sigma_u = 0.0309, loglik = -104845.7937
Iter 414: sigma_u = 0.0309, loglik = -104845.8777
Iter 415: sigma_u = 0.0309, loglik = -104846.1991
Iter 416: sigma_u = 0.0309, loglik = -104846.2839
Iter 417: sigma_u = 0.0309, loglik = -104846.5786
Iter 418: sigma_u = 0.0309, loglik = -104846.6656
Iter 419: sigma_u = 0.0309, loglik = -104846.9297
Iter 420: sigma_u = 0.0309, loglik = -104847.0188
Iter 421: sigma_u = 0.0309, loglik = -104847.2566
Iter 422: sigma_u = 0.0309, loglik = -104847.3471
Iter 423: sigma_u = 0.0309, loglik = -104847.5577
Iter 424: sigma_u = 0.0308, loglik = -104847.6513
Iter 425: sigma_u = 0.0308, loglik = -104847.8408
Iter 426: sigma_u = 0.0308, loglik = -104847.9384
Iter 427: sigma_u = 0.0308, loglik = -104848.1061
Iter 428: sigma_u = 0.0308, loglik = -104848.2091
Iter 429: sigma_u = 0.0308, loglik = -104848.3562
Iter 430: sigma_u = 0.0308, loglik = -104848.4675
Iter 431: sigma_u = 0.0308, loglik = -104848.5944
Iter 432: sigma_u = 0.0308, loglik = -104848.7155
Iter 433: sigma_u = 0.0308, loglik = -104848.8258
Iter 434: sigma_u = 0.0308, loglik = -104848.9627
Iter 435: sigma_u = 0.0308, loglik = -104849.0573
Iter 436: sigma_u = 0.0308, loglik = -104849.2239
Iter 437: sigma_u = 0.0308, loglik = -104849.3045
Iter 438: sigma_u = 0.0308, loglik = -104849.5219
Iter 439: sigma_u = 0.0308, loglik = -104849.5895
Iter 440: sigma_u = 0.0308, loglik = -104849.9507
Iter 441: sigma_u = 0.0308, loglik = -104850.0056
Iter 442: sigma_u = 0.0308, loglik = -104851.2865
Iter 443: sigma_u = 0.0308, loglik = -104851.3252
Iter 444: sigma_u = 0.0308, loglik = -104852.3200
Iter 445: sigma_u = 0.0307, loglik = -104852.3999
Iter 446: sigma_u = 0.0307, loglik = -104853.1876
Iter 447: sigma_u = 0.0307, loglik = -104853.2669
Iter 448: sigma_u = 0.0307, loglik = -104853.9158
Iter 449: sigma_u = 0.0307, loglik = -104853.9952
Iter 450: sigma_u = 0.0307, loglik = -104854.5941
Iter 451: sigma_u = 0.0307, loglik = -104854.6722
Iter 452: sigma_u = 0.0307, loglik = -104855.1790
Iter 453: sigma_u = 0.0307, loglik = -104855.2579
Iter 454: sigma_u = 0.0307, loglik = -104855.6966
Iter 455: sigma_u = 0.0307, loglik = -104855.7758
Iter 456: sigma_u = 0.0307, loglik = -104856.1672
Iter 457: sigma_u = 0.0307, loglik = -104856.2469
Iter 458: sigma_u = 0.0307, loglik = -104856.5866
Iter 459: sigma_u = 0.0307, loglik = -104856.6671
Iter 460: sigma_u = 0.0307, loglik = -104856.9756
Iter 461: sigma_u = 0.0307, loglik = -104857.0582
Iter 462: sigma_u = 0.0307, loglik = -104857.3391
Iter 463: sigma_u = 0.0307, loglik = -104857.4222
Iter 464: sigma_u = 0.0307, loglik = -104857.6714
Iter 465: sigma_u = 0.0307, loglik = -104857.7567
Iter 466: sigma_u = 0.0307, loglik = -104857.9818
Iter 467: sigma_u = 0.0307, loglik = -104858.0692
Iter 468: sigma_u = 0.0307, loglik = -104858.2692
Iter 469: sigma_u = 0.0307, loglik = -104858.3589
Iter 470: sigma_u = 0.0306, loglik = -104858.5356
Iter 471: sigma_u = 0.0306, loglik = -104858.6296
Iter 472: sigma_u = 0.0306, loglik = -104858.7895
Iter 473: sigma_u = 0.0306, loglik = -104858.8880
Iter 474: sigma_u = 0.0306, loglik = -104859.0302
Iter 475: sigma_u = 0.0306, loglik = -104859.1354
Iter 476: sigma_u = 0.0306, loglik = -104859.2578
Iter 477: sigma_u = 0.0306, loglik = -104859.3743
Iter 478: sigma_u = 0.0306, loglik = -104859.4796
Iter 479: sigma_u = 0.0306, loglik = -104859.6143
Iter 480: sigma_u = 0.0306, loglik = -104859.7046
Iter 481: sigma_u = 0.0306, loglik = -104859.8656
Iter 482: sigma_u = 0.0306, loglik = -104859.9421
Iter 483: sigma_u = 0.0306, loglik = -104860.1606
Iter 484: sigma_u = 0.0306, loglik = -104860.2241
Iter 485: sigma_u = 0.0306, loglik = -104860.6099
Iter 486: sigma_u = 0.0306, loglik = -104860.6606
Iter 487: sigma_u = 0.0306, loglik = -104862.4068
Iter 488: sigma_u = 0.0306, loglik = -104862.4412
Iter 489: sigma_u = 0.0306, loglik = -104862.9432
Iter 490: sigma_u = 0.0306, loglik = -104863.0193
Iter 491: sigma_u = 0.0306, loglik = -104863.4575
Iter 492: sigma_u = 0.0306, loglik = -104863.5346

Iter 493: sigma_u = 0.0305, loglik = -104863.9310
Iter 494: sigma_u = 0.0305, loglik = -104864.0077
Iter 495: sigma_u = 0.0305, loglik = -104864.3515
Iter 496: sigma_u = 0.0305, loglik = -104864.4295
Iter 497: sigma_u = 0.0305, loglik = -104864.7439
Iter 498: sigma_u = 0.0305, loglik = -104864.8227
Iter 499: sigma_u = 0.0305, loglik = -104865.1103
Iter 500: sigma_u = 0.0305, loglik = -104865.1903
Iter 501: sigma_u = 0.0305, loglik = -104865.4445
Iter 502: sigma_u = 0.0305, loglik = -104865.5262
Iter 503: sigma_u = 0.0305, loglik = -104865.7540
Iter 504: sigma_u = 0.0305, loglik = -104865.8372
Iter 505: sigma_u = 0.0305, loglik = -104866.0402
Iter 506: sigma_u = 0.0305, loglik = -104866.1268
Iter 507: sigma_u = 0.0305, loglik = -104866.3075
Iter 508: sigma_u = 0.0305, loglik = -104866.3969
Iter 509: sigma_u = 0.0305, loglik = -104866.5571
Iter 510: sigma_u = 0.0305, loglik = -104866.6515
Iter 511: sigma_u = 0.0305, loglik = -104866.7933
Iter 512: sigma_u = 0.0305, loglik = -104866.8935
Iter 513: sigma_u = 0.0305, loglik = -104867.0161
Iter 514: sigma_u = 0.0305, loglik = -104867.1269
Iter 515: sigma_u = 0.0305, loglik = -104867.2319
Iter 516: sigma_u = 0.0305, loglik = -104867.3556
Iter 517: sigma_u = 0.0305, loglik = -104867.4461
Iter 518: sigma_u = 0.0305, loglik = -104867.5931
Iter 519: sigma_u = 0.0305, loglik = -104867.6706
Iter 520: sigma_u = 0.0305, loglik = -104867.8640
Iter 521: sigma_u = 0.0305, loglik = -104867.9286
Iter 522: sigma_u = 0.0305, loglik = -104868.2481
Iter 523: sigma_u = 0.0305, loglik = -104868.3004
Iter 524: sigma_u = 0.0304, loglik = -104869.2859
Iter 525: sigma_u = 0.0304, loglik = -104869.3239
Iter 526: sigma_u = 0.0304, loglik = -104870.9344
Iter 527: sigma_u = 0.0304, loglik = -104871.0103
Iter 528: sigma_u = 0.0304, loglik = -104872.1019
Iter 529: sigma_u = 0.0304, loglik = -104872.1776
Iter 530: sigma_u = 0.0304, loglik = -104872.8258
Iter 531: sigma_u = 0.0304, loglik = -104872.8979
Iter 532: sigma_u = 0.0304, loglik = -104873.2039
Iter 533: sigma_u = 0.0304, loglik = -104873.2840
Iter 534: sigma_u = 0.0304, loglik = -104873.5016
Iter 535: sigma_u = 0.0304, loglik = -104873.5835
Iter 536: sigma_u = 0.0304, loglik = -104873.7745
Iter 537: sigma_u = 0.0304, loglik = -104873.8589
Iter 538: sigma_u = 0.0304, loglik = -104874.0288
Iter 539: sigma_u = 0.0304, loglik = -104874.1155
Iter 540: sigma_u = 0.0304, loglik = -104874.2683
Iter 541: sigma_u = 0.0304, loglik = -104874.3605
Iter 542: sigma_u = 0.0304, loglik = -104874.4957
Iter 543: sigma_u = 0.0303, loglik = -104874.5946
Iter 544: sigma_u = 0.0303, loglik = -104874.7104
Iter 545: sigma_u = 0.0303, loglik = -104874.8195
Iter 546: sigma_u = 0.0303, loglik = -104874.9194
Iter 547: sigma_u = 0.0303, loglik = -104875.0455
Iter 548: sigma_u = 0.0303, loglik = -104875.1304
Iter 549: sigma_u = 0.0303, loglik = -104875.2818
Iter 550: sigma_u = 0.0303, loglik = -104875.3527
Iter 551: sigma_u = 0.0303, loglik = -104875.5668
Iter 552: sigma_u = 0.0303, loglik = -104875.6253
Iter 553: sigma_u = 0.0303, loglik = -104876.0174
Iter 554: sigma_u = 0.0303, loglik = -104876.0639
Iter 555: sigma_u = 0.0303, loglik = -104878.6394
Iter 556: sigma_u = 0.0303, loglik = -104878.6676
Iter 557: sigma_u = 0.0303, loglik = -104878.9456
Iter 558: sigma_u = 0.0303, loglik = -104879.0208
Iter 559: sigma_u = 0.0303, loglik = -104879.2697
Iter 560: sigma_u = 0.0303, loglik = -104879.3455
Iter 561: sigma_u = 0.0303, loglik = -104879.5694
Iter 562: sigma_u = 0.0303, loglik = -104879.6478
Iter 563: sigma_u = 0.0303, loglik = -104879.8518
Iter 564: sigma_u = 0.0302, loglik = -104879.9322
Iter 565: sigma_u = 0.0302, loglik = -104880.1145
Iter 566: sigma_u = 0.0302, loglik = -104880.1969
Iter 567: sigma_u = 0.0302, loglik = -104880.3590
Iter 568: sigma_u = 0.0302, loglik = -104880.4448
Iter 569: sigma_u = 0.0302, loglik = -104880.5907
Iter 570: sigma_u = 0.0302, loglik = -104880.6809
Iter 571: sigma_u = 0.0302, loglik = -104880.8083
Iter 572: sigma_u = 0.0302, loglik = -104880.9055
Iter 573: sigma_u = 0.0302, loglik = -104881.0182
Iter 574: sigma_u = 0.0302, loglik = -104881.1251
Iter 575: sigma_u = 0.0302, loglik = -104881.2212
Iter 576: sigma_u = 0.0302, loglik = -104881.3421
Iter 577: sigma_u = 0.0302, loglik = -104881.4254
Iter 578: sigma_u = 0.0302, loglik = -104881.5689
Iter 579: sigma_u = 0.0302, loglik = -104881.6396
Iter 580: sigma_u = 0.0302, loglik = -104881.8338
Iter 581: sigma_u = 0.0302, loglik = -104881.8930
Iter 582: sigma_u = 0.0302, loglik = -104882.2249
Iter 583: sigma_u = 0.0302, loglik = -104882.2720
Iter 584: sigma_u = 0.0302, loglik = -104883.5864
Iter 585: sigma_u = 0.0302, loglik = -104883.6194
Iter 586: sigma_u = 0.0302, loglik = -104884.2894
Iter 587: sigma_u = 0.0302, loglik = -104884.3593
Iter 588: sigma_u = 0.0302, loglik = -104884.9237
Iter 589: sigma_u = 0.0301, loglik = -104884.9931
Iter 590: sigma_u = 0.0301, loglik = -104885.5079
Iter 591: sigma_u = 0.0301, loglik = -104885.5773
Iter 592: sigma_u = 0.0301, loglik = -104886.0240
Iter 593: sigma_u = 0.0301, loglik = -104886.0940
Iter 594: sigma_u = 0.0301, loglik = -104886.4973
Iter 595: sigma_u = 0.0301, loglik = -104886.5668
Iter 596: sigma_u = 0.0301, loglik = -104886.9332
Iter 597: sigma_u = 0.0301, loglik = -104887.0034
Iter 598: sigma_u = 0.0301, loglik = -104887.3213
Iter 599: sigma_u = 0.0301, loglik = -104887.3916
Iter 600: sigma_u = 0.0301, loglik = -104887.6708
Iter 601: sigma_u = 0.0301, loglik = -104887.7424
Iter 602: sigma_u = 0.0301, loglik = -104887.9965
Iter 603: sigma_u = 0.0301, loglik = -104888.0692
Iter 604: sigma_u = 0.0301, loglik = -104888.2968
Iter 605: sigma_u = 0.0301, loglik = -104888.3719
Iter 606: sigma_u = 0.0301, loglik = -104888.5725
Iter 607: sigma_u = 0.0301, loglik = -104888.6482
Iter 608: sigma_u = 0.0301, loglik = -104888.8329
Iter 609: sigma_u = 0.0301, loglik = -104888.9115
Iter 610: sigma_u = 0.0301, loglik = -104889.0750
Iter 611: sigma_u = 0.0301, loglik = -104889.1568
Iter 612: sigma_u = 0.0301, loglik = -104889.3022
Iter 613: sigma_u = 0.0301, loglik = -104889.3875
Iter 614: sigma_u = 0.0301, loglik = -104889.5163
Iter 615: sigma_u = 0.0301, loglik = -104889.6070
Iter 616: sigma_u = 0.0301, loglik = -104889.7195
Iter 617: sigma_u = 0.0301, loglik = -104889.8184
Iter 618: sigma_u = 0.0301, loglik = -104889.9160
Iter 619: sigma_u = 0.0301, loglik = -104890.0268
Iter 620: sigma_u = 0.0301, loglik = -104890.1109
Iter 621: sigma_u = 0.0301, loglik = -104890.2425
Iter 622: sigma_u = 0.0301, loglik = -104890.3141
Iter 623: sigma_u = 0.0301, loglik = -104890.4829
Iter 624: sigma_u = 0.0300, loglik = -104890.5431
Iter 625: sigma_u = 0.0300, loglik = -104890.8077
Iter 626: sigma_u = 0.0300, loglik = -104890.8564
Iter 627: sigma_u = 0.0300, loglik = -104891.6015
Iter 628: sigma_u = 0.0300, loglik = -104891.6377
Iter 629: sigma_u = 0.0300, loglik = -104894.6197
Iter 630: sigma_u = 0.0299, loglik = -104894.6921
Iter 631: sigma_u = 0.0299, loglik = -104896.0037
Iter 632: sigma_u = 0.0299, loglik = -104896.0771
Iter 633: sigma_u = 0.0299, loglik = -104896.3739
Iter 634: sigma_u = 0.0299, loglik = -104896.4457
Iter 635: sigma_u = 0.0299, loglik = -104896.6037
Iter 636: sigma_u = 0.0299, loglik = -104896.6829
Iter 637: sigma_u = 0.0299, loglik = -104896.8264
Iter 638: sigma_u = 0.0299, loglik = -104896.9080
Iter 639: sigma_u = 0.0299, loglik = -104897.0349
Iter 640: sigma_u = 0.0299, loglik = -104897.1226
Iter 641: sigma_u = 0.0299, loglik = -104897.2342
Iter 642: sigma_u = 0.0299, loglik = -104897.3291
Iter 643: sigma_u = 0.0299, loglik = -104897.4276
Iter 644: sigma_u = 0.0299, loglik = -104897.5322
Iter 645: sigma_u = 0.0299, loglik = -104897.6174
Iter 646: sigma_u = 0.0299, loglik = -104897.7386
Iter 647: sigma_u = 0.0299, loglik = -104897.8115
Iter 648: sigma_u = 0.0299, loglik = -104897.9629
Iter 649: sigma_u = 0.0299, loglik = -104898.0242
Iter 650: sigma_u = 0.0299, loglik = -104898.2350
Iter 651: sigma_u = 0.0299, loglik = -104898.2859
Iter 652: sigma_u = 0.0299, loglik = -104898.7248
Iter 653: sigma_u = 0.0298, loglik = -104898.7642
Iter 654: sigma_u = 0.0298, loglik = -104905.2215
Iter 655: sigma_u = 0.0298, loglik = -104905.3874
Iter 656: sigma_u = 0.0298, loglik = -104905.4613

Iter 657: sigma_u = 0.0298, loglik = -104905.6097
Iter 658: sigma_u = 0.0298, loglik = -104905.6876
Iter 659: sigma_u = 0.0298, loglik = -104905.8158
Iter 660: sigma_u = 0.0298, loglik = -104905.8981
Iter 661: sigma_u = 0.0298, loglik = -104906.0119
Iter 662: sigma_u = 0.0298, loglik = -104906.0984
Iter 663: sigma_u = 0.0298, loglik = -104906.1990
Iter 664: sigma_u = 0.0298, loglik = -104906.2946
Iter 665: sigma_u = 0.0297, loglik = -104906.3825
Iter 666: sigma_u = 0.0297, loglik = -104906.4915
Iter 667: sigma_u = 0.0297, loglik = -104906.5667
Iter 668: sigma_u = 0.0297, loglik = -104906.6989
Iter 669: sigma_u = 0.0297, loglik = -104906.7625
Iteration 669: beta norm = 2.175977832132576, sigma_u = 0.0297
Iter 670: sigma_u = 0.0297, loglik = -104906.9343
Iter 671: sigma_u = 0.0297, loglik = -104906.9875
Iter 672: sigma_u = 0.0297, loglik = -104907.2757
Iter 673: sigma_u = 0.0297, loglik = -104907.3189
Iter 674: sigma_u = 0.0297, loglik = -104908.3374
Iter 675: sigma_u = 0.0297, loglik = -104908.3680
Iter 676: sigma_u = 0.0297, loglik = -104909.1745
Iter 677: sigma_u = 0.0297, loglik = -104909.2376
Iter 678: sigma_u = 0.0297, loglik = -104909.8470
Iter 679: sigma_u = 0.0297, loglik = -104909.9095
Iter 680: sigma_u = 0.0297, loglik = -104910.3753
Iter 681: sigma_u = 0.0297, loglik = -104910.4386
Iter 682: sigma_u = 0.0297, loglik = -104910.8122
Iter 683: sigma_u = 0.0297, loglik = -104910.8744
Iter 684: sigma_u = 0.0297, loglik = -104911.1633
Iter 685: sigma_u = 0.0297, loglik = -104911.2278
Iter 686: sigma_u = 0.0297, loglik = -104911.4750
Iter 687: sigma_u = 0.0296, loglik = -104911.5401
Iter 688: sigma_u = 0.0296, loglik = -104911.7554
Iter 689: sigma_u = 0.0296, loglik = -104911.8224
Iter 690: sigma_u = 0.0296, loglik = -104912.0165
Iter 691: sigma_u = 0.0296, loglik = -104912.0848
Iter 692: sigma_u = 0.0296, loglik = -104912.2580
Iter 693: sigma_u = 0.0296, loglik = -104912.3285
Iter 694: sigma_u = 0.0296, loglik = -104912.4834
Iter 695: sigma_u = 0.0296, loglik = -104912.5567
Iter 696: sigma_u = 0.0296, loglik = -104912.6913
Iter 697: sigma_u = 0.0296, loglik = -104912.7692
Iter 698: sigma_u = 0.0296, loglik = -104912.8858
Iter 699: sigma_u = 0.0296, loglik = -104912.9693
Iter 700: sigma_u = 0.0296, loglik = -104913.0706
Iter 701: sigma_u = 0.0296, loglik = -104913.1606
Iter 702: sigma_u = 0.0296, loglik = -104913.2478
Iter 703: sigma_u = 0.0296, loglik = -104913.3498
Iter 704: sigma_u = 0.0296, loglik = -104913.4245
Iter 705: sigma_u = 0.0296, loglik = -104913.5471
Iter 706: sigma_u = 0.0296, loglik = -104913.6109
Iter 707: sigma_u = 0.0296, loglik = -104913.7715
Iter 708: sigma_u = 0.0296, loglik = -104913.8248
Iter 709: sigma_u = 0.0296, loglik = -104914.0734
Iter 710: sigma_u = 0.0296, loglik = -104914.1170
Iter 711: sigma_u = 0.0296, loglik = -104914.8400
Iter 712: sigma_u = 0.0296, loglik = -104914.8722
Iter 713: sigma_u = 0.0296, loglik = -104916.7535
Iter 714: sigma_u = 0.0295, loglik = -104916.8179
Iter 715: sigma_u = 0.0295, loglik = -104917.9696
Iter 716: sigma_u = 0.0295, loglik = -104918.0328
Iter 717: sigma_u = 0.0295, loglik = -104918.7078
Iter 718: sigma_u = 0.0295, loglik = -104918.7673
Iter 719: sigma_u = 0.0295, loglik = -104919.0278
Iter 720: sigma_u = 0.0295, loglik = -104919.0945
Iter 721: sigma_u = 0.0295, loglik = -104919.2651
Iter 722: sigma_u = 0.0295, loglik = -104919.3322
Iter 723: sigma_u = 0.0295, loglik = -104919.4829
Iter 724: sigma_u = 0.0295, loglik = -104919.5526
Iter 725: sigma_u = 0.0295, loglik = -104919.6877
Iter 726: sigma_u = 0.0295, loglik = -104919.7604
Iter 727: sigma_u = 0.0295, loglik = -104919.8813
Iter 728: sigma_u = 0.0295, loglik = -104919.9590
Iter 729: sigma_u = 0.0295, loglik = -104920.0656
Iter 730: sigma_u = 0.0295, loglik = -104920.1477
Iter 731: sigma_u = 0.0295, loglik = -104920.2411
Iter 732: sigma_u = 0.0295, loglik = -104920.3314
Iter 733: sigma_u = 0.0295, loglik = -104920.4128
Iter 734: sigma_u = 0.0295, loglik = -104920.5160
Iter 735: sigma_u = 0.0295, loglik = -104920.5848
Iter 736: sigma_u = 0.0295, loglik = -104920.7120
Iter 737: sigma_u = 0.0295, loglik = -104920.7704
Iter 738: sigma_u = 0.0295, loglik = -104920.9521
Iter 739: sigma_u = 0.0295, loglik = -104920.9999
Iter 740: sigma_u = 0.0295, loglik = -104921.3380
Iter 741: sigma_u = 0.0294, loglik = -104921.3757
Iter 742: sigma_u = 0.0294, loglik = -104923.8917
Iter 743: sigma_u = 0.0294, loglik = -104923.9143
Iter 744: sigma_u = 0.0294, loglik = -104924.1211
Iter 745: sigma_u = 0.0294, loglik = -104924.1842
Iter 746: sigma_u = 0.0294, loglik = -104924.3721
Iter 747: sigma_u = 0.0294, loglik = -104924.4366
Iter 748: sigma_u = 0.0294, loglik = -104924.6063
Iter 749: sigma_u = 0.0294, loglik = -104924.6724
Iter 750: sigma_u = 0.0294, loglik = -104924.8231
Iter 751: sigma_u = 0.0294, loglik = -104924.8917
Iter 752: sigma_u = 0.0294, loglik = -104925.0241
Iter 753: sigma_u = 0.0294, loglik = -104925.0961
Iter 754: sigma_u = 0.0294, loglik = -104925.2116
Iter 755: sigma_u = 0.0294, loglik = -104925.2869
Iter 756: sigma_u = 0.0294, loglik = -104925.3907
Iter 757: sigma_u = 0.0294, loglik = -104925.4717
Iter 758: sigma_u = 0.0294, loglik = -104925.5626
Iter 759: sigma_u = 0.0294, loglik = -104925.6532
Iter 760: sigma_u = 0.0294, loglik = -104925.7318
Iter 761: sigma_u = 0.0294, loglik = -104925.8345
Iter 762: sigma_u = 0.0294, loglik = -104925.9011
Iter 763: sigma_u = 0.0294, loglik = -104926.0276
Iter 764: sigma_u = 0.0294, loglik = -104926.0839
Iter 765: sigma_u = 0.0294, loglik = -104926.2624
Iter 766: sigma_u = 0.0294, loglik = -104926.3087
Iter 767: sigma_u = 0.0294, loglik = -104926.6565
Iter 768: sigma_u = 0.0293, loglik = -104926.6929
Iter 769: sigma_u = 0.0293, loglik = -104929.8538
Iter 770: sigma_u = 0.0293, loglik = -104929.8748
Iter 771: sigma_u = 0.0293, loglik = -104930.0418
Iter 772: sigma_u = 0.0293, loglik = -104930.1062
Iter 773: sigma_u = 0.0293, loglik = -104930.2618
Iter 774: sigma_u = 0.0293, loglik = -104930.3276
Iter 775: sigma_u = 0.0293, loglik = -104930.4653
Iter 776: sigma_u = 0.0293, loglik = -104930.5329
Iter 777: sigma_u = 0.0293, loglik = -104930.6565
Iter 778: sigma_u = 0.0293, loglik = -104930.7274
Iter 779: sigma_u = 0.0293, loglik = -104930.8363
Iter 780: sigma_u = 0.0293, loglik = -104930.9121
Iter 781: sigma_u = 0.0293, loglik = -104931.0075
Iter 782: sigma_u = 0.0293, loglik = -104931.0896
Iter 783: sigma_u = 0.0293, loglik = -104931.1737
Iter 784: sigma_u = 0.0293, loglik = -104931.2646
Iter 785: sigma_u = 0.0293, loglik = -104931.3372
Iter 786: sigma_u = 0.0293, loglik = -104931.4461
Iter 787: sigma_u = 0.0293, loglik = -104931.5074
Iter 788: sigma_u = 0.0293, loglik = -104931.6425
Iter 789: sigma_u = 0.0293, loglik = -104931.6944
Iter 790: sigma_u = 0.0293, loglik = -104931.9022
Iter 791: sigma_u = 0.0293, loglik = -104931.9444
Iter 792: sigma_u = 0.0292, loglik = -104932.4335
Iter 793: sigma_u = 0.0291, loglik = -104932.4657
Iter 794: sigma_u = 0.0291, loglik = -104938.0991
Iter 795: sigma_u = 0.0291, loglik = -104938.1582
Iter 796: sigma_u = 0.0291, loglik = -104938.6484
Iter 797: sigma_u = 0.0291, loglik = -104938.7034
Iter 798: sigma_u = 0.0291, loglik = -104938.8767
Iter 799: sigma_u = 0.0291, loglik = -104938.9397
Iter 800: sigma_u = 0.0291, loglik = -104939.0782
Iter 801: sigma_u = 0.0291, loglik = -104939.1416
Iter 802: sigma_u = 0.0291, loglik = -104939.2667
Iter 803: sigma_u = 0.0291, loglik = -104939.3338
Iter 804: sigma_u = 0.0291, loglik = -104939.4446
Iter 805: sigma_u = 0.0291, loglik = -104939.5151
Iter 806: sigma_u = 0.0291, loglik = -104939.6121
Iter 807: sigma_u = 0.0291, loglik = -104939.6901
Iter 808: sigma_u = 0.0291, loglik = -104939.7734
Iter 809: sigma_u = 0.0291, loglik = -104939.8594
Iter 810: sigma_u = 0.0291, loglik = -104939.9313
Iter 811: sigma_u = 0.0291, loglik = -104940.0292
Iter 812: sigma_u = 0.0291, loglik = -104940.0906
Iter 813: sigma_u = 0.0291, loglik = -104940.2126
Iter 814: sigma_u = 0.0291, loglik = -104940.2644
Iter 815: sigma_u = 0.0291, loglik = -104940.4430
Iter 816: sigma_u = 0.0291, loglik = -104940.4856
Iter 817: sigma_u = 0.0291, loglik = -104940.8585
Iter 818: sigma_u = 0.0290, loglik = -104940.8913
Iter 819: sigma_u = 0.0290, loglik = -104945.4471

Iter 820: sigma_u = 0.0290, loglik = -104945.4670
Iter 821: sigma_u = 0.0290, loglik = -104945.6366
Iter 822: sigma_u = 0.0290, loglik = -104945.6953
Iter 823: sigma_u = 0.0290, loglik = -104945.8487
Iter 824: sigma_u = 0.0290, loglik = -104945.9089
Iter 825: sigma_u = 0.0290, loglik = -104946.0458
Iter 826: sigma_u = 0.0290, loglik = -104946.1082
Iter 827: sigma_u = 0.0290, loglik = -104946.2297
Iter 828: sigma_u = 0.0290, loglik = -104946.2953
Iter 829: sigma_u = 0.0290, loglik = -104946.4013
Iter 830: sigma_u = 0.0290, loglik = -104946.4695
Iter 831: sigma_u = 0.0290, loglik = -104946.5628
Iter 832: sigma_u = 0.0290, loglik = -104946.6364
Iter 833: sigma_u = 0.0290, loglik = -104946.7186
Iter 834: sigma_u = 0.0290, loglik = -104946.8011
Iter 835: sigma_u = 0.0290, loglik = -104946.8718
Iter 836: sigma_u = 0.0290, loglik = -104946.9669
Iter 837: sigma_u = 0.0290, loglik = -104947.0267
Iter 838: sigma_u = 0.0290, loglik = -104947.1441
Iter 839: sigma_u = 0.0290, loglik = -104947.1947
Iter 840: sigma_u = 0.0290, loglik = -104947.3684
Iter 841: sigma_u = 0.0290, loglik = -104947.4093
Iter 842: sigma_u = 0.0290, loglik = -104947.7748
Iter 843: sigma_u = 0.0289, loglik = -104947.8065
Iter 844: sigma_u = 0.0289, loglik = -104952.8609
Iter 845: sigma_u = 0.0288, loglik = -104952.8818
Iter 846: sigma_u = 0.0288, loglik = -104953.0883
Iter 847: sigma_u = 0.0288, loglik = -104953.1432
Iter 848: sigma_u = 0.0288, loglik = -104953.3238
Iter 849: sigma_u = 0.0288, loglik = -104953.3789
Iter 850: sigma_u = 0.0288, loglik = -104953.5386
Iter 851: sigma_u = 0.0288, loglik = -104953.5954
Iter 852: sigma_u = 0.0288, loglik = -104953.7405
Iter 853: sigma_u = 0.0288, loglik = -104953.7982
Iter 854: sigma_u = 0.0288, loglik = -104953.9288
Iter 855: sigma_u = 0.0288, loglik = -104953.9890
Iter 856: sigma_u = 0.0288, loglik = -104954.1035
Iter 857: sigma_u = 0.0288, loglik = -104954.1669
Iter 858: sigma_u = 0.0288, loglik = -104954.2671
Iter 859: sigma_u = 0.0288, loglik = -104954.3335
Iter 860: sigma_u = 0.0288, loglik = -104954.4229
Iter 861: sigma_u = 0.0288, loglik = -104954.4943
Iter 862: sigma_u = 0.0288, loglik = -104954.5734
Iter 863: sigma_u = 0.0288, loglik = -104954.6519
Iter 864: sigma_u = 0.0288, loglik = -104954.7199
Iter 865: sigma_u = 0.0288, loglik = -104954.8122
Iter 866: sigma_u = 0.0288, loglik = -104954.8696
Iter 867: sigma_u = 0.0288, loglik = -104954.9870
Iter 868: sigma_u = 0.0288, loglik = -104955.0347
Iter 869: sigma_u = 0.0288, loglik = -104955.2067
Iter 870: sigma_u = 0.0288, loglik = -104955.2456
Iter 871: sigma_u = 0.0288, loglik = -104955.6164
Iter 872: sigma_u = 0.0287, loglik = -104955.6464
Iter 873: sigma_u = 0.0287, loglik = -104961.2185
Iter 874: sigma_u = 0.0287, loglik = -104961.2423
Iter 875: sigma_u = 0.0287, loglik = -104961.7835
Iter 876: sigma_u = 0.0287, loglik = -104961.8333
Iter 877: sigma_u = 0.0287, loglik = -104962.2793
Iter 878: sigma_u = 0.0287, loglik = -104962.3293
Iter 879: sigma_u = 0.0287, loglik = -104962.6947
Iter 880: sigma_u = 0.0286, loglik = -104962.7439
Iter 881: sigma_u = 0.0286, loglik = -104963.0563
Iter 882: sigma_u = 0.0286, loglik = -104963.1064
Iter 883: sigma_u = 0.0286, loglik = -104963.3666
Iter 884: sigma_u = 0.0286, loglik = -104963.4161
Iter 885: sigma_u = 0.0286, loglik = -104963.6460
Iter 886: sigma_u = 0.0286, loglik = -104963.6971
Iter 887: sigma_u = 0.0286, loglik = -104963.8977
Iter 888: sigma_u = 0.0286, loglik = -104963.9495
Iter 889: sigma_u = 0.0286, loglik = -104964.1249
Iter 890: sigma_u = 0.0286, loglik = -104964.1773
Iter 891: sigma_u = 0.0286, loglik = -104964.3326
Iter 892: sigma_u = 0.0286, loglik = -104964.3862
Iter 893: sigma_u = 0.0286, loglik = -104964.5274
Iter 894: sigma_u = 0.0286, loglik = -104964.5824
Iter 895: sigma_u = 0.0286, loglik = -104964.7083
Iter 896: sigma_u = 0.0286, loglik = -104964.7655
Iter 897: sigma_u = 0.0286, loglik = -104964.8775
Iter 898: sigma_u = 0.0286, loglik = -104964.9359
Iter 899: sigma_u = 0.0286, loglik = -104965.0351
Iter 900: sigma_u = 0.0286, loglik = -104965.0979
Iter 901: sigma_u = 0.0286, loglik = -104965.1842
Iter 902: sigma_u = 0.0286, loglik = -104965.2530
Iter 903: sigma_u = 0.0286, loglik = -104965.3264
Iter 904: sigma_u = 0.0286, loglik = -104965.4022
Iter 905: sigma_u = 0.0286, loglik = -104965.4658
Iter 906: sigma_u = 0.0286, loglik = -104965.5543
Iter 907: sigma_u = 0.0286, loglik = -104965.6085
Iter 908: sigma_u = 0.0286, loglik = -104965.7242
Iter 909: sigma_u = 0.0286, loglik = -104965.7686
Iter 910: sigma_u = 0.0286, loglik = -104965.9382
Iter 911: sigma_u = 0.0286, loglik = -104965.9745
Iter 912: sigma_u = 0.0286, loglik = -104966.3470
Iter 913: sigma_u = 0.0285, loglik = -104966.3755
Iter 914: sigma_u = 0.0285, loglik = -104972.4664
Iter 915: sigma_u = 0.0285, loglik = -104972.8596
Iter 916: sigma_u = 0.0285, loglik = -104972.9147
Iter 917: sigma_u = 0.0285, loglik = -104973.0263
Iter 918: sigma_u = 0.0284, loglik = -104973.0827
Iter 919: sigma_u = 0.0284, loglik = -104973.1851
Iter 920: sigma_u = 0.0284, loglik = -104973.2427
Iter 921: sigma_u = 0.0284, loglik = -104973.3331
Iter 922: sigma_u = 0.0284, loglik = -104973.3941
Iter 923: sigma_u = 0.0284, loglik = -104973.4745
Iter 924: sigma_u = 0.0284, loglik = -104973.5415
Iter 925: sigma_u = 0.0284, loglik = -104973.6114
Iter 926: sigma_u = 0.0284, loglik = -104973.6866
Iter 927: sigma_u = 0.0284, loglik = -104973.7468
Iter 928: sigma_u = 0.0284, loglik = -104973.8355
Iter 929: sigma_u = 0.0284, loglik = -104973.8865
Iter 930: sigma_u = 0.0284, loglik = -104973.9956
Iter 931: sigma_u = 0.0284, loglik = -104974.0382
Iter 932: sigma_u = 0.0284, loglik = -104974.2014
Iter 933: sigma_u = 0.0284, loglik = -104974.2364
Iter 934: sigma_u = 0.0284, loglik = -104974.6276
Iter 935: sigma_u = 0.0283, loglik = -104974.6544
Iter 936: sigma_u = 0.0283, loglik = -104980.2550
Iter 937: sigma_u = 0.0283, loglik = -104980.3007
Iter 938: sigma_u = 0.0283, loglik = -104980.5885
Iter 939: sigma_u = 0.0283, loglik = -104980.6342
Iter 940: sigma_u = 0.0283, loglik = -104980.8849
Iter 941: sigma_u = 0.0283, loglik = -104980.9312
Iter 942: sigma_u = 0.0283, loglik = -104981.1461
Iter 943: sigma_u = 0.0283, loglik = -104981.1929
Iter 944: sigma_u = 0.0283, loglik = -104981.3782
Iter 945: sigma_u = 0.0283, loglik = -104981.4255
Iter 946: sigma_u = 0.0283, loglik = -104981.5901
Iter 947: sigma_u = 0.0283, loglik = -104981.6382
Iter 948: sigma_u = 0.0283, loglik = -104981.7886
Iter 949: sigma_u = 0.0283, loglik = -104981.8376
Iter 950: sigma_u = 0.0283, loglik = -104981.9688
Iter 951: sigma_u = 0.0283, loglik = -104982.0194
Iter 952: sigma_u = 0.0283, loglik = -104982.1341
Iter 953: sigma_u = 0.0283, loglik = -104982.1858
Iter 954: sigma_u = 0.0283, loglik = -104982.2922
Iter 955: sigma_u = 0.0283, loglik = -104982.3465
Iter 956: sigma_u = 0.0283, loglik = -104982.4414
Iter 957: sigma_u = 0.0283, loglik = -104982.4975
Iter 958: sigma_u = 0.0283, loglik = -104982.5822
Iter 959: sigma_u = 0.0283, loglik = -104982.6432
Iter 960: sigma_u = 0.0283, loglik = -104982.7177
Iter 961: sigma_u = 0.0283, loglik = -104982.7823
Iter 962: sigma_u = 0.0283, loglik = -104982.8476
Iter 963: sigma_u = 0.0283, loglik = -104982.9198
Iter 964: sigma_u = 0.0283, loglik = -104982.9761
Iteration 964: beta norm = 2.1754122976204617, sigma_u = 0.0283
Iter 965: sigma_u = 0.0283, loglik = -104983.0624
Iter 966: sigma_u = 0.0282, loglik = -104983.1095
Iter 967: sigma_u = 0.0282, loglik = -104983.2238
Iter 968: sigma_u = 0.0282, loglik = -104983.2628
Iter 969: sigma_u = 0.0282, loglik = -104983.4457
Iter 970: sigma_u = 0.0282, loglik = -104983.4775
Iter 971: sigma_u = 0.0282, loglik = -104984.0179
Iter 972: sigma_u = 0.0282, loglik = -104984.0414
Iter 973: sigma_u = 0.0282, loglik = -104985.4254
Iter 974: sigma_u = 0.0282, loglik = -104985.4735
Iter 975: sigma_u = 0.0282, loglik = -104986.1002
Iter 976: sigma_u = 0.0282, loglik = -104986.1438
Iter 977: sigma_u = 0.0282, loglik = -104986.3403
Iter 978: sigma_u = 0.0282, loglik = -104986.3909
Iter 979: sigma_u = 0.0282, loglik = -104986.5047
Iter 980: sigma_u = 0.0282, loglik = -104986.5560
Iter 981: sigma_u = 0.0282, loglik = -104986.6556
Iter 982: sigma_u = 0.0282, loglik = -104986.7093

Iter 983: sigma_u = 0.0282, loglik = -104986.7999
Iter 984: sigma_u = 0.0282, loglik = -104986.8559
Iter 985: sigma_u = 0.0282, loglik = -104986.9348
Iter 986: sigma_u = 0.0282, loglik = -104986.9952
Iter 987: sigma_u = 0.0282, loglik = -104987.0645
Iter 988: sigma_u = 0.0282, loglik = -104987.1309
Iter 989: sigma_u = 0.0282, loglik = -104987.1904
Iter 990: sigma_u = 0.0282, loglik = -104987.2650
Iter 991: sigma_u = 0.0282, loglik = -104987.3173
Iter 992: sigma_u = 0.0282, loglik = -104987.4096
Iter 993: sigma_u = 0.0282, loglik = -104987.4532
Iter 994: sigma_u = 0.0282, loglik = -104987.5771
Iter 995: sigma_u = 0.0282, loglik = -104987.6134
Iter 996: sigma_u = 0.0282, loglik = -104987.8317
Iter 997: sigma_u = 0.0281, loglik = -104987.8605
Iter 998: sigma_u = 0.0281, loglik = -104988.8929
Iter 999: sigma_u = 0.0281, loglik = -104988.9121
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             1.50       1.446031     1.448748
1            -0.80      -0.816127    -0.817344
2             1.30       1.399794     1.401856
3             0.25       0.067455     0.028128



Time taken 8.342703000704448 minutes



Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 4.1896, loglik = -4661.8959
Iter 1: sigma_u = 3.4991, loglik = -4928.5238
Iter 2: sigma_u = 3.0708, loglik = -5094.5989
Iter 3: sigma_u = 2.7733, loglik = -5215.9459
Iter 4: sigma_u = 2.5452, loglik = -5323.1160
Iter 5: sigma_u = 2.3563, loglik = -5431.8621
Iter 6: sigma_u = 2.1909, loglik = -5550.5938
Iter 7: sigma_u = 2.0412, loglik = -5684.7290
Iter 8: sigma_u = 1.9033, loglik = -5838.3295
Iter 9: sigma_u = 1.7750, loglik = -6014.9609
Iter 10: sigma_u = 1.6554, loglik = -6218.1958
Iter 11: sigma_u = 1.5438, loglik = -6451.8721
Iter 12: sigma_u = 1.4397, loglik = -6720.3169
Iter 13: sigma_u = 1.3428, loglik = -7028.4704
Iter 14: sigma_u = 1.2524, loglik = -7381.9846
Iter 15: sigma_u = 1.1681, loglik = -7787.3087
Iter 16: sigma_u = 1.0896, loglik = -8251.7645
Iter 17: sigma_u = 1.0165, loglik = -8783.6359
Iter 18: sigma_u = 0.9484, loglik = -9392.2650
Iter 19: sigma_u = 0.8849, loglik = -10088.1290
Iter 20: sigma_u = 0.8258, loglik = -10882.9368
Iter 21: sigma_u = 0.7707, loglik = -11789.6945
Iter 22: sigma_u = 0.7195, loglik = -12822.7381
Iter 23: sigma_u = 0.6717, loglik = -13997.7371
Iter 24: sigma_u = 0.6273, loglik = -15331.6132
Iter 25: sigma_u = 0.5860, loglik = -16842.3194
Iter 26: sigma_u = 0.5475, loglik = -18548.4952
Iter 27: sigma_u = 0.5118, loglik = -20468.7569
Iter 28: sigma_u = 0.4786, loglik = -22620.4214
Iter 29: sigma_u = 0.4477, loglik = -25017.5116
Iter 30: sigma_u = 0.4191, loglik = -27667.4818
Iter 31: sigma_u = 0.3926, loglik = -30567.3943
Iter 32: sigma_u = 0.3680, loglik = -33700.7477
Iter 33: sigma_u = 0.3454, loglik = -37032.4847
Iter 34: sigma_u = 0.3245, loglik = -40511.7681
Iter 35: sigma_u = 0.3053, loglik = -44074.3210
Iter 36: sigma_u = 0.2877, loglik = -47648.6213
Iter 37: sigma_u = 0.2717, loglik = -51161.8825
Iter 38: sigma_u = 0.2572, loglik = -54550.1437
Iter 39: sigma_u = 0.2440, loglik = -57762.4712
Iter 40: sigma_u = 0.2320, loglik = -60763.4044
Iter 41: sigma_u = 0.2213, loglik = -63533.0784
Iter 42: sigma_u = 0.2116, loglik = -66064.9645
Iter 43: sigma_u = 0.2028, loglik = -68362.8395
Iter 44: sigma_u = 0.1949, loglik = -70436.7461
Iter 45: sigma_u = 0.1877, loglik = -72302.7789
Iter 46: sigma_u = 0.1812, loglik = -73978.8366
Iter 47: sigma_u = 0.1753, loglik = -75483.1540
Iter 48: sigma_u = 0.1700, loglik = -76833.8702
Iter 49: sigma_u = 0.1651, loglik = -78047.6569
Iter 50: sigma_u = 0.1607, loglik = -79139.8810
Iter 51: sigma_u = 0.1567, loglik = -80124.2790
Iter 52: sigma_u = 0.1529, loglik = -81013.4978
Iter 53: sigma_u = 0.1495, loglik = -81818.3641
Iter 54: sigma_u = 0.1464, loglik = -82548.4941
Iter 55: sigma_u = 0.1435, loglik = -83212.3559
Iter 56: sigma_u = 0.1408, loglik = -83817.4365
Iter 57: sigma_u = 0.1383, loglik = -84370.0262
Iter 58: sigma_u = 0.1360, loglik = -84875.8299
Iter 59: sigma_u = 0.1339, loglik = -85339.9285
Iter 60: sigma_u = 0.1319, loglik = -85766.6910
Iter 61: sigma_u = 0.1301, loglik = -86159.6628
Iter 62: sigma_u = 0.1283, loglik = -86523.2115
Iter 63: sigma_u = 0.1267, loglik = -86863.9716
Iter 64: sigma_u = 0.1252, loglik = -87164.4068
Iter 65: sigma_u = 0.1239, loglik = -87452.5029
Iter 66: sigma_u = 0.1225, loglik = -87706.9559
Iter 67: sigma_u = 0.1213, loglik = -87960.2069
Iter 68: sigma_u = 0.1201, loglik = -88186.2906
Iter 69: sigma_u = 0.1191, loglik = -88404.4084
Iter 70: sigma_u = 0.1181, loglik = -88598.7683
Iter 71: sigma_u = 0.1171, loglik = -88780.7017
Iter 72: sigma_u = 0.1162, loglik = -88960.2631
Iter 73: sigma_u = 0.1154, loglik = -89121.4252
Iter 74: sigma_u = 0.1145, loglik = -89272.6713
Iter 75: sigma_u = 0.1138, loglik = -89422.1883
Iter 76: sigma_u = 0.1130, loglik = -89557.1205
Iter 77: sigma_u = 0.1123, loglik = -89684.5990
Iter 78: sigma_u = 0.1117, loglik = -89806.3436
Iter 79: sigma_u = 0.1111, loglik = -89921.2320
Iter 80: sigma_u = 0.1105, loglik = -90030.1083
Iter 81: sigma_u = 0.1099, loglik = -90133.0891
Iter 82: sigma_u = 0.1094, loglik = -90230.8106
Iter 83: sigma_u = 0.1089, loglik = -90323.5823
Iter 84: sigma_u = 0.1084, loglik = -90411.5331
Iter 85: sigma_u = 0.1079, loglik = -90494.9870
Iter 86: sigma_u = 0.1075, loglik = -90574.3600
Iter 87: sigma_u = 0.1070, loglik = -90648.6051
Iter 88: sigma_u = 0.1066, loglik = -90720.7013
Iter 89: sigma_u = 0.1062, loglik = -90789.5268
Iter 90: sigma_u = 0.1058, loglik = -90855.2176
Iter 91: sigma_u = 0.1054, loglik = -90931.8478
Iter 92: sigma_u = 0.1050, loglik = -90991.1570
Iter 93: sigma_u = 0.1046, loglik = -91059.8856
Iter 94: sigma_u = 0.1042, loglik = -91124.0988
Iter 95: sigma_u = 0.1039, loglik = -91186.2127
Iter 96: sigma_u = 0.1036, loglik = -91243.2334
Iter 97: sigma_u = 0.1033, loglik = -91288.2973
Iter 98: sigma_u = 0.1030, loglik = -91339.6795
Iter 99: sigma_u = 0.1027, loglik = -91387.8125
Iter 100: sigma_u = 0.1025, loglik = -91433.9330
Iter 101: sigma_u = 0.1023, loglik = -91469.4572
Iter 102: sigma_u = 0.1020, loglik = -91511.8916
Iter 103: sigma_u = 0.1020, loglik = -91551.3689
Iter 104: sigma_u = 0.1019, loglik = -91557.5855
Iter 105: sigma_u = 0.1019, loglik = -91566.0695
Iter 106: sigma_u = 0.1018, loglik = -91572.3575
Iter 107: sigma_u = 0.1018, loglik = -91580.2104
Iter 108: sigma_u = 0.1018, loglik = -91586.5405
Iter 109: sigma_u = 0.1017, loglik = -91593.8892
Iter 110: sigma_u = 0.1017, loglik = -91600.3430
Iter 111: sigma_u = 0.1016, loglik = -91607.1613
Iter 112: sigma_u = 0.1016, loglik = -91613.7144
Iter 113: sigma_u = 0.1016, loglik = -91620.1561
Iter 114: sigma_u = 0.1015, loglik = -91626.7077
Iter 115: sigma_u = 0.1015, loglik = -91632.8322
Iter 116: sigma_u = 0.1014, loglik = -91639.4301
Iter 117: sigma_u = 0.1014, loglik = -91645.2780
Iter 118: sigma_u = 0.1014, loglik = -91651.8903
Iter 119: sigma_u = 0.1013, loglik = -91657.4963
Iter 120: sigma_u = 0.1013, loglik = -91664.1336
Iter 121: sigma_u = 0.1012, loglik = -91669.4925
Iter 122: sigma_u = 0.1012, loglik = -91676.1938
Iter 123: sigma_u = 0.1012, loglik = -91681.3226
Iter 124: sigma_u = 0.1011, loglik = -91688.0508
Iter 125: sigma_u = 0.1011, loglik = -91692.9540
Iter 126: sigma_u = 0.1011, loglik = -91699.6585
Iter 127: sigma_u = 0.1010, loglik = -91704.4057
Iter 128: sigma_u = 0.1010, loglik = -91711.0816
Iter 129: sigma_u = 0.1010, loglik = -91715.6753
Iter 130: sigma_u = 0.1009, loglik = -91722.3465
Iter 131: sigma_u = 0.1009, loglik = -91726.7681
Iter 132: sigma_u = 0.1009, loglik = -91733.4740
Iter 133: sigma_u = 0.1008, loglik = -91737.7383
Iter 134: sigma_u = 0.1008, loglik = -91744.4584
Iter 135: sigma_u = 0.1008, loglik = -91748.5888
Iter 136: sigma_u = 0.1007, loglik = -91755.2161
Iter 137: sigma_u = 0.1007, loglik = -91759.1900
Iter 138: sigma_u = 0.1007, loglik = -91765.7605
Iter 139: sigma_u = 0.1006, loglik = -91769.6363
Iter 140: sigma_u = 0.1006, loglik = -91776.2361
Iter 141: sigma_u = 0.1006, loglik = -91779.9788
Iter 142: sigma_u = 0.1005, loglik = -91786.5172
Iter 143: sigma_u = 0.1005, loglik = -91790.1455
Iter 144: sigma_u = 0.1005, loglik = -91796.5273
Iter 145: sigma_u = 0.1004, loglik = -91800.0659
Iter 146: sigma_u = 0.1004, loglik = -91806.4769
Iter 147: sigma_u = 0.1004, loglik = -91809.9214
Iter 148: sigma_u = 0.1004, loglik = -91816.1590
Iter 149: sigma_u = 0.1003, loglik = -91819.5072
Iter 150: sigma_u = 0.1003, loglik = -91825.6003
Iter 151: sigma_u = 0.1003, loglik = -91828.8876
Iter 152: sigma_u = 0.1002, loglik = -91834.8729
Iter 153: sigma_u = 0.1002, loglik = -91838.0840
Iter 154: sigma_u = 0.1002, loglik = -91843.9877
Iter 155: sigma_u = 0.1001, loglik = -91847.1157
Iter 156: sigma_u = 0.1001, loglik = -91853.0019
Iter 157: sigma_u = 0.1001, loglik = -91856.0252
Iter 158: sigma_u = 0.1001, loglik = -91861.7011
Iteration 158: beta norm = 5.062173477593029, sigma_u = 0.1001
Iter 159: sigma_u = 0.1000, loglik = -91864.6750
Iter 160: sigma_u = 0.1000, loglik = -91870.2450
Iter 161: sigma_u = 0.1000, loglik = -91873.1422
Iter 162: sigma_u = 0.1000, loglik = -91878.6971
Iter 163: sigma_u = 0.0999, loglik = -91881.5226
Iter 164: sigma_u = 0.0999, loglik = -91887.0928
Iter 165: sigma_u = 0.0999, loglik = -91889.8176
Iter 166: sigma_u = 0.0999, loglik = -91895.3135
Iter 167: sigma_u = 0.0998, loglik = -91897.9621
Iter 168: sigma_u = 0.0998, loglik = -91903.3104

Iter 169: sigma_u = 0.0998, loglik = -91905.9265
Iter 170: sigma_u = 0.0998, loglik = -91911.0281
Iter 171: sigma_u = 0.0997, loglik = -91913.6216
Iter 172: sigma_u = 0.0997, loglik = -91918.5298
Iter 173: sigma_u = 0.0997, loglik = -91921.0771
Iter 174: sigma_u = 0.0997, loglik = -91925.9028
Iter 175: sigma_u = 0.0996, loglik = -91928.3886
Iter 176: sigma_u = 0.0996, loglik = -91933.1322
Iter 177: sigma_u = 0.0996, loglik = -91935.5769
Iter 178: sigma_u = 0.0996, loglik = -91940.2650
Iter 179: sigma_u = 0.0996, loglik = -91942.6327
Iter 180: sigma_u = 0.0995, loglik = -91947.2126
Iter 181: sigma_u = 0.0995, loglik = -91949.5288
Iter 182: sigma_u = 0.0995, loglik = -91954.0912
Iter 183: sigma_u = 0.0995, loglik = -91956.3647
Iter 184: sigma_u = 0.0995, loglik = -91960.7135
Iter 185: sigma_u = 0.0994, loglik = -91962.9424
Iter 186: sigma_u = 0.0994, loglik = -91967.3434
Iter 187: sigma_u = 0.0994, loglik = -91969.4964
Iter 188: sigma_u = 0.0994, loglik = -91973.7806
Iter 189: sigma_u = 0.0993, loglik = -91975.9016
Iter 190: sigma_u = 0.0993, loglik = -91980.0980
Iter 191: sigma_u = 0.0993, loglik = -91982.1492
Iter 192: sigma_u = 0.0993, loglik = -91986.3596
Iter 193: sigma_u = 0.0993, loglik = -91988.3739
Iter 194: sigma_u = 0.0993, loglik = -91992.5337
Iter 195: sigma_u = 0.0992, loglik = -91994.4971
Iter 196: sigma_u = 0.0992, loglik = -91998.5200
Iter 197: sigma_u = 0.0992, loglik = -92000.4420
Iter 198: sigma_u = 0.0992, loglik = -92004.4060
Iter 199: sigma_u = 0.0992, loglik = -92006.2773
Iter 200: sigma_u = 0.0991, loglik = -92010.1628
Iter 201: sigma_u = 0.0991, loglik = -92011.9789
Iter 202: sigma_u = 0.0991, loglik = -92015.7397
Iter 203: sigma_u = 0.0991, loglik = -92017.5373
Iter 204: sigma_u = 0.0991, loglik = -92021.2397
Iter 205: sigma_u = 0.0991, loglik = -92023.0045
Iter 206: sigma_u = 0.0990, loglik = -92026.6654
Iter 207: sigma_u = 0.0990, loglik = -92028.3715
Iter 208: sigma_u = 0.0990, loglik = -92031.9548
Iter 209: sigma_u = 0.0990, loglik = -92033.6283
Iter 210: sigma_u = 0.0990, loglik = -92037.3024
Iter 211: sigma_u = 0.0990, loglik = -92038.9137
Iter 212: sigma_u = 0.0989, loglik = -92042.6146
Iter 213: sigma_u = 0.0989, loglik = -92044.1743
Iter 214: sigma_u = 0.0989, loglik = -92047.7162
Iter 215: sigma_u = 0.0989, loglik = -92049.2303
Iter 216: sigma_u = 0.0989, loglik = -92052.8016
Iter 217: sigma_u = 0.0989, loglik = -92054.2893
Iter 218: sigma_u = 0.0989, loglik = -92057.6153
Iter 219: sigma_u = 0.0988, loglik = -92059.0818
Iter 220: sigma_u = 0.0988, loglik = -92062.3512
Iter 221: sigma_u = 0.0988, loglik = -92063.7996
Iter 222: sigma_u = 0.0988, loglik = -92067.0167
Iter 223: sigma_u = 0.0988, loglik = -92068.4449
Iter 224: sigma_u = 0.0988, loglik = -92071.5066
Iter 225: sigma_u = 0.0987, loglik = -92072.9105
Iter 226: sigma_u = 0.0987, loglik = -92075.9343
Iter 227: sigma_u = 0.0987, loglik = -92077.3118
Iter 228: sigma_u = 0.0987, loglik = -92080.2478
Iter 229: sigma_u = 0.0987, loglik = -92081.5807
Iter 230: sigma_u = 0.0987, loglik = -92084.3630
Iter 231: sigma_u = 0.0987, loglik = -92085.7031
Iter 232: sigma_u = 0.0987, loglik = -92088.3482
Iter 233: sigma_u = 0.0986, loglik = -92089.6498
Iter 234: sigma_u = 0.0986, loglik = -92092.3740
Iter 235: sigma_u = 0.0986, loglik = -92093.6338
Iter 236: sigma_u = 0.0986, loglik = -92096.3197
Iter 237: sigma_u = 0.0986, loglik = -92097.5742
Iter 238: sigma_u = 0.0986, loglik = -92100.3008
Iter 239: sigma_u = 0.0986, loglik = -92101.5030
Iter 240: sigma_u = 0.0986, loglik = -92104.0741
Iter 241: sigma_u = 0.0985, loglik = -92105.2579
Iter 242: sigma_u = 0.0985, loglik = -92107.7800
Iter 243: sigma_u = 0.0985, loglik = -92108.9448
Iter 244: sigma_u = 0.0985, loglik = -92111.4585
Iter 245: sigma_u = 0.0985, loglik = -92112.6100
Iter 246: sigma_u = 0.0985, loglik = -92115.0367
Iter 247: sigma_u = 0.0985, loglik = -92116.1564
Iter 248: sigma_u = 0.0985, loglik = -92118.4519
Iter 249: sigma_u = 0.0985, loglik = -92119.5713
Iter 250: sigma_u = 0.0984, loglik = -92121.8016
Iter 251: sigma_u = 0.0984, loglik = -92122.8956
Iter 252: sigma_u = 0.0984, loglik = -92125.0412
Iter 253: sigma_u = 0.0984, loglik = -92126.1260
Iter 254: sigma_u = 0.0984, loglik = -92128.1830
Iter 255: sigma_u = 0.0984, loglik = -92129.2412
Iter 256: sigma_u = 0.0984, loglik = -92131.3293
Iter 257: sigma_u = 0.0984, loglik = -92132.3609
Iter 258: sigma_u = 0.0984, loglik = -92134.4079
Iter 259: sigma_u = 0.0984, loglik = -92135.4203
Iter 260: sigma_u = 0.0983, loglik = -92137.4666
Iter 261: sigma_u = 0.0983, loglik = -92138.4516
Iter 262: sigma_u = 0.0983, loglik = -92140.4413
Iter 263: sigma_u = 0.0983, loglik = -92141.4218
Iter 264: sigma_u = 0.0983, loglik = -92143.3212
Iter 265: sigma_u = 0.0983, loglik = -92144.2855
Iter 266: sigma_u = 0.0983, loglik = -92146.1911
Iter 267: sigma_u = 0.0983, loglik = -92147.1237
Iter 268: sigma_u = 0.0983, loglik = -92149.1130
Iter 269: sigma_u = 0.0983, loglik = -92150.0056
Iter 270: sigma_u = 0.0983, loglik = -92151.8615
Iter 271: sigma_u = 0.0982, loglik = -92152.7491
Iter 272: sigma_u = 0.0982, loglik = -92154.5134
Iter 273: sigma_u = 0.0982, loglik = -92155.3827
Iter 274: sigma_u = 0.0982, loglik = -92157.1531
Iter 275: sigma_u = 0.0982, loglik = -92157.9917
Iter 276: sigma_u = 0.0982, loglik = -92159.8511
Iter 277: sigma_u = 0.0982, loglik = -92160.6545
Iter 278: sigma_u = 0.0982, loglik = -92162.3485
Iter 279: sigma_u = 0.0982, loglik = -92163.1555
Iter 280: sigma_u = 0.0982, loglik = -92164.9271
Iter 281: sigma_u = 0.0982, loglik = -92165.7043
Iter 282: sigma_u = 0.0982, loglik = -92167.3909
Iter 283: sigma_u = 0.0981, loglik = -92168.1835
Iter 284: sigma_u = 0.0981, loglik = -92169.7498
Iter 285: sigma_u = 0.0981, loglik = -92170.5429
Iter 286: sigma_u = 0.0981, loglik = -92172.0883
Iter 287: sigma_u = 0.0981, loglik = -92172.8514
Iter 288: sigma_u = 0.0981, loglik = -92174.3136
Iter 289: sigma_u = 0.0981, loglik = -92175.0629
Iter 290: sigma_u = 0.0981, loglik = -92176.5516
Iter 291: sigma_u = 0.0981, loglik = -92177.3006
Iter 292: sigma_u = 0.0981, loglik = -92178.7689
Iter 293: sigma_u = 0.0981, loglik = -92179.5004
Iter 294: sigma_u = 0.0981, loglik = -92180.8651
Iter 295: sigma_u = 0.0981, loglik = -92181.5842
Iter 296: sigma_u = 0.0981, loglik = -92182.9275
Iter 297: sigma_u = 0.0981, loglik = -92183.6342
Iter 298: sigma_u = 0.0980, loglik = -92184.9825
Iter 299: sigma_u = 0.0980, loglik = -92185.6755
Iter 300: sigma_u = 0.0980, loglik = -92187.0669
Iter 301: sigma_u = 0.0980, loglik = -92187.7407
Iter 302: sigma_u = 0.0980, loglik = -92189.0061
Iter 303: sigma_u = 0.0980, loglik = -92189.6813
Iter 304: sigma_u = 0.0980, loglik = -92190.9464
Iter 305: sigma_u = 0.0980, loglik = -92191.6041
Iter 306: sigma_u = 0.0980, loglik = -92192.7497
Iter 307: sigma_u = 0.0980, loglik = -92193.3936
Iter 308: sigma_u = 0.0980, loglik = -92194.5170
Iter 309: sigma_u = 0.0980, loglik = -92195.1777
Iter 310: sigma_u = 0.0980, loglik = -92196.2673
Iter 311: sigma_u = 0.0980, loglik = -92196.9146
Iter 312: sigma_u = 0.0980, loglik = -92198.1226
Iter 313: sigma_u = 0.0980, loglik = -92198.7261
Iter 314: sigma_u = 0.0980, loglik = -92199.8778
Iter 315: sigma_u = 0.0979, loglik = -92200.4625
Iter 316: sigma_u = 0.0979, loglik = -92201.5934
Iter 317: sigma_u = 0.0979, loglik = -92202.1938
Iter 318: sigma_u = 0.0979, loglik = -92203.2379
Iter 319: sigma_u = 0.0979, loglik = -92203.8100
Iter 320: sigma_u = 0.0979, loglik = -92204.8556
Iter 321: sigma_u = 0.0979, loglik = -92205.4539
Iter 322: sigma_u = 0.0979, loglik = -92206.4633
Iter 323: sigma_u = 0.0979, loglik = -92207.0265
Iter 324: sigma_u = 0.0979, loglik = -92208.1007
Iter 325: sigma_u = 0.0979, loglik = -92208.6329
Iter 326: sigma_u = 0.0979, loglik = -92209.6217
Iter 327: sigma_u = 0.0979, loglik = -92210.1692
Iter 328: sigma_u = 0.0979, loglik = -92211.1344
Iter 329: sigma_u = 0.0979, loglik = -92211.6798
Iter 330: sigma_u = 0.0979, loglik = -92212.6102
Iter 331: sigma_u = 0.0979, loglik = -92213.1422
Iter 332: sigma_u = 0.0979, loglik = -92214.0737
Iter 333: sigma_u = 0.0979, loglik = -92214.5900
Iter 334: sigma_u = 0.0979, loglik = -92215.4984
Iter 335: sigma_u = 0.0978, loglik = -92215.9837
Iter 336: sigma_u = 0.0978, loglik = -92216.9907

Iter 337: sigma_u = 0.0978, loglik = -92217.4522
Iter 338: sigma_u = 0.0978, loglik = -92218.5089
Iter 339: sigma_u = 0.0978, loglik = -92218.9627
Iter 340: sigma_u = 0.0978, loglik = -92219.9506
Iter 341: sigma_u = 0.0978, loglik = -92220.3873
Iter 342: sigma_u = 0.0978, loglik = -92221.4267
Iter 343: sigma_u = 0.0978, loglik = -92221.8384
Iter 344: sigma_u = 0.0978, loglik = -92222.9763
Iter 345: sigma_u = 0.0978, loglik = -92223.3781
Iter 346: sigma_u = 0.0978, loglik = -92224.4610
Iter 347: sigma_u = 0.0978, loglik = -92224.8487
Iter 348: sigma_u = 0.0978, loglik = -92225.9750
Iter 349: sigma_u = 0.0978, loglik = -92226.3404
Iter 350: sigma_u = 0.0978, loglik = -92227.5925
Iter 351: sigma_u = 0.0978, loglik = -92227.9304
Iter 352: sigma_u = 0.0978, loglik = -92229.4106
Iter 353: sigma_u = 0.0978, loglik = -92229.7356
Iter 354: sigma_u = 0.0978, loglik = -92230.8934
Iter 355: sigma_u = 0.0978, loglik = -92231.2153
Iter 356: sigma_u = 0.0977, loglik = -92232.4332
Iter 357: sigma_u = 0.0977, loglik = -92232.7622
Iter 358: sigma_u = 0.0977, loglik = -92233.9800
Iter 359: sigma_u = 0.0977, loglik = -92234.3017
Iter 360: sigma_u = 0.0977, loglik = -92235.3682
Iter 361: sigma_u = 0.0977, loglik = -92235.6889
Iter 362: sigma_u = 0.0977, loglik = -92236.6677
Iter 363: sigma_u = 0.0977, loglik = -92236.9751
Iter 364: sigma_u = 0.0977, loglik = -92237.7663
Iter 365: sigma_u = 0.0977, loglik = -92238.0801
Iter 366: sigma_u = 0.0977, loglik = -92238.7882
Iter 367: sigma_u = 0.0977, loglik = -92239.1230
Iter 368: sigma_u = 0.0977, loglik = -92239.8020
Iter 369: sigma_u = 0.0977, loglik = -92240.1276
Iter 370: sigma_u = 0.0977, loglik = -92240.7699
Iter 371: sigma_u = 0.0977, loglik = -92241.1003
Iter 372: sigma_u = 0.0977, loglik = -92241.7706
Iter 373: sigma_u = 0.0977, loglik = -92242.0756
Iter 374: sigma_u = 0.0977, loglik = -92242.7265
Iter 375: sigma_u = 0.0977, loglik = -92243.0315
Iter 376: sigma_u = 0.0977, loglik = -92243.6280
Iter 377: sigma_u = 0.0977, loglik = -92243.9411
Iter 378: sigma_u = 0.0977, loglik = -92244.4451
Iter 379: sigma_u = 0.0977, loglik = -92244.7724
Iter 380: sigma_u = 0.0977, loglik = -92245.2579
Iter 381: sigma_u = 0.0977, loglik = -92245.5852
Iter 382: sigma_u = 0.0977, loglik = -92245.9844
Iter 383: sigma_u = 0.0977, loglik = -92246.3606
Iter 384: sigma_u = 0.0977, loglik = -92246.7829
Iter 385: sigma_u = 0.0977, loglik = -92247.1220
Iter 386: sigma_u = 0.0977, loglik = -92247.5974
Iter 387: sigma_u = 0.0976, loglik = -92247.9143
Iter 388: sigma_u = 0.0976, loglik = -92248.4167
Iter 389: sigma_u = 0.0976, loglik = -92248.7022
Iter 390: sigma_u = 0.0976, loglik = -92249.2423
Iter 391: sigma_u = 0.0976, loglik = -92249.5037
Iter 392: sigma_u = 0.0976, loglik = -92249.9844
Iter 393: sigma_u = 0.0976, loglik = -92250.2640
Iter 394: sigma_u = 0.0976, loglik = -92250.7446
Iter 395: sigma_u = 0.0976, loglik = -92251.0144
Iter 396: sigma_u = 0.0976, loglik = -92251.4950
Iter 397: sigma_u = 0.0976, loglik = -92251.7631
Iter 398: sigma_u = 0.0976, loglik = -92252.3409
Iter 399: sigma_u = 0.0976, loglik = -92252.5768
Iter 400: sigma_u = 0.0976, loglik = -92253.1377
Iter 401: sigma_u = 0.0976, loglik = -92253.3807
Iter 402: sigma_u = 0.0976, loglik = -92253.8647
Iter 403: sigma_u = 0.0976, loglik = -92254.0951
Iter 404: sigma_u = 0.0976, loglik = -92254.6197
Iter 405: sigma_u = 0.0976, loglik = -92254.8501
Iter 406: sigma_u = 0.0976, loglik = -92255.5699
Iter 407: sigma_u = 0.0976, loglik = -92255.7731
Iter 408: sigma_u = 0.0976, loglik = -92256.4346
Iter 409: sigma_u = 0.0976, loglik = -92256.6303
Iter 410: sigma_u = 0.0976, loglik = -92257.2560
Iter 411: sigma_u = 0.0976, loglik = -92257.4610
Iter 412: sigma_u = 0.0976, loglik = -92258.0867
Iter 413: sigma_u = 0.0976, loglik = -92258.2817
Iter 414: sigma_u = 0.0976, loglik = -92258.7901
Iter 415: sigma_u = 0.0976, loglik = -92258.9717
Iter 416: sigma_u = 0.0976, loglik = -92259.4663
Iter 417: sigma_u = 0.0976, loglik = -92259.6584
Iter 418: sigma_u = 0.0976, loglik = -92260.0666
Iter 419: sigma_u = 0.0976, loglik = -92260.2450
Iter 420: sigma_u = 0.0976, loglik = -92260.7836
Iter 421: sigma_u = 0.0976, loglik = -92260.9520
Iter 422: sigma_u = 0.0976, loglik = -92261.5764
Iter 423: sigma_u = 0.0976, loglik = -92261.7325
Iter 424: sigma_u = 0.0976, loglik = -92262.3235
Iter 425: sigma_u = 0.0976, loglik = -92262.4890
Iter 426: sigma_u = 0.0976, loglik = -92263.0209
Iter 427: sigma_u = 0.0976, loglik = -92263.1893
Iter 428: sigma_u = 0.0976, loglik = -92263.6094
Iter 429: sigma_u = 0.0975, loglik = -92263.7616
Iter 430: sigma_u = 0.0975, loglik = -92264.4684
Iter 431: sigma_u = 0.0975, loglik = -92264.6152
Iter 432: sigma_u = 0.0975, loglik = -92265.0614
Iter 433: sigma_u = 0.0975, loglik = -92265.2128
Iter 434: sigma_u = 0.0975, loglik = -92265.6590
Iter 435: sigma_u = 0.0975, loglik = -92265.7971
Iter 436: sigma_u = 0.0975, loglik = -92266.3956
Iter 437: sigma_u = 0.0975, loglik = -92266.5267
Iter 438: sigma_u = 0.0975, loglik = -92267.2620
Iter 439: sigma_u = 0.0975, loglik = -92267.3927
Iter 440: sigma_u = 0.0975, loglik = -92267.9621
Iter 441: sigma_u = 0.0975, loglik = -92268.0758
Iter 442: sigma_u = 0.0975, loglik = -92268.6938
Iter 443: sigma_u = 0.0975, loglik = -92268.8110
Iter 444: sigma_u = 0.0975, loglik = -92269.2143
Iter 445: sigma_u = 0.0975, loglik = -92269.3391
Iter 446: sigma_u = 0.0975, loglik = -92269.6981
Iter 447: sigma_u = 0.0975, loglik = -92269.8230
Iter 448: sigma_u = 0.0975, loglik = -92270.2262
Iter 449: sigma_u = 0.0975, loglik = -92270.3568
Iter 450: sigma_u = 0.0975, loglik = -92270.7600
Iter 451: sigma_u = 0.0975, loglik = -92270.8848
Iter 452: sigma_u = 0.0975, loglik = -92271.2035
Iter 453: sigma_u = 0.0975, loglik = -92271.3116
Iter 454: sigma_u = 0.0975, loglik = -92271.7148
Iter 455: sigma_u = 0.0975, loglik = -92271.8167
Iter 456: sigma_u = 0.0975, loglik = -92272.0982
Iter 457: sigma_u = 0.0975, loglik = -92272.2158
✅ Converged at iteration 458
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0           -1.438      -1.426886    -1.426367
1            4.847       4.833170     4.831289
2           -0.444      -0.433701    -0.433505
3            0.250       0.410728     0.097495



Time taken 3.942484931151072 minutes



Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.7040, loglik = -22127.6336
Iter 1: sigma_u = 0.5608, loglik = -25104.9599
Iter 2: sigma_u = 0.4476, loglik = -30089.8669
Iter 3: sigma_u = 0.3586, loglik = -37533.7972
Iter 4: sigma_u = 0.2892, loglik = -47811.6227
Iter 5: sigma_u = 0.2363, loglik = -60060.9620
Iter 6: sigma_u = 0.1971, loglik = -72037.7200
Iter 7: sigma_u = 0.1687, loglik = -81794.2186
Iter 8: sigma_u = 0.1480, loglik = -88872.6419
Iter 9: sigma_u = 0.1327, loglik = -93786.3130
Iter 10: sigma_u = 0.1210, loglik = -97204.3268
Iter 11: sigma_u = 0.1119, loglik = -99636.3231
Iter 12: sigma_u = 0.1046, loglik = -101417.4144
Iter 13: sigma_u = 0.0987, loglik = -102759.2496
Iter 14: sigma_u = 0.0938, loglik = -103796.3664
Iter 15: sigma_u = 0.0896, loglik = -104616.2376
Iter 16: sigma_u = 0.0861, loglik = -105277.0637
Iter 17: sigma_u = 0.0831, loglik = -105819.5045
Iter 18: sigma_u = 0.0805, loglik = -106269.8608
Iter 19: sigma_u = 0.0782, loglik = -106649.1173
Iter 20: sigma_u = 0.0761, loglik = -106972.7509
Iter 21: sigma_u = 0.0743, loglik = -107252.1133
Iter 22: sigma_u = 0.0727, loglik = -107493.5235
Iter 23: sigma_u = 0.0713, loglik = -107704.4614
Iter 24: sigma_u = 0.0699, loglik = -107889.5041
Iter 25: sigma_u = 0.0688, loglik = -108053.9669
Iter 26: sigma_u = 0.0677, loglik = -108200.6131
Iter 27: sigma_u = 0.0667, loglik = -108331.6212
Iter 28: sigma_u = 0.0658, loglik = -108449.5408
Iter 29: sigma_u = 0.0650, loglik = -108555.8944
Iter 30: sigma_u = 0.0642, loglik = -108651.4901
Iter 31: sigma_u = 0.0635, loglik = -108737.0394
Iter 32: sigma_u = 0.0629, loglik = -108816.3338
Iter 33: sigma_u = 0.0623, loglik = -108889.2436
Iter 34: sigma_u = 0.0618, loglik = -108955.8498
Iter 35: sigma_u = 0.0613, loglik = -109015.3901
Iter 36: sigma_u = 0.0608, loglik = -109071.3174
Iter 37: sigma_u = 0.0603, loglik = -109123.1303
Iter 38: sigma_u = 0.0599, loglik = -109170.8576
Iter 39: sigma_u = 0.0596, loglik = -109214.8873
Iter 40: sigma_u = 0.0592, loglik = -109255.7966
Iter 41: sigma_u = 0.0589, loglik = -109293.6614
Iter 42: sigma_u = 0.0586, loglik = -109328.9641
Iter 43: sigma_u = 0.0582, loglik = -109361.1594
Iter 44: sigma_u = 0.0579, loglik = -109399.8701
Iter 45: sigma_u = 0.0577, loglik = -109426.2473
Iter 46: sigma_u = 0.0574, loglik = -109450.7835
Iter 47: sigma_u = 0.0573, loglik = -109477.4028
Iter 48: sigma_u = 0.0571, loglik = -109495.2745
Iter 49: sigma_u = 0.0569, loglik = -109513.1592
Iter 50: sigma_u = 0.0567, loglik = -109530.7697
Iter 51: sigma_u = 0.0566, loglik = -109549.0790
Iter 52: sigma_u = 0.0565, loglik = -109562.7746
Iter 53: sigma_u = 0.0563, loglik = -109576.9557
Iter 54: sigma_u = 0.0562, loglik = -109590.9943
Iter 55: sigma_u = 0.0561, loglik = -109605.0326
Iter 56: sigma_u = 0.0559, loglik = -109616.9017
Iter 57: sigma_u = 0.0558, loglik = -109629.4618
Iter 58: sigma_u = 0.0557, loglik = -109641.4434
Iter 59: sigma_u = 0.0556, loglik = -109652.9964
Iter 60: sigma_u = 0.0555, loglik = -109662.8339
Iter 61: sigma_u = 0.0554, loglik = -109671.3151
Iter 62: sigma_u = 0.0553, loglik = -109680.5846
Iter 63: sigma_u = 0.0553, loglik = -109688.8394
Iter 64: sigma_u = 0.0552, loglik = -109695.8706
Iter 65: sigma_u = 0.0551, loglik = -109703.4212
Iter 66: sigma_u = 0.0551, loglik = -109709.8661
Iter 67: sigma_u = 0.0551, loglik = -109713.2758
Iter 68: sigma_u = 0.0551, loglik = -109713.6341
Iter 69: sigma_u = 0.0550, loglik = -109717.9342
Iter 70: sigma_u = 0.0549, loglik = -109718.2690
Iter 71: sigma_u = 0.0549, loglik = -109728.4273
Iter 72: sigma_u = 0.0549, loglik = -109728.8641
Iter 73: sigma_u = 0.0549, loglik = -109730.0704
Iter 74: sigma_u = 0.0549, loglik = -109730.4745
Iter 75: sigma_u = 0.0549, loglik = -109732.0281
Iter 76: sigma_u = 0.0549, loglik = -109732.3976
Iter 77: sigma_u = 0.0549, loglik = -109734.7336
Iter 78: sigma_u = 0.0548, loglik = -109735.0691
Iter 79: sigma_u = 0.0548, loglik = -109739.5061
Iter 80: sigma_u = 0.0547, loglik = -109739.8147
Iter 81: sigma_u = 0.0547, loglik = -109748.1806
Iter 82: sigma_u = 0.0547, loglik = -109748.4852
Iter 83: sigma_u = 0.0547, loglik = -109751.7582
Iter 84: sigma_u = 0.0546, loglik = -109752.0379
Iter 85: sigma_u = 0.0546, loglik = -109758.9168
Iter 86: sigma_u = 0.0546, loglik = -109759.1851
Iter 87: sigma_u = 0.0546, loglik = -109764.1176
Iter 88: sigma_u = 0.0545, loglik = -109764.3654
Iter 89: sigma_u = 0.0545, loglik = -109771.4729
Iter 90: sigma_u = 0.0545, loglik = -109771.7313
Iter 91: sigma_u = 0.0545, loglik = -109773.4753
Iter 92: sigma_u = 0.0544, loglik = -109773.7115
Iter 93: sigma_u = 0.0544, loglik = -109777.0595
Iter 94: sigma_u = 0.0544, loglik = -109777.2766
Iter 95: sigma_u = 0.0544, loglik = -109783.6625
Iter 96: sigma_u = 0.0544, loglik = -109783.9006
Iter 97: sigma_u = 0.0544, loglik = -109785.0984
Iter 98: sigma_u = 0.0543, loglik = -109785.3158
Iter 99: sigma_u = 0.0543, loglik = -109787.3058
Iter 100: sigma_u = 0.0543, loglik = -109787.5029
Iter 101: sigma_u = 0.0543, loglik = -109791.7866
Iter 102: sigma_u = 0.0542, loglik = -109791.9713
Iter 103: sigma_u = 0.0542, loglik = -109796.7214
Iter 104: sigma_u = 0.0542, loglik = -109796.9010
Iter 105: sigma_u = 0.0542, loglik = -109799.8450
Iter 106: sigma_u = 0.0542, loglik = -109800.0112
Iter 107: sigma_u = 0.0542, loglik = -109804.9991
Iter 108: sigma_u = 0.0542, loglik = -109805.1824
Iter 109: sigma_u = 0.0542, loglik = -109805.9964
Iter 110: sigma_u = 0.0541, loglik = -109806.1631
Iter 111: sigma_u = 0.0541, loglik = -109807.4884
Iter 112: sigma_u = 0.0541, loglik = -109807.6404
Iter 113: sigma_u = 0.0541, loglik = -109810.3713
Iter 114: sigma_u = 0.0541, loglik = -109810.5119
Iter 115: sigma_u = 0.0541, loglik = -109814.8195
Iter 116: sigma_u = 0.0541, loglik = -109814.9810
Iter 117: sigma_u = 0.0541, loglik = -109815.6221
Iter 118: sigma_u = 0.0540, loglik = -109815.7687
Iter 119: sigma_u = 0.0540, loglik = -109816.7055
Iter 120: sigma_u = 0.0540, loglik = -109816.8401
Iter 121: sigma_u = 0.0540, loglik = -109818.6607
Iter 122: sigma_u = 0.0540, loglik = -109818.7843
Iter 123: sigma_u = 0.0540, loglik = -109822.2791
Iter 124: sigma_u = 0.0540, loglik = -109822.4016
Iter 125: sigma_u = 0.0540, loglik = -109823.7941
Iter 126: sigma_u = 0.0539, loglik = -109823.9079
Iter 127: sigma_u = 0.0539, loglik = -109827.0313
Iter 128: sigma_u = 0.0539, loglik = -109827.1453
Iter 129: sigma_u = 0.0539, loglik = -109828.2200
Iter 130: sigma_u = 0.0539, loglik = -109828.3252
Iter 131: sigma_u = 0.0539, loglik = -109830.6540
Iter 132: sigma_u = 0.0539, loglik = -109830.7512
Iter 133: sigma_u = 0.0539, loglik = -109833.4984
Iter 134: sigma_u = 0.0539, loglik = -109833.5980
Iter 135: sigma_u = 0.0539, loglik = -109834.5227
Iter 136: sigma_u = 0.0538, loglik = -109834.6133
Iter 137: sigma_u = 0.0538, loglik = -109836.7161
Iter 138: sigma_u = 0.0538, loglik = -109836.8024
Iter 139: sigma_u = 0.0538, loglik = -109838.7277
Iter 140: sigma_u = 0.0538, loglik = -109838.8062
Iter 141: sigma_u = 0.0538, loglik = -109841.0583
Iter 142: sigma_u = 0.0538, loglik = -109841.1399
Iter 143: sigma_u = 0.0538, loglik = -109841.9096
Iter 144: sigma_u = 0.0538, loglik = -109841.9834
Iter 145: sigma_u = 0.0538, loglik = -109843.5315
Iter 146: sigma_u = 0.0537, loglik = -109843.6015
Iter 147: sigma_u = 0.0537, loglik = -109845.6285
Iter 148: sigma_u = 0.0537, loglik = -109845.7004
Iter 149: sigma_u = 0.0537, loglik = -109846.2664
Iter 150: sigma_u = 0.0537, loglik = -109846.3325
Iter 151: sigma_u = 0.0537, loglik = -109847.5086
Iter 152: sigma_u = 0.0537, loglik = -109847.5694
Iter 153: sigma_u = 0.0537, loglik = -109849.5381
Iter 154: sigma_u = 0.0537, loglik = -109849.6682
Iter 155: sigma_u = 0.0537, loglik = -109849.7531
Iter 156: sigma_u = 0.0537, loglik = -109849.8961
Iter 157: sigma_u = 0.0537, loglik = -109849.9780
Iter 158: sigma_u = 0.0537, loglik = -109850.1277
Iter 159: sigma_u = 0.0537, loglik = -109850.2038
Iter 160: sigma_u = 0.0537, loglik = -109850.3629
Iter 161: sigma_u = 0.0537, loglik = -109850.4338
Iter 162: sigma_u = 0.0537, loglik = -109850.6213
Iter 163: sigma_u = 0.0537, loglik = -109850.6876
Iter 164: sigma_u = 0.0537, loglik = -109850.8950
Iter 165: sigma_u = 0.0537, loglik = -109850.9568
Iter 166: sigma_u = 0.0537, loglik = -109851.2301

Iter 167: sigma_u = 0.0537, loglik = -109851.2866
Iter 168: sigma_u = 0.0537, loglik = -109851.6216
Iter 169: sigma_u = 0.0537, loglik = -109851.6745
Iter 170: sigma_u = 0.0537, loglik = -109852.1573
Iter 171: sigma_u = 0.0537, loglik = -109852.2063
Iter 172: sigma_u = 0.0537, loglik = -109853.0296
Iter 173: sigma_u = 0.0537, loglik = -109853.0744
Iter 174: sigma_u = 0.0537, loglik = -109854.3186
Iter 175: sigma_u = 0.0536, loglik = -109854.3638
Iter 176: sigma_u = 0.0536, loglik = -109854.9964
Iter 177: sigma_u = 0.0536, loglik = -109855.0383
Iter 178: sigma_u = 0.0536, loglik = -109856.1437
Iter 179: sigma_u = 0.0536, loglik = -109856.1830
Iter 180: sigma_u = 0.0536, loglik = -109856.9370
Iter 181: sigma_u = 0.0536, loglik = -109856.9744
Iter 182: sigma_u = 0.0536, loglik = -109857.8579
Iter 183: sigma_u = 0.0536, loglik = -109857.8938
Iter 184: sigma_u = 0.0536, loglik = -109858.7163
Iter 185: sigma_u = 0.0536, loglik = -109858.7508
Iter 186: sigma_u = 0.0536, loglik = -109859.5450
Iter 187: sigma_u = 0.0536, loglik = -109859.5783
Iter 188: sigma_u = 0.0536, loglik = -109860.3022
Iter 189: sigma_u = 0.0536, loglik = -109860.3326
Iter 190: sigma_u = 0.0536, loglik = -109860.9397
Iter 191: sigma_u = 0.0536, loglik = -109860.9712
Iter 192: sigma_u = 0.0536, loglik = -109861.6094
Iter 193: sigma_u = 0.0536, loglik = -109861.6377
Iter 194: sigma_u = 0.0536, loglik = -109862.1056
Iter 195: sigma_u = 0.0536, loglik = -109862.1343
Iter 196: sigma_u = 0.0536, loglik = -109862.6738
Iter 197: sigma_u = 0.0536, loglik = -109862.7013
Iter 198: sigma_u = 0.0536, loglik = -109863.0761
Iter 199: sigma_u = 0.0536, loglik = -109863.1044
Iter 200: sigma_u = 0.0536, loglik = -109863.4447
Iter 201: sigma_u = 0.0536, loglik = -109863.4703
Iter 202: sigma_u = 0.0536, loglik = -109863.9282
Iter 203: sigma_u = 0.0535, loglik = -109863.9527
Iter 204: sigma_u = 0.0535, loglik = -109864.6688
Iter 205: sigma_u = 0.0535, loglik = -109864.6916
Iter 206: sigma_u = 0.0535, loglik = -109865.1826
Iter 207: sigma_u = 0.0535, loglik = -109865.2053
Iter 208: sigma_u = 0.0535, loglik = -109865.7551
Iter 209: sigma_u = 0.0535, loglik = -109865.7763
Iter 210: sigma_u = 0.0535, loglik = -109866.0976
Iter 211: sigma_u = 0.0535, loglik = -109866.1189
Iter 212: sigma_u = 0.0535, loglik = -109866.4360
Iter 213: sigma_u = 0.0535, loglik = -109866.4560
Iter 214: sigma_u = 0.0535, loglik = -109866.6962
Iter 215: sigma_u = 0.0535, loglik = -109866.7155
Iter 216: sigma_u = 0.0535, loglik = -109867.1161
Iter 217: sigma_u = 0.0535, loglik = -109867.1354
Iter 218: sigma_u = 0.0535, loglik = -109867.5227
Iter 219: sigma_u = 0.0535, loglik = -109867.5402
✅ Converged at iteration 220
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            1.476       1.461810     1.461788
1           -0.151      -0.164200    -0.164198
2           -1.735      -1.758400    -1.758394
3            0.250       0.230886     0.053509



Time taken 2.0176999807357787 minutes



Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.7806, loglik = -16968.5387
Iter 1: sigma_u = 0.6497, loglik = -18732.1246
Iter 2: sigma_u = 0.5402, loglik = -22054.9108
Iter 3: sigma_u = 0.4496, loglik = -26740.6533
Iter 4: sigma_u = 0.3751, loglik = -33143.2461
Iter 5: sigma_u = 0.3143, loglik = -41462.4771
Iter 6: sigma_u = 0.2656, loglik = -51263.0028
Iter 7: sigma_u = 0.2272, loglik = -61329.7282
Iter 8: sigma_u = 0.1975, loglik = -70336.8743
Iter 9: sigma_u = 0.1744, loglik = -77614.1113
Iter 10: sigma_u = 0.1564, loglik = -83181.0079
Iter 11: sigma_u = 0.1421, loglik = -87365.5759
Iter 12: sigma_u = 0.1306, loglik = -90525.9702
Iter 13: sigma_u = 0.1211, loglik = -92943.8396
Iter 14: sigma_u = 0.1132, loglik = -94822.7555
Iter 15: sigma_u = 0.1065, loglik = -96310.8876
Iter 16: sigma_u = 0.1008, loglik = -97510.7025
Iter 17: sigma_u = 0.0958, loglik = -98492.7912
Iter 18: sigma_u = 0.0915, loglik = -99308.2406
Iter 19: sigma_u = 0.0876, loglik = -99993.7551
Iter 20: sigma_u = 0.0842, loglik = -100576.6805
Iter 21: sigma_u = 0.0811, loglik = -101076.9650
Iter 22: sigma_u = 0.0783, loglik = -101510.9199
Iter 23: sigma_u = 0.0758, loglik = -101890.2487
Iter 24: sigma_u = 0.0735, loglik = -102224.3254
Iter 25: sigma_u = 0.0713, loglik = -102520.5576
Iter 26: sigma_u = 0.0694, loglik = -102784.6553
Iter 27: sigma_u = 0.0676, loglik = -103022.9377
Iter 28: sigma_u = 0.0659, loglik = -103237.4420
Iter 29: sigma_u = 0.0643, loglik = -103430.0524
Iter 30: sigma_u = 0.0629, loglik = -103605.9576
Iter 31: sigma_u = 0.0615, loglik = -103767.3824
Iter 32: sigma_u = 0.0602, loglik = -103915.2161
Iter 33: sigma_u = 0.0590, loglik = -104054.6353
Iter 34: sigma_u = 0.0579, loglik = -104179.8430
Iter 35: sigma_u = 0.0568, loglik = -104296.1659
Iter 36: sigma_u = 0.0558, loglik = -104402.9872
Iter 37: sigma_u = 0.0548, loglik = -104502.2055
Iter 38: sigma_u = 0.0539, loglik = -104597.6571
Iter 39: sigma_u = 0.0530, loglik = -104683.1026
Iter 40: sigma_u = 0.0522, loglik = -104764.3573
Iter 41: sigma_u = 0.0514, loglik = -104839.6594
Iter 42: sigma_u = 0.0507, loglik = -104911.3114
Iter 43: sigma_u = 0.0500, loglik = -104978.8750
Iter 44: sigma_u = 0.0493, loglik = -105042.1519
Iter 45: sigma_u = 0.0486, loglik = -105101.9067
Iter 46: sigma_u = 0.0480, loglik = -105158.5389
Iter 47: sigma_u = 0.0474, loglik = -105210.9855
Iter 48: sigma_u = 0.0468, loglik = -105261.4975
Iter 49: sigma_u = 0.0463, loglik = -105308.6789
Iter 50: sigma_u = 0.0457, loglik = -105355.2294
Iter 51: sigma_u = 0.0452, loglik = -105399.7000
Iter 52: sigma_u = 0.0448, loglik = -105440.4543
Iter 53: sigma_u = 0.0443, loglik = -105474.7558
Iter 54: sigma_u = 0.0439, loglik = -105512.1079
Iter 55: sigma_u = 0.0434, loglik = -105546.6940
Iter 56: sigma_u = 0.0430, loglik = -105581.4709
Iter 57: sigma_u = 0.0424, loglik = -105615.0110
Iter 58: sigma_u = 0.0420, loglik = -105656.3121
Iter 59: sigma_u = 0.0416, loglik = -105687.3178
Iter 60: sigma_u = 0.0412, loglik = -105716.2652
Iter 61: sigma_u = 0.0408, loglik = -105744.8298
Iter 62: sigma_u = 0.0405, loglik = -105771.7793
Iter 63: sigma_u = 0.0401, loglik = -105797.0433
Iter 64: sigma_u = 0.0398, loglik = -105821.3734
Iter 65: sigma_u = 0.0395, loglik = -105845.6655
Iter 66: sigma_u = 0.0395, loglik = -105868.5467
Iter 67: sigma_u = 0.0395, loglik = -105869.3176
Iter 68: sigma_u = 0.0394, loglik = -105869.7739
Iter 69: sigma_u = 0.0394, loglik = -105870.5677
Iter 70: sigma_u = 0.0394, loglik = -105871.0102
Iter 71: sigma_u = 0.0394, loglik = -105871.8693
Iter 72: sigma_u = 0.0394, loglik = -105872.2960
Iter 73: sigma_u = 0.0394, loglik = -105873.2600
Iter 74: sigma_u = 0.0391, loglik = -105873.6680
Iter 75: sigma_u = 0.0388, loglik = -105896.0759
Iter 76: sigma_u = 0.0385, loglik = -105916.7027
Iter 77: sigma_u = 0.0382, loglik = -105937.5836
Iter 78: sigma_u = 0.0379, loglik = -105955.5480
Iter 79: sigma_u = 0.0379, loglik = -105973.9304
Iter 80: sigma_u = 0.0379, loglik = -105974.3118
Iter 81: sigma_u = 0.0379, loglik = -105974.7838
Iter 82: sigma_u = 0.0379, loglik = -105975.1475
Iter 83: sigma_u = 0.0379, loglik = -105975.6297
Iter 84: sigma_u = 0.0379, loglik = -105975.9799
Iter 85: sigma_u = 0.0379, loglik = -105976.4807
Iter 86: sigma_u = 0.0379, loglik = -105976.8128
Iter 87: sigma_u = 0.0379, loglik = -105977.3388
Iter 88: sigma_u = 0.0379, loglik = -105977.6511
Iter 89: sigma_u = 0.0379, loglik = -105978.2167
Iter 90: sigma_u = 0.0379, loglik = -105978.5059
Iter 91: sigma_u = 0.0379, loglik = -105979.1275
Iter 92: sigma_u = 0.0378, loglik = -105979.3935
Iter 93: sigma_u = 0.0378, loglik = -105980.1054
Iter 94: sigma_u = 0.0378, loglik = -105980.3450
Iter 95: sigma_u = 0.0378, loglik = -105981.2187
Iter 96: sigma_u = 0.0378, loglik = -105981.4299
Iter 97: sigma_u = 0.0378, loglik = -105982.6177
Iter 98: sigma_u = 0.0375, loglik = -105982.7966
Iter 99: sigma_u = 0.0372, loglik = -106001.5089
Iter 100: sigma_u = 0.0370, loglik = -106019.4792
Iter 101: sigma_u = 0.0370, loglik = -106033.0877
Iter 102: sigma_u = 0.0369, loglik = -106037.8444
Iter 103: sigma_u = 0.0368, loglik = -106041.9354
Iter 104: sigma_u = 0.0366, loglik = -106045.6558
Iter 105: sigma_u = 0.0363, loglik = -106062.5647
Iter 106: sigma_u = 0.0361, loglik = -106078.7675
Iter 107: sigma_u = 0.0361, loglik = -106092.9610
Iter 108: sigma_u = 0.0361, loglik = -106093.8155
Iter 109: sigma_u = 0.0361, loglik = -106093.9545
Iter 110: sigma_u = 0.0361, loglik = -106095.2773
Iter 111: sigma_u = 0.0358, loglik = -106095.3936
Iter 112: sigma_u = 0.0356, loglik = -106110.6200
Iter 113: sigma_u = 0.0355, loglik = -106124.0651
Iter 114: sigma_u = 0.0355, loglik = -106131.5642
Iter 115: sigma_u = 0.0355, loglik = -106131.9686
Iter 116: sigma_u = 0.0355, loglik = -106132.1327
Iter 117: sigma_u = 0.0355, loglik = -106132.5573
Iter 118: sigma_u = 0.0355, loglik = -106132.7127
Iter 119: sigma_u = 0.0355, loglik = -106133.2275
Iter 120: sigma_u = 0.0355, loglik = -106133.3685
Iter 121: sigma_u = 0.0355, loglik = -106134.0515
Iter 122: sigma_u = 0.0354, loglik = -106134.1762
Iter 123: sigma_u = 0.0354, loglik = -106135.2566
Iter 124: sigma_u = 0.0352, loglik = -106135.3596
Iter 125: sigma_u = 0.0350, loglik = -106149.2602
Iter 126: sigma_u = 0.0350, loglik = -106160.4291
Iter 127: sigma_u = 0.0350, loglik = -106160.7929
Iter 128: sigma_u = 0.0350, loglik = -106160.9414
Iter 129: sigma_u = 0.0350, loglik = -106161.3683
Iteration 129: beta norm = 2.809458828581909, sigma_u = 0.0350
Iter 130: sigma_u = 0.0350, loglik = -106161.5052
Iter 131: sigma_u = 0.0350, loglik = -106162.0512
Iter 132: sigma_u = 0.0350, loglik = -106162.1731
Iter 133: sigma_u = 0.0350, loglik = -106162.9713
Iter 134: sigma_u = 0.0350, loglik = -106163.0763
Iter 135: sigma_u = 0.0350, loglik = -106164.6179
Iter 136: sigma_u = 0.0348, loglik = -106164.6990
Iter 137: sigma_u = 0.0345, loglik = -106178.0686
Iter 138: sigma_u = 0.0345, loglik = -106191.4949
Iter 139: sigma_u = 0.0345, loglik = -106191.9131
Iter 140: sigma_u = 0.0345, loglik = -106192.0278
Iter 141: sigma_u = 0.0345, loglik = -106192.5010
Iter 142: sigma_u = 0.0345, loglik = -106192.6094
Iter 143: sigma_u = 0.0345, loglik = -106193.2993
Iter 144: sigma_u = 0.0345, loglik = -106193.3939
Iter 145: sigma_u = 0.0345, loglik = -106194.6984
Iter 146: sigma_u = 0.0343, loglik = -106194.7746
Iter 147: sigma_u = 0.0341, loglik = -106206.8387
Iter 148: sigma_u = 0.0341, loglik = -106215.4750
Iter 149: sigma_u = 0.0341, loglik = -106216.3939
Iter 150: sigma_u = 0.0340, loglik = -106216.4645
Iter 151: sigma_u = 0.0339, loglik = -106223.6133
Iter 152: sigma_u = 0.0339, loglik = -106227.2539
Iter 153: sigma_u = 0.0339, loglik = -106227.4116
Iter 154: sigma_u = 0.0339, loglik = -106227.9620
Iter 155: sigma_u = 0.0339, loglik = -106228.1108
Iter 156: sigma_u = 0.0339, loglik = -106228.9450
Iter 157: sigma_u = 0.0339, loglik = -106229.0900
Iter 158: sigma_u = 0.0339, loglik = -106230.5294
Iter 159: sigma_u = 0.0339, loglik = -106230.6789
Iter 160: sigma_u = 0.0339, loglik = -106231.3256
Iter 161: sigma_u = 0.0339, loglik = -106231.4957
Iter 162: sigma_u = 0.0339, loglik = -106231.7832
Iter 163: sigma_u = 0.0339, loglik = -106231.9587
Iter 164: sigma_u = 0.0339, loglik = -106232.2412
Iter 165: sigma_u = 0.0339, loglik = -106232.4132

Iter 166: sigma_u = 0.0339, loglik = -106232.7205
Iter 167: sigma_u = 0.0338, loglik = -106232.8878
Iter 168: sigma_u = 0.0338, loglik = -106233.2239
Iter 169: sigma_u = 0.0338, loglik = -106233.3862
Iter 170: sigma_u = 0.0338, loglik = -106233.7647
Iter 171: sigma_u = 0.0338, loglik = -106233.9209
Iter 172: sigma_u = 0.0338, loglik = -106234.3660
Iter 173: sigma_u = 0.0338, loglik = -106234.5166
Iter 174: sigma_u = 0.0338, loglik = -106235.0861
Iter 175: sigma_u = 0.0338, loglik = -106235.2308
Iter 176: sigma_u = 0.0338, loglik = -106236.0622
Iter 177: sigma_u = 0.0338, loglik = -106236.2038
Iter 178: sigma_u = 0.0338, loglik = -106237.8596
Iter 179: sigma_u = 0.0336, loglik = -106238.0027
Iter 180: sigma_u = 0.0334, loglik = -106249.5514
Iter 181: sigma_u = 0.0334, loglik = -106260.8144
Iter 182: sigma_u = 0.0334, loglik = -106261.0036
Iter 183: sigma_u = 0.0334, loglik = -106261.1858
Iter 184: sigma_u = 0.0334, loglik = -106261.3783
Iter 185: sigma_u = 0.0334, loglik = -106261.5564
Iter 186: sigma_u = 0.0334, loglik = -106261.7515
Iter 187: sigma_u = 0.0334, loglik = -106261.9244
Iter 188: sigma_u = 0.0334, loglik = -106262.1247
Iter 189: sigma_u = 0.0334, loglik = -106262.2914
Iter 190: sigma_u = 0.0334, loglik = -106262.4968
Iter 191: sigma_u = 0.0333, loglik = -106262.6574
Iter 192: sigma_u = 0.0333, loglik = -106262.8703
Iter 193: sigma_u = 0.0333, loglik = -106263.0238
Iter 194: sigma_u = 0.0333, loglik = -106263.2470
Iter 195: sigma_u = 0.0333, loglik = -106263.3921
Iter 196: sigma_u = 0.0333, loglik = -106263.6273
Iter 197: sigma_u = 0.0333, loglik = -106263.7636
Iter 198: sigma_u = 0.0333, loglik = -106264.0174
Iter 199: sigma_u = 0.0333, loglik = -106264.1442
Iter 200: sigma_u = 0.0333, loglik = -106264.4268
Iter 201: sigma_u = 0.0333, loglik = -106264.5425
Iter 202: sigma_u = 0.0333, loglik = -106264.8748
Iter 203: sigma_u = 0.0333, loglik = -106264.9784
Iter 204: sigma_u = 0.0333, loglik = -106265.3925
Iter 205: sigma_u = 0.0333, loglik = -106265.4839
Iter 206: sigma_u = 0.0333, loglik = -106266.0771
Iter 207: sigma_u = 0.0333, loglik = -106266.1547
Iter 208: sigma_u = 0.0333, loglik = -106267.2813
Iter 209: sigma_u = 0.0331, loglik = -106267.3406
Iter 210: sigma_u = 0.0329, loglik = -106278.1479
Iter 211: sigma_u = 0.0328, loglik = -106292.0333
Iter 212: sigma_u = 0.0328, loglik = -106292.7736
Iter 213: sigma_u = 0.0328, loglik = -106292.8914
Iter 214: sigma_u = 0.0328, loglik = -106294.2232
Iter 215: sigma_u = 0.0328, loglik = -106294.3454
Iter 216: sigma_u = 0.0328, loglik = -106294.9951
Iter 217: sigma_u = 0.0328, loglik = -106295.1387
Iter 218: sigma_u = 0.0328, loglik = -106295.3403
Iter 219: sigma_u = 0.0328, loglik = -106295.4954
Iter 220: sigma_u = 0.0328, loglik = -106295.6882
Iter 221: sigma_u = 0.0328, loglik = -106295.8417
Iter 222: sigma_u = 0.0328, loglik = -106296.0385
Iter 223: sigma_u = 0.0328, loglik = -106296.1895
Iter 224: sigma_u = 0.0328, loglik = -106296.3933
Iter 225: sigma_u = 0.0328, loglik = -106296.5423
Iter 226: sigma_u = 0.0328, loglik = -106296.7523
Iter 227: sigma_u = 0.0328, loglik = -106296.8979
Iter 228: sigma_u = 0.0328, loglik = -106297.1161
Iter 229: sigma_u = 0.0328, loglik = -106297.2589
Iter 230: sigma_u = 0.0328, loglik = -106297.4887
Iter 231: sigma_u = 0.0328, loglik = -106297.6284
Iter 232: sigma_u = 0.0327, loglik = -106297.8742
Iter 233: sigma_u = 0.0327, loglik = -106298.0094
Iter 234: sigma_u = 0.0327, loglik = -106298.2795
Iter 235: sigma_u = 0.0327, loglik = -106298.4102
Iter 236: sigma_u = 0.0327, loglik = -106298.7181
Iter 237: sigma_u = 0.0327, loglik = -106298.8442
Iter 238: sigma_u = 0.0327, loglik = -106299.2111
Iter 239: sigma_u = 0.0327, loglik = -106299.3324
Iter 240: sigma_u = 0.0327, loglik = -106299.8118
Iter 241: sigma_u = 0.0327, loglik = -106299.9292
Iter 242: sigma_u = 0.0327, loglik = -106300.6267
Iter 243: sigma_u = 0.0327, loglik = -106300.7416
Iter 244: sigma_u = 0.0327, loglik = -106302.1906
Iter 245: sigma_u = 0.0325, loglik = -106302.3075
Iter 246: sigma_u = 0.0325, loglik = -106312.1724
Iter 247: sigma_u = 0.0325, loglik = -106313.0962
Iter 248: sigma_u = 0.0325, loglik = -106313.2463
Iter 249: sigma_u = 0.0325, loglik = -106313.3724
Iter 250: sigma_u = 0.0325, loglik = -106313.5640
Iter 251: sigma_u = 0.0325, loglik = -106313.6843
Iter 252: sigma_u = 0.0325, loglik = -106313.8895
Iter 253: sigma_u = 0.0325, loglik = -106314.0019
Iter 254: sigma_u = 0.0325, loglik = -106314.2259
Iter 255: sigma_u = 0.0325, loglik = -106314.3296
Iter 256: sigma_u = 0.0325, loglik = -106314.5794
Iter 257: sigma_u = 0.0325, loglik = -106314.6743
Iter 258: sigma_u = 0.0325, loglik = -106314.9714
Iter 259: sigma_u = 0.0324, loglik = -106315.0558
Iter 260: sigma_u = 0.0324, loglik = -106315.4374
Iter 261: sigma_u = 0.0324, loglik = -106315.5115
Iter 262: sigma_u = 0.0324, loglik = -106316.0807
Iter 263: sigma_u = 0.0324, loglik = -106316.1431
Iter 264: sigma_u = 0.0324, loglik = -106317.3861
Iter 265: sigma_u = 0.0322, loglik = -106317.4312
Iter 266: sigma_u = 0.0322, loglik = -106328.8181
Iter 267: sigma_u = 0.0322, loglik = -106329.0420
Iter 268: sigma_u = 0.0322, loglik = -106329.1852
Iter 269: sigma_u = 0.0322, loglik = -106329.3382
Iter 270: sigma_u = 0.0322, loglik = -106329.4845
Iter 271: sigma_u = 0.0322, loglik = -106329.6374
Iter 272: sigma_u = 0.0322, loglik = -106329.7832
Iter 273: sigma_u = 0.0322, loglik = -106329.9364
Iter 274: sigma_u = 0.0322, loglik = -106330.0831
Iter 275: sigma_u = 0.0322, loglik = -106330.2345
Iter 276: sigma_u = 0.0322, loglik = -106330.3814
Iter 277: sigma_u = 0.0322, loglik = -106330.5314
Iter 278: sigma_u = 0.0322, loglik = -106330.6789
Iter 279: sigma_u = 0.0322, loglik = -106330.8272
Iter 280: sigma_u = 0.0322, loglik = -106330.9762
Iter 281: sigma_u = 0.0322, loglik = -106331.1223
Iter 282: sigma_u = 0.0322, loglik = -106331.2722
Iter 283: sigma_u = 0.0322, loglik = -106331.4159
Iter 284: sigma_u = 0.0322, loglik = -106331.5686
Iter 285: sigma_u = 0.0322, loglik = -106331.7084
Iter 286: sigma_u = 0.0322, loglik = -106331.8629
Iter 287: sigma_u = 0.0322, loglik = -106331.9997
Iter 288: sigma_u = 0.0322, loglik = -106332.1567
Iter 289: sigma_u = 0.0322, loglik = -106332.2897
Iter 290: sigma_u = 0.0321, loglik = -106332.4504
Iter 291: sigma_u = 0.0321, loglik = -106332.5796
Iter 292: sigma_u = 0.0321, loglik = -106332.7452
Iter 293: sigma_u = 0.0321, loglik = -106332.8696
Iter 294: sigma_u = 0.0321, loglik = -106333.0414
Iter 295: sigma_u = 0.0321, loglik = -106333.1600
Iter 296: sigma_u = 0.0321, loglik = -106333.3376
Iter 297: sigma_u = 0.0321, loglik = -106333.4505
Iter 298: sigma_u = 0.0321, loglik = -106333.6389
Iter 299: sigma_u = 0.0321, loglik = -106333.7456
Iter 300: sigma_u = 0.0321, loglik = -106333.9475
Iter 301: sigma_u = 0.0321, loglik = -106334.0473
Iter 302: sigma_u = 0.0321, loglik = -106334.2716
Iter 303: sigma_u = 0.0321, loglik = -106334.3624
Iter 304: sigma_u = 0.0321, loglik = -106334.6273
Iter 305: sigma_u = 0.0321, loglik = -106334.7090
Iter 306: sigma_u = 0.0321, loglik = -106335.0378
Iter 307: sigma_u = 0.0321, loglik = -106335.1098
Iter 308: sigma_u = 0.0321, loglik = -106335.5723
Iter 309: sigma_u = 0.0321, loglik = -106335.6338
Iter 310: sigma_u = 0.0321, loglik = -106336.4838
Iter 311: sigma_u = 0.0319, loglik = -106336.5313
Iter 312: sigma_u = 0.0317, loglik = -106345.6932
Iter 313: sigma_u = 0.0317, loglik = -106357.6137
Iter 314: sigma_u = 0.0317, loglik = -106358.4227
Iter 315: sigma_u = 0.0317, loglik = -106358.5603
Iter 316: sigma_u = 0.0317, loglik = -106358.6688
Iter 317: sigma_u = 0.0317, loglik = -106358.8353
Iter 318: sigma_u = 0.0317, loglik = -106358.9364
Iter 319: sigma_u = 0.0317, loglik = -106359.1110
Iter 320: sigma_u = 0.0317, loglik = -106359.2062
Iter 321: sigma_u = 0.0317, loglik = -106359.3985
Iter 322: sigma_u = 0.0317, loglik = -106359.4861
Iter 323: sigma_u = 0.0317, loglik = -106359.7017
Iter 324: sigma_u = 0.0317, loglik = -106359.7814
Iter 325: sigma_u = 0.0317, loglik = -106360.0412
Iter 326: sigma_u = 0.0317, loglik = -106360.1126
Iter 327: sigma_u = 0.0317, loglik = -106360.4389
Iter 328: sigma_u = 0.0316, loglik = -106360.5017
Iter 329: sigma_u = 0.0316, loglik = -106360.9981

Iter 330: sigma_u = 0.0316, loglik = -106361.0509
Iter 331: sigma_u = 0.0316, loglik = -106362.1306
Iter 332: sigma_u = 0.0314, loglik = -106362.1687
Iter 333: sigma_u = 0.0314, loglik = -106372.0614
Iter 334: sigma_u = 0.0314, loglik = -106372.2561
Iter 335: sigma_u = 0.0314, loglik = -106372.4113
Iter 336: sigma_u = 0.0314, loglik = -106372.5093
Iter 337: sigma_u = 0.0314, loglik = -106372.6737
Iter 338: sigma_u = 0.0314, loglik = -106372.7663
Iter 339: sigma_u = 0.0314, loglik = -106372.9422
Iter 340: sigma_u = 0.0314, loglik = -106373.0285
Iter 341: sigma_u = 0.0314, loglik = -106373.2257
Iter 342: sigma_u = 0.0314, loglik = -106373.3044
Iter 343: sigma_u = 0.0314, loglik = -106373.5298
Iter 344: sigma_u = 0.0314, loglik = -106373.6012
Iter 345: sigma_u = 0.0314, loglik = -106373.8804
Iter 346: sigma_u = 0.0314, loglik = -106373.9432
Iter 347: sigma_u = 0.0314, loglik = -106374.3409
Iter 348: sigma_u = 0.0314, loglik = -106374.3946
Iter 349: sigma_u = 0.0314, loglik = -106375.1138
Iter 350: sigma_u = 0.0312, loglik = -106375.1556
Iter 351: sigma_u = 0.0311, loglik = -106383.4631
Iter 352: sigma_u = 0.0311, loglik = -106392.4294
Iter 353: sigma_u = 0.0311, loglik = -106392.5492
Iter 354: sigma_u = 0.0311, loglik = -106392.6486
Iter 355: sigma_u = 0.0311, loglik = -106392.7761
Iter 356: sigma_u = 0.0311, loglik = -106392.8742
Iter 357: sigma_u = 0.0311, loglik = -106393.0093
Iter 358: sigma_u = 0.0311, loglik = -106393.1042
Iter 359: sigma_u = 0.0311, loglik = -106393.2465
Iter 360: sigma_u = 0.0311, loglik = -106393.3364
Iter 361: sigma_u = 0.0311, loglik = -106393.4894
Iter 362: sigma_u = 0.0311, loglik = -106393.5738
Iter 363: sigma_u = 0.0311, loglik = -106393.7390
Iter 364: sigma_u = 0.0311, loglik = -106393.8169
Iter 365: sigma_u = 0.0310, loglik = -106394.0063
Iter 366: sigma_u = 0.0310, loglik = -106394.0766
Iter 367: sigma_u = 0.0310, loglik = -106394.3015
Iter 368: sigma_u = 0.0310, loglik = -106394.3650
Iter 369: sigma_u = 0.0310, loglik = -106394.6506
Iter 370: sigma_u = 0.0310, loglik = -106394.7059
Iter 371: sigma_u = 0.0310, loglik = -106395.1328
Iter 372: sigma_u = 0.0310, loglik = -106395.1792
Iter 373: sigma_u = 0.0310, loglik = -106396.1250
Iter 374: sigma_u = 0.0308, loglik = -106396.1584
Iter 375: sigma_u = 0.0308, loglik = -106405.5095
Iter 376: sigma_u = 0.0308, loglik = -106405.6680
Iter 377: sigma_u = 0.0308, loglik = -106405.7733
Iter 378: sigma_u = 0.0308, loglik = -106405.8968
Iter 379: sigma_u = 0.0308, loglik = -106406.0020
Iter 380: sigma_u = 0.0308, loglik = -106406.1272
Iter 381: sigma_u = 0.0308, loglik = -106406.2310
Iter 382: sigma_u = 0.0308, loglik = -106406.3586
Iter 383: sigma_u = 0.0308, loglik = -106406.4619
Iter 384: sigma_u = 0.0308, loglik = -106406.5915
Iter 385: sigma_u = 0.0308, loglik = -106406.6943
Iter 386: sigma_u = 0.0308, loglik = -106406.8263
Iter 387: sigma_u = 0.0308, loglik = -106406.9277
Iter 388: sigma_u = 0.0308, loglik = -106407.0641
Iter 389: sigma_u = 0.0308, loglik = -106407.1639
Iter 390: sigma_u = 0.0308, loglik = -106407.3038
Iter 391: sigma_u = 0.0308, loglik = -106407.4020
Iter 392: sigma_u = 0.0308, loglik = -106407.5477
Iter 393: sigma_u = 0.0308, loglik = -106407.6440
Iter 394: sigma_u = 0.0308, loglik = -106407.7964
Iter 395: sigma_u = 0.0308, loglik = -106407.8909
Iter 396: sigma_u = 0.0308, loglik = -106408.0534
Iteration 396: beta norm = 2.8065130461070407, sigma_u = 0.0308
Iter 397: sigma_u = 0.0308, loglik = -106408.1453
Iter 398: sigma_u = 0.0308, loglik = -106408.3206
Iter 399: sigma_u = 0.0308, loglik = -106408.4094
Iter 400: sigma_u = 0.0308, loglik = -106408.6055
Iter 401: sigma_u = 0.0308, loglik = -106408.6912
Iter 402: sigma_u = 0.0308, loglik = -106408.9209
Iter 403: sigma_u = 0.0308, loglik = -106409.0034
Iter 404: sigma_u = 0.0308, loglik = -106409.2916
Iter 405: sigma_u = 0.0308, loglik = -106409.3711
Iter 406: sigma_u = 0.0308, loglik = -106409.7784
Iter 407: sigma_u = 0.0307, loglik = -106409.8557
Iter 408: sigma_u = 0.0307, loglik = -106410.5940
Iter 409: sigma_u = 0.0306, loglik = -106410.6714
Iter 410: sigma_u = 0.0304, loglik = -106418.2402
Iter 411: sigma_u = 0.0304, loglik = -106427.9573
Iter 412: sigma_u = 0.0304, loglik = -106428.3995
Iter 413: sigma_u = 0.0304, loglik = -106428.4785
Iter 414: sigma_u = 0.0304, loglik = -106428.6669
Iter 415: sigma_u = 0.0304, loglik = -106428.7508
Iter 416: sigma_u = 0.0304, loglik = -106428.9090
Iter 417: sigma_u = 0.0304, loglik = -106428.9920
Iter 418: sigma_u = 0.0304, loglik = -106429.1640
Iter 419: sigma_u = 0.0304, loglik = -106429.2445
Iter 420: sigma_u = 0.0304, loglik = -106429.4388
Iter 421: sigma_u = 0.0304, loglik = -106429.5162
Iter 422: sigma_u = 0.0304, loglik = -106429.7489
Iter 423: sigma_u = 0.0304, loglik = -106429.8240
Iter 424: sigma_u = 0.0304, loglik = -106430.1228
Iter 425: sigma_u = 0.0304, loglik = -106430.1950
Iter 426: sigma_u = 0.0304, loglik = -106430.6484
Iter 427: sigma_u = 0.0304, loglik = -106430.7195
Iter 428: sigma_u = 0.0304, loglik = -106431.6960
Iter 429: sigma_u = 0.0302, loglik = -106431.7691
Iter 430: sigma_u = 0.0302, loglik = -106439.6890
Iter 431: sigma_u = 0.0302, loglik = -106439.8087
Iter 432: sigma_u = 0.0302, loglik = -106440.2328
Iter 433: sigma_u = 0.0302, loglik = -106440.2936
Iter 434: sigma_u = 0.0302, loglik = -106440.4295
Iter 435: sigma_u = 0.0302, loglik = -106440.4960
Iter 436: sigma_u = 0.0302, loglik = -106440.6492
Iter 437: sigma_u = 0.0302, loglik = -106440.7094
Iter 438: sigma_u = 0.0302, loglik = -106440.8888
Iter 439: sigma_u = 0.0302, loglik = -106440.9428
Iter 440: sigma_u = 0.0302, loglik = -106441.1638
Iter 441: sigma_u = 0.0302, loglik = -106441.2117
Iter 442: sigma_u = 0.0302, loglik = -106441.5264
Iter 443: sigma_u = 0.0302, loglik = -106441.5675
Iter 444: sigma_u = 0.0302, loglik = -106442.1350
Iter 445: sigma_u = 0.0301, loglik = -106442.1675
Iter 446: sigma_u = 0.0301, loglik = -106444.5756
Iter 447: sigma_u = 0.0301, loglik = -106444.5904
Iter 448: sigma_u = 0.0301, loglik = -106445.4532
Iter 449: sigma_u = 0.0301, loglik = -106445.5230
Iter 450: sigma_u = 0.0301, loglik = -106446.0408
Iter 451: sigma_u = 0.0301, loglik = -106446.1273
Iter 452: sigma_u = 0.0301, loglik = -106446.2198
Iter 453: sigma_u = 0.0301, loglik = -106446.3212
Iter 454: sigma_u = 0.0301, loglik = -106446.4078
Iter 455: sigma_u = 0.0301, loglik = -106446.5114
Iter 456: sigma_u = 0.0301, loglik = -106446.5952
Iter 457: sigma_u = 0.0301, loglik = -106446.7033
Iter 458: sigma_u = 0.0301, loglik = -106446.7828
Iter 459: sigma_u = 0.0301, loglik = -106446.8956
Iter 460: sigma_u = 0.0301, loglik = -106446.9709
Iter 461: sigma_u = 0.0301, loglik = -106447.0899
Iter 462: sigma_u = 0.0301, loglik = -106447.1616
Iter 463: sigma_u = 0.0301, loglik = -106447.2873
Iter 464: sigma_u = 0.0301, loglik = -106447.3543
Iter 465: sigma_u = 0.0301, loglik = -106447.4940
Iter 466: sigma_u = 0.0301, loglik = -106447.5552
Iter 467: sigma_u = 0.0301, loglik = -106447.7121
Iter 468: sigma_u = 0.0301, loglik = -106447.7678
Iter 469: sigma_u = 0.0301, loglik = -106447.9545
Iter 470: sigma_u = 0.0300, loglik = -106448.0047
Iter 471: sigma_u = 0.0300, loglik = -106448.2441
Iter 472: sigma_u = 0.0300, loglik = -106448.2883
Iter 473: sigma_u = 0.0300, loglik = -106448.6553
Iter 474: sigma_u = 0.0300, loglik = -106448.6923
Iter 475: sigma_u = 0.0300, loglik = -106449.5220
Iter 476: sigma_u = 0.0299, loglik = -106449.5481
Iter 477: sigma_u = 0.0299, loglik = -106458.0962
Iter 478: sigma_u = 0.0299, loglik = -106458.2620
Iter 479: sigma_u = 0.0299, loglik = -106458.4087
Iter 480: sigma_u = 0.0299, loglik = -106458.4781
Iter 481: sigma_u = 0.0299, loglik = -106458.6002
Iter 482: sigma_u = 0.0299, loglik = -106458.6626
Iter 483: sigma_u = 0.0298, loglik = -106458.7996
Iter 484: sigma_u = 0.0298, loglik = -106458.8567
Iter 485: sigma_u = 0.0298, loglik = -106459.0124
Iter 486: sigma_u = 0.0298, loglik = -106459.0646
Iter 487: sigma_u = 0.0298, loglik = -106459.2513
Iter 488: sigma_u = 0.0298, loglik = -106459.2980
Iter 489: sigma_u = 0.0298, loglik = -106459.5404
Iter 490: sigma_u = 0.0298, loglik = -106459.5816
Iter 491: sigma_u = 0.0298, loglik = -106459.9486
Iter 492: sigma_u = 0.0298, loglik = -106459.9834

Iter 493: sigma_u = 0.0298, loglik = -106460.8265
Iter 494: sigma_u = 0.0296, loglik = -106460.8507
Iter 495: sigma_u = 0.0296, loglik = -106469.3775
Iter 496: sigma_u = 0.0296, loglik = -106469.5474
Iter 497: sigma_u = 0.0296, loglik = -106469.6010
Iter 498: sigma_u = 0.0296, loglik = -106469.7427
Iter 499: sigma_u = 0.0296, loglik = -106469.7946
Iter 500: sigma_u = 0.0296, loglik = -106469.9632
Iter 501: sigma_u = 0.0296, loglik = -106470.0094
Iter 502: sigma_u = 0.0296, loglik = -106470.2256
Iter 503: sigma_u = 0.0296, loglik = -106470.2659
Iter 504: sigma_u = 0.0296, loglik = -106470.6031
Iter 505: sigma_u = 0.0296, loglik = -106470.6367
Iter 506: sigma_u = 0.0296, loglik = -106471.4286
Iter 507: sigma_u = 0.0294, loglik = -106471.4519
Iter 508: sigma_u = 0.0293, loglik = -106480.0354
Iter 509: sigma_u = 0.0293, loglik = -106485.9235
Iter 510: sigma_u = 0.0293, loglik = -106486.0284
Iter 511: sigma_u = 0.0293, loglik = -106486.0826
Iter 512: sigma_u = 0.0293, loglik = -106486.1980
Iter 513: sigma_u = 0.0293, loglik = -106486.2491
Iter 514: sigma_u = 0.0293, loglik = -106486.3841
Iter 515: sigma_u = 0.0293, loglik = -106486.4313
Iter 516: sigma_u = 0.0293, loglik = -106486.5901
Iter 517: sigma_u = 0.0293, loglik = -106486.6332
Iter 518: sigma_u = 0.0293, loglik = -106486.8389
Iter 519: sigma_u = 0.0293, loglik = -106486.8763
Iter 520: sigma_u = 0.0293, loglik = -106487.1926
Iter 521: sigma_u = 0.0293, loglik = -106487.2240
Iter 522: sigma_u = 0.0293, loglik = -106487.9183
Iter 523: sigma_u = 0.0291, loglik = -106487.9406
Iter 524: sigma_u = 0.0291, loglik = -106495.7964
Iter 525: sigma_u = 0.0291, loglik = -106495.9635
Iter 526: sigma_u = 0.0291, loglik = -106496.0830
Iter 527: sigma_u = 0.0291, loglik = -106496.2445
Iter 528: sigma_u = 0.0291, loglik = -106496.2975
Iter 529: sigma_u = 0.0291, loglik = -106496.4081
Iter 530: sigma_u = 0.0291, loglik = -106496.4587
Iter 531: sigma_u = 0.0291, loglik = -106496.5805
Iter 532: sigma_u = 0.0291, loglik = -106496.6276
Iter 533: sigma_u = 0.0291, loglik = -106496.7665
Iter 534: sigma_u = 0.0291, loglik = -106496.8096
Iter 535: sigma_u = 0.0291, loglik = -106496.9820
Iter 536: sigma_u = 0.0291, loglik = -106497.0200
Iter 537: sigma_u = 0.0291, loglik = -106497.2594
Iter 538: sigma_u = 0.0291, loglik = -106497.2920
Iter 539: sigma_u = 0.0291, loglik = -106497.7403
Iter 540: sigma_u = 0.0291, loglik = -106497.7658
Iter 541: sigma_u = 0.0291, loglik = -106499.8724
Iter 542: sigma_u = 0.0291, loglik = -106499.8825
Iter 543: sigma_u = 0.0291, loglik = -106500.3686
Iter 544: sigma_u = 0.0291, loglik = -106500.4315
Iter 545: sigma_u = 0.0290, loglik = -106500.5206
Iter 546: sigma_u = 0.0290, loglik = -106500.5937
Iter 547: sigma_u = 0.0290, loglik = -106500.6717
Iter 548: sigma_u = 0.0290, loglik = -106500.7474
Iter 549: sigma_u = 0.0290, loglik = -106500.8227
Iter 550: sigma_u = 0.0290, loglik = -106500.9000
Iter 551: sigma_u = 0.0290, loglik = -106500.9729
Iter 552: sigma_u = 0.0290, loglik = -106501.0508
Iter 553: sigma_u = 0.0290, loglik = -106501.1226
Iter 554: sigma_u = 0.0290, loglik = -106501.2015
Iter 555: sigma_u = 0.0290, loglik = -106501.2722
Iter 556: sigma_u = 0.0290, loglik = -106501.3522
Iter 557: sigma_u = 0.0290, loglik = -106501.4204
Iter 558: sigma_u = 0.0290, loglik = -106501.5031
Iter 559: sigma_u = 0.0290, loglik = -106501.5691
Iter 560: sigma_u = 0.0290, loglik = -106501.6541
Iter 561: sigma_u = 0.0290, loglik = -106501.7177
Iter 562: sigma_u = 0.0290, loglik = -106501.8056
Iter 563: sigma_u = 0.0290, loglik = -106501.8662
Iter 564: sigma_u = 0.0290, loglik = -106501.9581
Iter 565: sigma_u = 0.0290, loglik = -106502.0156
Iter 566: sigma_u = 0.0290, loglik = -106502.1140
Iter 567: sigma_u = 0.0290, loglik = -106502.1680
Iter 568: sigma_u = 0.0290, loglik = -106502.2750
Iter 569: sigma_u = 0.0290, loglik = -106502.3244
Iter 570: sigma_u = 0.0290, loglik = -106502.4433
Iter 571: sigma_u = 0.0290, loglik = -106502.4890
Iter 572: sigma_u = 0.0290, loglik = -106502.6277
Iter 573: sigma_u = 0.0290, loglik = -106502.6691
Iter 574: sigma_u = 0.0290, loglik = -106502.8449
Iter 575: sigma_u = 0.0290, loglik = -106502.8811
Iter 576: sigma_u = 0.0290, loglik = -106503.1430
Iter 577: sigma_u = 0.0290, loglik = -106503.1736
Iter 578: sigma_u = 0.0290, loglik = -106503.7051
Iter 579: sigma_u = 0.0289, loglik = -106503.7278
Iter 580: sigma_u = 0.0289, loglik = -106510.4306
Iter 581: sigma_u = 0.0289, loglik = -106510.4818
Iter 582: sigma_u = 0.0288, loglik = -106510.8289
Iter 583: sigma_u = 0.0288, loglik = -106510.8808
Iter 584: sigma_u = 0.0288, loglik = -106511.1725
Iter 585: sigma_u = 0.0288, loglik = -106511.2272
Iter 586: sigma_u = 0.0288, loglik = -106511.3558
Iter 587: sigma_u = 0.0288, loglik = -106511.4137
Iter 588: sigma_u = 0.0288, loglik = -106511.5381
Iter 589: sigma_u = 0.0288, loglik = -106511.5949
Iter 590: sigma_u = 0.0288, loglik = -106511.7324
Iter 591: sigma_u = 0.0288, loglik = -106511.7870
Iter 592: sigma_u = 0.0288, loglik = -106511.9536
Iter 593: sigma_u = 0.0288, loglik = -106512.0061
Iter 594: sigma_u = 0.0288, loglik = -106512.2253
Iter 595: sigma_u = 0.0288, loglik = -106512.2761
Iter 596: sigma_u = 0.0288, loglik = -106512.6187
Iter 597: sigma_u = 0.0288, loglik = -106512.6687
Iter 598: sigma_u = 0.0288, loglik = -106513.4429
Iter 599: sigma_u = 0.0288, loglik = -106513.4957
Iter 600: sigma_u = 0.0288, loglik = -106515.6466
Iter 601: sigma_u = 0.0288, loglik = -106515.7183
Iter 602: sigma_u = 0.0288, loglik = -106515.7682
Iter 603: sigma_u = 0.0288, loglik = -106515.8681
Iter 604: sigma_u = 0.0287, loglik = -106515.9145
Iter 605: sigma_u = 0.0287, loglik = -106516.0273
Iter 606: sigma_u = 0.0287, loglik = -106516.0697
Iter 607: sigma_u = 0.0287, loglik = -106516.2018
Iter 608: sigma_u = 0.0287, loglik = -106516.2401
Iter 609: sigma_u = 0.0287, loglik = -106516.4035
Iter 610: sigma_u = 0.0287, loglik = -106516.4375
Iter 611: sigma_u = 0.0287, loglik = -106516.6757
Iter 612: sigma_u = 0.0287, loglik = -106516.7046
Iter 613: sigma_u = 0.0287, loglik = -106517.1735
Iter 614: sigma_u = 0.0287, loglik = -106517.1956
Iter 615: sigma_u = 0.0287, loglik = -106519.9856
Iter 616: sigma_u = 0.0287, loglik = -106519.9924
Iter 617: sigma_u = 0.0287, loglik = -106520.3540
Iter 618: sigma_u = 0.0287, loglik = -106520.4024
Iter 619: sigma_u = 0.0287, loglik = -106521.0020
Iter 620: sigma_u = 0.0286, loglik = -106521.0536
Iter 621: sigma_u = 0.0286, loglik = -106521.2660
Iter 622: sigma_u = 0.0286, loglik = -106521.3288
Iter 623: sigma_u = 0.0286, loglik = -106521.3970
Iter 624: sigma_u = 0.0286, loglik = -106521.4670
Iter 625: sigma_u = 0.0286, loglik = -106521.5341
Iter 626: sigma_u = 0.0286, loglik = -106521.6054
Iter 627: sigma_u = 0.0286, loglik = -106521.6712
Iter 628: sigma_u = 0.0286, loglik = -106521.7423
Iter 629: sigma_u = 0.0286, loglik = -106521.8075
Iter 630: sigma_u = 0.0286, loglik = -106521.8789
Iter 631: sigma_u = 0.0286, loglik = -106521.9435
Iter 632: sigma_u = 0.0286, loglik = -106522.0151
Iter 633: sigma_u = 0.0286, loglik = -106522.0794
Iter 634: sigma_u = 0.0286, loglik = -106522.1513
Iter 635: sigma_u = 0.0286, loglik = -106522.2144
Iter 636: sigma_u = 0.0286, loglik = -106522.2889
Iter 637: sigma_u = 0.0286, loglik = -106522.3497
Iter 638: sigma_u = 0.0286, loglik = -106522.4268
Iter 639: sigma_u = 0.0286, loglik = -106522.4841
Iter 640: sigma_u = 0.0286, loglik = -106522.5655
Iter 641: sigma_u = 0.0286, loglik = -106522.6192
Iter 642: sigma_u = 0.0286, loglik = -106522.7061
Iter 643: sigma_u = 0.0286, loglik = -106522.7570
Iter 644: sigma_u = 0.0286, loglik = -106522.8487
Iter 645: sigma_u = 0.0286, loglik = -106522.8963
Iter 646: sigma_u = 0.0286, loglik = -106522.9967
Iter 647: sigma_u = 0.0286, loglik = -106523.0403
Iter 648: sigma_u = 0.0286, loglik = -106523.1568
Iter 649: sigma_u = 0.0286, loglik = -106523.1965
Iter 650: sigma_u = 0.0286, loglik = -106523.3353
Iter 651: sigma_u = 0.0286, loglik = -106523.3707
Iter 652: sigma_u = 0.0286, loglik = -106523.5547
Iter 653: sigma_u = 0.0286, loglik = -106523.5856
Iter 654: sigma_u = 0.0286, loglik = -106523.8682
Iter 655: sigma_u = 0.0286, loglik = -106523.8940
Iter 656: sigma_u = 0.0286, loglik = -106524.6500

Iter 657: sigma_u = 0.0284, loglik = -106524.6668
Iter 658: sigma_u = 0.0284, loglik = -106531.3886
Iter 659: sigma_u = 0.0284, loglik = -106531.4023
Iter 660: sigma_u = 0.0284, loglik = -106531.7463
Iter 661: sigma_u = 0.0284, loglik = -106531.8310
Iter 662: sigma_u = 0.0284, loglik = -106532.0788
Iter 663: sigma_u = 0.0284, loglik = -106532.1583
Iter 664: sigma_u = 0.0284, loglik = -106532.2154
Iter 665: sigma_u = 0.0284, loglik = -106532.2895
Iter 666: sigma_u = 0.0284, loglik = -106532.3436
Iter 667: sigma_u = 0.0284, loglik = -106532.4204
Iter 668: sigma_u = 0.0284, loglik = -106532.4719
Iter 669: sigma_u = 0.0284, loglik = -106532.5535
Iter 670: sigma_u = 0.0284, loglik = -106532.6026
Iter 671: sigma_u = 0.0284, loglik = -106532.6905
Iter 672: sigma_u = 0.0284, loglik = -106532.7356
Iter 673: sigma_u = 0.0284, loglik = -106532.8315
Iter 674: sigma_u = 0.0284, loglik = -106532.8735
Iter 675: sigma_u = 0.0284, loglik = -106532.9835
Iter 676: sigma_u = 0.0284, loglik = -106533.0216
Iter 677: sigma_u = 0.0284, loglik = -106533.1572
Iter 678: sigma_u = 0.0284, loglik = -106533.1905
Iter 679: sigma_u = 0.0284, loglik = -106533.3768
Iter 680: sigma_u = 0.0284, loglik = -106533.4055
Iter 681: sigma_u = 0.0284, loglik = -106533.7190
Iter 682: sigma_u = 0.0284, loglik = -106533.7424
Iter 683: sigma_u = 0.0284, loglik = -106534.7069
Iter 684: sigma_u = 0.0283, loglik = -106534.7210
Iter 685: sigma_u = 0.0283, loglik = -106536.6965
Iter 686: sigma_u = 0.0283, loglik = -106536.7500
Iter 687: sigma_u = 0.0283, loglik = -106536.9590
Iter 688: sigma_u = 0.0283, loglik = -106537.0560
Iter 689: sigma_u = 0.0283, loglik = -106537.2150
Iter 690: sigma_u = 0.0283, loglik = -106537.3006
Iter 691: sigma_u = 0.0283, loglik = -106537.3531
Iter 692: sigma_u = 0.0283, loglik = -106537.4290
Iter 693: sigma_u = 0.0283, loglik = -106537.4798
Iter 694: sigma_u = 0.0283, loglik = -106537.5577
Iter 695: sigma_u = 0.0283, loglik = -106537.6058
Iter 696: sigma_u = 0.0283, loglik = -106537.6912
Iter 697: sigma_u = 0.0283, loglik = -106537.7357
Iter 698: sigma_u = 0.0283, loglik = -106537.8316
Iter 699: sigma_u = 0.0283, loglik = -106537.8718
Iter 700: sigma_u = 0.0283, loglik = -106537.9826
Iter 701: sigma_u = 0.0283, loglik = -106538.0191
Iter 702: sigma_u = 0.0283, loglik = -106538.1552
Iter 703: sigma_u = 0.0283, loglik = -106538.1873
Iter 704: sigma_u = 0.0283, loglik = -106538.3768
Iteration 704: beta norm = 2.8051009008389998, sigma_u = 0.0283
Iter 705: sigma_u = 0.0283, loglik = -106538.4045
Iter 706: sigma_u = 0.0283, loglik = -106538.7231
Iter 707: sigma_u = 0.0283, loglik = -106538.7457
Iter 708: sigma_u = 0.0283, loglik = -106539.7973
Iter 709: sigma_u = 0.0283, loglik = -106539.8102
Iter 710: sigma_u = 0.0283, loglik = -106541.0938
Iter 711: sigma_u = 0.0282, loglik = -106541.1441
Iter 712: sigma_u = 0.0282, loglik = -106541.2456
Iter 713: sigma_u = 0.0282, loglik = -106541.3206
Iter 714: sigma_u = 0.0282, loglik = -106541.3707
Iter 715: sigma_u = 0.0282, loglik = -106541.4493
Iter 716: sigma_u = 0.0282, loglik = -106541.4961
Iter 717: sigma_u = 0.0282, loglik = -106541.5796
Iter 718: sigma_u = 0.0282, loglik = -106541.6231
Iter 719: sigma_u = 0.0282, loglik = -106541.7171
Iter 720: sigma_u = 0.0282, loglik = -106541.7568
Iter 721: sigma_u = 0.0282, loglik = -106541.8615
Iter 722: sigma_u = 0.0282, loglik = -106541.8983
Iter 723: sigma_u = 0.0282, loglik = -106542.0211
Iter 724: sigma_u = 0.0282, loglik = -106542.0543
Iter 725: sigma_u = 0.0282, loglik = -106542.2123
Iter 726: sigma_u = 0.0282, loglik = -106542.2417
Iter 727: sigma_u = 0.0282, loglik = -106542.4686
Iter 728: sigma_u = 0.0282, loglik = -106542.4937
Iter 729: sigma_u = 0.0282, loglik = -106542.9659
Iter 730: sigma_u = 0.0281, loglik = -106542.9845
Iter 731: sigma_u = 0.0281, loglik = -106547.1260
Iter 732: sigma_u = 0.0281, loglik = -106547.1331
Iter 733: sigma_u = 0.0281, loglik = -106547.2230
Iter 734: sigma_u = 0.0281, loglik = -106547.3284
Iter 735: sigma_u = 0.0281, loglik = -106547.3858
Iter 736: sigma_u = 0.0281, loglik = -106547.4500
Iter 737: sigma_u = 0.0281, loglik = -106547.5086
Iter 738: sigma_u = 0.0281, loglik = -106547.5738
Iter 739: sigma_u = 0.0281, loglik = -106547.6316
Iter 740: sigma_u = 0.0281, loglik = -106547.6974
Iter 741: sigma_u = 0.0281, loglik = -106547.7559
Iter 742: sigma_u = 0.0281, loglik = -106547.8215
Iter 743: sigma_u = 0.0281, loglik = -106547.8794
Iter 744: sigma_u = 0.0281, loglik = -106547.9444
Iter 745: sigma_u = 0.0281, loglik = -106548.0022
Iter 746: sigma_u = 0.0281, loglik = -106548.0685
Iter 747: sigma_u = 0.0281, loglik = -106548.1255
Iter 748: sigma_u = 0.0281, loglik = -106548.1930
Iter 749: sigma_u = 0.0281, loglik = -106548.2498
Iter 750: sigma_u = 0.0281, loglik = -106548.3183
Iter 751: sigma_u = 0.0281, loglik = -106548.3754
Iter 752: sigma_u = 0.0281, loglik = -106548.4445
Iter 753: sigma_u = 0.0281, loglik = -106548.5004
Iter 754: sigma_u = 0.0281, loglik = -106548.5711
Iter 755: sigma_u = 0.0281, loglik = -106548.6263
Iter 756: sigma_u = 0.0281, loglik = -106548.6985
Iter 757: sigma_u = 0.0281, loglik = -106548.7530
Iter 758: sigma_u = 0.0281, loglik = -106548.8274
Iter 759: sigma_u = 0.0281, loglik = -106548.8810
Iter 760: sigma_u = 0.0281, loglik = -106548.9598
Iter 761: sigma_u = 0.0281, loglik = -106549.0115
Iter 762: sigma_u = 0.0281, loglik = -106549.0962
Iter 763: sigma_u = 0.0281, loglik = -106549.1467
Iter 764: sigma_u = 0.0281, loglik = -106549.2378
Iter 765: sigma_u = 0.0281, loglik = -106549.2869
Iter 766: sigma_u = 0.0281, loglik = -106549.3883
Iter 767: sigma_u = 0.0281, loglik = -106549.4358
Iter 768: sigma_u = 0.0281, loglik = -106549.5509
Iter 769: sigma_u = 0.0281, loglik = -106549.5968
Iter 770: sigma_u = 0.0281, loglik = -106549.7308
Iter 771: sigma_u = 0.0281, loglik = -106549.7747
Iter 772: sigma_u = 0.0281, loglik = -106549.9470
Iter 773: sigma_u = 0.0281, loglik = -106549.9899
Iter 774: sigma_u = 0.0281, loglik = -106550.2515
Iter 775: sigma_u = 0.0281, loglik = -106550.2935
Iter 776: sigma_u = 0.0281, loglik = -106550.8108
Iter 777: sigma_u = 0.0280, loglik = -106550.8540
Iter 778: sigma_u = 0.0280, loglik = -106553.3289
Iter 779: sigma_u = 0.0280, loglik = -106553.3808
Iter 780: sigma_u = 0.0280, loglik = -106553.4360
Iter 781: sigma_u = 0.0280, loglik = -106553.5169
Iter 782: sigma_u = 0.0280, loglik = -106553.5575
Iter 783: sigma_u = 0.0280, loglik = -106553.6442
Iter 784: sigma_u = 0.0280, loglik = -106553.6825
Iter 785: sigma_u = 0.0280, loglik = -106553.7791
Iter 786: sigma_u = 0.0280, loglik = -106553.8142
Iter 787: sigma_u = 0.0280, loglik = -106553.9332
Iter 788: sigma_u = 0.0280, loglik = -106553.9642
Iter 789: sigma_u = 0.0280, loglik = -106554.1207
Iter 790: sigma_u = 0.0280, loglik = -106554.1474
Iter 791: sigma_u = 0.0280, loglik = -106554.3938
Iter 792: sigma_u = 0.0280, loglik = -106554.4164
Iter 793: sigma_u = 0.0280, loglik = -106555.0282
Iter 794: sigma_u = 0.0279, loglik = -106555.0433
Iter 795: sigma_u = 0.0279, loglik = -106559.0855
Iter 796: sigma_u = 0.0279, loglik = -106559.1405
Iter 797: sigma_u = 0.0279, loglik = -106559.1713
Iter 798: sigma_u = 0.0279, loglik = -106559.2656
Iter 799: sigma_u = 0.0279, loglik = -106559.3007
Iter 800: sigma_u = 0.0279, loglik = -106559.4050
Iter 801: sigma_u = 0.0279, loglik = -106559.4367
Iter 802: sigma_u = 0.0279, loglik = -106559.5708
Iter 803: sigma_u = 0.0279, loglik = -106559.5985
Iter 804: sigma_u = 0.0279, loglik = -106559.7997
Iter 805: sigma_u = 0.0279, loglik = -106559.8230
Iter 806: sigma_u = 0.0279, loglik = -106560.2442
Iter 807: sigma_u = 0.0278, loglik = -106560.2615
Iter 808: sigma_u = 0.0278, loglik = -106563.4259
Iter 809: sigma_u = 0.0278, loglik = -106563.4323
Iter 810: sigma_u = 0.0278, loglik = -106563.5108
Iter 811: sigma_u = 0.0278, loglik = -106563.5990
Iter 812: sigma_u = 0.0278, loglik = -106563.6494
Iter 813: sigma_u = 0.0278, loglik = -106563.7150
Iter 814: sigma_u = 0.0278, loglik = -106563.7662
Iter 815: sigma_u = 0.0278, loglik = -106563.8336
Iter 816: sigma_u = 0.0278, loglik = -106563.8834
Iter 817: sigma_u = 0.0278, loglik = -106563.9545
Iter 818: sigma_u = 0.0278, loglik = -106564.0038
Iter 819: sigma_u = 0.0278, loglik = -106564.0778

Iter 820: sigma_u = 0.0278, loglik = -106564.1259
Iter 821: sigma_u = 0.0278, loglik = -106564.2050
Iter 822: sigma_u = 0.0278, loglik = -106564.2518
Iter 823: sigma_u = 0.0278, loglik = -106564.3357
Iter 824: sigma_u = 0.0278, loglik = -106564.3815
Iter 825: sigma_u = 0.0278, loglik = -106564.4736
Iter 826: sigma_u = 0.0278, loglik = -106564.5174
Iter 827: sigma_u = 0.0278, loglik = -106564.6224
Iter 828: sigma_u = 0.0278, loglik = -106564.6651
Iter 829: sigma_u = 0.0278, loglik = -106564.7898
Iter 830: sigma_u = 0.0278, loglik = -106564.8314
Iter 831: sigma_u = 0.0278, loglik = -106564.9923
Iter 832: sigma_u = 0.0278, loglik = -106565.0317
Iter 833: sigma_u = 0.0278, loglik = -106565.2713
Iter 834: sigma_u = 0.0278, loglik = -106565.3106
Iter 835: sigma_u = 0.0278, loglik = -106565.7752
Iter 836: sigma_u = 0.0277, loglik = -106565.8152
Iter 837: sigma_u = 0.0277, loglik = -106568.0836
Iter 838: sigma_u = 0.0277, loglik = -106568.1333
Iter 839: sigma_u = 0.0277, loglik = -106568.2213
Iter 840: sigma_u = 0.0277, loglik = -106568.3138
Iter 841: sigma_u = 0.0277, loglik = -106568.3519
Iter 842: sigma_u = 0.0277, loglik = -106568.4346
Iter 843: sigma_u = 0.0277, loglik = -106568.4695
Iter 844: sigma_u = 0.0277, loglik = -106568.5635
Iter 845: sigma_u = 0.0277, loglik = -106568.5949
Iter 846: sigma_u = 0.0277, loglik = -106568.7077
Iter 847: sigma_u = 0.0277, loglik = -106568.7359
Iter 848: sigma_u = 0.0277, loglik = -106568.8852
Iter 849: sigma_u = 0.0277, loglik = -106568.9100
Iter 850: sigma_u = 0.0277, loglik = -106569.1553
Iter 851: sigma_u = 0.0277, loglik = -106569.1754
Iter 852: sigma_u = 0.0277, loglik = -106569.9150
Iter 853: sigma_u = 0.0276, loglik = -106569.9272
Iter 854: sigma_u = 0.0276, loglik = -106572.1180
Iter 855: sigma_u = 0.0276, loglik = -106572.1647
Iter 856: sigma_u = 0.0276, loglik = -106572.4252
Iter 857: sigma_u = 0.0276, loglik = -106572.4765
Iter 858: sigma_u = 0.0276, loglik = -106572.5463
Iter 859: sigma_u = 0.0276, loglik = -106572.5849
Iter 860: sigma_u = 0.0276, loglik = -106572.6589
Iter 861: sigma_u = 0.0276, loglik = -106572.6956
Iter 862: sigma_u = 0.0276, loglik = -106572.7780
Iter 863: sigma_u = 0.0276, loglik = -106572.8112
Iter 864: sigma_u = 0.0276, loglik = -106572.9102
Iter 865: sigma_u = 0.0276, loglik = -106572.9402
Iter 866: sigma_u = 0.0276, loglik = -106573.0652
Iter 867: sigma_u = 0.0276, loglik = -106573.0915
Iter 868: sigma_u = 0.0276, loglik = -106573.2599
Iter 869: sigma_u = 0.0276, loglik = -106573.2827
Iter 870: sigma_u = 0.0276, loglik = -106573.5906
Iter 871: sigma_u = 0.0276, loglik = -106573.6084
Iter 872: sigma_u = 0.0276, loglik = -106574.8830
Iter 873: sigma_u = 0.0276, loglik = -106574.8909
Iter 874: sigma_u = 0.0276, loglik = -106575.2791
Iter 875: sigma_u = 0.0276, loglik = -106575.3220
Iter 876: sigma_u = 0.0276, loglik = -106575.3913
Iter 877: sigma_u = 0.0276, loglik = -106575.4424
Iter 878: sigma_u = 0.0276, loglik = -106575.4989
Iter 879: sigma_u = 0.0276, loglik = -106575.5501
Iter 880: sigma_u = 0.0276, loglik = -106575.6062
Iter 881: sigma_u = 0.0276, loglik = -106575.6570
Iter 882: sigma_u = 0.0276, loglik = -106575.7141
Iter 883: sigma_u = 0.0276, loglik = -106575.7655
Iter 884: sigma_u = 0.0276, loglik = -106575.8214
Iter 885: sigma_u = 0.0275, loglik = -106575.8734
Iter 886: sigma_u = 0.0275, loglik = -106575.9280
Iter 887: sigma_u = 0.0275, loglik = -106575.9798
Iter 888: sigma_u = 0.0275, loglik = -106576.0341
Iter 889: sigma_u = 0.0275, loglik = -106576.0859
Iter 890: sigma_u = 0.0275, loglik = -106576.1402
Iter 891: sigma_u = 0.0275, loglik = -106576.1919
Iter 892: sigma_u = 0.0275, loglik = -106576.2468
Iter 893: sigma_u = 0.0275, loglik = -106576.2989
Iter 894: sigma_u = 0.0275, loglik = -106576.3536
Iter 895: sigma_u = 0.0275, loglik = -106576.4052
Iter 896: sigma_u = 0.0275, loglik = -106576.4597
Iter 897: sigma_u = 0.0275, loglik = -106576.5114
Iter 898: sigma_u = 0.0275, loglik = -106576.5657
Iter 899: sigma_u = 0.0275, loglik = -106576.6175
Iter 900: sigma_u = 0.0275, loglik = -106576.6715
Iter 901: sigma_u = 0.0275, loglik = -106576.7236
Iter 902: sigma_u = 0.0275, loglik = -106576.7769
Iter 903: sigma_u = 0.0275, loglik = -106576.8283
Iter 904: sigma_u = 0.0275, loglik = -106576.8826
Iter 905: sigma_u = 0.0275, loglik = -106576.9346
Iter 906: sigma_u = 0.0275, loglik = -106576.9881
Iter 907: sigma_u = 0.0275, loglik = -106577.0404
Iter 908: sigma_u = 0.0275, loglik = -106577.0941
Iter 909: sigma_u = 0.0275, loglik = -106577.1465
Iter 910: sigma_u = 0.0275, loglik = -106577.1997
Iter 911: sigma_u = 0.0275, loglik = -106577.2512
Iter 912: sigma_u = 0.0275, loglik = -106577.3049
Iter 913: sigma_u = 0.0275, loglik = -106577.3570
Iter 914: sigma_u = 0.0275, loglik = -106577.4104
Iter 915: sigma_u = 0.0275, loglik = -106577.4627
Iter 916: sigma_u = 0.0275, loglik = -106577.5159
Iter 917: sigma_u = 0.0275, loglik = -106577.5685
Iter 918: sigma_u = 0.0275, loglik = -106577.6207
Iter 919: sigma_u = 0.0275, loglik = -106577.6727
Iter 920: sigma_u = 0.0275, loglik = -106577.7251
Iter 921: sigma_u = 0.0275, loglik = -106577.7770
Iter 922: sigma_u = 0.0275, loglik = -106577.8304
Iter 923: sigma_u = 0.0275, loglik = -106577.8829
Iter 924: sigma_u = 0.0275, loglik = -106577.9351
Iter 925: sigma_u = 0.0275, loglik = -106577.9887
Iter 926: sigma_u = 0.0275, loglik = -106578.0394
Iter 927: sigma_u = 0.0275, loglik = -106578.0927
Iter 928: sigma_u = 0.0275, loglik = -106578.1430
Iter 929: sigma_u = 0.0275, loglik = -106578.1973
Iter 930: sigma_u = 0.0275, loglik = -106578.2473
Iter 931: sigma_u = 0.0275, loglik = -106578.3016
Iter 932: sigma_u = 0.0275, loglik = -106578.3504
Iter 933: sigma_u = 0.0275, loglik = -106578.4067
Iter 934: sigma_u = 0.0275, loglik = -106578.4532
Iter 935: sigma_u = 0.0275, loglik = -106578.5105
Iter 936: sigma_u = 0.0275, loglik = -106578.5559
Iter 937: sigma_u = 0.0275, loglik = -106578.6145
Iter 938: sigma_u = 0.0275, loglik = -106578.6588
Iter 939: sigma_u = 0.0275, loglik = -106578.7195
Iter 940: sigma_u = 0.0275, loglik = -106578.7620
Iter 941: sigma_u = 0.0275, loglik = -106578.8248
Iter 942: sigma_u = 0.0275, loglik = -106578.8656
Iter 943: sigma_u = 0.0275, loglik = -106578.9339
Iter 944: sigma_u = 0.0275, loglik = -106578.9716
Iter 945: sigma_u = 0.0275, loglik = -106579.0437
Iter 946: sigma_u = 0.0275, loglik = -106579.0788
Iter 947: sigma_u = 0.0275, loglik = -106579.1565
Iter 948: sigma_u = 0.0275, loglik = -106579.1890
Iter 949: sigma_u = 0.0275, loglik = -106579.2818
Iter 950: sigma_u = 0.0275, loglik = -106579.3111
Iter 951: sigma_u = 0.0275, loglik = -106579.4261
Iter 952: sigma_u = 0.0275, loglik = -106579.4521
Iter 953: sigma_u = 0.0275, loglik = -106579.6107
Iter 954: sigma_u = 0.0275, loglik = -106579.6329
Iter 955: sigma_u = 0.0275, loglik = -106579.9164
Iter 956: sigma_u = 0.0274, loglik = -106579.9342
Iter 957: sigma_u = 0.0274, loglik = -106581.0027
Iter 958: sigma_u = 0.0274, loglik = -106581.0114
Iter 959: sigma_u = 0.0274, loglik = -106581.6449
Iter 960: sigma_u = 0.0274, loglik = -106581.6856
Iter 961: sigma_u = 0.0274, loglik = -106581.7873
Iter 962: sigma_u = 0.0274, loglik = -106581.8411
Iter 963: sigma_u = 0.0274, loglik = -106581.8867
Iter 964: sigma_u = 0.0274, loglik = -106581.9430
Iter 965: sigma_u = 0.0274, loglik = -106581.9879
Iter 966: sigma_u = 0.0274, loglik = -106582.0462
Iter 967: sigma_u = 0.0274, loglik = -106582.0894
Iter 968: sigma_u = 0.0274, loglik = -106582.1488
Iter 969: sigma_u = 0.0274, loglik = -106582.1904
Iter 970: sigma_u = 0.0274, loglik = -106582.2532
Iter 971: sigma_u = 0.0274, loglik = -106582.2922
Iter 972: sigma_u = 0.0274, loglik = -106582.3583
Iter 973: sigma_u = 0.0274, loglik = -106582.3954
Iter 974: sigma_u = 0.0274, loglik = -106582.4663
Iter 975: sigma_u = 0.0274, loglik = -106582.5007
Iter 976: sigma_u = 0.0274, loglik = -106582.5798
Iter 977: sigma_u = 0.0274, loglik = -106582.6116
Iter 978: sigma_u = 0.0274, loglik = -106582.7004
Iter 979: sigma_u = 0.0274, loglik = -106582.7296
Iter 980: sigma_u = 0.0274, loglik = -106582.8382
Iter 981: sigma_u = 0.0274, loglik = -106582.8642
Iter 982: sigma_u = 0.0274, loglik = -106583.0141
Iter 983: sigma_u = 0.0274, loglik = -106583.0365

Iter 984: sigma_u = 0.0274, loglik = -106583.3047
Iter 985: sigma_u = 0.0274, loglik = -106583.3223
Iter 986: sigma_u = 0.0274, loglik = -106584.2762
Iter 987: sigma_u = 0.0274, loglik = -106584.2858
Iter 988: sigma_u = 0.0274, loglik = -106584.7586
Iter 989: sigma_u = 0.0274, loglik = -106584.8004
Iter 990: sigma_u = 0.0274, loglik = -106584.8474
Iter 991: sigma_u = 0.0274, loglik = -106584.9042
Iter 992: sigma_u = 0.0274, loglik = -106584.9472
Iter 993: sigma_u = 0.0274, loglik = -106585.0049
Iter 994: sigma_u = 0.0274, loglik = -106585.0468
Iter 995: sigma_u = 0.0274, loglik = -106585.1070
Iter 996: sigma_u = 0.0274, loglik = -106585.1468
Iter 997: sigma_u = 0.0274, loglik = -106585.2078
Iter 998: sigma_u = 0.0274, loglik = -106585.2464
Iter 999: sigma_u = 0.0274, loglik = -106585.3139
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             2.50       2.484406     2.488804
1             0.45       0.437431     0.438043
2             0.25       0.225639     0.226053
3            -1.20      -1.193167    -1.195243
4             0.25       0.067687     0.027356



Time taken 7.600436997413635 minutes



Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.2161, loglik = -16565.5565
Iter 1: sigma_u = 0.9710, loglik = -17666.1610
Iter 2: sigma_u = 0.7757, loglik = -19410.1810
Iter 3: sigma_u = 0.6203, loglik = -22107.7867
Iter 4: sigma_u = 0.4968, loglik = -26228.8934
Iter 5: sigma_u = 0.3990, loglik = -32394.8659
Iter 6: sigma_u = 0.3219, loglik = -41206.7675
Iter 7: sigma_u = 0.2620, loglik = -52530.8202
Iter 8: sigma_u = 0.2166, loglik = -64745.3850
Iter 9: sigma_u = 0.1831, loglik = -75616.1737
Iter 10: sigma_u = 0.1584, loglik = -83974.1310
Iter 11: sigma_u = 0.1401, loglik = -89938.0145
Iter 12: sigma_u = 0.1261, loglik = -94119.1272
Iter 13: sigma_u = 0.1152, loglik = -97088.9845
Iter 14: sigma_u = 0.1065, loglik = -99251.7413
Iter 15: sigma_u = 0.0995, loglik = -100870.6102
Iter 16: sigma_u = 0.0936, loglik = -102114.2741
Iter 17: sigma_u = 0.0886, loglik = -103091.7869
Iter 18: sigma_u = 0.0843, loglik = -103877.1363
Iter 19: sigma_u = 0.0806, loglik = -104518.6115
Iter 20: sigma_u = 0.0774, loglik = -105051.2051
Iter 21: sigma_u = 0.0745, loglik = -105499.4353
Iter 22: sigma_u = 0.0720, loglik = -105883.5064
Iter 23: sigma_u = 0.0697, loglik = -106211.4918
Iter 24: sigma_u = 0.0677, loglik = -106498.6007
Iter 25: sigma_u = 0.0658, loglik = -106747.9629
Iter 26: sigma_u = 0.0641, loglik = -106969.4648
Iter 27: sigma_u = 0.0625, loglik = -107165.1859
Iter 28: sigma_u = 0.0611, loglik = -107339.6610
Iter 29: sigma_u = 0.0598, loglik = -107497.2103
Iter 30: sigma_u = 0.0586, loglik = -107639.0439
Iter 31: sigma_u = 0.0574, loglik = -107768.4530
Iter 32: sigma_u = 0.0564, loglik = -107886.2616
Iter 33: sigma_u = 0.0554, loglik = -107991.2402
Iter 34: sigma_u = 0.0545, loglik = -108089.4442
Iter 35: sigma_u = 0.0536, loglik = -108180.1862
Iter 36: sigma_u = 0.0528, loglik = -108263.7228
Iter 37: sigma_u = 0.0521, loglik = -108340.9354
Iter 38: sigma_u = 0.0513, loglik = -108412.4427
Iter 39: sigma_u = 0.0507, loglik = -108478.7904
Iter 40: sigma_u = 0.0500, loglik = -108540.9438
Iter 41: sigma_u = 0.0494, loglik = -108599.7797
Iter 42: sigma_u = 0.0488, loglik = -108655.5666
Iter 43: sigma_u = 0.0483, loglik = -108706.6309
Iter 44: sigma_u = 0.0477, loglik = -108754.6351
Iter 45: sigma_u = 0.0472, loglik = -108799.6952
Iter 46: sigma_u = 0.0468, loglik = -108841.4724
Iter 47: sigma_u = 0.0463, loglik = -108881.9152
Iter 48: sigma_u = 0.0459, loglik = -108919.7852
Iter 49: sigma_u = 0.0455, loglik = -108955.9106
Iter 50: sigma_u = 0.0451, loglik = -108989.9757
Iter 51: sigma_u = 0.0447, loglik = -109021.9716
Iter 52: sigma_u = 0.0443, loglik = -109053.1017
Iter 53: sigma_u = 0.0440, loglik = -109082.4958
Iter 54: sigma_u = 0.0436, loglik = -109109.8479
Iter 55: sigma_u = 0.0433, loglik = -109136.6052
Iter 56: sigma_u = 0.0430, loglik = -109163.2487
Iter 57: sigma_u = 0.0427, loglik = -109187.4231
Iter 58: sigma_u = 0.0424, loglik = -109210.7009
Iter 59: sigma_u = 0.0421, loglik = -109232.7428
Iter 60: sigma_u = 0.0418, loglik = -109253.5297
Iter 61: sigma_u = 0.0416, loglik = -109274.3818
Iter 62: sigma_u = 0.0414, loglik = -109292.5499
Iter 63: sigma_u = 0.0412, loglik = -109302.9501
Iter 64: sigma_u = 0.0412, loglik = -109319.7168
Iter 65: sigma_u = 0.0412, loglik = -109321.0507
Iter 66: sigma_u = 0.0412, loglik = -109321.8954
Iter 67: sigma_u = 0.0412, loglik = -109322.4524
Iter 68: sigma_u = 0.0412, loglik = -109323.2196
Iter 69: sigma_u = 0.0411, loglik = -109323.7644
Iter 70: sigma_u = 0.0411, loglik = -109324.5415
Iter 71: sigma_u = 0.0411, loglik = -109325.0799
Iter 72: sigma_u = 0.0411, loglik = -109325.8788
Iter 73: sigma_u = 0.0411, loglik = -109326.4054
Iter 74: sigma_u = 0.0411, loglik = -109327.2255
Iter 75: sigma_u = 0.0411, loglik = -109327.7399
Iter 76: sigma_u = 0.0411, loglik = -109328.5831
Iter 77: sigma_u = 0.0411, loglik = -109329.0847
Iter 78: sigma_u = 0.0411, loglik = -109329.9557
Iter 79: sigma_u = 0.0411, loglik = -109330.4449
Iter 80: sigma_u = 0.0410, loglik = -109331.3511
Iter 81: sigma_u = 0.0410, loglik = -109331.8265
Iter 82: sigma_u = 0.0410, loglik = -109332.7757
Iter 83: sigma_u = 0.0410, loglik = -109333.2368
Iter 84: sigma_u = 0.0410, loglik = -109334.2384
Iter 85: sigma_u = 0.0410, loglik = -109334.6845
Iter 86: sigma_u = 0.0410, loglik = -109335.7495
Iter 87: sigma_u = 0.0410, loglik = -109336.1815
Iter 88: sigma_u = 0.0410, loglik = -109337.3372
Iter 89: sigma_u = 0.0407, loglik = -109337.7505
Iter 90: sigma_u = 0.0404, loglik = -109354.6730
Iter 91: sigma_u = 0.0402, loglik = -109376.3937
Iter 92: sigma_u = 0.0400, loglik = -109391.1913
Iter 93: sigma_u = 0.0398, loglik = -109406.2116
Iter 94: sigma_u = 0.0396, loglik = -109424.5525
Iter 95: sigma_u = 0.0396, loglik = -109437.1174
Iter 96: sigma_u = 0.0396, loglik = -109438.3307
Iter 97: sigma_u = 0.0396, loglik = -109438.5927
Iter 98: sigma_u = 0.0396, loglik = -109439.9538
Iter 99: sigma_u = 0.0395, loglik = -109440.2237
Iter 100: sigma_u = 0.0395, loglik = -109441.8101
Iter 101: sigma_u = 0.0393, loglik = -109442.0579
Iter 102: sigma_u = 0.0392, loglik = -109455.6064
Iter 103: sigma_u = 0.0390, loglik = -109468.1102
Iter 104: sigma_u = 0.0389, loglik = -109481.1211
Iter 105: sigma_u = 0.0389, loglik = -109487.8919
Iter 106: sigma_u = 0.0389, loglik = -109488.5531
Iter 107: sigma_u = 0.0389, loglik = -109488.8084
Iter 108: sigma_u = 0.0388, loglik = -109489.5041
Iter 109: sigma_u = 0.0388, loglik = -109489.7501
Iter 110: sigma_u = 0.0388, loglik = -109490.5182
Iter 111: sigma_u = 0.0388, loglik = -109490.7583
Iter 112: sigma_u = 0.0388, loglik = -109491.6359
Iter 113: sigma_u = 0.0388, loglik = -109491.8672
Iter 114: sigma_u = 0.0388, loglik = -109492.9047
Iter 115: sigma_u = 0.0388, loglik = -109493.1264
Iter 116: sigma_u = 0.0388, loglik = -109494.4104
Iter 117: sigma_u = 0.0388, loglik = -109494.6217
Iter 118: sigma_u = 0.0388, loglik = -109496.3187
Iter 119: sigma_u = 0.0386, loglik = -109496.5197
Iter 120: sigma_u = 0.0384, loglik = -109507.7508
Iter 121: sigma_u = 0.0382, loglik = -109522.3348
Iter 122: sigma_u = 0.0381, loglik = -109532.3438
Iter 123: sigma_u = 0.0381, loglik = -109539.1769
Iter 124: sigma_u = 0.0381, loglik = -109542.1180
Iter 125: sigma_u = 0.0381, loglik = -109543.1988
Iter 126: sigma_u = 0.0381, loglik = -109543.4807
Iter 127: sigma_u = 0.0381, loglik = -109543.9722
Iter 128: sigma_u = 0.0381, loglik = -109544.1942
Iter 129: sigma_u = 0.0380, loglik = -109544.7186
Iter 130: sigma_u = 0.0380, loglik = -109544.9274
Iter 131: sigma_u = 0.0380, loglik = -109545.5117
Iter 132: sigma_u = 0.0380, loglik = -109545.7122
Iter 133: sigma_u = 0.0380, loglik = -109546.3786
Iter 134: sigma_u = 0.0380, loglik = -109546.5690
Iter 135: sigma_u = 0.0380, loglik = -109547.3656
Iter 136: sigma_u = 0.0380, loglik = -109547.5462
Iter 137: sigma_u = 0.0380, loglik = -109548.5370
Iter 138: sigma_u = 0.0380, loglik = -109548.7073
Iter 139: sigma_u = 0.0380, loglik = -109550.0949
Iter 140: sigma_u = 0.0379, loglik = -109550.2557
Iter 141: sigma_u = 0.0379, loglik = -109552.5295
Iter 142: sigma_u = 0.0378, loglik = -109552.6798
Iter 143: sigma_u = 0.0376, loglik = -109562.1480
Iter 144: sigma_u = 0.0376, loglik = -109574.4298
Iter 145: sigma_u = 0.0376, loglik = -109576.3775
Iter 146: sigma_u = 0.0376, loglik = -109576.5046
Iter 147: sigma_u = 0.0376, loglik = -109578.1088
Iter 148: sigma_u = 0.0376, loglik = -109578.3245
Iter 149: sigma_u = 0.0375, loglik = -109578.7450
Iter 150: sigma_u = 0.0375, loglik = -109578.9325
Iter 151: sigma_u = 0.0375, loglik = -109579.3872
Iter 152: sigma_u = 0.0375, loglik = -109579.5678
Iter 153: sigma_u = 0.0375, loglik = -109580.0728
Iter 154: sigma_u = 0.0375, loglik = -109580.2463
Iter 155: sigma_u = 0.0375, loglik = -109580.8254
Iter 156: sigma_u = 0.0375, loglik = -109580.9900
Iter 157: sigma_u = 0.0375, loglik = -109581.6845
Iter 158: sigma_u = 0.0375, loglik = -109581.8398
Iter 159: sigma_u = 0.0375, loglik = -109582.7178
Iter 160: sigma_u = 0.0375, loglik = -109582.8651
Iter 161: sigma_u = 0.0375, loglik = -109584.1042
Iter 162: sigma_u = 0.0374, loglik = -109584.2437
Iter 163: sigma_u = 0.0374, loglik = -109586.3192
Iter 164: sigma_u = 0.0373, loglik = -109586.4497
Iter 165: sigma_u = 0.0371, loglik = -109594.8603
Iter 166: sigma_u = 0.0371, loglik = -109605.7901

Iter 167: sigma_u = 0.0371, loglik = -109607.3744
Iter 168: sigma_u = 0.0371, loglik = -109607.4928
Iter 169: sigma_u = 0.0371, loglik = -109608.0210
Iter 170: sigma_u = 0.0371, loglik = -109608.1882
Iter 171: sigma_u = 0.0371, loglik = -109608.6340
Iter 172: sigma_u = 0.0371, loglik = -109608.7860
Iter 173: sigma_u = 0.0371, loglik = -109609.2863
Iter 174: sigma_u = 0.0371, loglik = -109609.4320
Iter 175: sigma_u = 0.0371, loglik = -109610.0224
Iter 176: sigma_u = 0.0371, loglik = -109610.1606
Iter 177: sigma_u = 0.0371, loglik = -109610.8889
Iter 178: sigma_u = 0.0371, loglik = -109611.0202
Iter 179: sigma_u = 0.0371, loglik = -109611.9986
Iter 180: sigma_u = 0.0370, loglik = -109612.1230
Iter 181: sigma_u = 0.0370, loglik = -109613.6716
Iter 182: sigma_u = 0.0369, loglik = -109613.7883
Iter 183: sigma_u = 0.0368, loglik = -109621.3876
Iter 184: sigma_u = 0.0367, loglik = -109631.2882
Iter 185: sigma_u = 0.0367, loglik = -109633.2803
Iter 186: sigma_u = 0.0367, loglik = -109633.4219
Iter 187: sigma_u = 0.0367, loglik = -109633.8140
Iter 188: sigma_u = 0.0367, loglik = -109633.9519
Iter 189: sigma_u = 0.0367, loglik = -109634.3573
Iter 190: sigma_u = 0.0367, loglik = -109634.4914
Iter 191: sigma_u = 0.0367, loglik = -109634.9578
Iter 192: sigma_u = 0.0367, loglik = -109635.0856
Iter 193: sigma_u = 0.0367, loglik = -109635.6478
Iter 194: sigma_u = 0.0367, loglik = -109635.7690
Iter 195: sigma_u = 0.0367, loglik = -109636.4996
Iter 196: sigma_u = 0.0367, loglik = -109636.6137
Iter 197: sigma_u = 0.0367, loglik = -109637.6661
Iter 198: sigma_u = 0.0366, loglik = -109637.7739
Iter 199: sigma_u = 0.0366, loglik = -109639.6241
Iter 200: sigma_u = 0.0365, loglik = -109639.7255
Iter 201: sigma_u = 0.0365, loglik = -109648.0254
Iter 202: sigma_u = 0.0365, loglik = -109648.1348
Iter 203: sigma_u = 0.0365, loglik = -109648.9617
Iter 204: sigma_u = 0.0365, loglik = -109649.0688
Iter 205: sigma_u = 0.0365, loglik = -109650.2005
Iter 206: sigma_u = 0.0364, loglik = -109650.3009
Iter 207: sigma_u = 0.0364, loglik = -109652.1372
Iter 208: sigma_u = 0.0364, loglik = -109652.2416
Iter 209: sigma_u = 0.0364, loglik = -109653.7306
Iter 210: sigma_u = 0.0364, loglik = -109653.8214
Iter 211: sigma_u = 0.0364, loglik = -109654.2425
Iter 212: sigma_u = 0.0364, loglik = -109654.3905
Iter 213: sigma_u = 0.0364, loglik = -109654.6724
Iter 214: sigma_u = 0.0364, loglik = -109654.8092
Iter 215: sigma_u = 0.0364, loglik = -109655.1101
Iter 216: sigma_u = 0.0364, loglik = -109655.2420
Iter 217: sigma_u = 0.0364, loglik = -109655.5655
Iter 218: sigma_u = 0.0364, loglik = -109655.6925
Iter 219: sigma_u = 0.0364, loglik = -109656.0467
Iter 220: sigma_u = 0.0364, loglik = -109656.1692
Iter 221: sigma_u = 0.0364, loglik = -109656.5630
Iter 222: sigma_u = 0.0364, loglik = -109656.6805
Iter 223: sigma_u = 0.0364, loglik = -109657.1326
Iter 224: sigma_u = 0.0364, loglik = -109657.2461
Iter 225: sigma_u = 0.0364, loglik = -109657.7764
Iter 226: sigma_u = 0.0364, loglik = -109657.8845
Iter 227: sigma_u = 0.0363, loglik = -109658.5584
Iter 228: sigma_u = 0.0363, loglik = -109658.6612
Iter 229: sigma_u = 0.0363, loglik = -109659.5941
Iter 230: sigma_u = 0.0363, loglik = -109659.6924
Iter 231: sigma_u = 0.0363, loglik = -109661.0679
Iter 232: sigma_u = 0.0363, loglik = -109661.1627
Iter 233: sigma_u = 0.0363, loglik = -109663.6678
Iter 234: sigma_u = 0.0362, loglik = -109663.7549
Iter 235: sigma_u = 0.0362, loglik = -109671.2150
Iter 236: sigma_u = 0.0361, loglik = -109671.3002
Iter 237: sigma_u = 0.0361, loglik = -109672.2339
Iter 238: sigma_u = 0.0361, loglik = -109672.3506
Iter 239: sigma_u = 0.0361, loglik = -109672.7073
Iter 240: sigma_u = 0.0361, loglik = -109672.8125
Iter 241: sigma_u = 0.0361, loglik = -109673.2210
Iter 242: sigma_u = 0.0361, loglik = -109673.3253
Iter 243: sigma_u = 0.0361, loglik = -109673.8205
Iter 244: sigma_u = 0.0361, loglik = -109673.9179
Iter 245: sigma_u = 0.0361, loglik = -109674.5555
Iter 246: sigma_u = 0.0361, loglik = -109674.6485
Iter 247: sigma_u = 0.0361, loglik = -109675.5914
Iter 248: sigma_u = 0.0361, loglik = -109675.6786
Iter 249: sigma_u = 0.0361, loglik = -109677.5232
Iter 250: sigma_u = 0.0360, loglik = -109677.6068
Iter 251: sigma_u = 0.0360, loglik = -109683.7847
Iter 252: sigma_u = 0.0360, loglik = -109683.9955
Iter 253: sigma_u = 0.0360, loglik = -109684.2411
Iteration 253: beta norm = 2.0793694954961204, sigma_u = 0.0360
Iter 254: sigma_u = 0.0360, loglik = -109684.4011
Iter 255: sigma_u = 0.0359, loglik = -109684.5984
Iter 256: sigma_u = 0.0359, loglik = -109684.7356
Iter 257: sigma_u = 0.0359, loglik = -109684.9233
Iter 258: sigma_u = 0.0359, loglik = -109685.0592
Iter 259: sigma_u = 0.0359, loglik = -109685.2485
Iter 260: sigma_u = 0.0359, loglik = -109685.3833
Iter 261: sigma_u = 0.0359, loglik = -109685.5768
Iter 262: sigma_u = 0.0359, loglik = -109685.7079
Iter 263: sigma_u = 0.0359, loglik = -109685.9071
Iter 264: sigma_u = 0.0359, loglik = -109686.0362
Iter 265: sigma_u = 0.0359, loglik = -109686.2397
Iter 266: sigma_u = 0.0359, loglik = -109686.3654
Iter 267: sigma_u = 0.0359, loglik = -109686.5745
Iter 268: sigma_u = 0.0359, loglik = -109686.6987
Iter 269: sigma_u = 0.0359, loglik = -109686.9165
Iter 270: sigma_u = 0.0359, loglik = -109687.0367
Iter 271: sigma_u = 0.0359, loglik = -109687.2594
Iter 272: sigma_u = 0.0359, loglik = -109687.3773
Iter 273: sigma_u = 0.0359, loglik = -109687.6091
Iter 274: sigma_u = 0.0359, loglik = -109687.7247
Iter 275: sigma_u = 0.0359, loglik = -109687.9737
Iter 276: sigma_u = 0.0359, loglik = -109688.0854
Iter 277: sigma_u = 0.0359, loglik = -109688.3488
Iter 278: sigma_u = 0.0359, loglik = -109688.4569
Iter 279: sigma_u = 0.0359, loglik = -109688.7335
Iter 280: sigma_u = 0.0359, loglik = -109688.8391
Iter 281: sigma_u = 0.0359, loglik = -109689.1414
Iter 282: sigma_u = 0.0359, loglik = -109689.2434
Iter 283: sigma_u = 0.0359, loglik = -109689.5738
Iter 284: sigma_u = 0.0359, loglik = -109689.6722
Iter 285: sigma_u = 0.0359, loglik = -109690.0593
Iter 286: sigma_u = 0.0359, loglik = -109690.1534
Iter 287: sigma_u = 0.0359, loglik = -109690.5965
Iter 288: sigma_u = 0.0358, loglik = -109690.6878
Iter 289: sigma_u = 0.0358, loglik = -109691.2168
Iter 290: sigma_u = 0.0358, loglik = -109691.3039
Iter 291: sigma_u = 0.0358, loglik = -109692.0004
Iter 292: sigma_u = 0.0358, loglik = -109692.0836
Iter 293: sigma_u = 0.0358, loglik = -109693.1242
Iter 294: sigma_u = 0.0358, loglik = -109693.2038
Iter 295: sigma_u = 0.0358, loglik = -109695.2102
Iter 296: sigma_u = 0.0357, loglik = -109695.2851
Iter 297: sigma_u = 0.0357, loglik = -109699.6962
Iter 298: sigma_u = 0.0357, loglik = -109699.7980
Iter 299: sigma_u = 0.0357, loglik = -109700.0220
Iter 300: sigma_u = 0.0357, loglik = -109700.1372
Iter 301: sigma_u = 0.0357, loglik = -109700.3300
Iter 302: sigma_u = 0.0357, loglik = -109700.4438
Iter 303: sigma_u = 0.0357, loglik = -109700.6456
Iter 304: sigma_u = 0.0357, loglik = -109700.7564
Iter 305: sigma_u = 0.0357, loglik = -109700.9663
Iter 306: sigma_u = 0.0357, loglik = -109701.0746
Iter 307: sigma_u = 0.0357, loglik = -109701.2945
Iter 308: sigma_u = 0.0357, loglik = -109701.4002
Iter 309: sigma_u = 0.0357, loglik = -109701.6343
Iter 310: sigma_u = 0.0357, loglik = -109701.7361
Iter 311: sigma_u = 0.0357, loglik = -109701.9865
Iter 312: sigma_u = 0.0357, loglik = -109702.0853
Iter 313: sigma_u = 0.0357, loglik = -109702.3636
Iter 314: sigma_u = 0.0357, loglik = -109702.4584
Iter 315: sigma_u = 0.0357, loglik = -109702.7701
Iter 316: sigma_u = 0.0357, loglik = -109702.8610
Iter 317: sigma_u = 0.0357, loglik = -109703.2176
Iter 318: sigma_u = 0.0357, loglik = -109703.3050
Iter 319: sigma_u = 0.0357, loglik = -109703.7133
Iter 320: sigma_u = 0.0356, loglik = -109703.7975
Iter 321: sigma_u = 0.0356, loglik = -109704.3024
Iter 322: sigma_u = 0.0356, loglik = -109704.3830
Iter 323: sigma_u = 0.0356, loglik = -109705.0543
Iter 324: sigma_u = 0.0356, loglik = -109705.1315
Iter 325: sigma_u = 0.0356, loglik = -109706.1073
Iter 326: sigma_u = 0.0356, loglik = -109706.1818
Iter 327: sigma_u = 0.0356, loglik = -109707.8860
Iter 328: sigma_u = 0.0355, loglik = -109707.9561
Iter 329: sigma_u = 0.0355, loglik = -109712.4982

Iter 330: sigma_u = 0.0355, loglik = -109712.5755
Iter 331: sigma_u = 0.0355, loglik = -109713.2731
Iter 332: sigma_u = 0.0355, loglik = -109713.3475
Iter 333: sigma_u = 0.0355, loglik = -109713.6184
Iter 334: sigma_u = 0.0355, loglik = -109713.7115
Iter 335: sigma_u = 0.0355, loglik = -109713.9761
Iter 336: sigma_u = 0.0355, loglik = -109714.0631
Iter 337: sigma_u = 0.0355, loglik = -109714.3600
Iter 338: sigma_u = 0.0355, loglik = -109714.4444
Iter 339: sigma_u = 0.0355, loglik = -109714.7884
Iter 340: sigma_u = 0.0355, loglik = -109714.8687
Iter 341: sigma_u = 0.0355, loglik = -109715.2884
Iter 342: sigma_u = 0.0355, loglik = -109715.3654
Iter 343: sigma_u = 0.0355, loglik = -109715.8932
Iter 344: sigma_u = 0.0355, loglik = -109715.9672
Iter 345: sigma_u = 0.0355, loglik = -109716.6659
Iter 346: sigma_u = 0.0354, loglik = -109716.7370
Iter 347: sigma_u = 0.0354, loglik = -109717.8608
Iter 348: sigma_u = 0.0354, loglik = -109717.9290
Iter 349: sigma_u = 0.0354, loglik = -109720.2862
Iter 350: sigma_u = 0.0354, loglik = -109720.3488
Iter 351: sigma_u = 0.0353, loglik = -109723.0905
Iter 352: sigma_u = 0.0353, loglik = -109723.2181
Iter 353: sigma_u = 0.0353, loglik = -109723.4663
Iter 354: sigma_u = 0.0353, loglik = -109723.5528
Iter 355: sigma_u = 0.0353, loglik = -109723.8030
Iter 356: sigma_u = 0.0353, loglik = -109723.8852
Iter 357: sigma_u = 0.0353, loglik = -109724.1688
Iter 358: sigma_u = 0.0353, loglik = -109724.2479
Iter 359: sigma_u = 0.0353, loglik = -109724.5626
Iter 360: sigma_u = 0.0353, loglik = -109724.6391
Iter 361: sigma_u = 0.0353, loglik = -109725.0169
Iter 362: sigma_u = 0.0353, loglik = -109725.0895
Iter 363: sigma_u = 0.0353, loglik = -109725.5718
Iter 364: sigma_u = 0.0353, loglik = -109725.6417
Iter 365: sigma_u = 0.0353, loglik = -109726.3487
Iter 366: sigma_u = 0.0353, loglik = -109726.4149
Iter 367: sigma_u = 0.0353, loglik = -109727.6021
Iter 368: sigma_u = 0.0352, loglik = -109727.6662
Iter 369: sigma_u = 0.0352, loglik = -109729.9883
Iter 370: sigma_u = 0.0352, loglik = -109730.0443
Iter 371: sigma_u = 0.0352, loglik = -109730.7375
Iter 372: sigma_u = 0.0352, loglik = -109730.8580
Iter 373: sigma_u = 0.0352, loglik = -109731.1461
Iter 374: sigma_u = 0.0352, loglik = -109731.2354
Iter 375: sigma_u = 0.0352, loglik = -109731.4457
Iter 376: sigma_u = 0.0352, loglik = -109731.5276
Iter 377: sigma_u = 0.0352, loglik = -109731.7542
Iter 378: sigma_u = 0.0352, loglik = -109731.8343
Iter 379: sigma_u = 0.0352, loglik = -109732.0887
Iter 380: sigma_u = 0.0352, loglik = -109732.1648
Iter 381: sigma_u = 0.0352, loglik = -109732.4577
Iter 382: sigma_u = 0.0352, loglik = -109732.5310
Iter 383: sigma_u = 0.0352, loglik = -109732.8866
Iter 384: sigma_u = 0.0352, loglik = -109732.9564
Iter 385: sigma_u = 0.0352, loglik = -109733.3910
Iter 386: sigma_u = 0.0352, loglik = -109733.4581
Iter 387: sigma_u = 0.0352, loglik = -109734.0654
Iter 388: sigma_u = 0.0352, loglik = -109734.1292
Iter 389: sigma_u = 0.0352, loglik = -109735.0990
Iter 390: sigma_u = 0.0351, loglik = -109735.1612
Iter 391: sigma_u = 0.0351, loglik = -109736.7714
Iter 392: sigma_u = 0.0351, loglik = -109736.8280
Iter 393: sigma_u = 0.0351, loglik = -109739.2519
Iter 394: sigma_u = 0.0351, loglik = -109739.3563
Iter 395: sigma_u = 0.0351, loglik = -109739.4912
Iter 396: sigma_u = 0.0351, loglik = -109739.5880
Iter 397: sigma_u = 0.0351, loglik = -109739.7235
Iter 398: sigma_u = 0.0351, loglik = -109739.8195
Iter 399: sigma_u = 0.0351, loglik = -109739.9582
Iter 400: sigma_u = 0.0351, loglik = -109740.0527
Iter 401: sigma_u = 0.0351, loglik = -109740.1960
Iter 402: sigma_u = 0.0351, loglik = -109740.2879
Iter 403: sigma_u = 0.0351, loglik = -109740.4354
Iter 404: sigma_u = 0.0351, loglik = -109740.5263
Iter 405: sigma_u = 0.0351, loglik = -109740.6787
Iter 406: sigma_u = 0.0351, loglik = -109740.7674
Iter 407: sigma_u = 0.0351, loglik = -109740.9183
Iter 408: sigma_u = 0.0351, loglik = -109741.0066
Iter 409: sigma_u = 0.0351, loglik = -109741.1648
Iter 410: sigma_u = 0.0351, loglik = -109741.2505
Iter 411: sigma_u = 0.0351, loglik = -109741.4143
Iter 412: sigma_u = 0.0351, loglik = -109741.4986
Iter 413: sigma_u = 0.0351, loglik = -109741.6707
Iter 414: sigma_u = 0.0351, loglik = -109741.7520
Iter 415: sigma_u = 0.0351, loglik = -109741.9370
Iter 416: sigma_u = 0.0350, loglik = -109742.0158
Iter 417: sigma_u = 0.0350, loglik = -109742.2095
Iter 418: sigma_u = 0.0350, loglik = -109742.2866
Iter 419: sigma_u = 0.0350, loglik = -109742.4977
Iter 420: sigma_u = 0.0350, loglik = -109742.5715
Iter 421: sigma_u = 0.0350, loglik = -109742.8034
Iter 422: sigma_u = 0.0350, loglik = -109742.8748
Iter 423: sigma_u = 0.0350, loglik = -109743.1437
Iter 424: sigma_u = 0.0350, loglik = -109743.2119
Iter 425: sigma_u = 0.0350, loglik = -109743.5288
Iter 426: sigma_u = 0.0350, loglik = -109743.5947
Iter 427: sigma_u = 0.0350, loglik = -109743.9839
Iter 428: sigma_u = 0.0350, loglik = -109744.0471
Iter 429: sigma_u = 0.0350, loglik = -109744.5701
Iter 430: sigma_u = 0.0350, loglik = -109744.6305
Iter 431: sigma_u = 0.0350, loglik = -109745.3603
Iter 432: sigma_u = 0.0350, loglik = -109745.4180
Iter 433: sigma_u = 0.0350, loglik = -109746.6940
Iter 434: sigma_u = 0.0349, loglik = -109746.7498
Iter 435: sigma_u = 0.0349, loglik = -109749.6079
Iter 436: sigma_u = 0.0349, loglik = -109749.6596
Iter 437: sigma_u = 0.0349, loglik = -109752.3010
Iter 438: sigma_u = 0.0349, loglik = -109752.4107
Iter 439: sigma_u = 0.0349, loglik = -109752.9572
Iter 440: sigma_u = 0.0349, loglik = -109753.0389
Iter 441: sigma_u = 0.0349, loglik = -109753.2102
Iter 442: sigma_u = 0.0349, loglik = -109753.2819
Iter 443: sigma_u = 0.0349, loglik = -109753.4678
Iter 444: sigma_u = 0.0349, loglik = -109753.5369
Iter 445: sigma_u = 0.0349, loglik = -109753.7443
Iter 446: sigma_u = 0.0349, loglik = -109753.8096
Iter 447: sigma_u = 0.0349, loglik = -109754.0550
Iter 448: sigma_u = 0.0349, loglik = -109754.1175
Iter 449: sigma_u = 0.0349, loglik = -109754.4152
Iter 450: sigma_u = 0.0348, loglik = -109754.4751
Iter 451: sigma_u = 0.0348, loglik = -109754.8672
Iter 452: sigma_u = 0.0348, loglik = -109754.9234
Iter 453: sigma_u = 0.0348, loglik = -109755.4963
Iter 454: sigma_u = 0.0348, loglik = -109755.5496
Iter 455: sigma_u = 0.0348, loglik = -109756.6746
Iter 456: sigma_u = 0.0348, loglik = -109756.7249
Iter 457: sigma_u = 0.0348, loglik = -109760.2838
Iter 458: sigma_u = 0.0348, loglik = -109760.3397
Iter 459: sigma_u = 0.0348, loglik = -109760.7953
Iter 460: sigma_u = 0.0347, loglik = -109760.8510
Iter 461: sigma_u = 0.0347, loglik = -109761.1036
Iter 462: sigma_u = 0.0347, loglik = -109761.1645
Iter 463: sigma_u = 0.0347, loglik = -109761.4456
Iter 464: sigma_u = 0.0347, loglik = -109761.5016
Iter 465: sigma_u = 0.0347, loglik = -109761.8672
Iter 466: sigma_u = 0.0347, loglik = -109761.9224
Iter 467: sigma_u = 0.0347, loglik = -109762.4310
Iter 468: sigma_u = 0.0347, loglik = -109762.4820
Iter 469: sigma_u = 0.0347, loglik = -109763.4303
Iter 470: sigma_u = 0.0347, loglik = -109763.4826
Iter 471: sigma_u = 0.0347, loglik = -109764.2724
Iter 472: sigma_u = 0.0347, loglik = -109764.3174
Iter 473: sigma_u = 0.0347, loglik = -109764.5168
Iter 474: sigma_u = 0.0347, loglik = -109764.5963
Iter 475: sigma_u = 0.0347, loglik = -109764.7364
Iter 476: sigma_u = 0.0347, loglik = -109764.8064
Iter 477: sigma_u = 0.0347, loglik = -109764.9594
Iter 478: sigma_u = 0.0347, loglik = -109765.0262
Iter 479: sigma_u = 0.0347, loglik = -109765.1898
Iter 480: sigma_u = 0.0347, loglik = -109765.2546
Iter 481: sigma_u = 0.0347, loglik = -109765.4414
Iter 482: sigma_u = 0.0347, loglik = -109765.5024
Iter 483: sigma_u = 0.0347, loglik = -109765.7197
Iter 484: sigma_u = 0.0347, loglik = -109765.7778
Iter 485: sigma_u = 0.0347, loglik = -109766.0433
Iter 486: sigma_u = 0.0347, loglik = -109766.0982
Iter 487: sigma_u = 0.0347, loglik = -109766.4356
Iter 488: sigma_u = 0.0347, loglik = -109766.4877
Iter 489: sigma_u = 0.0347, loglik = -109767.0055
Iter 490: sigma_u = 0.0346, loglik = -109767.0547
Iter 491: sigma_u = 0.0346, loglik = -109768.0486
Iter 492: sigma_u = 0.0346, loglik = -109768.0954
Iter 493: sigma_u = 0.0346, loglik = -109771.0768

Iter 494: sigma_u = 0.0345, loglik = -109771.1212
Iter 495: sigma_u = 0.0345, loglik = -109775.4218
Iter 496: sigma_u = 0.0345, loglik = -109775.4783
Iter 497: sigma_u = 0.0345, loglik = -109775.7153
Iter 498: sigma_u = 0.0345, loglik = -109775.7671
Iter 499: sigma_u = 0.0345, loglik = -109776.0151
Iter 500: sigma_u = 0.0345, loglik = -109776.0683
Iter 501: sigma_u = 0.0345, loglik = -109776.3527
Iter 502: sigma_u = 0.0345, loglik = -109776.4023
Iter 503: sigma_u = 0.0345, loglik = -109776.7703
Iter 504: sigma_u = 0.0345, loglik = -109776.8192
Iter 505: sigma_u = 0.0345, loglik = -109777.3080
Iter 506: sigma_u = 0.0345, loglik = -109777.3533
Iter 507: sigma_u = 0.0345, loglik = -109778.1134
Iter 508: sigma_u = 0.0345, loglik = -109778.1616
Iter 509: sigma_u = 0.0345, loglik = -109778.7331
Iter 510: sigma_u = 0.0345, loglik = -109778.7756
Iter 511: sigma_u = 0.0345, loglik = -109778.9943
Iter 512: sigma_u = 0.0345, loglik = -109779.0591
Iter 513: sigma_u = 0.0345, loglik = -109779.2032
Iter 514: sigma_u = 0.0345, loglik = -109779.2626
Iter 515: sigma_u = 0.0345, loglik = -109779.4183
Iter 516: sigma_u = 0.0345, loglik = -109779.4762
Iter 517: sigma_u = 0.0344, loglik = -109779.6418
Iter 518: sigma_u = 0.0344, loglik = -109779.6975
Iter 519: sigma_u = 0.0344, loglik = -109779.8841
Iter 520: sigma_u = 0.0344, loglik = -109779.9378
Iter 521: sigma_u = 0.0344, loglik = -109780.1419
Iter 522: sigma_u = 0.0344, loglik = -109780.1942
Iter 523: sigma_u = 0.0344, loglik = -109780.4339
Iter 524: sigma_u = 0.0344, loglik = -109780.4842
Iter 525: sigma_u = 0.0344, loglik = -109780.7609
Iter 526: sigma_u = 0.0344, loglik = -109780.8093
Iter 527: sigma_u = 0.0344, loglik = -109781.1585
Iter 528: sigma_u = 0.0344, loglik = -109781.2051
Iter 529: sigma_u = 0.0344, loglik = -109781.6834
Iter 530: sigma_u = 0.0344, loglik = -109781.7282
Iter 531: sigma_u = 0.0344, loglik = -109782.5302
Iter 532: sigma_u = 0.0344, loglik = -109782.5730
Iter 533: sigma_u = 0.0344, loglik = -109784.3180
Iter 534: sigma_u = 0.0344, loglik = -109784.3572
Iter 535: sigma_u = 0.0344, loglik = -109785.4737
Iter 536: sigma_u = 0.0343, loglik = -109785.5559
Iter 537: sigma_u = 0.0343, loglik = -109785.8872
Iter 538: sigma_u = 0.0343, loglik = -109785.9436
Iter 539: sigma_u = 0.0343, loglik = -109786.1066
Iter 540: sigma_u = 0.0343, loglik = -109786.1582
Iter 541: sigma_u = 0.0343, loglik = -109786.3332
Iter 542: sigma_u = 0.0343, loglik = -109786.3843
Iter 543: sigma_u = 0.0343, loglik = -109786.5839
Iter 544: sigma_u = 0.0343, loglik = -109786.6330
Iter 545: sigma_u = 0.0343, loglik = -109786.8701
Iter 546: sigma_u = 0.0343, loglik = -109786.9173
Iter 547: sigma_u = 0.0343, loglik = -109787.2191
Iter 548: sigma_u = 0.0343, loglik = -109787.2637
Iter 549: sigma_u = 0.0343, loglik = -109787.7024
Iter 550: sigma_u = 0.0343, loglik = -109787.7456
Iter 551: sigma_u = 0.0343, loglik = -109788.4267
Iter 552: sigma_u = 0.0343, loglik = -109788.4667
Iter 553: sigma_u = 0.0343, loglik = -109790.1220
Iter 554: sigma_u = 0.0343, loglik = -109790.1687
Iter 555: sigma_u = 0.0343, loglik = -109790.3991
Iter 556: sigma_u = 0.0343, loglik = -109790.4484
Iter 557: sigma_u = 0.0343, loglik = -109790.5951
Iter 558: sigma_u = 0.0343, loglik = -109790.6474
Iter 559: sigma_u = 0.0343, loglik = -109790.8046
Iter 560: sigma_u = 0.0343, loglik = -109790.8544
Iter 561: sigma_u = 0.0343, loglik = -109791.0285
Iter 562: sigma_u = 0.0343, loglik = -109791.0769
Iter 563: sigma_u = 0.0343, loglik = -109791.2776
Iter 564: sigma_u = 0.0343, loglik = -109791.3242
Iter 565: sigma_u = 0.0343, loglik = -109791.5589
Iter 566: sigma_u = 0.0343, loglik = -109791.6041
Iter 567: sigma_u = 0.0343, loglik = -109791.8967
Iter 568: sigma_u = 0.0342, loglik = -109791.9399
Iter 569: sigma_u = 0.0342, loglik = -109792.3511
Iter 570: sigma_u = 0.0342, loglik = -109792.3921
Iter 571: sigma_u = 0.0342, loglik = -109793.0327
Iter 572: sigma_u = 0.0342, loglik = -109793.0730
Iter 573: sigma_u = 0.0342, loglik = -109794.3012
Iter 574: sigma_u = 0.0342, loglik = -109794.3359
Iter 575: sigma_u = 0.0342, loglik = -109794.6845
Iter 576: sigma_u = 0.0342, loglik = -109794.7580
Iter 577: sigma_u = 0.0342, loglik = -109794.8908
Iter 578: sigma_u = 0.0342, loglik = -109794.9466
Iter 579: sigma_u = 0.0342, loglik = -109795.0645
Iter 580: sigma_u = 0.0342, loglik = -109795.1182
Iter 581: sigma_u = 0.0342, loglik = -109795.2470
Iter 582: sigma_u = 0.0342, loglik = -109795.2979
Iter 583: sigma_u = 0.0342, loglik = -109795.4402
Iter 584: sigma_u = 0.0342, loglik = -109795.4890
Iter 585: sigma_u = 0.0342, loglik = -109795.6446
Iter 586: sigma_u = 0.0342, loglik = -109795.6921
Iter 587: sigma_u = 0.0342, loglik = -109795.8778
Iter 588: sigma_u = 0.0342, loglik = -109795.9229
Iter 589: sigma_u = 0.0342, loglik = -109796.1538
Iter 590: sigma_u = 0.0342, loglik = -109796.1974
Iter 591: sigma_u = 0.0342, loglik = -109796.4592
Iter 592: sigma_u = 0.0342, loglik = -109796.5008
Iter 593: sigma_u = 0.0342, loglik = -109796.8482
Iter 594: sigma_u = 0.0342, loglik = -109796.8881
Iter 595: sigma_u = 0.0342, loglik = -109797.4116
Iter 596: sigma_u = 0.0341, loglik = -109797.4501
Iter 597: sigma_u = 0.0341, loglik = -109798.4137
Iter 598: sigma_u = 0.0341, loglik = -109798.4506
Iter 599: sigma_u = 0.0341, loglik = -109801.0130
Iter 600: sigma_u = 0.0341, loglik = -109801.0488
Iter 601: sigma_u = 0.0341, loglik = -109804.0560
Iter 602: sigma_u = 0.0341, loglik = -109804.1053
Iter 603: sigma_u = 0.0341, loglik = -109804.2153
Iter 604: sigma_u = 0.0340, loglik = -109804.2611
Iter 605: sigma_u = 0.0340, loglik = -109804.3872
Iter 606: sigma_u = 0.0340, loglik = -109804.4328
Iter 607: sigma_u = 0.0340, loglik = -109804.5756
Iter 608: sigma_u = 0.0340, loglik = -109804.6198
Iter 609: sigma_u = 0.0340, loglik = -109804.7812
Iter 610: sigma_u = 0.0340, loglik = -109804.8239
Iter 611: sigma_u = 0.0340, loglik = -109805.0070
Iter 612: sigma_u = 0.0340, loglik = -109805.0479
Iter 613: sigma_u = 0.0340, loglik = -109805.2710
Iter 614: sigma_u = 0.0340, loglik = -109805.3108
Iter 615: sigma_u = 0.0340, loglik = -109805.5798
Iter 616: sigma_u = 0.0340, loglik = -109805.6180
Iter 617: sigma_u = 0.0340, loglik = -109805.9976
Iter 618: sigma_u = 0.0340, loglik = -109806.0337
Iter 619: sigma_u = 0.0340, loglik = -109806.6125
Iter 620: sigma_u = 0.0340, loglik = -109806.6489
Iter 621: sigma_u = 0.0340, loglik = -109807.3882
Iter 622: sigma_u = 0.0340, loglik = -109807.4190
Iter 623: sigma_u = 0.0340, loglik = -109807.6038
Iter 624: sigma_u = 0.0340, loglik = -109807.6636
Iter 625: sigma_u = 0.0340, loglik = -109807.7593
Iter 626: sigma_u = 0.0340, loglik = -109807.8104
Iter 627: sigma_u = 0.0340, loglik = -109807.9090
Iter 628: sigma_u = 0.0340, loglik = -109807.9584
Iter 629: sigma_u = 0.0340, loglik = -109808.0620
Iter 630: sigma_u = 0.0340, loglik = -109808.1100
Iter 631: sigma_u = 0.0340, loglik = -109808.2160
Iter 632: sigma_u = 0.0340, loglik = -109808.2637
Iter 633: sigma_u = 0.0340, loglik = -109808.3783
Iter 634: sigma_u = 0.0340, loglik = -109808.4243
Iter 635: sigma_u = 0.0340, loglik = -109808.5507
Iter 636: sigma_u = 0.0340, loglik = -109808.5948
Iter 637: sigma_u = 0.0340, loglik = -109808.7266
Iter 638: sigma_u = 0.0340, loglik = -109808.7695
Iter 639: sigma_u = 0.0340, loglik = -109808.9238
Iter 640: sigma_u = 0.0340, loglik = -109808.9647
Iter 641: sigma_u = 0.0340, loglik = -109809.1481
Iter 642: sigma_u = 0.0340, loglik = -109809.1873
Iter 643: sigma_u = 0.0340, loglik = -109809.4123
Iter 644: sigma_u = 0.0340, loglik = -109809.4501
Iter 645: sigma_u = 0.0340, loglik = -109809.7285
Iter 646: sigma_u = 0.0340, loglik = -109809.7648
Iteration 646: beta norm = 2.0783129771008606, sigma_u = 0.0340
Iter 647: sigma_u = 0.0340, loglik = -109810.1383
Iter 648: sigma_u = 0.0339, loglik = -109810.1739
Iter 649: sigma_u = 0.0339, loglik = -109810.7216
Iter 650: sigma_u = 0.0339, loglik = -109810.7552
Iter 651: sigma_u = 0.0339, loglik = -109811.8511
Iter 652: sigma_u = 0.0339, loglik = -109811.8849
Iter 653: sigma_u = 0.0339, loglik = -109813.2090
Iter 654: sigma_u = 0.0339, loglik = -109813.2367
Iter 655: sigma_u = 0.0339, loglik = -109813.3142
Iter 656: sigma_u = 0.0339, loglik = -109813.3786

Iter 657: sigma_u = 0.0339, loglik = -109813.4415
Iter 658: sigma_u = 0.0339, loglik = -109813.5048
Iter 659: sigma_u = 0.0339, loglik = -109813.5691
Iter 660: sigma_u = 0.0339, loglik = -109813.6316
Iter 661: sigma_u = 0.0339, loglik = -109813.6929
Iter 662: sigma_u = 0.0339, loglik = -109813.7562
Iter 663: sigma_u = 0.0339, loglik = -109813.8158
Iter 664: sigma_u = 0.0339, loglik = -109813.8799
Iter 665: sigma_u = 0.0339, loglik = -109813.9400
Iter 666: sigma_u = 0.0339, loglik = -109814.0056
Iter 667: sigma_u = 0.0339, loglik = -109814.0657
Iter 668: sigma_u = 0.0339, loglik = -109814.1313
Iter 669: sigma_u = 0.0339, loglik = -109814.1907
Iter 670: sigma_u = 0.0339, loglik = -109814.2574
Iter 671: sigma_u = 0.0339, loglik = -109814.3160
Iter 672: sigma_u = 0.0339, loglik = -109814.3836
Iter 673: sigma_u = 0.0339, loglik = -109814.4400
Iter 674: sigma_u = 0.0339, loglik = -109814.5093
Iter 675: sigma_u = 0.0339, loglik = -109814.5665
Iter 676: sigma_u = 0.0339, loglik = -109814.6358
Iter 677: sigma_u = 0.0339, loglik = -109814.6921
Iter 678: sigma_u = 0.0339, loglik = -109814.7631
Iter 679: sigma_u = 0.0339, loglik = -109814.8179
Iter 680: sigma_u = 0.0339, loglik = -109814.8904
Iter 681: sigma_u = 0.0339, loglik = -109814.9444
Iter 682: sigma_u = 0.0339, loglik = -109815.0191
Iter 683: sigma_u = 0.0339, loglik = -109815.0720
Iter 684: sigma_u = 0.0339, loglik = -109815.1469
Iter 685: sigma_u = 0.0339, loglik = -109815.1973
Iter 686: sigma_u = 0.0339, loglik = -109815.2755
Iter 687: sigma_u = 0.0339, loglik = -109815.3258
Iter 688: sigma_u = 0.0339, loglik = -109815.4092
Iter 689: sigma_u = 0.0339, loglik = -109815.4574
Iter 690: sigma_u = 0.0339, loglik = -109815.5440
Iter 691: sigma_u = 0.0339, loglik = -109815.5901
Iter 692: sigma_u = 0.0339, loglik = -109815.6841
Iter 693: sigma_u = 0.0339, loglik = -109815.7285
Iter 694: sigma_u = 0.0339, loglik = -109815.8305
Iter 695: sigma_u = 0.0339, loglik = -109815.8730
Iter 696: sigma_u = 0.0339, loglik = -109815.9863
Iter 697: sigma_u = 0.0339, loglik = -109816.0269
Iter 698: sigma_u = 0.0339, loglik = -109816.1558
Iter 699: sigma_u = 0.0339, loglik = -109816.1948
Iter 700: sigma_u = 0.0339, loglik = -109816.3441
Iter 701: sigma_u = 0.0338, loglik = -109816.3812
Iter 702: sigma_u = 0.0338, loglik = -109816.5685
Iter 703: sigma_u = 0.0338, loglik = -109816.6038
Iter 704: sigma_u = 0.0338, loglik = -109816.8424
Iter 705: sigma_u = 0.0338, loglik = -109816.8757
Iter 706: sigma_u = 0.0338, loglik = -109817.2642
Iter 707: sigma_u = 0.0338, loglik = -109817.2960
Iter 708: sigma_u = 0.0338, loglik = -109818.0778
Iter 709: sigma_u = 0.0338, loglik = -109818.1074
Iter 710: sigma_u = 0.0338, loglik = -109820.1900
Iter 711: sigma_u = 0.0338, loglik = -109820.2339
Iter 712: sigma_u = 0.0338, loglik = -109820.3119
Iter 713: sigma_u = 0.0338, loglik = -109820.3613
Iter 714: sigma_u = 0.0338, loglik = -109820.4375
Iter 715: sigma_u = 0.0338, loglik = -109820.4834
Iter 716: sigma_u = 0.0338, loglik = -109820.5636
Iter 717: sigma_u = 0.0338, loglik = -109820.6079
Iter 718: sigma_u = 0.0338, loglik = -109820.6955
Iter 719: sigma_u = 0.0338, loglik = -109820.7381
Iter 720: sigma_u = 0.0338, loglik = -109820.8307
Iter 721: sigma_u = 0.0338, loglik = -109820.8721
Iter 722: sigma_u = 0.0338, loglik = -109820.9743
Iter 723: sigma_u = 0.0338, loglik = -109821.0138
Iter 724: sigma_u = 0.0338, loglik = -109821.1295
Iter 725: sigma_u = 0.0338, loglik = -109821.1677
Iter 726: sigma_u = 0.0338, loglik = -109821.2989
Iter 727: sigma_u = 0.0338, loglik = -109821.3353
Iter 728: sigma_u = 0.0338, loglik = -109821.4987
Iter 729: sigma_u = 0.0338, loglik = -109821.5330
Iter 730: sigma_u = 0.0338, loglik = -109821.7445
Iter 731: sigma_u = 0.0338, loglik = -109821.7766
Iter 732: sigma_u = 0.0338, loglik = -109822.0886
Iter 733: sigma_u = 0.0337, loglik = -109822.1190
Iter 734: sigma_u = 0.0337, loglik = -109822.7532
Iter 735: sigma_u = 0.0337, loglik = -109822.7824
Iter 736: sigma_u = 0.0337, loglik = -109824.7429
Iter 737: sigma_u = 0.0337, loglik = -109824.7674
Iter 738: sigma_u = 0.0337, loglik = -109825.0263
Iter 739: sigma_u = 0.0337, loglik = -109825.0849
Iter 740: sigma_u = 0.0337, loglik = -109825.2564
Iter 741: sigma_u = 0.0337, loglik = -109825.3113
Iter 742: sigma_u = 0.0337, loglik = -109825.3946
Iter 743: sigma_u = 0.0337, loglik = -109825.4395
Iter 744: sigma_u = 0.0337, loglik = -109825.5147
Iter 745: sigma_u = 0.0337, loglik = -109825.5586
Iter 746: sigma_u = 0.0337, loglik = -109825.6376
Iter 747: sigma_u = 0.0337, loglik = -109825.6807
Iter 748: sigma_u = 0.0337, loglik = -109825.7588
Iter 749: sigma_u = 0.0337, loglik = -109825.8015
Iter 750: sigma_u = 0.0337, loglik = -109825.8834
Iter 751: sigma_u = 0.0337, loglik = -109825.9247
Iter 752: sigma_u = 0.0337, loglik = -109826.0059
Iter 753: sigma_u = 0.0337, loglik = -109826.0473
Iter 754: sigma_u = 0.0337, loglik = -109826.1315
Iter 755: sigma_u = 0.0337, loglik = -109826.1713
Iter 756: sigma_u = 0.0337, loglik = -109826.2621
Iter 757: sigma_u = 0.0337, loglik = -109826.3013
Iter 758: sigma_u = 0.0337, loglik = -109826.4010
Iter 759: sigma_u = 0.0337, loglik = -109826.4382
Iter 760: sigma_u = 0.0337, loglik = -109826.5510
Iter 761: sigma_u = 0.0337, loglik = -109826.5864
Iter 762: sigma_u = 0.0337, loglik = -109826.7130
Iter 763: sigma_u = 0.0337, loglik = -109826.7472
Iter 764: sigma_u = 0.0337, loglik = -109826.8912
Iter 765: sigma_u = 0.0337, loglik = -109826.9249
Iter 766: sigma_u = 0.0337, loglik = -109827.0985
Iter 767: sigma_u = 0.0337, loglik = -109827.1303
Iter 768: sigma_u = 0.0337, loglik = -109827.3565
Iter 769: sigma_u = 0.0337, loglik = -109827.3875
Iter 770: sigma_u = 0.0337, loglik = -109827.6693
Iter 771: sigma_u = 0.0337, loglik = -109827.6989
Iter 772: sigma_u = 0.0337, loglik = -109828.1448
Iter 773: sigma_u = 0.0336, loglik = -109828.1727
Iter 774: sigma_u = 0.0336, loglik = -109829.3872
Iter 775: sigma_u = 0.0336, loglik = -109829.4152
Iter 776: sigma_u = 0.0336, loglik = -109830.6120
Iter 777: sigma_u = 0.0336, loglik = -109830.6351
Iter 778: sigma_u = 0.0336, loglik = -109830.7231
Iter 779: sigma_u = 0.0336, loglik = -109830.7656
Iter 780: sigma_u = 0.0336, loglik = -109830.8415
Iter 781: sigma_u = 0.0336, loglik = -109830.8814
Iter 782: sigma_u = 0.0336, loglik = -109830.9578
Iter 783: sigma_u = 0.0336, loglik = -109830.9973
Iter 784: sigma_u = 0.0336, loglik = -109831.0795
Iter 785: sigma_u = 0.0336, loglik = -109831.1174
Iter 786: sigma_u = 0.0336, loglik = -109831.2046
Iter 787: sigma_u = 0.0336, loglik = -109831.2415
Iter 788: sigma_u = 0.0336, loglik = -109831.3362
Iter 789: sigma_u = 0.0336, loglik = -109831.3719
Iter 790: sigma_u = 0.0336, loglik = -109831.4719
Iter 791: sigma_u = 0.0336, loglik = -109831.5061
Iter 792: sigma_u = 0.0336, loglik = -109831.6207
Iter 793: sigma_u = 0.0336, loglik = -109831.6540
Iter 794: sigma_u = 0.0336, loglik = -109831.7823
Iter 795: sigma_u = 0.0336, loglik = -109831.8148
Iter 796: sigma_u = 0.0336, loglik = -109831.9624
Iter 797: sigma_u = 0.0336, loglik = -109831.9932
Iter 798: sigma_u = 0.0336, loglik = -109832.1731
Iter 799: sigma_u = 0.0336, loglik = -109832.2027
Iter 800: sigma_u = 0.0336, loglik = -109832.4585
Iter 801: sigma_u = 0.0336, loglik = -109832.4869
Iter 802: sigma_u = 0.0336, loglik = -109832.8572
Iter 803: sigma_u = 0.0336, loglik = -109832.8837
Iter 804: sigma_u = 0.0336, loglik = -109833.6062
Iter 805: sigma_u = 0.0336, loglik = -109833.6350
Iter 806: sigma_u = 0.0336, loglik = -109833.9469
Iter 807: sigma_u = 0.0336, loglik = -109833.9730
Iter 808: sigma_u = 0.0336, loglik = -109834.0895
Iter 809: sigma_u = 0.0336, loglik = -109834.1258
Iter 810: sigma_u = 0.0336, loglik = -109834.2184
Iter 811: sigma_u = 0.0336, loglik = -109834.2524
Iter 812: sigma_u = 0.0336, loglik = -109834.3618
Iter 813: sigma_u = 0.0336, loglik = -109834.3945
Iter 814: sigma_u = 0.0336, loglik = -109834.5111
Iter 815: sigma_u = 0.0336, loglik = -109834.5433
Iter 816: sigma_u = 0.0336, loglik = -109834.6676
Iter 817: sigma_u = 0.0335, loglik = -109834.6986
Iter 818: sigma_u = 0.0335, loglik = -109834.8446
Iter 819: sigma_u = 0.0335, loglik = -109834.8744
Iter 820: sigma_u = 0.0335, loglik = -109835.0469

Iter 821: sigma_u = 0.0335, loglik = -109835.0754
Iter 822: sigma_u = 0.0335, loglik = -109835.3392
Iter 823: sigma_u = 0.0335, loglik = -109835.3663
Iter 824: sigma_u = 0.0335, loglik = -109835.7467
Iter 825: sigma_u = 0.0335, loglik = -109835.7735
Iter 826: sigma_u = 0.0335, loglik = -109836.3890
Iter 827: sigma_u = 0.0335, loglik = -109836.4124
Iter 828: sigma_u = 0.0335, loglik = -109836.6128
Iter 829: sigma_u = 0.0335, loglik = -109836.6571
Iter 830: sigma_u = 0.0335, loglik = -109836.7285
Iter 831: sigma_u = 0.0335, loglik = -109836.7660
Iter 832: sigma_u = 0.0335, loglik = -109836.8433
Iter 833: sigma_u = 0.0335, loglik = -109836.8793
Iter 834: sigma_u = 0.0335, loglik = -109836.9574
Iter 835: sigma_u = 0.0335, loglik = -109836.9926
Iter 836: sigma_u = 0.0335, loglik = -109837.0813
Iter 837: sigma_u = 0.0335, loglik = -109837.1146
Iter 838: sigma_u = 0.0335, loglik = -109837.2083
Iter 839: sigma_u = 0.0335, loglik = -109837.2415
Iter 840: sigma_u = 0.0335, loglik = -109837.3421
Iter 841: sigma_u = 0.0335, loglik = -109837.3738
Iter 842: sigma_u = 0.0335, loglik = -109837.4874
Iter 843: sigma_u = 0.0335, loglik = -109837.5181
Iter 844: sigma_u = 0.0335, loglik = -109837.6470
Iter 845: sigma_u = 0.0335, loglik = -109837.6768
Iter 846: sigma_u = 0.0335, loglik = -109837.8299
Iter 847: sigma_u = 0.0335, loglik = -109837.8584
Iter 848: sigma_u = 0.0335, loglik = -109838.0300
Iter 849: sigma_u = 0.0335, loglik = -109838.0582
Iter 850: sigma_u = 0.0335, loglik = -109838.2766
Iter 851: sigma_u = 0.0335, loglik = -109838.3034
Iter 852: sigma_u = 0.0335, loglik = -109838.6098
Iter 853: sigma_u = 0.0335, loglik = -109838.6358
Iter 854: sigma_u = 0.0335, loglik = -109839.0981
Iter 855: sigma_u = 0.0335, loglik = -109839.1218
Iter 856: sigma_u = 0.0335, loglik = -109840.0550
Iter 857: sigma_u = 0.0335, loglik = -109840.0925
Iter 858: sigma_u = 0.0335, loglik = -109840.1483
Iter 859: sigma_u = 0.0335, loglik = -109840.1907
Iter 860: sigma_u = 0.0335, loglik = -109840.2439
Iter 861: sigma_u = 0.0335, loglik = -109840.2856
Iter 862: sigma_u = 0.0335, loglik = -109840.3411
Iter 863: sigma_u = 0.0335, loglik = -109840.3820
Iter 864: sigma_u = 0.0335, loglik = -109840.4389
Iter 865: sigma_u = 0.0335, loglik = -109840.4786
Iter 866: sigma_u = 0.0335, loglik = -109840.5389
Iter 867: sigma_u = 0.0335, loglik = -109840.5770
Iter 868: sigma_u = 0.0335, loglik = -109840.6416
Iter 869: sigma_u = 0.0335, loglik = -109840.6785
Iter 870: sigma_u = 0.0334, loglik = -109840.7451
Iter 871: sigma_u = 0.0334, loglik = -109840.7810
Iter 872: sigma_u = 0.0334, loglik = -109840.8504
Iter 873: sigma_u = 0.0334, loglik = -109840.8855
Iter 874: sigma_u = 0.0334, loglik = -109840.9595
Iter 875: sigma_u = 0.0334, loglik = -109840.9938
Iter 876: sigma_u = 0.0334, loglik = -109841.0716
Iter 877: sigma_u = 0.0334, loglik = -109841.1045
Iter 878: sigma_u = 0.0334, loglik = -109841.1901
Iter 879: sigma_u = 0.0334, loglik = -109841.2218
Iter 880: sigma_u = 0.0334, loglik = -109841.3148
Iter 881: sigma_u = 0.0334, loglik = -109841.3450
Iter 882: sigma_u = 0.0334, loglik = -109841.4507
Iter 883: sigma_u = 0.0334, loglik = -109841.4798
Iter 884: sigma_u = 0.0334, loglik = -109841.6071
Iter 885: sigma_u = 0.0334, loglik = -109841.6352
Iter 886: sigma_u = 0.0334, loglik = -109841.7956
Iter 887: sigma_u = 0.0334, loglik = -109841.8220
Iter 888: sigma_u = 0.0334, loglik = -109842.0283
Iter 889: sigma_u = 0.0334, loglik = -109842.0542
Iter 890: sigma_u = 0.0334, loglik = -109842.3497
Iter 891: sigma_u = 0.0334, loglik = -109842.3744
Iter 892: sigma_u = 0.0334, loglik = -109842.9167
Iter 893: sigma_u = 0.0334, loglik = -109842.9395
Iter 894: sigma_u = 0.0334, loglik = -109844.0087
Iter 895: sigma_u = 0.0334, loglik = -109844.0409
Iter 896: sigma_u = 0.0334, loglik = -109844.1049
Iter 897: sigma_u = 0.0334, loglik = -109844.1434
Iter 898: sigma_u = 0.0334, loglik = -109844.1988
Iter 899: sigma_u = 0.0334, loglik = -109844.2363
Iter 900: sigma_u = 0.0334, loglik = -109844.2949
Iter 901: sigma_u = 0.0334, loglik = -109844.3307
Iter 902: sigma_u = 0.0334, loglik = -109844.3917
Iter 903: sigma_u = 0.0334, loglik = -109844.4266
Iter 904: sigma_u = 0.0334, loglik = -109844.4905
Iter 905: sigma_u = 0.0334, loglik = -109844.5246
Iter 906: sigma_u = 0.0334, loglik = -109844.5914
Iter 907: sigma_u = 0.0334, loglik = -109844.6246
Iter 908: sigma_u = 0.0334, loglik = -109844.6939
Iter 909: sigma_u = 0.0334, loglik = -109844.7263
Iter 910: sigma_u = 0.0334, loglik = -109844.7993
Iter 911: sigma_u = 0.0334, loglik = -109844.8309
Iter 912: sigma_u = 0.0334, loglik = -109844.9077
Iter 913: sigma_u = 0.0334, loglik = -109844.9386
Iter 914: sigma_u = 0.0334, loglik = -109845.0238
Iter 915: sigma_u = 0.0334, loglik = -109845.0537
Iter 916: sigma_u = 0.0334, loglik = -109845.1453
Iter 917: sigma_u = 0.0334, loglik = -109845.1744
Iter 918: sigma_u = 0.0334, loglik = -109845.2729
Iter 919: sigma_u = 0.0334, loglik = -109845.3012
Iter 920: sigma_u = 0.0334, loglik = -109845.4190
Iter 921: sigma_u = 0.0334, loglik = -109845.4455
Iter 922: sigma_u = 0.0334, loglik = -109845.5876
Iter 923: sigma_u = 0.0334, loglik = -109845.6133
Iter 924: sigma_u = 0.0334, loglik = -109845.8217
Iter 925: sigma_u = 0.0334, loglik = -109845.8458
Iter 926: sigma_u = 0.0334, loglik = -109846.1865
Iter 927: sigma_u = 0.0334, loglik = -109846.2100
Iter 928: sigma_u = 0.0333, loglik = -109846.7535
Iter 929: sigma_u = 0.0333, loglik = -109846.7765
Iter 930: sigma_u = 0.0333, loglik = -109847.7728
Iter 931: sigma_u = 0.0333, loglik = -109847.7919
Iter 932: sigma_u = 0.0333, loglik = -109847.9089
Iter 933: sigma_u = 0.0333, loglik = -109847.9556
Iter 934: sigma_u = 0.0333, loglik = -109848.0234
Iter 935: sigma_u = 0.0333, loglik = -109848.0615
Iter 936: sigma_u = 0.0333, loglik = -109848.1148
Iter 937: sigma_u = 0.0333, loglik = -109848.1506
Iter 938: sigma_u = 0.0333, loglik = -109848.2079
Iter 939: sigma_u = 0.0333, loglik = -109848.2417
Iter 940: sigma_u = 0.0333, loglik = -109848.3000
Iter 941: sigma_u = 0.0333, loglik = -109848.3330
Iter 942: sigma_u = 0.0333, loglik = -109848.3940
Iter 943: sigma_u = 0.0333, loglik = -109848.4264
Iter 944: sigma_u = 0.0333, loglik = -109848.4887
Iter 945: sigma_u = 0.0333, loglik = -109848.5211
Iter 946: sigma_u = 0.0333, loglik = -109848.5823
Iter 947: sigma_u = 0.0333, loglik = -109848.6145
Iter 948: sigma_u = 0.0333, loglik = -109848.6792
Iter 949: sigma_u = 0.0333, loglik = -109848.7107
Iter 950: sigma_u = 0.0333, loglik = -109848.7798
Iter 951: sigma_u = 0.0333, loglik = -109848.8102
Iter 952: sigma_u = 0.0333, loglik = -109848.8833
Iter 953: sigma_u = 0.0333, loglik = -109848.9130
Iter 954: sigma_u = 0.0333, loglik = -109848.9886
Iter 955: sigma_u = 0.0333, loglik = -109849.0174
Iter 956: sigma_u = 0.0333, loglik = -109849.0979
Iter 957: sigma_u = 0.0333, loglik = -109849.1264
Iter 958: sigma_u = 0.0333, loglik = -109849.2183
Iter 959: sigma_u = 0.0333, loglik = -109849.2450
Iter 960: sigma_u = 0.0333, loglik = -109849.3530
Iter 961: sigma_u = 0.0333, loglik = -109849.3791
Iter 962: sigma_u = 0.0333, loglik = -109849.4961
Iter 963: sigma_u = 0.0333, loglik = -109849.5212
Iter 964: sigma_u = 0.0333, loglik = -109849.6667
Iter 965: sigma_u = 0.0333, loglik = -109849.6908
Iter 966: sigma_u = 0.0333, loglik = -109849.8987
Iter 967: sigma_u = 0.0333, loglik = -109849.9214
Iter 968: sigma_u = 0.0333, loglik = -109850.2523
Iter 969: sigma_u = 0.0333, loglik = -109850.2750
Iter 970: sigma_u = 0.0333, loglik = -109850.7234
Iter 971: sigma_u = 0.0333, loglik = -109850.7432
Iter 972: sigma_u = 0.0333, loglik = -109850.9688
Iter 973: sigma_u = 0.0333, loglik = -109851.0044
Iter 974: sigma_u = 0.0333, loglik = -109851.0652
Iter 975: sigma_u = 0.0333, loglik = -109851.0959
Iter 976: sigma_u = 0.0333, loglik = -109851.1590
Iter 977: sigma_u = 0.0333, loglik = -109851.1891
Iter 978: sigma_u = 0.0333, loglik = -109851.2559
Iter 979: sigma_u = 0.0333, loglik = -109851.2852
Iter 980: sigma_u = 0.0333, loglik = -109851.3547
Iter 981: sigma_u = 0.0333, loglik = -109851.3835
Iter 982: sigma_u = 0.0333, loglik = -109851.4637
Iter 983: sigma_u = 0.0333, loglik = -109851.4909
Iter 984: sigma_u = 0.0333, loglik = -109851.5708

Iter 985: sigma_u = 0.0333, loglik = -109851.5976
Iter 986: sigma_u = 0.0333, loglik = -109851.6970
Iter 987: sigma_u = 0.0333, loglik = -109851.7225
Iter 988: sigma_u = 0.0333, loglik = -109851.8245
Iter 989: sigma_u = 0.0333, loglik = -109851.8494
Iter 990: sigma_u = 0.0333, loglik = -109851.9813
Iter 991: sigma_u = 0.0333, loglik = -109852.0045
Iter 992: sigma_u = 0.0333, loglik = -109852.1810
Iter 993: sigma_u = 0.0333, loglik = -109852.2040
Iter 994: sigma_u = 0.0333, loglik = -109852.4300
Iter 995: sigma_u = 0.0332, loglik = -109852.4518
Iter 996: sigma_u = 0.0332, loglik = -109852.8171
Iter 997: sigma_u = 0.0332, loglik = -109852.8381
Iter 998: sigma_u = 0.0332, loglik = -109853.5959
Iter 999: sigma_u = 0.0332, loglik = -109853.6142
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             0.80       0.761465     0.761726
1            -0.90      -0.889261    -0.889559
2             0.50       0.498783     0.498969
3            -1.70      -1.641782    -1.642345
4             0.25       0.137736     0.033233



Time taken 5.8721642851829525 minutes



Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 2.1969, loglik = -10557.9456
Iter 1: sigma_u = 1.8457, loglik = -10818.0760
Iter 2: sigma_u = 1.5549, loglik = -11223.2477
Iter 3: sigma_u = 1.3102, loglik = -11793.2437
Iter 4: sigma_u = 1.1043, loglik = -12592.9691
Iter 5: sigma_u = 0.9310, loglik = -13712.0439
Iter 6: sigma_u = 0.7853, loglik = -15273.0906
Iter 7: sigma_u = 0.6627, loglik = -17440.4168
Iter 8: sigma_u = 0.5598, loglik = -20428.3011
Iter 9: sigma_u = 0.4735, loglik = -24502.4492
Iter 10: sigma_u = 0.4013, loglik = -29955.5670
Iter 11: sigma_u = 0.3412, loglik = -36993.3991
Iter 12: sigma_u = 0.2915, loglik = -45462.0666
Iter 13: sigma_u = 0.2510, loglik = -54646.3712
Iter 14: sigma_u = 0.2186, loglik = -63510.5125
Iter 15: sigma_u = 0.1928, loglik = -71226.4924
Iter 16: sigma_u = 0.1724, loglik = -77483.5654
Iter 17: sigma_u = 0.1560, loglik = -82367.1901
Iter 18: sigma_u = 0.1428, loglik = -86129.2422
Iter 19: sigma_u = 0.1319, loglik = -89034.7252
Iter 20: sigma_u = 0.1229, loglik = -91302.1111
Iter 21: sigma_u = 0.1153, loglik = -93095.9558
Iter 22: sigma_u = 0.1088, loglik = -94537.8695
Iter 23: sigma_u = 0.1031, loglik = -95713.0955
Iter 24: sigma_u = 0.0982, loglik = -96683.9866
Iter 25: sigma_u = 0.0939, loglik = -97496.2684
Iter 26: sigma_u = 0.0901, loglik = -98183.7535
Iter 27: sigma_u = 0.0867, loglik = -98770.5381
Iter 28: sigma_u = 0.0836, loglik = -99278.0493
Iter 29: sigma_u = 0.0808, loglik = -99719.5861
Iter 30: sigma_u = 0.0783, loglik = -100108.5888
Iter 31: sigma_u = 0.0760, loglik = -100451.5305
Iter 32: sigma_u = 0.0739, loglik = -100752.4478
Iter 33: sigma_u = 0.0719, loglik = -101025.0876
Iter 34: sigma_u = 0.0701, loglik = -101267.5452
Iter 35: sigma_u = 0.0684, loglik = -101492.8111
Iter 36: sigma_u = 0.0668, loglik = -101693.5422
Iter 37: sigma_u = 0.0654, loglik = -101875.9659
Iter 38: sigma_u = 0.0640, loglik = -102042.2291
Iter 39: sigma_u = 0.0627, loglik = -102197.2149
Iter 40: sigma_u = 0.0615, loglik = -102338.8237
Iter 41: sigma_u = 0.0603, loglik = -102468.2464
Iter 42: sigma_u = 0.0593, loglik = -102590.2785
Iter 43: sigma_u = 0.0582, loglik = -102701.3886
Iter 44: sigma_u = 0.0573, loglik = -102806.5224
Iter 45: sigma_u = 0.0564, loglik = -102901.9604
Iter 46: sigma_u = 0.0555, loglik = -102992.2967
Iter 47: sigma_u = 0.0547, loglik = -103076.7977
Iter 48: sigma_u = 0.0539, loglik = -103156.3774
Iter 49: sigma_u = 0.0531, loglik = -103232.3871
Iter 50: sigma_u = 0.0523, loglik = -103304.1887
Iter 51: sigma_u = 0.0516, loglik = -103373.4410
Iter 52: sigma_u = 0.0510, loglik = -103436.7332
Iter 53: sigma_u = 0.0503, loglik = -103496.5759
Iter 54: sigma_u = 0.0497, loglik = -103552.7469
Iter 55: sigma_u = 0.0491, loglik = -103607.0380
Iter 56: sigma_u = 0.0486, loglik = -103656.9871
Iter 57: sigma_u = 0.0480, loglik = -103706.4677
Iter 58: sigma_u = 0.0475, loglik = -103752.5511
Iter 59: sigma_u = 0.0470, loglik = -103794.9226
Iter 60: sigma_u = 0.0465, loglik = -103836.7714
Iter 61: sigma_u = 0.0460, loglik = -103877.3327
Iter 62: sigma_u = 0.0455, loglik = -103918.5309
Iter 63: sigma_u = 0.0451, loglik = -103955.6951
Iter 64: sigma_u = 0.0447, loglik = -103991.0525
Iter 65: sigma_u = 0.0443, loglik = -104024.0440
Iter 66: sigma_u = 0.0439, loglik = -104055.9879
Iter 67: sigma_u = 0.0435, loglik = -104086.2592
Iter 68: sigma_u = 0.0431, loglik = -104115.3470
Iter 69: sigma_u = 0.0428, loglik = -104141.8936
Iter 70: sigma_u = 0.0424, loglik = -104169.8291
Iter 71: sigma_u = 0.0421, loglik = -104196.7013
Iter 72: sigma_u = 0.0416, loglik = -104222.7175
Iter 73: sigma_u = 0.0413, loglik = -104255.3793
Iter 74: sigma_u = 0.0410, loglik = -104279.8929
Iter 75: sigma_u = 0.0406, loglik = -104303.0466
Iter 76: sigma_u = 0.0403, loglik = -104330.2817
Iter 77: sigma_u = 0.0400, loglik = -104351.9257
Iter 78: sigma_u = 0.0397, loglik = -104372.4106
Iter 79: sigma_u = 0.0397, loglik = -104391.3037
Iter 80: sigma_u = 0.0397, loglik = -104392.3236
Iter 81: sigma_u = 0.0397, loglik = -104392.7706
Iter 82: sigma_u = 0.0397, loglik = -104393.6936
Iter 83: sigma_u = 0.0397, loglik = -104394.1509
Iter 84: sigma_u = 0.0396, loglik = -104395.0628
Iter 85: sigma_u = 0.0396, loglik = -104395.5180
Iter 86: sigma_u = 0.0396, loglik = -104396.4350
Iter 87: sigma_u = 0.0396, loglik = -104396.8884
Iter 88: sigma_u = 0.0396, loglik = -104397.8128
Iter 89: sigma_u = 0.0396, loglik = -104398.2630
Iter 90: sigma_u = 0.0396, loglik = -104399.1869
Iter 91: sigma_u = 0.0396, loglik = -104399.6348
Iter 92: sigma_u = 0.0396, loglik = -104400.5582
Iter 93: sigma_u = 0.0396, loglik = -104401.0030
Iter 94: sigma_u = 0.0395, loglik = -104401.9329
Iter 95: sigma_u = 0.0395, loglik = -104402.3744
Iter 96: sigma_u = 0.0395, loglik = -104403.3163
Iter 97: sigma_u = 0.0395, loglik = -104403.7545
Iter 98: sigma_u = 0.0395, loglik = -104404.6960
Iter 99: sigma_u = 0.0395, loglik = -104405.1306
Iter 100: sigma_u = 0.0395, loglik = -104406.0837
Iter 101: sigma_u = 0.0395, loglik = -104406.5149
Iter 102: sigma_u = 0.0395, loglik = -104407.4725
Iter 103: sigma_u = 0.0395, loglik = -104407.8997
Iter 104: sigma_u = 0.0395, loglik = -104408.8636
Iter 105: sigma_u = 0.0394, loglik = -104409.2889
Iter 106: sigma_u = 0.0394, loglik = -104410.2600
Iter 107: sigma_u = 0.0394, loglik = -104410.6824
Iter 108: sigma_u = 0.0394, loglik = -104411.6630
Iter 109: sigma_u = 0.0394, loglik = -104412.0803
Iter 110: sigma_u = 0.0394, loglik = -104413.0859
Iter 111: sigma_u = 0.0394, loglik = -104413.4971
Iter 112: sigma_u = 0.0394, loglik = -104414.5175
Iter 113: sigma_u = 0.0394, loglik = -104414.9239
Iter 114: sigma_u = 0.0393, loglik = -104415.9720
Iter 115: sigma_u = 0.0393, loglik = -104416.3727
Iter 116: sigma_u = 0.0393, loglik = -104417.4383
Iter 117: sigma_u = 0.0393, loglik = -104417.8342
Iter 118: sigma_u = 0.0393, loglik = -104418.9332
Iter 119: sigma_u = 0.0393, loglik = -104419.3229
Iter 120: sigma_u = 0.0393, loglik = -104420.4334
Iter 121: sigma_u = 0.0393, loglik = -104420.8199
Iter 122: sigma_u = 0.0393, loglik = -104421.9549
Iter 123: sigma_u = 0.0392, loglik = -104422.3356
Iter 124: sigma_u = 0.0392, loglik = -104423.5247
Iter 125: sigma_u = 0.0392, loglik = -104423.8990
Iter 126: sigma_u = 0.0392, loglik = -104425.1184
Iter 127: sigma_u = 0.0392, loglik = -104425.4873
Iter 128: sigma_u = 0.0392, loglik = -104426.7685
Iter 129: sigma_u = 0.0392, loglik = -104427.1302
Iter 130: sigma_u = 0.0392, loglik = -104428.4662
Iter 131: sigma_u = 0.0391, loglik = -104428.8222
Iter 132: sigma_u = 0.0391, loglik = -104430.2251
Iter 133: sigma_u = 0.0391, loglik = -104430.5751
Iter 134: sigma_u = 0.0391, loglik = -104432.0482
Iter 135: sigma_u = 0.0391, loglik = -104432.3915
Iter 136: sigma_u = 0.0391, loglik = -104433.9555
Iter 137: sigma_u = 0.0388, loglik = -104434.2907
Iter 138: sigma_u = 0.0385, loglik = -104452.3762
Iter 139: sigma_u = 0.0382, loglik = -104475.8142
Iter 140: sigma_u = 0.0381, loglik = -104492.2662
Iter 141: sigma_u = 0.0380, loglik = -104504.1991
Iter 142: sigma_u = 0.0380, loglik = -104504.8902
Iter 143: sigma_u = 0.0380, loglik = -104505.2121
Iter 144: sigma_u = 0.0380, loglik = -104505.9270
Iter 145: sigma_u = 0.0380, loglik = -104506.2610
Iter 146: sigma_u = 0.0380, loglik = -104506.9710
Iter 147: sigma_u = 0.0380, loglik = -104507.3112
Iter 148: sigma_u = 0.0380, loglik = -104508.0212
Iter 149: sigma_u = 0.0380, loglik = -104508.3613
Iter 150: sigma_u = 0.0380, loglik = -104509.0770
Iter 151: sigma_u = 0.0380, loglik = -104509.4156
Iter 152: sigma_u = 0.0380, loglik = -104510.1341
Iter 153: sigma_u = 0.0380, loglik = -104510.4709
Iter 154: sigma_u = 0.0379, loglik = -104511.1912
Iter 155: sigma_u = 0.0379, loglik = -104511.5262
Iter 156: sigma_u = 0.0379, loglik = -104512.2463
Iter 157: sigma_u = 0.0379, loglik = -104512.5802
Iter 158: sigma_u = 0.0379, loglik = -104513.3040
Iter 159: sigma_u = 0.0379, loglik = -104513.6364
Iter 160: sigma_u = 0.0379, loglik = -104514.3628
Iter 161: sigma_u = 0.0379, loglik = -104514.6925
Iter 162: sigma_u = 0.0379, loglik = -104515.4352
Iter 163: sigma_u = 0.0379, loglik = -104515.7622
Iter 164: sigma_u = 0.0379, loglik = -104516.5057
Iter 165: sigma_u = 0.0379, loglik = -104516.8293
Iter 166: sigma_u = 0.0379, loglik = -104517.5848

Iter 167: sigma_u = 0.0378, loglik = -104517.9051
Iter 168: sigma_u = 0.0378, loglik = -104518.6733
Iter 169: sigma_u = 0.0378, loglik = -104518.9902
Iter 170: sigma_u = 0.0378, loglik = -104519.7728
Iter 171: sigma_u = 0.0378, loglik = -104520.0866
Iter 172: sigma_u = 0.0378, loglik = -104520.8817
Iter 173: sigma_u = 0.0378, loglik = -104521.1927
Iter 174: sigma_u = 0.0378, loglik = -104522.0069
Iter 175: sigma_u = 0.0378, loglik = -104522.3126
Iter 176: sigma_u = 0.0378, loglik = -104523.1439
Iter 177: sigma_u = 0.0378, loglik = -104523.4465
Iter 178: sigma_u = 0.0378, loglik = -104524.2957
Iter 179: sigma_u = 0.0377, loglik = -104524.5947
Iter 180: sigma_u = 0.0377, loglik = -104525.4695
Iter 181: sigma_u = 0.0377, loglik = -104525.7637
Iter 182: sigma_u = 0.0377, loglik = -104526.6544
Iter 183: sigma_u = 0.0377, loglik = -104526.9456
Iter 184: sigma_u = 0.0377, loglik = -104527.8665
Iter 185: sigma_u = 0.0377, loglik = -104528.1544
Iter 186: sigma_u = 0.0377, loglik = -104529.1163
Iter 187: sigma_u = 0.0377, loglik = -104529.3989
Iter 188: sigma_u = 0.0377, loglik = -104530.3776
Iter 189: sigma_u = 0.0376, loglik = -104530.6572
Iter 190: sigma_u = 0.0376, loglik = -104531.6926
Iter 191: sigma_u = 0.0376, loglik = -104531.9667
Iter 192: sigma_u = 0.0376, loglik = -104533.0461
Iter 193: sigma_u = 0.0376, loglik = -104533.3160
Iter 194: sigma_u = 0.0376, loglik = -104534.4554
Iter 195: sigma_u = 0.0376, loglik = -104534.7205
Iter 196: sigma_u = 0.0376, loglik = -104535.9262
Iter 197: sigma_u = 0.0376, loglik = -104536.1867
Iter 198: sigma_u = 0.0376, loglik = -104537.4743
Iter 199: sigma_u = 0.0375, loglik = -104537.7310
Iter 200: sigma_u = 0.0375, loglik = -104539.1034
Iter 201: sigma_u = 0.0375, loglik = -104539.3559
Iter 202: sigma_u = 0.0375, loglik = -104540.7873
Iter 203: sigma_u = 0.0375, loglik = -104541.0359
Iter 204: sigma_u = 0.0375, loglik = -104542.5534
Iter 205: sigma_u = 0.0375, loglik = -104542.7975
Iter 206: sigma_u = 0.0374, loglik = -104544.4521
Iter 207: sigma_u = 0.0374, loglik = -104544.6920
Iter 208: sigma_u = 0.0374, loglik = -104546.5583
Iter 209: sigma_u = 0.0372, loglik = -104546.7918
Iter 210: sigma_u = 0.0369, loglik = -104561.6474
Iter 211: sigma_u = 0.0369, loglik = -104580.3848
Iter 212: sigma_u = 0.0369, loglik = -104581.0836
Iter 213: sigma_u = 0.0369, loglik = -104581.3662
Iter 214: sigma_u = 0.0369, loglik = -104581.9500
Iter 215: sigma_u = 0.0369, loglik = -104582.2303
Iter 216: sigma_u = 0.0369, loglik = -104582.8088
Iter 217: sigma_u = 0.0369, loglik = -104583.0901
Iter 218: sigma_u = 0.0368, loglik = -104583.6701
Iter 219: sigma_u = 0.0368, loglik = -104583.9497
Iter 220: sigma_u = 0.0368, loglik = -104584.5326
Iter 221: sigma_u = 0.0368, loglik = -104584.8106
Iter 222: sigma_u = 0.0368, loglik = -104585.4008
Iter 223: sigma_u = 0.0368, loglik = -104585.6767
Iter 224: sigma_u = 0.0368, loglik = -104586.2722
Iter 225: sigma_u = 0.0368, loglik = -104586.5459
Iter 226: sigma_u = 0.0368, loglik = -104587.1404
Iter 227: sigma_u = 0.0368, loglik = -104587.4124
Iter 228: sigma_u = 0.0368, loglik = -104588.0249
Iter 229: sigma_u = 0.0368, loglik = -104588.2929
Iter 230: sigma_u = 0.0368, loglik = -104588.9087
Iter 231: sigma_u = 0.0368, loglik = -104589.1745
Iter 232: sigma_u = 0.0368, loglik = -104589.8000
Iter 233: sigma_u = 0.0367, loglik = -104590.0637
Iter 234: sigma_u = 0.0367, loglik = -104590.6934
Iter 235: sigma_u = 0.0367, loglik = -104590.9561
Iter 236: sigma_u = 0.0367, loglik = -104591.5930
Iter 237: sigma_u = 0.0367, loglik = -104591.8532
Iter 238: sigma_u = 0.0367, loglik = -104592.5023
Iter 239: sigma_u = 0.0367, loglik = -104592.7599
Iter 240: sigma_u = 0.0367, loglik = -104593.4097
Iter 241: sigma_u = 0.0367, loglik = -104593.6656
Iteration 241: beta norm = 3.2592562710377195, sigma_u = 0.0367
Iter 242: sigma_u = 0.0367, loglik = -104594.3283
Iter 243: sigma_u = 0.0367, loglik = -104594.5821
Iter 244: sigma_u = 0.0367, loglik = -104595.2538
Iter 245: sigma_u = 0.0367, loglik = -104595.5054
Iter 246: sigma_u = 0.0367, loglik = -104596.1865
Iter 247: sigma_u = 0.0366, loglik = -104596.4353
Iter 248: sigma_u = 0.0366, loglik = -104597.1377
Iter 249: sigma_u = 0.0366, loglik = -104597.3824
Iter 250: sigma_u = 0.0366, loglik = -104598.1021
Iter 251: sigma_u = 0.0366, loglik = -104598.3442
Iter 252: sigma_u = 0.0366, loglik = -104599.0677
Iter 253: sigma_u = 0.0366, loglik = -104599.3090
Iter 254: sigma_u = 0.0366, loglik = -104600.0460
Iter 255: sigma_u = 0.0366, loglik = -104600.2849
Iter 256: sigma_u = 0.0366, loglik = -104601.0346
Iter 257: sigma_u = 0.0366, loglik = -104601.2707
Iter 258: sigma_u = 0.0366, loglik = -104602.0501
Iter 259: sigma_u = 0.0365, loglik = -104602.2834
Iter 260: sigma_u = 0.0365, loglik = -104603.0887
Iter 261: sigma_u = 0.0365, loglik = -104603.3184
Iter 262: sigma_u = 0.0365, loglik = -104604.1337
Iter 263: sigma_u = 0.0365, loglik = -104604.3616
Iter 264: sigma_u = 0.0365, loglik = -104605.2228
Iter 265: sigma_u = 0.0365, loglik = -104605.4461
Iter 266: sigma_u = 0.0365, loglik = -104606.3560
Iter 267: sigma_u = 0.0365, loglik = -104606.5761
Iter 268: sigma_u = 0.0365, loglik = -104607.5236
Iter 269: sigma_u = 0.0365, loglik = -104607.7395
Iter 270: sigma_u = 0.0365, loglik = -104608.7399
Iter 271: sigma_u = 0.0364, loglik = -104608.9530
Iter 272: sigma_u = 0.0364, loglik = -104610.0199
Iter 273: sigma_u = 0.0364, loglik = -104610.2299
Iter 274: sigma_u = 0.0364, loglik = -104611.3712
Iter 275: sigma_u = 0.0364, loglik = -104611.5770
Iter 276: sigma_u = 0.0364, loglik = -104612.7951
Iter 277: sigma_u = 0.0364, loglik = -104612.9973
Iter 278: sigma_u = 0.0364, loglik = -104614.3118
Iter 279: sigma_u = 0.0363, loglik = -104614.5116
Iter 280: sigma_u = 0.0363, loglik = -104615.9133
Iter 281: sigma_u = 0.0363, loglik = -104616.1091
Iter 282: sigma_u = 0.0363, loglik = -104617.6886
Iter 283: sigma_u = 0.0363, loglik = -104617.8816
Iter 284: sigma_u = 0.0363, loglik = -104619.6543
Iter 285: sigma_u = 0.0363, loglik = -104619.8427
Iter 286: sigma_u = 0.0363, loglik = -104621.8697
Iter 287: sigma_u = 0.0361, loglik = -104622.0545
Iter 288: sigma_u = 0.0358, loglik = -104634.9258
Iter 289: sigma_u = 0.0358, loglik = -104650.7758
Iter 290: sigma_u = 0.0358, loglik = -104651.7253
Iter 291: sigma_u = 0.0358, loglik = -104651.9295
Iter 292: sigma_u = 0.0358, loglik = -104652.5865
Iter 293: sigma_u = 0.0358, loglik = -104652.7823
Iter 294: sigma_u = 0.0358, loglik = -104653.5296
Iter 295: sigma_u = 0.0357, loglik = -104653.7227
Iter 296: sigma_u = 0.0357, loglik = -104654.5313
Iter 297: sigma_u = 0.0357, loglik = -104654.7164
Iter 298: sigma_u = 0.0357, loglik = -104655.6840
Iter 299: sigma_u = 0.0357, loglik = -104655.8634
Iter 300: sigma_u = 0.0357, loglik = -104657.0195
Iter 301: sigma_u = 0.0357, loglik = -104657.1898
Iter 302: sigma_u = 0.0357, loglik = -104658.7103
Iter 303: sigma_u = 0.0356, loglik = -104658.8764
Iter 304: sigma_u = 0.0356, loglik = -104660.8430
Iter 305: sigma_u = 0.0354, loglik = -104660.9986
Iter 306: sigma_u = 0.0352, loglik = -104672.8773
Iter 307: sigma_u = 0.0352, loglik = -104687.3746
Iter 308: sigma_u = 0.0352, loglik = -104688.2606
Iter 309: sigma_u = 0.0352, loglik = -104688.6414
Iter 310: sigma_u = 0.0352, loglik = -104689.0564
Iter 311: sigma_u = 0.0352, loglik = -104689.2619
Iter 312: sigma_u = 0.0352, loglik = -104689.6999
Iter 313: sigma_u = 0.0352, loglik = -104689.8989
Iter 314: sigma_u = 0.0352, loglik = -104690.3652
Iter 315: sigma_u = 0.0352, loglik = -104690.5574
Iter 316: sigma_u = 0.0352, loglik = -104691.0598
Iter 317: sigma_u = 0.0351, loglik = -104691.2464
Iter 318: sigma_u = 0.0351, loglik = -104691.7933
Iter 319: sigma_u = 0.0351, loglik = -104691.9740
Iter 320: sigma_u = 0.0351, loglik = -104692.5816
Iter 321: sigma_u = 0.0351, loglik = -104692.7545
Iter 322: sigma_u = 0.0351, loglik = -104693.4449
Iter 323: sigma_u = 0.0351, loglik = -104693.6124
Iter 324: sigma_u = 0.0351, loglik = -104694.4006
Iter 325: sigma_u = 0.0351, loglik = -104694.5624
Iter 326: sigma_u = 0.0351, loglik = -104695.5149
Iter 327: sigma_u = 0.0351, loglik = -104695.6704
Iter 328: sigma_u = 0.0351, loglik = -104696.8596
Iter 329: sigma_u = 0.0350, loglik = -104697.0078

Iter 330: sigma_u = 0.0350, loglik = -104698.6118
Iter 331: sigma_u = 0.0350, loglik = -104698.7554
Iter 332: sigma_u = 0.0350, loglik = -104701.0949
Iter 333: sigma_u = 0.0348, loglik = -104701.2297
Iter 334: sigma_u = 0.0346, loglik = -104712.0282
Iter 335: sigma_u = 0.0344, loglik = -104722.6445
Iter 336: sigma_u = 0.0344, loglik = -104736.0771
Iter 337: sigma_u = 0.0344, loglik = -104737.2104
Iter 338: sigma_u = 0.0344, loglik = -104737.5232
Iter 339: sigma_u = 0.0344, loglik = -104737.7190
Iter 340: sigma_u = 0.0344, loglik = -104738.0283
Iter 341: sigma_u = 0.0344, loglik = -104738.2210
Iter 342: sigma_u = 0.0344, loglik = -104738.5403
Iter 343: sigma_u = 0.0344, loglik = -104738.7258
Iter 344: sigma_u = 0.0344, loglik = -104739.0583
Iter 345: sigma_u = 0.0344, loglik = -104739.2404
Iter 346: sigma_u = 0.0344, loglik = -104739.5910
Iter 347: sigma_u = 0.0344, loglik = -104739.7670
Iter 348: sigma_u = 0.0344, loglik = -104740.1404
Iter 349: sigma_u = 0.0343, loglik = -104740.3098
Iter 350: sigma_u = 0.0343, loglik = -104740.7043
Iter 351: sigma_u = 0.0343, loglik = -104740.8680
Iter 352: sigma_u = 0.0343, loglik = -104741.2963
Iter 353: sigma_u = 0.0343, loglik = -104741.4552
Iter 354: sigma_u = 0.0343, loglik = -104741.9210
Iter 355: sigma_u = 0.0343, loglik = -104742.0750
Iter 356: sigma_u = 0.0343, loglik = -104742.5855
Iter 357: sigma_u = 0.0343, loglik = -104742.7337
Iter 358: sigma_u = 0.0343, loglik = -104743.3184
Iter 359: sigma_u = 0.0343, loglik = -104743.4614
Iter 360: sigma_u = 0.0343, loglik = -104744.1378
Iter 361: sigma_u = 0.0343, loglik = -104744.2758
Iter 362: sigma_u = 0.0343, loglik = -104745.0897
Iter 363: sigma_u = 0.0343, loglik = -104745.2219
Iter 364: sigma_u = 0.0343, loglik = -104746.2403
Iter 365: sigma_u = 0.0342, loglik = -104746.3667
Iter 366: sigma_u = 0.0342, loglik = -104747.7386
Iter 367: sigma_u = 0.0342, loglik = -104747.8617
Iter 368: sigma_u = 0.0342, loglik = -104749.7186
Iter 369: sigma_u = 0.0340, loglik = -104749.8341
Iter 370: sigma_u = 0.0340, loglik = -104759.2599
Iter 371: sigma_u = 0.0340, loglik = -104760.3190
Iter 372: sigma_u = 0.0340, loglik = -104760.4548
Iter 373: sigma_u = 0.0340, loglik = -104760.7762
Iter 374: sigma_u = 0.0340, loglik = -104760.9548
Iter 375: sigma_u = 0.0340, loglik = -104761.2526
Iter 376: sigma_u = 0.0340, loglik = -104761.4262
Iter 377: sigma_u = 0.0340, loglik = -104761.7380
Iter 378: sigma_u = 0.0340, loglik = -104761.9058
Iter 379: sigma_u = 0.0340, loglik = -104762.2350
Iter 380: sigma_u = 0.0340, loglik = -104762.3977
Iter 381: sigma_u = 0.0340, loglik = -104762.7469
Iter 382: sigma_u = 0.0340, loglik = -104762.9034
Iter 383: sigma_u = 0.0340, loglik = -104763.2799
Iter 384: sigma_u = 0.0340, loglik = -104763.4308
Iter 385: sigma_u = 0.0340, loglik = -104763.8372
Iter 386: sigma_u = 0.0340, loglik = -104763.9842
Iter 387: sigma_u = 0.0339, loglik = -104764.4311
Iter 388: sigma_u = 0.0339, loglik = -104764.5720
Iter 389: sigma_u = 0.0339, loglik = -104765.0747
Iter 390: sigma_u = 0.0339, loglik = -104765.2108
Iter 391: sigma_u = 0.0339, loglik = -104765.7879
Iter 392: sigma_u = 0.0339, loglik = -104765.9181
Iter 393: sigma_u = 0.0339, loglik = -104766.5975
Iter 394: sigma_u = 0.0339, loglik = -104766.7229
Iter 395: sigma_u = 0.0339, loglik = -104767.5497
Iter 396: sigma_u = 0.0339, loglik = -104767.6709
Iter 397: sigma_u = 0.0339, loglik = -104768.7401
Iter 398: sigma_u = 0.0339, loglik = -104768.8562
Iter 399: sigma_u = 0.0338, loglik = -104770.3166
Iter 400: sigma_u = 0.0338, loglik = -104770.4287
Iter 401: sigma_u = 0.0338, loglik = -104772.7200
Iter 402: sigma_u = 0.0337, loglik = -104772.8265
Iter 403: sigma_u = 0.0336, loglik = -104781.9935
Iter 404: sigma_u = 0.0336, loglik = -104784.0224
Iter 405: sigma_u = 0.0336, loglik = -104784.1764
Iter 406: sigma_u = 0.0336, loglik = -104784.3649
Iter 407: sigma_u = 0.0336, loglik = -104784.5750
Iter 408: sigma_u = 0.0336, loglik = -104784.7736
Iter 409: sigma_u = 0.0336, loglik = -104784.9822
Iter 410: sigma_u = 0.0336, loglik = -104785.1826
Iter 411: sigma_u = 0.0336, loglik = -104785.3864
Iter 412: sigma_u = 0.0336, loglik = -104785.5910
Iter 413: sigma_u = 0.0336, loglik = -104785.7898
Iter 414: sigma_u = 0.0336, loglik = -104785.9993
Iter 415: sigma_u = 0.0336, loglik = -104786.1915
Iter 416: sigma_u = 0.0336, loglik = -104786.4071
Iter 417: sigma_u = 0.0336, loglik = -104786.5975
Iter 418: sigma_u = 0.0336, loglik = -104786.8164
Iter 419: sigma_u = 0.0336, loglik = -104787.0007
Iter 420: sigma_u = 0.0336, loglik = -104787.2282
Iter 421: sigma_u = 0.0336, loglik = -104787.4071
Iter 422: sigma_u = 0.0336, loglik = -104787.6434
Iter 423: sigma_u = 0.0336, loglik = -104787.8187
Iter 424: sigma_u = 0.0335, loglik = -104788.0620
Iter 425: sigma_u = 0.0335, loglik = -104788.2324
Iter 426: sigma_u = 0.0335, loglik = -104788.4827
Iter 427: sigma_u = 0.0335, loglik = -104788.6472
Iter 428: sigma_u = 0.0335, loglik = -104788.9093
Iter 429: sigma_u = 0.0335, loglik = -104789.0689
Iter 430: sigma_u = 0.0335, loglik = -104789.3431
Iter 431: sigma_u = 0.0335, loglik = -104789.4989
Iter 432: sigma_u = 0.0335, loglik = -104789.7863
Iter 433: sigma_u = 0.0335, loglik = -104789.9363
Iter 434: sigma_u = 0.0335, loglik = -104790.2415
Iter 435: sigma_u = 0.0335, loglik = -104790.3882
Iter 436: sigma_u = 0.0335, loglik = -104790.7155
Iter 437: sigma_u = 0.0335, loglik = -104790.8566
Iter 438: sigma_u = 0.0335, loglik = -104791.2066
Iter 439: sigma_u = 0.0335, loglik = -104791.3429
Iter 440: sigma_u = 0.0335, loglik = -104791.7234
Iter 441: sigma_u = 0.0335, loglik = -104791.8555
Iter 442: sigma_u = 0.0335, loglik = -104792.2702
Iter 443: sigma_u = 0.0335, loglik = -104792.3986
Iter 444: sigma_u = 0.0335, loglik = -104792.8474
Iter 445: sigma_u = 0.0335, loglik = -104792.9710
Iter 446: sigma_u = 0.0335, loglik = -104793.4828
Iter 447: sigma_u = 0.0334, loglik = -104793.6027
Iter 448: sigma_u = 0.0334, loglik = -104794.2085
Iter 449: sigma_u = 0.0334, loglik = -104794.3240
Iter 450: sigma_u = 0.0334, loglik = -104795.0576
Iter 451: sigma_u = 0.0334, loglik = -104795.1681
Iter 452: sigma_u = 0.0334, loglik = -104796.1022
Iter 453: sigma_u = 0.0334, loglik = -104796.2092
Iter 454: sigma_u = 0.0334, loglik = -104797.4816
Iter 455: sigma_u = 0.0334, loglik = -104797.5842
Iter 456: sigma_u = 0.0334, loglik = -104799.5882
Iter 457: sigma_u = 0.0332, loglik = -104799.6862
Iter 458: sigma_u = 0.0330, loglik = -104808.3026
Iter 459: sigma_u = 0.0330, loglik = -104818.0568
Iter 460: sigma_u = 0.0330, loglik = -104818.2760
Iter 461: sigma_u = 0.0330, loglik = -104818.4296
Iter 462: sigma_u = 0.0330, loglik = -104818.6523
Iter 463: sigma_u = 0.0330, loglik = -104818.8026
Iter 464: sigma_u = 0.0330, loglik = -104819.0338
Iter 465: sigma_u = 0.0330, loglik = -104819.1788
Iter 466: sigma_u = 0.0330, loglik = -104819.4209
Iter 467: sigma_u = 0.0330, loglik = -104819.5611
Iter 468: sigma_u = 0.0330, loglik = -104819.8177
Iter 469: sigma_u = 0.0330, loglik = -104819.9530
Iter 470: sigma_u = 0.0330, loglik = -104820.2270
Iter 471: sigma_u = 0.0330, loglik = -104820.3586
Iter 472: sigma_u = 0.0330, loglik = -104820.6499
Iter 473: sigma_u = 0.0330, loglik = -104820.7780
Iter 474: sigma_u = 0.0330, loglik = -104821.0853
Iter 475: sigma_u = 0.0330, loglik = -104821.2090
Iter 476: sigma_u = 0.0330, loglik = -104821.5450
Iter 477: sigma_u = 0.0330, loglik = -104821.6645
Iter 478: sigma_u = 0.0330, loglik = -104822.0361
Iter 479: sigma_u = 0.0330, loglik = -104822.1515
Iter 480: sigma_u = 0.0330, loglik = -104822.5631
Iter 481: sigma_u = 0.0330, loglik = -104822.6740
Iter 482: sigma_u = 0.0330, loglik = -104823.1361
Iter 483: sigma_u = 0.0329, loglik = -104823.2432
Iter 484: sigma_u = 0.0329, loglik = -104823.7816
Iter 485: sigma_u = 0.0329, loglik = -104823.8845
Iter 486: sigma_u = 0.0329, loglik = -104824.5430
Iter 487: sigma_u = 0.0329, loglik = -104824.6428
Iter 488: sigma_u = 0.0329, loglik = -104825.4958
Iter 489: sigma_u = 0.0329, loglik = -104825.5919
Iter 490: sigma_u = 0.0329, loglik = -104826.7276
Iter 491: sigma_u = 0.0329, loglik = -104826.8197
Iter 492: sigma_u = 0.0329, loglik = -104828.8013
Iter 493: sigma_u = 0.0328, loglik = -104828.8935

Iter 494: sigma_u = 0.0328, loglik = -104830.5079
Iter 495: sigma_u = 0.0328, loglik = -104830.5959
Iter 496: sigma_u = 0.0328, loglik = -104830.8972
Iter 497: sigma_u = 0.0328, loglik = -104831.0606
Iter 498: sigma_u = 0.0328, loglik = -104831.2483
Iter 499: sigma_u = 0.0328, loglik = -104831.4091
Iter 500: sigma_u = 0.0328, loglik = -104831.6002
Iter 501: sigma_u = 0.0328, loglik = -104831.7553
Iter 502: sigma_u = 0.0328, loglik = -104831.9530
Iter 503: sigma_u = 0.0328, loglik = -104832.1051
Iter 504: sigma_u = 0.0328, loglik = -104832.3084
Iter 505: sigma_u = 0.0328, loglik = -104832.4573
Iter 506: sigma_u = 0.0328, loglik = -104832.6659
Iter 507: sigma_u = 0.0328, loglik = -104832.8106
Iter 508: sigma_u = 0.0328, loglik = -104833.0264
Iter 509: sigma_u = 0.0328, loglik = -104833.1678
Iter 510: sigma_u = 0.0328, loglik = -104833.3921
Iter 511: sigma_u = 0.0328, loglik = -104833.5292
Iter 512: sigma_u = 0.0328, loglik = -104833.7612
Iter 513: sigma_u = 0.0328, loglik = -104833.8945
Iter 514: sigma_u = 0.0328, loglik = -104834.1405
Iter 515: sigma_u = 0.0328, loglik = -104834.2699
Iter 516: sigma_u = 0.0328, loglik = -104834.5272
Iter 517: sigma_u = 0.0328, loglik = -104834.6525
Iter 518: sigma_u = 0.0327, loglik = -104834.9274
Iter 519: sigma_u = 0.0327, loglik = -104835.0496
Iter 520: sigma_u = 0.0327, loglik = -104835.3423
Iter 521: sigma_u = 0.0327, loglik = -104835.4596
Iter 522: sigma_u = 0.0327, loglik = -104835.7801
Iter 523: sigma_u = 0.0327, loglik = -104835.8933
Iter 524: sigma_u = 0.0327, loglik = -104836.2485
Iter 525: sigma_u = 0.0327, loglik = -104836.3571
Iter 526: sigma_u = 0.0327, loglik = -104836.7544
Iter 527: sigma_u = 0.0327, loglik = -104836.8590
Iter 528: sigma_u = 0.0327, loglik = -104837.3065
Iter 529: sigma_u = 0.0327, loglik = -104837.4079
Iter 530: sigma_u = 0.0327, loglik = -104837.9432
Iter 531: sigma_u = 0.0327, loglik = -104838.0410
Iter 532: sigma_u = 0.0327, loglik = -104838.6797
Iter 533: sigma_u = 0.0327, loglik = -104838.7746
Iter 534: sigma_u = 0.0327, loglik = -104839.5798
Iter 535: sigma_u = 0.0326, loglik = -104839.6709
Iter 536: sigma_u = 0.0326, loglik = -104840.7616
Iter 537: sigma_u = 0.0326, loglik = -104840.8490
Iter 538: sigma_u = 0.0326, loglik = -104842.6338
Iter 539: sigma_u = 0.0326, loglik = -104842.7181
Iter 540: sigma_u = 0.0326, loglik = -104846.1034
Iter 541: sigma_u = 0.0325, loglik = -104846.1820
Iter 542: sigma_u = 0.0325, loglik = -104848.8380
Iter 543: sigma_u = 0.0325, loglik = -104849.0929
Iter 544: sigma_u = 0.0325, loglik = -104850.0284
Iter 545: sigma_u = 0.0325, loglik = -104850.2572
Iter 546: sigma_u = 0.0325, loglik = -104850.4089
Iter 547: sigma_u = 0.0325, loglik = -104850.5762
Iter 548: sigma_u = 0.0325, loglik = -104850.7317
Iter 549: sigma_u = 0.0325, loglik = -104850.8951
Iter 550: sigma_u = 0.0325, loglik = -104851.0550
Iter 551: sigma_u = 0.0325, loglik = -104851.2154
Iter 552: sigma_u = 0.0325, loglik = -104851.3769
Iter 553: sigma_u = 0.0325, loglik = -104851.5344
Iter 554: sigma_u = 0.0325, loglik = -104851.6981
Iter 555: sigma_u = 0.0325, loglik = -104851.8536
Iter 556: sigma_u = 0.0325, loglik = -104852.0205
Iter 557: sigma_u = 0.0324, loglik = -104852.1736
Iter 558: sigma_u = 0.0324, loglik = -104852.3447
Iter 559: sigma_u = 0.0324, loglik = -104852.4909
Iter 560: sigma_u = 0.0324, loglik = -104852.6685
Iter 561: sigma_u = 0.0324, loglik = -104852.8103
Iter 562: sigma_u = 0.0324, loglik = -104852.9946
Iter 563: sigma_u = 0.0324, loglik = -104853.1357
Iter 564: sigma_u = 0.0324, loglik = -104853.3208
Iter 565: sigma_u = 0.0324, loglik = -104853.4574
Iter 566: sigma_u = 0.0324, loglik = -104853.6505
Iter 567: sigma_u = 0.0324, loglik = -104853.7840
Iter 568: sigma_u = 0.0324, loglik = -104853.9815
Iter 569: sigma_u = 0.0324, loglik = -104854.1107
Iter 570: sigma_u = 0.0324, loglik = -104854.3188
Iter 571: sigma_u = 0.0324, loglik = -104854.4463
Iter 572: sigma_u = 0.0324, loglik = -104854.6625
Iter 573: sigma_u = 0.0324, loglik = -104854.7863
Iter 574: sigma_u = 0.0324, loglik = -104855.0117
Iter 575: sigma_u = 0.0324, loglik = -104855.1329
Iter 576: sigma_u = 0.0324, loglik = -104855.3678
Iter 577: sigma_u = 0.0324, loglik = -104855.4842
Iter 578: sigma_u = 0.0324, loglik = -104855.7388
Iter 579: sigma_u = 0.0324, loglik = -104855.8515
Iter 580: sigma_u = 0.0324, loglik = -104856.1188
Iter 581: sigma_u = 0.0324, loglik = -104856.2282
Iter 582: sigma_u = 0.0324, loglik = -104856.5161
Iter 583: sigma_u = 0.0324, loglik = -104856.6220
Iter 584: sigma_u = 0.0324, loglik = -104856.9356
Iter 585: sigma_u = 0.0324, loglik = -104857.0387
Iter 586: sigma_u = 0.0324, loglik = -104857.3841
Iter 587: sigma_u = 0.0324, loglik = -104857.4834
Iter 588: sigma_u = 0.0323, loglik = -104857.8748
Iter 589: sigma_u = 0.0323, loglik = -104857.9703
Iter 590: sigma_u = 0.0323, loglik = -104858.4304
Iter 591: sigma_u = 0.0323, loglik = -104858.5228
Iter 592: sigma_u = 0.0323, loglik = -104859.0588
Iter 593: sigma_u = 0.0323, loglik = -104859.1483
Iter 594: sigma_u = 0.0323, loglik = -104859.8130
Iter 595: sigma_u = 0.0323, loglik = -104859.8989
Iter 596: sigma_u = 0.0323, loglik = -104860.8146
Iter 597: sigma_u = 0.0323, loglik = -104860.8966
Iter 598: sigma_u = 0.0323, loglik = -104862.2543
Iter 599: sigma_u = 0.0322, loglik = -104862.3334
Iter 600: sigma_u = 0.0322, loglik = -104864.9156
Iter 601: sigma_u = 0.0321, loglik = -104864.9922
Iter 602: sigma_u = 0.0321, loglik = -104873.6880
Iter 603: sigma_u = 0.0321, loglik = -104873.7653
Iter 604: sigma_u = 0.0321, loglik = -104874.1873
Iter 605: sigma_u = 0.0321, loglik = -104874.2996
Iter 606: sigma_u = 0.0321, loglik = -104874.5057
Iter 607: sigma_u = 0.0321, loglik = -104874.6212
Iter 608: sigma_u = 0.0321, loglik = -104874.8216
Iter 609: sigma_u = 0.0320, loglik = -104874.9382
Iter 610: sigma_u = 0.0320, loglik = -104875.1396
Iter 611: sigma_u = 0.0320, loglik = -104875.2556
Iter 612: sigma_u = 0.0320, loglik = -104875.4533
Iter 613: sigma_u = 0.0320, loglik = -104875.5695
Iter 614: sigma_u = 0.0320, loglik = -104875.7660
Iter 615: sigma_u = 0.0320, loglik = -104875.8832
Iter 616: sigma_u = 0.0320, loglik = -104876.0776
Iter 617: sigma_u = 0.0320, loglik = -104876.1951
Iter 618: sigma_u = 0.0320, loglik = -104876.3883
Iteration 618: beta norm = 3.2560051519467303, sigma_u = 0.0320
Iter 619: sigma_u = 0.0320, loglik = -104876.5058
Iter 620: sigma_u = 0.0320, loglik = -104876.6931
Iter 621: sigma_u = 0.0320, loglik = -104876.8126
Iter 622: sigma_u = 0.0320, loglik = -104876.9992
Iter 623: sigma_u = 0.0320, loglik = -104877.1190
Iter 624: sigma_u = 0.0320, loglik = -104877.3055
Iter 625: sigma_u = 0.0320, loglik = -104877.4249
Iter 626: sigma_u = 0.0320, loglik = -104877.6114
Iter 627: sigma_u = 0.0320, loglik = -104877.7305
Iter 628: sigma_u = 0.0320, loglik = -104877.9170
Iter 629: sigma_u = 0.0320, loglik = -104878.0361
Iter 630: sigma_u = 0.0320, loglik = -104878.2213
Iter 631: sigma_u = 0.0320, loglik = -104878.3407
Iter 632: sigma_u = 0.0320, loglik = -104878.5259
Iter 633: sigma_u = 0.0320, loglik = -104878.6449
Iter 634: sigma_u = 0.0320, loglik = -104878.8287
Iter 635: sigma_u = 0.0320, loglik = -104878.9485
Iter 636: sigma_u = 0.0320, loglik = -104879.1305
Iter 637: sigma_u = 0.0320, loglik = -104879.2504
Iter 638: sigma_u = 0.0320, loglik = -104879.4318
Iter 639: sigma_u = 0.0320, loglik = -104879.5521
Iter 640: sigma_u = 0.0320, loglik = -104879.7340
Iter 641: sigma_u = 0.0320, loglik = -104879.8546
Iter 642: sigma_u = 0.0320, loglik = -104880.0303
Iter 643: sigma_u = 0.0320, loglik = -104880.1531
Iter 644: sigma_u = 0.0320, loglik = -104880.3257
Iter 645: sigma_u = 0.0319, loglik = -104880.4495
Iter 646: sigma_u = 0.0319, loglik = -104880.6241
Iter 647: sigma_u = 0.0319, loglik = -104880.7470
Iter 648: sigma_u = 0.0319, loglik = -104880.9210
Iter 649: sigma_u = 0.0319, loglik = -104881.0434
Iter 650: sigma_u = 0.0319, loglik = -104881.2181
Iter 651: sigma_u = 0.0319, loglik = -104881.3406
Iter 652: sigma_u = 0.0319, loglik = -104881.5125
Iter 653: sigma_u = 0.0319, loglik = -104881.6362
Iter 654: sigma_u = 0.0319, loglik = -104881.8060
Iter 655: sigma_u = 0.0319, loglik = -104881.9298
Iter 656: sigma_u = 0.0319, loglik = -104882.0980

Iter 657: sigma_u = 0.0319, loglik = -104882.2224
Iter 658: sigma_u = 0.0319, loglik = -104882.3907
Iter 659: sigma_u = 0.0319, loglik = -104882.5155
Iter 660: sigma_u = 0.0319, loglik = -104882.6812
Iter 661: sigma_u = 0.0319, loglik = -104882.8073
Iter 662: sigma_u = 0.0319, loglik = -104882.9720
Iter 663: sigma_u = 0.0319, loglik = -104883.0981
Iter 664: sigma_u = 0.0319, loglik = -104883.2623
Iter 665: sigma_u = 0.0319, loglik = -104883.3886
Iter 666: sigma_u = 0.0319, loglik = -104883.5500
Iter 667: sigma_u = 0.0319, loglik = -104883.6762
Iter 668: sigma_u = 0.0319, loglik = -104883.8371
Iter 669: sigma_u = 0.0319, loglik = -104883.9638
Iter 670: sigma_u = 0.0319, loglik = -104884.1242
Iter 671: sigma_u = 0.0319, loglik = -104884.2525
Iter 672: sigma_u = 0.0319, loglik = -104884.4112
Iter 673: sigma_u = 0.0319, loglik = -104884.5398
Iter 674: sigma_u = 0.0319, loglik = -104884.6966
Iter 675: sigma_u = 0.0319, loglik = -104884.8271
Iter 676: sigma_u = 0.0319, loglik = -104884.9792
Iter 677: sigma_u = 0.0319, loglik = -104885.1107
Iter 678: sigma_u = 0.0319, loglik = -104885.2621
Iter 679: sigma_u = 0.0319, loglik = -104885.3942
Iter 680: sigma_u = 0.0319, loglik = -104885.5436
Iter 681: sigma_u = 0.0319, loglik = -104885.6778
Iter 682: sigma_u = 0.0319, loglik = -104885.8259
Iter 683: sigma_u = 0.0319, loglik = -104885.9617
Iter 684: sigma_u = 0.0318, loglik = -104886.1053
Iter 685: sigma_u = 0.0318, loglik = -104886.2453
Iter 686: sigma_u = 0.0318, loglik = -104886.3839
Iter 687: sigma_u = 0.0318, loglik = -104886.5268
Iter 688: sigma_u = 0.0318, loglik = -104886.6632
Iter 689: sigma_u = 0.0318, loglik = -104886.8099
Iter 690: sigma_u = 0.0318, loglik = -104886.9428
Iter 691: sigma_u = 0.0318, loglik = -104887.0922
Iter 692: sigma_u = 0.0318, loglik = -104887.2232
Iter 693: sigma_u = 0.0318, loglik = -104887.3758
Iter 694: sigma_u = 0.0318, loglik = -104887.5049
Iter 695: sigma_u = 0.0318, loglik = -104887.6605
Iter 696: sigma_u = 0.0318, loglik = -104887.7851
Iter 697: sigma_u = 0.0318, loglik = -104887.9459
Iter 698: sigma_u = 0.0318, loglik = -104888.0671
Iter 699: sigma_u = 0.0318, loglik = -104888.2317
Iter 700: sigma_u = 0.0318, loglik = -104888.3506
Iter 701: sigma_u = 0.0318, loglik = -104888.5208
Iter 702: sigma_u = 0.0318, loglik = -104888.6383
Iter 703: sigma_u = 0.0318, loglik = -104888.8129
Iter 704: sigma_u = 0.0318, loglik = -104888.9266
Iter 705: sigma_u = 0.0318, loglik = -104889.1083
Iter 706: sigma_u = 0.0318, loglik = -104889.2183
Iter 707: sigma_u = 0.0318, loglik = -104889.4103
Iter 708: sigma_u = 0.0318, loglik = -104889.5174
Iter 709: sigma_u = 0.0318, loglik = -104889.7176
Iter 710: sigma_u = 0.0318, loglik = -104889.8208
Iter 711: sigma_u = 0.0318, loglik = -104890.0334
Iter 712: sigma_u = 0.0318, loglik = -104890.1331
Iter 713: sigma_u = 0.0318, loglik = -104890.3631
Iter 714: sigma_u = 0.0318, loglik = -104890.4602
Iter 715: sigma_u = 0.0318, loglik = -104890.7049
Iter 716: sigma_u = 0.0318, loglik = -104890.7988
Iter 717: sigma_u = 0.0318, loglik = -104891.0629
Iter 718: sigma_u = 0.0318, loglik = -104891.1542
Iter 719: sigma_u = 0.0318, loglik = -104891.4458
Iter 720: sigma_u = 0.0317, loglik = -104891.5341
Iter 721: sigma_u = 0.0317, loglik = -104891.8628
Iter 722: sigma_u = 0.0317, loglik = -104891.9484
Iter 723: sigma_u = 0.0317, loglik = -104892.3172
Iter 724: sigma_u = 0.0317, loglik = -104892.3993
Iter 725: sigma_u = 0.0317, loglik = -104892.8287
Iter 726: sigma_u = 0.0317, loglik = -104892.9080
Iter 727: sigma_u = 0.0317, loglik = -104893.4358
Iter 728: sigma_u = 0.0317, loglik = -104893.5124
Iter 729: sigma_u = 0.0317, loglik = -104894.1812
Iter 730: sigma_u = 0.0317, loglik = -104894.2553
Iter 731: sigma_u = 0.0317, loglik = -104895.2041
Iter 732: sigma_u = 0.0317, loglik = -104895.2751
Iter 733: sigma_u = 0.0317, loglik = -104896.8683
Iter 734: sigma_u = 0.0316, loglik = -104896.9369
Iter 735: sigma_u = 0.0316, loglik = -104900.3085
Iter 736: sigma_u = 0.0316, loglik = -104900.3719
Iter 737: sigma_u = 0.0315, loglik = -104902.8649
Iter 738: sigma_u = 0.0315, loglik = -104903.0624
Iter 739: sigma_u = 0.0315, loglik = -104903.2108
Iter 740: sigma_u = 0.0315, loglik = -104903.3313
Iter 741: sigma_u = 0.0315, loglik = -104903.4739
Iter 742: sigma_u = 0.0315, loglik = -104903.5956
Iter 743: sigma_u = 0.0315, loglik = -104903.7369
Iter 744: sigma_u = 0.0315, loglik = -104903.8601
Iter 745: sigma_u = 0.0315, loglik = -104903.9998
Iter 746: sigma_u = 0.0315, loglik = -104904.1250
Iter 747: sigma_u = 0.0315, loglik = -104904.2619
Iter 748: sigma_u = 0.0315, loglik = -104904.3885
Iter 749: sigma_u = 0.0315, loglik = -104904.5243
Iter 750: sigma_u = 0.0315, loglik = -104904.6514
Iter 751: sigma_u = 0.0315, loglik = -104904.7826
Iter 752: sigma_u = 0.0315, loglik = -104904.9127
Iter 753: sigma_u = 0.0315, loglik = -104905.0407
Iter 754: sigma_u = 0.0315, loglik = -104905.1745
Iter 755: sigma_u = 0.0315, loglik = -104905.3030
Iter 756: sigma_u = 0.0315, loglik = -104905.4367
Iter 757: sigma_u = 0.0315, loglik = -104905.5617
Iter 758: sigma_u = 0.0315, loglik = -104905.6979
Iter 759: sigma_u = 0.0315, loglik = -104905.8233
Iter 760: sigma_u = 0.0315, loglik = -104905.9591
Iter 761: sigma_u = 0.0315, loglik = -104906.0813
Iter 762: sigma_u = 0.0315, loglik = -104906.2216
Iter 763: sigma_u = 0.0315, loglik = -104906.3419
Iter 764: sigma_u = 0.0315, loglik = -104906.4840
Iter 765: sigma_u = 0.0315, loglik = -104906.6017
Iter 766: sigma_u = 0.0315, loglik = -104906.7490
Iter 767: sigma_u = 0.0315, loglik = -104906.8626
Iter 768: sigma_u = 0.0315, loglik = -104907.0143
Iter 769: sigma_u = 0.0315, loglik = -104907.1258
Iter 770: sigma_u = 0.0315, loglik = -104907.2817
Iter 771: sigma_u = 0.0315, loglik = -104907.3901
Iter 772: sigma_u = 0.0315, loglik = -104907.5540
Iter 773: sigma_u = 0.0315, loglik = -104907.6601
Iter 774: sigma_u = 0.0315, loglik = -104907.8283
Iter 775: sigma_u = 0.0315, loglik = -104907.9315
Iter 776: sigma_u = 0.0315, loglik = -104908.1071
Iter 777: sigma_u = 0.0315, loglik = -104908.2075
Iter 778: sigma_u = 0.0315, loglik = -104908.3923
Iter 779: sigma_u = 0.0314, loglik = -104908.4898
Iter 780: sigma_u = 0.0314, loglik = -104908.6864
Iter 781: sigma_u = 0.0314, loglik = -104908.7805
Iter 782: sigma_u = 0.0314, loglik = -104908.9891
Iter 783: sigma_u = 0.0314, loglik = -104909.0805
Iter 784: sigma_u = 0.0314, loglik = -104909.3049
Iter 785: sigma_u = 0.0314, loglik = -104909.3928
Iter 786: sigma_u = 0.0314, loglik = -104909.6355
Iter 787: sigma_u = 0.0314, loglik = -104909.7204
Iter 788: sigma_u = 0.0314, loglik = -104909.9894
Iter 789: sigma_u = 0.0314, loglik = -104910.0713
Iter 790: sigma_u = 0.0314, loglik = -104910.3820
Iter 791: sigma_u = 0.0314, loglik = -104910.4609
Iter 792: sigma_u = 0.0314, loglik = -104910.8174
Iter 793: sigma_u = 0.0314, loglik = -104910.8933
Iter 794: sigma_u = 0.0314, loglik = -104911.3142
Iter 795: sigma_u = 0.0314, loglik = -104911.3875
Iter 796: sigma_u = 0.0314, loglik = -104911.9043
Iter 797: sigma_u = 0.0314, loglik = -104911.9750
Iter 798: sigma_u = 0.0314, loglik = -104912.6340
Iter 799: sigma_u = 0.0314, loglik = -104912.7022
Iter 800: sigma_u = 0.0314, loglik = -104913.6352
Iter 801: sigma_u = 0.0313, loglik = -104913.7006
Iter 802: sigma_u = 0.0313, loglik = -104915.4599
Iter 803: sigma_u = 0.0313, loglik = -104915.5256
Iter 804: sigma_u = 0.0313, loglik = -104916.6166
Iter 805: sigma_u = 0.0313, loglik = -104916.6830
Iter 806: sigma_u = 0.0313, loglik = -104916.8638
Iter 807: sigma_u = 0.0313, loglik = -104916.9749
Iter 808: sigma_u = 0.0313, loglik = -104917.1177
Iter 809: sigma_u = 0.0313, loglik = -104917.2256
Iter 810: sigma_u = 0.0313, loglik = -104917.3740
Iter 811: sigma_u = 0.0313, loglik = -104917.4799
Iter 812: sigma_u = 0.0313, loglik = -104917.6330
Iter 813: sigma_u = 0.0313, loglik = -104917.7360
Iter 814: sigma_u = 0.0313, loglik = -104917.8939
Iter 815: sigma_u = 0.0313, loglik = -104917.9952
Iter 816: sigma_u = 0.0313, loglik = -104918.1581
Iter 817: sigma_u = 0.0313, loglik = -104918.2553
Iter 818: sigma_u = 0.0313, loglik = -104918.4266
Iter 819: sigma_u = 0.0313, loglik = -104918.5214
Iter 820: sigma_u = 0.0313, loglik = -104918.7034

Iter 821: sigma_u = 0.0313, loglik = -104918.7959
Iter 822: sigma_u = 0.0313, loglik = -104918.9872
Iter 823: sigma_u = 0.0313, loglik = -104919.0778
Iter 824: sigma_u = 0.0313, loglik = -104919.2801
Iter 825: sigma_u = 0.0312, loglik = -104919.3665
Iter 826: sigma_u = 0.0312, loglik = -104919.5863
Iter 827: sigma_u = 0.0312, loglik = -104919.6703
Iter 828: sigma_u = 0.0312, loglik = -104919.9070
Iter 829: sigma_u = 0.0312, loglik = -104919.9884
Iter 830: sigma_u = 0.0312, loglik = -104920.2471
Iter 831: sigma_u = 0.0312, loglik = -104920.3261
Iter 832: sigma_u = 0.0312, loglik = -104920.6230
Iter 833: sigma_u = 0.0312, loglik = -104920.6984
Iter 834: sigma_u = 0.0312, loglik = -104921.0355
Iter 835: sigma_u = 0.0312, loglik = -104921.1077
Iter 836: sigma_u = 0.0312, loglik = -104921.5071
Iter 837: sigma_u = 0.0312, loglik = -104921.5775
Iter 838: sigma_u = 0.0312, loglik = -104922.0708
Iter 839: sigma_u = 0.0312, loglik = -104922.1386
Iter 840: sigma_u = 0.0312, loglik = -104922.8007
Iter 841: sigma_u = 0.0312, loglik = -104922.8663
Iter 842: sigma_u = 0.0312, loglik = -104923.8434
Iter 843: sigma_u = 0.0311, loglik = -104923.9056
Iter 844: sigma_u = 0.0311, loglik = -104925.8401
Iter 845: sigma_u = 0.0311, loglik = -104925.9026
Iter 846: sigma_u = 0.0311, loglik = -104926.9967
Iter 847: sigma_u = 0.0311, loglik = -104927.0630
Iter 848: sigma_u = 0.0311, loglik = -104927.2105
Iter 849: sigma_u = 0.0311, loglik = -104927.3181
Iter 850: sigma_u = 0.0311, loglik = -104927.4528
Iter 851: sigma_u = 0.0311, loglik = -104927.5572
Iter 852: sigma_u = 0.0311, loglik = -104927.6974
Iter 853: sigma_u = 0.0311, loglik = -104927.7992
Iter 854: sigma_u = 0.0311, loglik = -104927.9433
Iter 855: sigma_u = 0.0311, loglik = -104928.0411
Iter 856: sigma_u = 0.0311, loglik = -104928.1919
Iter 857: sigma_u = 0.0311, loglik = -104928.2878
Iter 858: sigma_u = 0.0311, loglik = -104928.4438
Iter 859: sigma_u = 0.0311, loglik = -104928.5372
Iter 860: sigma_u = 0.0311, loglik = -104928.7010
Iter 861: sigma_u = 0.0311, loglik = -104928.7926
Iter 862: sigma_u = 0.0311, loglik = -104928.9638
Iter 863: sigma_u = 0.0311, loglik = -104929.0537
Iter 864: sigma_u = 0.0311, loglik = -104929.2303
Iter 865: sigma_u = 0.0311, loglik = -104929.3167
Iter 866: sigma_u = 0.0311, loglik = -104929.5076
Iter 867: sigma_u = 0.0311, loglik = -104929.5920
Iter 868: sigma_u = 0.0311, loglik = -104929.7961
Iter 869: sigma_u = 0.0311, loglik = -104929.8775
Iter 870: sigma_u = 0.0311, loglik = -104930.1016
Iter 871: sigma_u = 0.0311, loglik = -104930.1796
Iter 872: sigma_u = 0.0311, loglik = -104930.4229
Iter 873: sigma_u = 0.0310, loglik = -104930.4986
Iter 874: sigma_u = 0.0310, loglik = -104930.7718
Iter 875: sigma_u = 0.0310, loglik = -104930.8453
Iter 876: sigma_u = 0.0310, loglik = -104931.1514
Iter 877: sigma_u = 0.0310, loglik = -104931.2220
Iter 878: sigma_u = 0.0310, loglik = -104931.5750
Iter 879: sigma_u = 0.0310, loglik = -104931.6432
Iter 880: sigma_u = 0.0310, loglik = -104932.0698
Iter 881: sigma_u = 0.0310, loglik = -104932.1357
Iter 882: sigma_u = 0.0310, loglik = -104932.6357
Iter 883: sigma_u = 0.0310, loglik = -104932.6997
Iter 884: sigma_u = 0.0310, loglik = -104933.4120
Iter 885: sigma_u = 0.0310, loglik = -104933.4741
Iter 886: sigma_u = 0.0310, loglik = -104934.5698
Iter 887: sigma_u = 0.0309, loglik = -104934.6279
Iter 888: sigma_u = 0.0309, loglik = -104936.6344
Iter 889: sigma_u = 0.0309, loglik = -104936.7048
Iter 890: sigma_u = 0.0309, loglik = -104936.9107
Iter 891: sigma_u = 0.0309, loglik = -104936.9982
Iter 892: sigma_u = 0.0309, loglik = -104937.1608
Iter 893: sigma_u = 0.0309, loglik = -104937.2477
Iter 894: sigma_u = 0.0309, loglik = -104937.4169
Iter 895: sigma_u = 0.0309, loglik = -104937.5020
Iter 896: sigma_u = 0.0309, loglik = -104937.6807
Iter 897: sigma_u = 0.0309, loglik = -104937.7633
Iter 898: sigma_u = 0.0309, loglik = -104937.9528
Iter 899: sigma_u = 0.0309, loglik = -104938.0333
Iter 900: sigma_u = 0.0309, loglik = -104938.2315
Iter 901: sigma_u = 0.0309, loglik = -104938.3105
Iter 902: sigma_u = 0.0309, loglik = -104938.5228
Iter 903: sigma_u = 0.0309, loglik = -104938.5985
Iter 904: sigma_u = 0.0309, loglik = -104938.8308
Iter 905: sigma_u = 0.0309, loglik = -104938.9044
Iter 906: sigma_u = 0.0309, loglik = -104939.1682
Iter 907: sigma_u = 0.0309, loglik = -104939.2388
Iter 908: sigma_u = 0.0309, loglik = -104939.5337
Iter 909: sigma_u = 0.0309, loglik = -104939.6022
Iter 910: sigma_u = 0.0309, loglik = -104939.9448
Iter 911: sigma_u = 0.0309, loglik = -104940.0109
Iter 912: sigma_u = 0.0309, loglik = -104940.4230
Iter 913: sigma_u = 0.0309, loglik = -104940.4862
Iter 914: sigma_u = 0.0309, loglik = -104941.0149
Iter 915: sigma_u = 0.0308, loglik = -104941.0766
Iter 916: sigma_u = 0.0308, loglik = -104941.7850
Iter 917: sigma_u = 0.0308, loglik = -104941.8438
Iter 918: sigma_u = 0.0308, loglik = -104942.9501
Iter 919: sigma_u = 0.0308, loglik = -104943.0068
Iter 920: sigma_u = 0.0308, loglik = -104945.3931
Iter 921: sigma_u = 0.0307, loglik = -104945.4483
Iter 922: sigma_u = 0.0307, loglik = -104951.8620
Iter 923: sigma_u = 0.0307, loglik = -104951.9921
Iter 924: sigma_u = 0.0307, loglik = -104952.1542
Iter 925: sigma_u = 0.0306, loglik = -104952.2353
Iter 926: sigma_u = 0.0306, loglik = -104952.3971
Iter 927: sigma_u = 0.0306, loglik = -104952.4781
Iter 928: sigma_u = 0.0306, loglik = -104952.6347
Iter 929: sigma_u = 0.0306, loglik = -104952.7159
Iter 930: sigma_u = 0.0306, loglik = -104952.8724
Iter 931: sigma_u = 0.0306, loglik = -104952.9535
Iter 932: sigma_u = 0.0306, loglik = -104953.1082
Iter 933: sigma_u = 0.0306, loglik = -104953.1887
Iter 934: sigma_u = 0.0306, loglik = -104953.3530
Iter 935: sigma_u = 0.0306, loglik = -104953.4326
Iter 936: sigma_u = 0.0306, loglik = -104953.5965
Iter 937: sigma_u = 0.0306, loglik = -104953.6755
Iter 938: sigma_u = 0.0306, loglik = -104953.8364
Iter 939: sigma_u = 0.0306, loglik = -104953.9164
Iter 940: sigma_u = 0.0306, loglik = -104954.0789
Iter 941: sigma_u = 0.0306, loglik = -104954.1584
Iter 942: sigma_u = 0.0306, loglik = -104954.3218
Iter 943: sigma_u = 0.0306, loglik = -104954.4006
Iter 944: sigma_u = 0.0306, loglik = -104954.5641
Iter 945: sigma_u = 0.0306, loglik = -104954.6432
Iter 946: sigma_u = 0.0306, loglik = -104954.8067
Iter 947: sigma_u = 0.0306, loglik = -104954.8850
Iter 948: sigma_u = 0.0306, loglik = -104955.0443
Iter 949: sigma_u = 0.0306, loglik = -104955.1233
Iter 950: sigma_u = 0.0306, loglik = -104955.2842
Iter 951: sigma_u = 0.0306, loglik = -104955.3628
Iter 952: sigma_u = 0.0306, loglik = -104955.5243
Iter 953: sigma_u = 0.0306, loglik = -104955.6032
Iter 954: sigma_u = 0.0306, loglik = -104955.7638
Iter 955: sigma_u = 0.0306, loglik = -104955.8420
Iter 956: sigma_u = 0.0306, loglik = -104956.0072
Iter 957: sigma_u = 0.0306, loglik = -104956.0850
Iter 958: sigma_u = 0.0306, loglik = -104956.2482
Iter 959: sigma_u = 0.0306, loglik = -104956.3267
Iter 960: sigma_u = 0.0306, loglik = -104956.4898
Iter 961: sigma_u = 0.0306, loglik = -104956.5671
Iter 962: sigma_u = 0.0306, loglik = -104956.7322
Iter 963: sigma_u = 0.0306, loglik = -104956.8091
Iter 964: sigma_u = 0.0306, loglik = -104956.9752
Iter 965: sigma_u = 0.0306, loglik = -104957.0526
Iter 966: sigma_u = 0.0306, loglik = -104957.2140
Iter 967: sigma_u = 0.0306, loglik = -104957.2915
Iter 968: sigma_u = 0.0306, loglik = -104957.4548
Iter 969: sigma_u = 0.0306, loglik = -104957.5317
Iter 970: sigma_u = 0.0305, loglik = -104957.6959
Iter 971: sigma_u = 0.0305, loglik = -104957.7731
Iter 972: sigma_u = 0.0305, loglik = -104957.9404
Iter 973: sigma_u = 0.0305, loglik = -104958.0170
Iter 974: sigma_u = 0.0305, loglik = -104958.1876
Iter 975: sigma_u = 0.0305, loglik = -104958.2631
Iter 976: sigma_u = 0.0305, loglik = -104958.4274
Iter 977: sigma_u = 0.0305, loglik = -104958.5040
Iter 978: sigma_u = 0.0305, loglik = -104958.6649
Iter 979: sigma_u = 0.0305, loglik = -104958.7422
Iter 980: sigma_u = 0.0305, loglik = -104958.8985
Iter 981: sigma_u = 0.0305, loglik = -104958.9769
Iter 982: sigma_u = 0.0305, loglik = -104959.1316
Iter 983: sigma_u = 0.0305, loglik = -104959.2098
Iter 984: sigma_u = 0.0305, loglik = -104959.3669

Iter 985: sigma_u = 0.0305, loglik = -104959.4454
Iter 986: sigma_u = 0.0305, loglik = -104959.5988
Iter 987: sigma_u = 0.0305, loglik = -104959.6776
Iter 988: sigma_u = 0.0305, loglik = -104959.8346
Iter 989: sigma_u = 0.0305, loglik = -104959.9131
Iter 990: sigma_u = 0.0305, loglik = -104960.0613
Iter 991: sigma_u = 0.0305, loglik = -104960.1403
Iter 992: sigma_u = 0.0305, loglik = -104960.2938
Iter 993: sigma_u = 0.0305, loglik = -104960.3720
Iter 994: sigma_u = 0.0305, loglik = -104960.5250
Iter 995: sigma_u = 0.0305, loglik = -104960.6028
Iter 996: sigma_u = 0.0305, loglik = -104960.7570
Iter 997: sigma_u = 0.0305, loglik = -104960.8345
Iter 998: sigma_u = 0.0305, loglik = -104960.9952
Iter 999: sigma_u = 0.0305, loglik = -104961.0711
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             1.80       1.770097     1.773206
1            -2.10      -2.072570    -2.076374
2            -0.50      -0.483602    -0.484366
3            -1.70      -1.701427    -1.704407
4             0.25       0.083017     0.030485



Time taken 6.050352346897125 minutes



Initial sigma: 0.25

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.2965, loglik = -14651.0341
Iter 1: sigma_u = 1.0715, loglik = -15477.3780
Iter 2: sigma_u = 0.8854, loglik = -16756.9247
Iter 3: sigma_u = 0.7321, loglik = -18618.1389
Iter 4: sigma_u = 0.6058, loglik = -21298.7944
Iter 5: sigma_u = 0.5020, loglik = -25120.8902
Iter 6: sigma_u = 0.4169, loglik = -30478.9484
Iter 7: sigma_u = 0.3474, loglik = -37738.3832
Iter 8: sigma_u = 0.2912, loglik = -46891.0078
Iter 9: sigma_u = 0.2466, loglik = -57118.2846
Iter 10: sigma_u = 0.2120, loglik = -67000.8909
Iter 11: sigma_u = 0.1854, loglik = -75397.6412
Iter 12: sigma_u = 0.1649, loglik = -81944.9489
Iter 13: sigma_u = 0.1491, loglik = -86845.5575
Iter 14: sigma_u = 0.1366, loglik = -90480.3425
Iter 15: sigma_u = 0.1266, loglik = -93204.2967
Iter 16: sigma_u = 0.1185, loglik = -95277.2683
Iter 17: sigma_u = 0.1117, loglik = -96885.8353
Iter 18: sigma_u = 0.1060, loglik = -98157.8635
Iter 19: sigma_u = 0.1012, loglik = -99181.8168
Iter 20: sigma_u = 0.0970, loglik = -100018.8945
Iter 21: sigma_u = 0.0934, loglik = -100713.2023
Iter 22: sigma_u = 0.0902, loglik = -101296.4711
Iter 23: sigma_u = 0.0874, loglik = -101791.9704
Iter 24: sigma_u = 0.0849, loglik = -102217.1997
Iter 25: sigma_u = 0.0826, loglik = -102585.3790
Iter 26: sigma_u = 0.0806, loglik = -102906.7199
Iter 27: sigma_u = 0.0788, loglik = -103189.1710
Iter 28: sigma_u = 0.0772, loglik = -103436.1277
Iter 29: sigma_u = 0.0757, loglik = -103658.6095
Iter 30: sigma_u = 0.0743, loglik = -103856.4734
Iter 31: sigma_u = 0.0731, loglik = -104037.5046
Iter 32: sigma_u = 0.0719, loglik = -104196.3624
Iter 33: sigma_u = 0.0708, loglik = -104341.5017
Iter 34: sigma_u = 0.0698, loglik = -104474.3576
Iter 35: sigma_u = 0.0689, loglik = -104596.5034
Iter 36: sigma_u = 0.0681, loglik = -104705.0180
Iter 37: sigma_u = 0.0673, loglik = -104808.7615
Iter 38: sigma_u = 0.0665, loglik = -104902.1960
Iter 39: sigma_u = 0.0658, loglik = -104988.4379
Iter 40: sigma_u = 0.0652, loglik = -105069.8519
Iter 41: sigma_u = 0.0646, loglik = -105144.2781
Iter 42: sigma_u = 0.0640, loglik = -105214.3364
Iter 43: sigma_u = 0.0635, loglik = -105278.3527
Iter 44: sigma_u = 0.0630, loglik = -105338.3673
Iter 45: sigma_u = 0.0625, loglik = -105394.2337
Iter 46: sigma_u = 0.0620, loglik = -105447.2594
Iter 47: sigma_u = 0.0616, loglik = -105496.0302
Iter 48: sigma_u = 0.0611, loglik = -105542.6400
Iter 49: sigma_u = 0.0607, loglik = -105599.7446
Iter 50: sigma_u = 0.0603, loglik = -105639.6875
Iter 51: sigma_u = 0.0600, loglik = -105676.2482
Iter 52: sigma_u = 0.0597, loglik = -105709.2440
Iter 53: sigma_u = 0.0594, loglik = -105740.4815
Iter 54: sigma_u = 0.0592, loglik = -105770.4499
Iter 55: sigma_u = 0.0589, loglik = -105800.9546
Iter 56: sigma_u = 0.0586, loglik = -105829.5233
Iter 57: sigma_u = 0.0584, loglik = -105855.7302
Iter 58: sigma_u = 0.0582, loglik = -105878.0618
Iter 59: sigma_u = 0.0581, loglik = -105894.9010
Iter 60: sigma_u = 0.0579, loglik = -105909.2392
Iter 61: sigma_u = 0.0577, loglik = -105932.1851
Iter 62: sigma_u = 0.0575, loglik = -105953.1292
Iter 63: sigma_u = 0.0574, loglik = -105970.7954
Iter 64: sigma_u = 0.0572, loglik = -105984.5515
Iter 65: sigma_u = 0.0572, loglik = -105998.1851
Iter 66: sigma_u = 0.0571, loglik = -105999.6622
Iter 67: sigma_u = 0.0569, loglik = -106013.9323
Iter 68: sigma_u = 0.0568, loglik = -106026.5917
Iter 69: sigma_u = 0.0568, loglik = -106036.6036
Iter 70: sigma_u = 0.0567, loglik = -106045.3278
Iter 71: sigma_u = 0.0566, loglik = -106054.9778
Iter 72: sigma_u = 0.0565, loglik = -106065.1910
Iter 73: sigma_u = 0.0565, loglik = -106065.9484
Iter 74: sigma_u = 0.0565, loglik = -106066.9161
Iter 75: sigma_u = 0.0565, loglik = -106067.6858
Iter 76: sigma_u = 0.0565, loglik = -106068.6170
Iter 77: sigma_u = 0.0565, loglik = -106069.3984
Iter 78: sigma_u = 0.0565, loglik = -106070.2946
Iter 79: sigma_u = 0.0565, loglik = -106071.0874
Iter 80: sigma_u = 0.0565, loglik = -106071.9528
Iter 81: sigma_u = 0.0565, loglik = -106072.7602
Iter 82: sigma_u = 0.0565, loglik = -106073.5902
Iter 83: sigma_u = 0.0565, loglik = -106074.4202
Iter 84: sigma_u = 0.0564, loglik = -106075.2152
Iter 85: sigma_u = 0.0564, loglik = -106076.0809
Iter 86: sigma_u = 0.0564, loglik = -106076.8316
Iter 87: sigma_u = 0.0564, loglik = -106077.7426
Iter 88: sigma_u = 0.0564, loglik = -106078.4513
Iter 89: sigma_u = 0.0564, loglik = -106079.4319
Iter 90: sigma_u = 0.0564, loglik = -106080.0934
Iter 91: sigma_u = 0.0564, loglik = -106081.1885
Iter 92: sigma_u = 0.0564, loglik = -106081.7976
Iter 93: sigma_u = 0.0564, loglik = -106083.0619
Iter 94: sigma_u = 0.0564, loglik = -106083.6193
Iter 95: sigma_u = 0.0564, loglik = -106085.2047
Iter 96: sigma_u = 0.0563, loglik = -106085.7093
Iter 97: sigma_u = 0.0563, loglik = -106088.0278
Iter 98: sigma_u = 0.0562, loglik = -106088.4788
Iter 99: sigma_u = 0.0560, loglik = -106102.7977
Iter 100: sigma_u = 0.0560, loglik = -106120.8744
Iter 101: sigma_u = 0.0560, loglik = -106123.3522
Iter 102: sigma_u = 0.0558, loglik = -106123.7321
Iter 103: sigma_u = 0.0557, loglik = -106136.3789
Iter 104: sigma_u = 0.0556, loglik = -106151.9884
Iter 105: sigma_u = 0.0555, loglik = -106163.9225
Iter 106: sigma_u = 0.0555, loglik = -106164.7442
Iter 107: sigma_u = 0.0555, loglik = -106165.1943
Iter 108: sigma_u = 0.0555, loglik = -106166.0660
Iter 109: sigma_u = 0.0555, loglik = -106166.4831
Iter 110: sigma_u = 0.0555, loglik = -106167.5361
Iter 111: sigma_u = 0.0555, loglik = -106167.9110
Iter 112: sigma_u = 0.0555, loglik = -106169.3498
Iter 113: sigma_u = 0.0555, loglik = -106169.6878
Iter 114: sigma_u = 0.0555, loglik = -106172.1265
Iter 115: sigma_u = 0.0553, loglik = -106172.4298
Iter 116: sigma_u = 0.0553, loglik = -106184.7564
Iter 117: sigma_u = 0.0553, loglik = -106185.1192
Iter 118: sigma_u = 0.0553, loglik = -106186.0328
Iter 119: sigma_u = 0.0553, loglik = -106186.3811
Iter 120: sigma_u = 0.0553, loglik = -106187.3730
Iter 121: sigma_u = 0.0553, loglik = -106187.7028
Iter 122: sigma_u = 0.0553, loglik = -106188.8220
Iter 123: sigma_u = 0.0553, loglik = -106189.1348
Iter 124: sigma_u = 0.0553, loglik = -106190.4378
Iter 125: sigma_u = 0.0553, loglik = -106190.7357
Iter 126: sigma_u = 0.0553, loglik = -106192.3208
Iter 127: sigma_u = 0.0552, loglik = -106192.6014
Iter 128: sigma_u = 0.0552, loglik = -106194.7169
Iter 129: sigma_u = 0.0552, loglik = -106194.9785
Iter 130: sigma_u = 0.0552, loglik = -106198.2729
Iter 131: sigma_u = 0.0551, loglik = -106198.5161
Iter 132: sigma_u = 0.0551, loglik = -106204.2679
Iter 133: sigma_u = 0.0550, loglik = -106204.4936
Iter 134: sigma_u = 0.0550, loglik = -106215.0277
Iter 135: sigma_u = 0.0550, loglik = -106216.7928
Iter 136: sigma_u = 0.0550, loglik = -106217.0436
Iter 137: sigma_u = 0.0550, loglik = -106218.4126
Iter 138: sigma_u = 0.0550, loglik = -106218.7112
Iter 139: sigma_u = 0.0550, loglik = -106219.7253
Iter 140: sigma_u = 0.0550, loglik = -106219.9978
Iter 141: sigma_u = 0.0550, loglik = -106221.2603
Iter 142: sigma_u = 0.0549, loglik = -106221.5213
Iter 143: sigma_u = 0.0549, loglik = -106223.5151
Iter 144: sigma_u = 0.0549, loglik = -106223.7430
Iter 145: sigma_u = 0.0549, loglik = -106227.6940
Iter 146: sigma_u = 0.0549, loglik = -106227.9899
Iter 147: sigma_u = 0.0549, loglik = -106228.6715
Iter 148: sigma_u = 0.0549, loglik = -106228.9888
Iter 149: sigma_u = 0.0549, loglik = -106229.6124
Iter 150: sigma_u = 0.0549, loglik = -106229.9119
Iter 151: sigma_u = 0.0549, loglik = -106230.6717
Iter 152: sigma_u = 0.0549, loglik = -106230.9434
Iter 153: sigma_u = 0.0549, loglik = -106231.9755
Iter 154: sigma_u = 0.0548, loglik = -106232.2208
Iter 155: sigma_u = 0.0548, loglik = -106234.0293
Iter 156: sigma_u = 0.0548, loglik = -106234.2493
Iter 157: sigma_u = 0.0548, loglik = -106239.7418
Iter 158: sigma_u = 0.0547, loglik = -106239.9441
Iter 159: sigma_u = 0.0547, loglik = -106247.4622
Iter 160: sigma_u = 0.0547, loglik = -106247.6389
Iter 161: sigma_u = 0.0547, loglik = -106248.9393
Iter 162: sigma_u = 0.0547, loglik = -106249.2259
Iter 163: sigma_u = 0.0547, loglik = -106249.7275
Iter 164: sigma_u = 0.0547, loglik = -106250.0115
Iter 165: sigma_u = 0.0547, loglik = -106250.5096
Iter 166: sigma_u = 0.0547, loglik = -106250.7914

Iter 167: sigma_u = 0.0547, loglik = -106251.2992
Iter 168: sigma_u = 0.0546, loglik = -106251.5721
Iter 169: sigma_u = 0.0546, loglik = -106252.1017
Iter 170: sigma_u = 0.0546, loglik = -106252.3655
Iter 171: sigma_u = 0.0546, loglik = -106252.9190
Iter 172: sigma_u = 0.0546, loglik = -106253.1740
Iter 173: sigma_u = 0.0546, loglik = -106253.7595
Iter 174: sigma_u = 0.0546, loglik = -106254.0047
Iter 175: sigma_u = 0.0546, loglik = -106254.6428
Iter 176: sigma_u = 0.0546, loglik = -106254.8781
Iter 177: sigma_u = 0.0546, loglik = -106255.5837
Iter 178: sigma_u = 0.0546, loglik = -106255.8066
Iter 179: sigma_u = 0.0546, loglik = -106256.6155
Iter 180: sigma_u = 0.0546, loglik = -106256.8282
Iter 181: sigma_u = 0.0546, loglik = -106257.7649
Iter 182: sigma_u = 0.0546, loglik = -106257.9646
Iter 183: sigma_u = 0.0546, loglik = -106259.1624
Iter 184: sigma_u = 0.0546, loglik = -106259.3495
Iter 185: sigma_u = 0.0546, loglik = -106260.9817
Iter 186: sigma_u = 0.0545, loglik = -106261.1576
Iter 187: sigma_u = 0.0545, loglik = -106263.6769
Iter 188: sigma_u = 0.0545, loglik = -106263.8413
Iter 189: sigma_u = 0.0545, loglik = -106268.2595
Iter 190: sigma_u = 0.0544, loglik = -106268.4113
Iter 191: sigma_u = 0.0544, loglik = -106274.1423
Iter 192: sigma_u = 0.0544, loglik = -106274.3388
Iter 193: sigma_u = 0.0544, loglik = -106274.9114
Iter 194: sigma_u = 0.0544, loglik = -106275.1384
Iter 195: sigma_u = 0.0544, loglik = -106275.5616
Iter 196: sigma_u = 0.0544, loglik = -106275.7965
Iter 197: sigma_u = 0.0544, loglik = -106276.2349
Iter 198: sigma_u = 0.0544, loglik = -106276.4628
Iter 199: sigma_u = 0.0544, loglik = -106276.9201
Iter 200: sigma_u = 0.0544, loglik = -106277.1400
Iter 201: sigma_u = 0.0544, loglik = -106277.6225
Iter 202: sigma_u = 0.0544, loglik = -106277.8337
Iter 203: sigma_u = 0.0544, loglik = -106278.3503
Iter 204: sigma_u = 0.0544, loglik = -106278.5541
Iter 205: sigma_u = 0.0544, loglik = -106279.1173
Iter 206: sigma_u = 0.0544, loglik = -106279.3139
Iter 207: sigma_u = 0.0544, loglik = -106279.9424
Iter 208: sigma_u = 0.0543, loglik = -106280.1275
Iter 209: sigma_u = 0.0543, loglik = -106280.8628
Iter 210: sigma_u = 0.0543, loglik = -106281.0359
Iter 211: sigma_u = 0.0543, loglik = -106281.9403
Iter 212: sigma_u = 0.0543, loglik = -106282.1048
Iter 213: sigma_u = 0.0543, loglik = -106283.2817
Iter 214: sigma_u = 0.0543, loglik = -106283.4348
Iter 215: sigma_u = 0.0543, loglik = -106285.1481
Iter 216: sigma_u = 0.0543, loglik = -106285.2926
Iter 217: sigma_u = 0.0543, loglik = -106288.1212
Iter 218: sigma_u = 0.0542, loglik = -106288.2530
Iter 219: sigma_u = 0.0542, loglik = -106291.6233
Iter 220: sigma_u = 0.0542, loglik = -106291.8086
Iter 221: sigma_u = 0.0542, loglik = -106292.2067
Iter 222: sigma_u = 0.0542, loglik = -106292.4221
Iter 223: sigma_u = 0.0542, loglik = -106292.7727
Iter 224: sigma_u = 0.0542, loglik = -106292.9878
Iter 225: sigma_u = 0.0542, loglik = -106293.3448
Iter 226: sigma_u = 0.0542, loglik = -106293.5563
Iter 227: sigma_u = 0.0542, loglik = -106293.9198
Iter 228: sigma_u = 0.0542, loglik = -106294.1247
Iter 229: sigma_u = 0.0542, loglik = -106294.5019
Iter 230: sigma_u = 0.0542, loglik = -106294.7003
Iter 231: sigma_u = 0.0542, loglik = -106295.0944
Iter 232: sigma_u = 0.0542, loglik = -106295.2881
Iter 233: sigma_u = 0.0542, loglik = -106295.7040
Iter 234: sigma_u = 0.0542, loglik = -106295.8909
Iter 235: sigma_u = 0.0542, loglik = -106296.3276
Iter 236: sigma_u = 0.0542, loglik = -106296.5081
Iter 237: sigma_u = 0.0542, loglik = -106296.9798
Iter 238: sigma_u = 0.0542, loglik = -106297.1525
Iter 239: sigma_u = 0.0542, loglik = -106297.6724
Iter 240: sigma_u = 0.0542, loglik = -106297.8379
Iter 241: sigma_u = 0.0542, loglik = -106298.4330
Iter 242: sigma_u = 0.0542, loglik = -106298.5886
Iter 243: sigma_u = 0.0542, loglik = -106299.3085
Iter 244: sigma_u = 0.0541, loglik = -106299.4549
Iter 245: sigma_u = 0.0541, loglik = -106300.3545
Iter 246: sigma_u = 0.0541, loglik = -106300.4929
Iter 247: sigma_u = 0.0541, loglik = -106301.7188
Iter 248: sigma_u = 0.0541, loglik = -106301.8484
Iter 249: sigma_u = 0.0541, loglik = -106303.7532
Iter 250: sigma_u = 0.0541, loglik = -106303.8731
Iter 251: sigma_u = 0.0541, loglik = -106307.3142
Iter 252: sigma_u = 0.0540, loglik = -106307.4300
Iter 253: sigma_u = 0.0540, loglik = -106311.8271
Iter 254: sigma_u = 0.0540, loglik = -106311.9380
Iter 255: sigma_u = 0.0540, loglik = -106312.3384
Iter 256: sigma_u = 0.0540, loglik = -106312.5245
Iter 257: sigma_u = 0.0540, loglik = -106312.8207
Iter 258: sigma_u = 0.0540, loglik = -106313.0014
Iter 259: sigma_u = 0.0540, loglik = -106313.3006
Iter 260: sigma_u = 0.0540, loglik = -106313.4772
Iter 261: sigma_u = 0.0540, loglik = -106313.7871
Iter 262: sigma_u = 0.0540, loglik = -106313.9582
Iter 263: sigma_u = 0.0540, loglik = -106314.2745
Iter 264: sigma_u = 0.0540, loglik = -106314.4429
Iter 265: sigma_u = 0.0540, loglik = -106314.7720
Iter 266: sigma_u = 0.0540, loglik = -106314.9344
Iter 267: sigma_u = 0.0540, loglik = -106315.2802
Iter 268: sigma_u = 0.0540, loglik = -106315.4368
Iter 269: sigma_u = 0.0540, loglik = -106315.7999
Iteration 269: beta norm = 2.211544160085024, sigma_u = 0.0540
Iter 270: sigma_u = 0.0540, loglik = -106315.9522
Iter 271: sigma_u = 0.0540, loglik = -106316.3396
Iter 272: sigma_u = 0.0540, loglik = -106316.4864
Iter 273: sigma_u = 0.0540, loglik = -106316.9064
Iter 274: sigma_u = 0.0540, loglik = -106317.0469
Iter 275: sigma_u = 0.0540, loglik = -106317.5258
Iter 276: sigma_u = 0.0540, loglik = -106317.6599
Iter 277: sigma_u = 0.0540, loglik = -106318.2280
Iter 278: sigma_u = 0.0539, loglik = -106318.3539
Iter 279: sigma_u = 0.0539, loglik = -106319.0404
Iter 280: sigma_u = 0.0539, loglik = -106319.1584
Iter 281: sigma_u = 0.0539, loglik = -106320.0466
Iter 282: sigma_u = 0.0539, loglik = -106320.1582
Iter 283: sigma_u = 0.0539, loglik = -106321.5014
Iter 284: sigma_u = 0.0539, loglik = -106321.6052
Iter 285: sigma_u = 0.0539, loglik = -106324.0556
Iter 286: sigma_u = 0.0539, loglik = -106324.1552
Iter 287: sigma_u = 0.0539, loglik = -106326.9753
Iter 288: sigma_u = 0.0539, loglik = -106327.0759
Iter 289: sigma_u = 0.0539, loglik = -106327.3237
Iter 290: sigma_u = 0.0539, loglik = -106327.4992
Iter 291: sigma_u = 0.0539, loglik = -106327.7240
Iter 292: sigma_u = 0.0539, loglik = -106327.8981
Iter 293: sigma_u = 0.0538, loglik = -106328.1184
Iter 294: sigma_u = 0.0538, loglik = -106328.2939
Iter 295: sigma_u = 0.0538, loglik = -106328.5093
Iter 296: sigma_u = 0.0538, loglik = -106328.6874
Iter 297: sigma_u = 0.0538, loglik = -106328.8970
Iter 298: sigma_u = 0.0538, loglik = -106329.0767
Iter 299: sigma_u = 0.0538, loglik = -106329.2817
Iter 300: sigma_u = 0.0538, loglik = -106329.4653
Iter 301: sigma_u = 0.0538, loglik = -106329.6619
Iter 302: sigma_u = 0.0538, loglik = -106329.8492
Iter 303: sigma_u = 0.0538, loglik = -106330.0399
Iter 304: sigma_u = 0.0538, loglik = -106330.2363
Iter 305: sigma_u = 0.0538, loglik = -106330.4178
Iter 306: sigma_u = 0.0538, loglik = -106330.6292
Iter 307: sigma_u = 0.0538, loglik = -106330.7994
Iter 308: sigma_u = 0.0538, loglik = -106331.0137
Iter 309: sigma_u = 0.0538, loglik = -106331.1776
Iter 310: sigma_u = 0.0538, loglik = -106331.4087
Iter 311: sigma_u = 0.0538, loglik = -106331.5635
Iter 312: sigma_u = 0.0538, loglik = -106331.8136
Iter 313: sigma_u = 0.0538, loglik = -106331.9587
Iter 314: sigma_u = 0.0538, loglik = -106332.2396
Iter 315: sigma_u = 0.0538, loglik = -106332.3740
Iter 316: sigma_u = 0.0538, loglik = -106332.7256
Iter 317: sigma_u = 0.0538, loglik = -106332.8465
Iter 318: sigma_u = 0.0538, loglik = -106333.3950
Iter 319: sigma_u = 0.0538, loglik = -106333.5020
Iter 320: sigma_u = 0.0538, loglik = -106334.6901
Iter 321: sigma_u = 0.0537, loglik = -106334.7863
Iter 322: sigma_u = 0.0537, loglik = -106339.2846
Iter 323: sigma_u = 0.0537, loglik = -106339.3950
Iter 324: sigma_u = 0.0537, loglik = -106339.9536
Iter 325: sigma_u = 0.0537, loglik = -106340.0500
Iter 326: sigma_u = 0.0537, loglik = -106340.8645
Iter 327: sigma_u = 0.0537, loglik = -106340.9673
Iter 328: sigma_u = 0.0537, loglik = -106341.6084
Iter 329: sigma_u = 0.0537, loglik = -106341.7074

Iter 330: sigma_u = 0.0537, loglik = -106342.0712
Iter 331: sigma_u = 0.0537, loglik = -106342.1878
Iter 332: sigma_u = 0.0537, loglik = -106342.5483
Iter 333: sigma_u = 0.0537, loglik = -106342.6508
Iter 334: sigma_u = 0.0537, loglik = -106343.1761
Iter 335: sigma_u = 0.0537, loglik = -106343.2710
Iter 336: sigma_u = 0.0537, loglik = -106344.3735
Iter 337: sigma_u = 0.0537, loglik = -106344.4563
Iter 338: sigma_u = 0.0537, loglik = -106346.3651
Iter 339: sigma_u = 0.0537, loglik = -106346.5758
Iter 340: sigma_u = 0.0537, loglik = -106346.7254
Iter 341: sigma_u = 0.0537, loglik = -106346.8849
Iter 342: sigma_u = 0.0536, loglik = -106347.0408
Iter 343: sigma_u = 0.0536, loglik = -106347.1931
Iter 344: sigma_u = 0.0536, loglik = -106347.3530
Iter 345: sigma_u = 0.0536, loglik = -106347.5003
Iter 346: sigma_u = 0.0536, loglik = -106347.6668
Iter 347: sigma_u = 0.0536, loglik = -106347.8085
Iter 348: sigma_u = 0.0536, loglik = -106347.9821
Iter 349: sigma_u = 0.0536, loglik = -106348.1160
Iter 350: sigma_u = 0.0536, loglik = -106348.3007
Iter 351: sigma_u = 0.0536, loglik = -106348.4272
Iter 352: sigma_u = 0.0536, loglik = -106348.6283
Iter 353: sigma_u = 0.0536, loglik = -106348.7485
Iter 354: sigma_u = 0.0536, loglik = -106348.9737
Iter 355: sigma_u = 0.0536, loglik = -106349.0858
Iter 356: sigma_u = 0.0536, loglik = -106349.3563
Iter 357: sigma_u = 0.0536, loglik = -106349.4583
Iter 358: sigma_u = 0.0536, loglik = -106349.8083
Iter 359: sigma_u = 0.0536, loglik = -106349.9009
Iter 360: sigma_u = 0.0536, loglik = -106350.4430
Iter 361: sigma_u = 0.0536, loglik = -106350.5266
Iter 362: sigma_u = 0.0536, loglik = -106351.8854
Iter 363: sigma_u = 0.0536, loglik = -106351.9618
Iter 364: sigma_u = 0.0536, loglik = -106355.6138
Iter 365: sigma_u = 0.0536, loglik = -106355.7037
Iter 366: sigma_u = 0.0536, loglik = -106355.9867
Iter 367: sigma_u = 0.0536, loglik = -106356.0760
Iter 368: sigma_u = 0.0536, loglik = -106356.3487
Iter 369: sigma_u = 0.0535, loglik = -106356.4362
Iter 370: sigma_u = 0.0535, loglik = -106356.7538
Iter 371: sigma_u = 0.0535, loglik = -106356.8351
Iter 372: sigma_u = 0.0535, loglik = -106357.2027
Iter 373: sigma_u = 0.0535, loglik = -106357.2810
Iter 374: sigma_u = 0.0535, loglik = -106357.7640
Iter 375: sigma_u = 0.0535, loglik = -106357.8369
Iter 376: sigma_u = 0.0535, loglik = -106358.4826
Iter 377: sigma_u = 0.0535, loglik = -106358.5508
Iter 378: sigma_u = 0.0535, loglik = -106359.6929
Iter 379: sigma_u = 0.0535, loglik = -106359.7567
Iter 380: sigma_u = 0.0535, loglik = -106361.6226
Iter 381: sigma_u = 0.0535, loglik = -106361.6800
Iter 382: sigma_u = 0.0535, loglik = -106362.0631
Iter 383: sigma_u = 0.0535, loglik = -106362.1760
Iter 384: sigma_u = 0.0535, loglik = -106362.3187
Iter 385: sigma_u = 0.0535, loglik = -106362.4311
Iter 386: sigma_u = 0.0535, loglik = -106362.5702
Iter 387: sigma_u = 0.0535, loglik = -106362.6888
Iter 388: sigma_u = 0.0535, loglik = -106362.8209
Iter 389: sigma_u = 0.0535, loglik = -106362.9423
Iter 390: sigma_u = 0.0535, loglik = -106363.0702
Iter 391: sigma_u = 0.0535, loglik = -106363.1935
Iter 392: sigma_u = 0.0535, loglik = -106363.3182
Iter 393: sigma_u = 0.0535, loglik = -106363.4442
Iter 394: sigma_u = 0.0535, loglik = -106363.5625
Iter 395: sigma_u = 0.0535, loglik = -106363.6925
Iter 396: sigma_u = 0.0535, loglik = -106363.8048
Iter 397: sigma_u = 0.0535, loglik = -106363.9436
Iter 398: sigma_u = 0.0535, loglik = -106364.0514
Iter 399: sigma_u = 0.0535, loglik = -106364.1969
Iter 400: sigma_u = 0.0535, loglik = -106364.2996
Iter 401: sigma_u = 0.0535, loglik = -106364.4582
Iter 402: sigma_u = 0.0535, loglik = -106364.5544
Iter 403: sigma_u = 0.0535, loglik = -106364.7331
Iter 404: sigma_u = 0.0535, loglik = -106364.8212
Iter 405: sigma_u = 0.0535, loglik = -106365.0430
Iter 406: sigma_u = 0.0535, loglik = -106365.1231
Iter 407: sigma_u = 0.0535, loglik = -106365.4080
Iter 408: sigma_u = 0.0535, loglik = -106365.4808
Iter 409: sigma_u = 0.0534, loglik = -106365.9970
Iter 410: sigma_u = 0.0534, loglik = -106366.0625
Iter 411: sigma_u = 0.0534, loglik = -106367.6988
Iter 412: sigma_u = 0.0534, loglik = -106367.7568
Iter 413: sigma_u = 0.0534, loglik = -106369.3046
Iter 414: sigma_u = 0.0534, loglik = -106369.3771
Iter 415: sigma_u = 0.0534, loglik = -106369.5570
Iter 416: sigma_u = 0.0534, loglik = -106369.6445
Iter 417: sigma_u = 0.0534, loglik = -106369.7871
Iter 418: sigma_u = 0.0534, loglik = -106369.8736
Iter 419: sigma_u = 0.0534, loglik = -106370.0249
Iter 420: sigma_u = 0.0534, loglik = -106370.1089
Iter 421: sigma_u = 0.0534, loglik = -106370.2650
Iter 422: sigma_u = 0.0534, loglik = -106370.3495
Iter 423: sigma_u = 0.0534, loglik = -106370.5082
Iter 424: sigma_u = 0.0534, loglik = -106370.5903
Iter 425: sigma_u = 0.0534, loglik = -106370.7557
Iter 426: sigma_u = 0.0534, loglik = -106370.8338
Iter 427: sigma_u = 0.0534, loglik = -106371.0054
Iter 428: sigma_u = 0.0534, loglik = -106371.0826
Iter 429: sigma_u = 0.0534, loglik = -106371.2661
Iter 430: sigma_u = 0.0534, loglik = -106371.3402
Iter 431: sigma_u = 0.0534, loglik = -106371.5372
Iter 432: sigma_u = 0.0534, loglik = -106371.6096
Iter 433: sigma_u = 0.0534, loglik = -106371.8221
Iter 434: sigma_u = 0.0534, loglik = -106371.8887
Iter 435: sigma_u = 0.0534, loglik = -106372.1334
Iter 436: sigma_u = 0.0534, loglik = -106372.1973
Iter 437: sigma_u = 0.0534, loglik = -106372.5031
Iter 438: sigma_u = 0.0534, loglik = -106372.5632
Iter 439: sigma_u = 0.0534, loglik = -106372.9764
Iter 440: sigma_u = 0.0534, loglik = -106373.0319
Iter 441: sigma_u = 0.0534, loglik = -106373.5842
Iter 442: sigma_u = 0.0534, loglik = -106373.6378
Iter 443: sigma_u = 0.0534, loglik = -106374.6085
Iter 444: sigma_u = 0.0533, loglik = -106374.6566
Iter 445: sigma_u = 0.0533, loglik = -106375.6898
Iter 446: sigma_u = 0.0533, loglik = -106375.7601
Iter 447: sigma_u = 0.0533, loglik = -106375.8958
Iter 448: sigma_u = 0.0533, loglik = -106375.9779
Iter 449: sigma_u = 0.0533, loglik = -106376.1004
Iter 450: sigma_u = 0.0533, loglik = -106376.1838
Iter 451: sigma_u = 0.0533, loglik = -106376.3035
Iter 452: sigma_u = 0.0533, loglik = -106376.3845
Iter 453: sigma_u = 0.0533, loglik = -106376.5085
Iter 454: sigma_u = 0.0533, loglik = -106376.5888
Iter 455: sigma_u = 0.0533, loglik = -106376.7119
Iter 456: sigma_u = 0.0533, loglik = -106376.7908
Iter 457: sigma_u = 0.0533, loglik = -106376.9163
Iter 458: sigma_u = 0.0533, loglik = -106376.9943
Iter 459: sigma_u = 0.0533, loglik = -106377.1265
Iter 460: sigma_u = 0.0533, loglik = -106377.2005
Iter 461: sigma_u = 0.0533, loglik = -106377.3368
Iter 462: sigma_u = 0.0533, loglik = -106377.4127
Iter 463: sigma_u = 0.0533, loglik = -106377.5468
Iter 464: sigma_u = 0.0533, loglik = -106377.6191
Iter 465: sigma_u = 0.0533, loglik = -106377.7533
Iter 466: sigma_u = 0.0533, loglik = -106377.8235
Iter 467: sigma_u = 0.0533, loglik = -106377.9644
Iter 468: sigma_u = 0.0533, loglik = -106378.0352
Iter 469: sigma_u = 0.0533, loglik = -106378.1797
Iter 470: sigma_u = 0.0533, loglik = -106378.2481
Iter 471: sigma_u = 0.0533, loglik = -106378.3904
Iter 472: sigma_u = 0.0533, loglik = -106378.4586
Iter 473: sigma_u = 0.0533, loglik = -106378.6102
Iter 474: sigma_u = 0.0533, loglik = -106378.6740
Iter 475: sigma_u = 0.0533, loglik = -106378.8383
Iter 476: sigma_u = 0.0533, loglik = -106378.9007
Iter 477: sigma_u = 0.0533, loglik = -106379.0679
Iter 478: sigma_u = 0.0533, loglik = -106379.1289
Iter 479: sigma_u = 0.0533, loglik = -106379.3042
Iter 480: sigma_u = 0.0533, loglik = -106379.3646
Iter 481: sigma_u = 0.0533, loglik = -106379.5555
Iter 482: sigma_u = 0.0533, loglik = -106379.6143
Iter 483: sigma_u = 0.0533, loglik = -106379.8302
Iter 484: sigma_u = 0.0533, loglik = -106379.8848
Iter 485: sigma_u = 0.0533, loglik = -106380.1359
Iter 486: sigma_u = 0.0533, loglik = -106380.1887
Iter 487: sigma_u = 0.0533, loglik = -106380.5109
Iter 488: sigma_u = 0.0533, loglik = -106380.5600
Iter 489: sigma_u = 0.0533, loglik = -106380.9588
Iter 490: sigma_u = 0.0533, loglik = -106381.0061
Iter 491: sigma_u = 0.0533, loglik = -106381.6266
Iter 492: sigma_u = 0.0533, loglik = -106381.6694
Iter 493: sigma_u = 0.0533, loglik = -106382.7517

Iter 494: sigma_u = 0.0533, loglik = -106382.7969
Iter 495: sigma_u = 0.0533, loglik = -106383.2212
Iter 496: sigma_u = 0.0533, loglik = -106383.2747
Iter 497: sigma_u = 0.0533, loglik = -106383.3758
Iter 498: sigma_u = 0.0533, loglik = -106383.4500
Iter 499: sigma_u = 0.0533, loglik = -106383.5499
Iter 500: sigma_u = 0.0533, loglik = -106383.6252
Iter 501: sigma_u = 0.0533, loglik = -106383.7238
Iter 502: sigma_u = 0.0533, loglik = -106383.7961
Iter 503: sigma_u = 0.0533, loglik = -106383.8948
Iter 504: sigma_u = 0.0533, loglik = -106383.9681
Iter 505: sigma_u = 0.0533, loglik = -106384.0630
Iter 506: sigma_u = 0.0533, loglik = -106384.1332
Iter 507: sigma_u = 0.0533, loglik = -106384.2303
Iter 508: sigma_u = 0.0533, loglik = -106384.3029
Iter 509: sigma_u = 0.0533, loglik = -106384.3978
Iter 510: sigma_u = 0.0533, loglik = -106384.4681
Iter 511: sigma_u = 0.0533, loglik = -106384.5652
Iter 512: sigma_u = 0.0533, loglik = -106384.6393
Iter 513: sigma_u = 0.0533, loglik = -106384.7343
Iter 514: sigma_u = 0.0532, loglik = -106384.8054
Iter 515: sigma_u = 0.0532, loglik = -106384.9014
Iter 516: sigma_u = 0.0532, loglik = -106384.9703
Iter 517: sigma_u = 0.0532, loglik = -106385.0665
Iter 518: sigma_u = 0.0532, loglik = -106385.1372
Iter 519: sigma_u = 0.0532, loglik = -106385.2332
Iter 520: sigma_u = 0.0532, loglik = -106385.3022
Iter 521: sigma_u = 0.0532, loglik = -106385.3996
Iter 522: sigma_u = 0.0532, loglik = -106385.4668
Iter 523: sigma_u = 0.0532, loglik = -106385.5634
Iter 524: sigma_u = 0.0532, loglik = -106385.6323
Iter 525: sigma_u = 0.0532, loglik = -106385.7283
Iter 526: sigma_u = 0.0532, loglik = -106385.7948
Iter 527: sigma_u = 0.0532, loglik = -106385.8913
Iter 528: sigma_u = 0.0532, loglik = -106385.9571
Iter 529: sigma_u = 0.0532, loglik = -106386.0537
Iter 530: sigma_u = 0.0532, loglik = -106386.1222
Iter 531: sigma_u = 0.0532, loglik = -106386.2157
Iter 532: sigma_u = 0.0532, loglik = -106386.2842
Iter 533: sigma_u = 0.0532, loglik = -106386.3754
Iter 534: sigma_u = 0.0532, loglik = -106386.4455
Iter 535: sigma_u = 0.0532, loglik = -106386.5351
Iter 536: sigma_u = 0.0532, loglik = -106386.6023
Iter 537: sigma_u = 0.0532, loglik = -106386.6970
Iter 538: sigma_u = 0.0532, loglik = -106386.7614
Iter 539: sigma_u = 0.0532, loglik = -106386.8579
Iter 540: sigma_u = 0.0532, loglik = -106386.9213
Iter 541: sigma_u = 0.0532, loglik = -106387.0170
Iter 542: sigma_u = 0.0532, loglik = -106387.0810
Iter 543: sigma_u = 0.0532, loglik = -106387.1749
Iter 544: sigma_u = 0.0532, loglik = -106387.2395
Iter 545: sigma_u = 0.0532, loglik = -106387.3377
Iter 546: sigma_u = 0.0532, loglik = -106387.4008
Iter 547: sigma_u = 0.0532, loglik = -106387.4973
Iter 548: sigma_u = 0.0532, loglik = -106387.5598
Iter 549: sigma_u = 0.0532, loglik = -106387.6597
Iter 550: sigma_u = 0.0532, loglik = -106387.7225
Iter 551: sigma_u = 0.0532, loglik = -106387.8224
Iter 552: sigma_u = 0.0532, loglik = -106387.8823
Iter 553: sigma_u = 0.0532, loglik = -106387.9862
Iter 554: sigma_u = 0.0532, loglik = -106388.0444
Iter 555: sigma_u = 0.0532, loglik = -106388.1552
Iter 556: sigma_u = 0.0532, loglik = -106388.2096
Iter 557: sigma_u = 0.0532, loglik = -106388.3297
Iter 558: sigma_u = 0.0532, loglik = -106388.3835
Iter 559: sigma_u = 0.0532, loglik = -106388.5119
Iter 560: sigma_u = 0.0532, loglik = -106388.5643
Iter 561: sigma_u = 0.0532, loglik = -106388.7029
Iter 562: sigma_u = 0.0532, loglik = -106388.7512
Iter 563: sigma_u = 0.0532, loglik = -106388.9100
Iter 564: sigma_u = 0.0532, loglik = -106388.9546
Iter 565: sigma_u = 0.0532, loglik = -106389.1634
Iter 566: sigma_u = 0.0532, loglik = -106389.2051
Iter 567: sigma_u = 0.0532, loglik = -106389.4724
Iter 568: sigma_u = 0.0532, loglik = -106389.5118
Iter 569: sigma_u = 0.0532, loglik = -106389.9368
Iter 570: sigma_u = 0.0532, loglik = -106389.9739
Iter 571: sigma_u = 0.0532, loglik = -106390.7209
Iter 572: sigma_u = 0.0532, loglik = -106390.7558
Iter 573: sigma_u = 0.0532, loglik = -106392.0559
Iter 574: sigma_u = 0.0532, loglik = -106392.0886
Iter 575: sigma_u = 0.0532, loglik = -106392.2527
Iter 576: sigma_u = 0.0532, loglik = -106392.3089
Iter 577: sigma_u = 0.0532, loglik = -106392.3971
Iter 578: sigma_u = 0.0532, loglik = -106392.4512
Iter 579: sigma_u = 0.0532, loglik = -106392.5429
Iter 580: sigma_u = 0.0532, loglik = -106392.5943
Iter 581: sigma_u = 0.0532, loglik = -106392.6889
Iter 582: sigma_u = 0.0532, loglik = -106392.7385
Iter 583: sigma_u = 0.0532, loglik = -106392.8405
Iter 584: sigma_u = 0.0532, loglik = -106392.8886
Iter 585: sigma_u = 0.0532, loglik = -106392.9960
Iter 586: sigma_u = 0.0532, loglik = -106393.0427
Iter 587: sigma_u = 0.0532, loglik = -106393.1506
Iter 588: sigma_u = 0.0532, loglik = -106393.1968
Iter 589: sigma_u = 0.0532, loglik = -106393.3092
Iter 590: sigma_u = 0.0532, loglik = -106393.3528
Iter 591: sigma_u = 0.0532, loglik = -106393.4830
Iter 592: sigma_u = 0.0532, loglik = -106393.5247
Iter 593: sigma_u = 0.0532, loglik = -106393.6808
Iter 594: sigma_u = 0.0532, loglik = -106393.7202
Iter 595: sigma_u = 0.0532, loglik = -106393.8894
Iter 596: sigma_u = 0.0532, loglik = -106393.9276
Iter 597: sigma_u = 0.0532, loglik = -106394.1364
Iter 598: sigma_u = 0.0531, loglik = -106394.1729
Iter 599: sigma_u = 0.0531, loglik = -106394.4577
Iter 600: sigma_u = 0.0531, loglik = -106394.4912
Iter 601: sigma_u = 0.0531, loglik = -106394.9440
Iter 602: sigma_u = 0.0531, loglik = -106394.9750
Iter 603: sigma_u = 0.0531, loglik = -106395.6060
Iter 604: sigma_u = 0.0531, loglik = -106395.6345
Iter 605: sigma_u = 0.0531, loglik = -106396.0171
Iter 606: sigma_u = 0.0531, loglik = -106396.0734
Iter 607: sigma_u = 0.0531, loglik = -106396.1349
Iter 608: sigma_u = 0.0531, loglik = -106396.1949
Iter 609: sigma_u = 0.0531, loglik = -106396.2568
Iter 610: sigma_u = 0.0531, loglik = -106396.3204
Iter 611: sigma_u = 0.0531, loglik = -106396.3773
Iter 612: sigma_u = 0.0531, loglik = -106396.4446
Iter 613: sigma_u = 0.0531, loglik = -106396.4980
Iter 614: sigma_u = 0.0531, loglik = -106396.5659
Iter 615: sigma_u = 0.0531, loglik = -106396.6179
Iter 616: sigma_u = 0.0531, loglik = -106396.6953
Iter 617: sigma_u = 0.0531, loglik = -106396.7418
Iter 618: sigma_u = 0.0531, loglik = -106396.8388
Iter 619: sigma_u = 0.0531, loglik = -106396.8799
Iter 620: sigma_u = 0.0531, loglik = -106397.0123
Iter 621: sigma_u = 0.0531, loglik = -106397.0493
Iter 622: sigma_u = 0.0531, loglik = -106397.2603
Iter 623: sigma_u = 0.0531, loglik = -106397.2922
Iter 624: sigma_u = 0.0531, loglik = -106397.8893
Iter 625: sigma_u = 0.0531, loglik = -106397.9189
Iter 626: sigma_u = 0.0531, loglik = -106399.1842
Iter 627: sigma_u = 0.0531, loglik = -106399.2102
Iter 628: sigma_u = 0.0531, loglik = -106399.9824
Iter 629: sigma_u = 0.0531, loglik = -106400.0073
Iter 630: sigma_u = 0.0531, loglik = -106400.6469
Iter 631: sigma_u = 0.0531, loglik = -106400.6896
Iter 632: sigma_u = 0.0531, loglik = -106400.7451
✅ Converged at iteration 633
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            -1.24      -1.215846    -1.216063
1             1.17       1.160523     1.160728
2            -1.04      -1.059171    -1.059347
3             0.97       0.969034     0.969218
4             0.25       0.226600     0.053079



Time taken 3.9367352684338885 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.6919, loglik = -25318.0010
Iter 1: sigma_u = 0.6420, loglik = -26650.7380
Iter 2: sigma_u = 0.5962, loglik = -28192.9264
Iter 3: sigma_u = 0.5540, loglik = -29951.0178
Iter 4: sigma_u = 0.5154, loglik = -31940.2306
Iter 5: sigma_u = 0.4800, loglik = -34174.3349
Iter 6: sigma_u = 0.4477, loglik = -36660.6067
Iter 7: sigma_u = 0.4183, loglik = -39395.6279
Iter 8: sigma_u = 0.3916, loglik = -42360.0402
Iter 9: sigma_u = 0.3675, loglik = -45514.4225
Iter 10: sigma_u = 0.3458, loglik = -48798.2073
Iter 11: sigma_u = 0.3266, loglik = -52133.0300
Iter 12: sigma_u = 0.3095, loglik = -55430.8634
Iter 13: sigma_u = 0.2947, loglik = -58604.9528
Iter 14: sigma_u = 0.2818, loglik = -61580.8355
Iter 15: sigma_u = 0.2707, loglik = -64304.0568
Iter 16: sigma_u = 0.2613, loglik = -66743.1528
Iter 17: sigma_u = 0.2533, loglik = -68888.2474
Iter 18: sigma_u = 0.2466, loglik = -70746.7184
Iter 19: sigma_u = 0.2410, loglik = -72337.5630
Iter 20: sigma_u = 0.2363, loglik = -73686.8999
Iter 21: sigma_u = 0.2324, loglik = -74823.1641
Iter 22: sigma_u = 0.2292, loglik = -75774.6211
Iter 23: sigma_u = 0.2265, loglik = -76568.2007
Iter 24: sigma_u = 0.2243, loglik = -77227.9176
Iter 25: sigma_u = 0.2225, loglik = -77774.9435
Iter 26: sigma_u = 0.2210, loglik = -78221.6174
Iter 27: sigma_u = 0.2198, loglik = -78595.2149
Iter 28: sigma_u = 0.2188, loglik = -78900.9294
Iter 29: sigma_u = 0.2179, loglik = -79152.6652
Iter 30: sigma_u = 0.2172, loglik = -79360.6494
Iter 31: sigma_u = 0.2167, loglik = -79532.7737
Iter 32: sigma_u = 0.2162, loglik = -79675.2503
Iter 33: sigma_u = 0.2158, loglik = -79793.1855
Iter 34: sigma_u = 0.2155, loglik = -79890.8253
Iter 35: sigma_u = 0.2152, loglik = -79971.9410
Iter 36: sigma_u = 0.2150, loglik = -80039.0483
Iter 37: sigma_u = 0.2148, loglik = -80094.5081
Iter 38: sigma_u = 0.2146, loglik = -80143.1636
Iter 39: sigma_u = 0.2145, loglik = -80180.3048
Iter 40: sigma_u = 0.2144, loglik = -80213.2086
Iter 41: sigma_u = 0.2143, loglik = -80238.1378
Iter 42: sigma_u = 0.2143, loglik = -80260.3963
Iter 43: sigma_u = 0.2142, loglik = -80274.4121
Iter 44: sigma_u = 0.2142, loglik = -80286.0755
Iter 45: sigma_u = 0.2141, loglik = -80295.1597
Iter 46: sigma_u = 0.2141, loglik = -80304.0969
Iter 47: sigma_u = 0.2141, loglik = -80310.7228
Iter 48: sigma_u = 0.2141, loglik = -80317.5141
Iter 49: sigma_u = 0.2140, loglik = -80322.4388
Iter 50: sigma_u = 0.2140, loglik = -80327.5476
Iter 51: sigma_u = 0.2140, loglik = -80331.2891
Iter 52: sigma_u = 0.2140, loglik = -80335.1426
Iter 53: sigma_u = 0.2140, loglik = -80337.9113
Iter 54: sigma_u = 0.2140, loglik = -80340.8739
Iter 55: sigma_u = 0.2140, loglik = -80342.9822
Iter 56: sigma_u = 0.2140, loglik = -80345.2424
Iter 57: sigma_u = 0.2140, loglik = -80346.8112
Iter 58: sigma_u = 0.2140, loglik = -80348.4856
Iter 59: sigma_u = 0.2139, loglik = -80349.6559
Iter 60: sigma_u = 0.2139, loglik = -80350.9241
Iter 61: sigma_u = 0.2139, loglik = -80351.8795
✅ Converged at iteration 62
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              0.5       0.518098     0.518666
1              0.5       0.495437     0.495259
2             -1.2      -1.216457    -1.216541
3              0.8       0.772839     0.213941



Time taken 0.6020685990651449 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.0178, loglik = -14628.4922
Iter 1: sigma_u = 0.9678, loglik = -14988.7013
Iter 2: sigma_u = 0.9179, loglik = -15517.8589
Iter 3: sigma_u = 0.8701, loglik = -16105.1151
Iter 4: sigma_u = 0.8247, loglik = -16751.5347
Iter 5: sigma_u = 0.7818, loglik = -17464.2610
Iter 6: sigma_u = 0.7413, loglik = -18250.2747
Iter 7: sigma_u = 0.7032, loglik = -19115.8228
Iter 8: sigma_u = 0.6672, loglik = -20067.3459
Iter 9: sigma_u = 0.6333, loglik = -21111.1943
Iter 10: sigma_u = 0.6015, loglik = -22253.6042
Iter 11: sigma_u = 0.5714, loglik = -23500.4628
Iter 12: sigma_u = 0.5432, loglik = -24857.7011
Iter 13: sigma_u = 0.5167, loglik = -26329.0993
Iter 14: sigma_u = 0.4918, loglik = -27917.4328
Iter 15: sigma_u = 0.4685, loglik = -29623.2634
Iter 16: sigma_u = 0.4467, loglik = -31444.1671
Iter 17: sigma_u = 0.4264, loglik = -33373.7160
Iter 18: sigma_u = 0.4075, loglik = -35400.6082
Iter 19: sigma_u = 0.3899, loglik = -37507.9491
Iter 20: sigma_u = 0.3737, loglik = -39673.3752
Iter 21: sigma_u = 0.3588, loglik = -41869.5998
Iter 22: sigma_u = 0.3451, loglik = -44066.1275
Iter 23: sigma_u = 0.3326, loglik = -46231.4054
Iter 24: sigma_u = 0.3214, loglik = -48336.6452
Iter 25: sigma_u = 0.3112, loglik = -50353.0143
Iter 26: sigma_u = 0.3021, loglik = -52259.6329
Iter 27: sigma_u = 0.2939, loglik = -54041.2733
Iter 28: sigma_u = 0.2867, loglik = -55688.0994
Iter 29: sigma_u = 0.2802, loglik = -57193.8976
Iter 30: sigma_u = 0.2745, loglik = -58562.1630
Iter 31: sigma_u = 0.2695, loglik = -59797.2887
Iter 32: sigma_u = 0.2651, loglik = -60906.2842
Iter 33: sigma_u = 0.2611, loglik = -61897.5503
Iter 34: sigma_u = 0.2577, loglik = -62780.3770
Iter 35: sigma_u = 0.2547, loglik = -63564.2292
Iter 36: sigma_u = 0.2520, loglik = -64258.5950
Iter 37: sigma_u = 0.2497, loglik = -64872.4537
Iter 38: sigma_u = 0.2476, loglik = -65414.2448
Iter 39: sigma_u = 0.2458, loglik = -65891.8337
Iter 40: sigma_u = 0.2442, loglik = -66312.3276
Iter 41: sigma_u = 0.2428, loglik = -66682.3141
Iter 42: sigma_u = 0.2416, loglik = -67007.5844
Iter 43: sigma_u = 0.2406, loglik = -67293.3686
Iter 44: sigma_u = 0.2396, loglik = -67544.3891
Iter 45: sigma_u = 0.2388, loglik = -67764.7493
Iter 46: sigma_u = 0.2381, loglik = -67958.1809
Iter 47: sigma_u = 0.2375, loglik = -68127.9416
Iter 48: sigma_u = 0.2369, loglik = -68276.8205
Iter 49: sigma_u = 0.2365, loglik = -68407.2147
Iter 50: sigma_u = 0.2361, loglik = -68512.3771
Iter 51: sigma_u = 0.2357, loglik = -68607.8949
Iter 52: sigma_u = 0.2354, loglik = -68692.5623
Iter 53: sigma_u = 0.2351, loglik = -68767.4130
Iter 54: sigma_u = 0.2349, loglik = -68833.5578
Iter 55: sigma_u = 0.2347, loglik = -68892.0173
Iter 56: sigma_u = 0.2345, loglik = -68943.6471
Iter 57: sigma_u = 0.2343, loglik = -68989.3091
Iter 58: sigma_u = 0.2341, loglik = -69028.0594
Iter 59: sigma_u = 0.2340, loglik = -69064.1920
Iter 60: sigma_u = 0.2339, loglik = -69095.4933
Iter 61: sigma_u = 0.2338, loglik = -69123.9034
Iter 62: sigma_u = 0.2337, loglik = -69145.0711
Iter 63: sigma_u = 0.2337, loglik = -69160.7639
Iter 64: sigma_u = 0.2336, loglik = -69172.6822
Iter 65: sigma_u = 0.2336, loglik = -69188.5190
Iter 66: sigma_u = 0.2335, loglik = -69198.1470
Iter 67: sigma_u = 0.2335, loglik = -69212.2849
Iter 68: sigma_u = 0.2334, loglik = -69220.3159
Iter 69: sigma_u = 0.2334, loglik = -69232.1626
Iter 70: sigma_u = 0.2334, loglik = -69238.9248
Iter 71: sigma_u = 0.2333, loglik = -69248.7781
Iter 72: sigma_u = 0.2333, loglik = -69254.3763
Iter 73: sigma_u = 0.2333, loglik = -69262.8508
Iter 74: sigma_u = 0.2333, loglik = -69267.6452
Iter 75: sigma_u = 0.2332, loglik = -69274.6507
Iter 76: sigma_u = 0.2332, loglik = -69278.6328
Iter 77: sigma_u = 0.2332, loglik = -69284.5467
Iter 78: sigma_u = 0.2332, loglik = -69287.9026
Iter 79: sigma_u = 0.2332, loglik = -69292.9715
Iter 80: sigma_u = 0.2332, loglik = -69295.7315
Iter 81: sigma_u = 0.2331, loglik = -69299.8694
Iter 82: sigma_u = 0.2331, loglik = -69302.1555
Iter 83: sigma_u = 0.2331, loglik = -69305.6673
Iter 84: sigma_u = 0.2331, loglik = -69307.6628
Iter 85: sigma_u = 0.2331, loglik = -69310.5147
Iter 86: sigma_u = 0.2331, loglik = -69312.1779
Iter 87: sigma_u = 0.2331, loglik = -69314.6477
Iter 88: sigma_u = 0.2331, loglik = -69315.9992
Iter 89: sigma_u = 0.2331, loglik = -69318.1383
Iter 90: sigma_u = 0.2331, loglik = -69319.2928
Iter 91: sigma_u = 0.2331, loglik = -69321.0892
Iter 92: sigma_u = 0.2331, loglik = -69322.0578
Iter 93: sigma_u = 0.2331, loglik = -69323.4961
Iter 94: sigma_u = 0.2330, loglik = -69324.2949
✅ Converged at iteration 95
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              1.5       1.464638     1.469740
1             -0.8      -0.822129    -0.823051
2              1.3       1.339157     1.341286
3              0.8       0.788510     0.233045



Time taken 1.1789812723795572 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 4.1650, loglik = -5045.9117
Iter 1: sigma_u = 3.6760, loglik = -5252.1492
Iter 2: sigma_u = 3.3609, loglik = -5384.0853
Iter 3: sigma_u = 3.1407, loglik = -5476.3223
Iter 4: sigma_u = 2.9758, loglik = -5546.5539
Iter 5: sigma_u = 2.8452, loglik = -5604.4039
Iter 6: sigma_u = 2.7370, loglik = -5655.1340
Iter 7: sigma_u = 2.6441, loglik = -5701.7610
Iter 8: sigma_u = 2.5621, loglik = -5746.1043
Iter 9: sigma_u = 2.4880, loglik = -5789.3549
Iter 10: sigma_u = 2.4200, loglik = -5832.3308
Iter 11: sigma_u = 2.3567, loglik = -5875.6198
Iter 12: sigma_u = 2.2971, loglik = -5919.6901
Iter 13: sigma_u = 2.2405, loglik = -5964.9050
Iter 14: sigma_u = 2.1863, loglik = -6011.5625
Iter 15: sigma_u = 2.1343, loglik = -6059.9134
Iter 16: sigma_u = 2.0841, loglik = -6110.1715
Iter 17: sigma_u = 2.0355, loglik = -6162.5224
Iter 18: sigma_u = 1.9883, loglik = -6217.1363
Iter 19: sigma_u = 1.9424, loglik = -6274.1674
Iter 20: sigma_u = 1.8977, loglik = -6333.7629
Iter 21: sigma_u = 1.8542, loglik = -6396.0654
Iter 22: sigma_u = 1.8118, loglik = -6461.2188
Iter 23: sigma_u = 1.7704, loglik = -6529.3635
Iter 24: sigma_u = 1.7300, loglik = -6600.6464
Iter 25: sigma_u = 1.6905, loglik = -6675.2142
Iter 26: sigma_u = 1.6520, loglik = -6753.2186
Iter 27: sigma_u = 1.6144, loglik = -6834.8184
Iter 28: sigma_u = 1.5777, loglik = -6920.1761
Iter 29: sigma_u = 1.5418, loglik = -7009.4614
Iter 30: sigma_u = 1.5068, loglik = -7102.8473
Iter 31: sigma_u = 1.4726, loglik = -7200.5142
Iter 32: sigma_u = 1.4392, loglik = -7302.6509
Iter 33: sigma_u = 1.4065, loglik = -7409.4502
Iter 34: sigma_u = 1.3747, loglik = -7521.1137
Iter 35: sigma_u = 1.3436, loglik = -7637.8517
Iter 36: sigma_u = 1.3132, loglik = -7759.8757
Iter 37: sigma_u = 1.2835, loglik = -7887.4121
Iter 38: sigma_u = 1.2546, loglik = -8020.6900
Iter 39: sigma_u = 1.2263, loglik = -8159.9517
Iter 40: sigma_u = 1.1987, loglik = -8305.4442
Iter 41: sigma_u = 1.1717, loglik = -8457.4184
Iter 42: sigma_u = 1.1454, loglik = -8616.1436
Iter 43: sigma_u = 1.1197, loglik = -8781.8953
Iter 44: sigma_u = 1.0947, loglik = -8954.9525
Iter 45: sigma_u = 1.0702, loglik = -9135.6053
Iter 46: sigma_u = 1.0463, loglik = -9324.1534
Iter 47: sigma_u = 1.0230, loglik = -9520.9083
Iter 48: sigma_u = 1.0002, loglik = -9726.1789
Iter 49: sigma_u = 0.9780, loglik = -9940.2963
Iter 50: sigma_u = 0.9563, loglik = -10163.5845
Iter 51: sigma_u = 0.9351, loglik = -10396.3860
Iter 52: sigma_u = 0.9145, loglik = -10639.0476
Iter 53: sigma_u = 0.8943, loglik = -10891.9256
Iter 54: sigma_u = 0.8747, loglik = -11155.3791
Iter 55: sigma_u = 0.8555, loglik = -11429.7689
Iter 56: sigma_u = 0.8368, loglik = -11715.4700
Iter 57: sigma_u = 0.8185, loglik = -12012.8531
Iter 58: sigma_u = 0.8007, loglik = -12322.2957
Iter 59: sigma_u = 0.7833, loglik = -12644.1802
Iter 60: sigma_u = 0.7664, loglik = -12978.8913
Iter 61: sigma_u = 0.7499, loglik = -13326.8029
Iter 62: sigma_u = 0.7338, loglik = -13688.2866
Iter 63: sigma_u = 0.7181, loglik = -14063.7351
Iter 64: sigma_u = 0.7027, loglik = -14453.5050
Iter 65: sigma_u = 0.6878, loglik = -14857.9612
Iter 66: sigma_u = 0.6733, loglik = -15277.4629
Iter 67: sigma_u = 0.6591, loglik = -15712.3416
Iter 68: sigma_u = 0.6452, loglik = -16162.9267
Iter 69: sigma_u = 0.6318, loglik = -16629.5188
Iter 70: sigma_u = 0.6186, loglik = -17112.4146
Iter 71: sigma_u = 0.6059, loglik = -17611.8662
Iter 72: sigma_u = 0.5934, loglik = -18128.1088
Iter 73: sigma_u = 0.5813, loglik = -18661.3541
Iter 74: sigma_u = 0.5695, loglik = -19211.7479
Iter 75: sigma_u = 0.5580, loglik = -19779.3995
Iter 76: sigma_u = 0.5468, loglik = -20364.3906
Iter 77: sigma_u = 0.5359, loglik = -20966.7235
Iter 78: sigma_u = 0.5253, loglik = -21586.3554
Iter 79: sigma_u = 0.5150, loglik = -22223.1343
Iter 80: sigma_u = 0.5050, loglik = -22876.8954
Iter 81: sigma_u = 0.4953, loglik = -23547.2968
Iter 82: sigma_u = 0.4858, loglik = -24233.9919
Iter 83: sigma_u = 0.4767, loglik = -24936.4577
Iter 84: sigma_u = 0.4677, loglik = -25654.0885
Iter 85: sigma_u = 0.4591, loglik = -26386.1558
Iter 86: sigma_u = 0.4507, loglik = -27131.8228
Iter 87: sigma_u = 0.4426, loglik = -27890.0701
Iter 88: sigma_u = 0.4347, loglik = -28659.8625
Iter 89: sigma_u = 0.4270, loglik = -29439.8607
Iter 90: sigma_u = 0.4196, loglik = -30228.7503
Iter 91: sigma_u = 0.4125, loglik = -31025.0667
Iter 92: sigma_u = 0.4055, loglik = -31827.1955
Iter 93: sigma_u = 0.3989, loglik = -32633.4574
Iter 94: sigma_u = 0.3924, loglik = -33442.1030
Iter 95: sigma_u = 0.3862, loglik = -34251.3261
Iter 96: sigma_u = 0.3802, loglik = -35059.2384
Iter 97: sigma_u = 0.3744, loglik = -35864.0181
Iter 98: sigma_u = 0.3689, loglik = -36663.7549
Iter 99: sigma_u = 0.3635, loglik = -37456.6512
Iter 100: sigma_u = 0.3584, loglik = -38240.9536
Iter 101: sigma_u = 0.3534, loglik = -39014.9308
Iter 102: sigma_u = 0.3487, loglik = -39776.9469
Iter 103: sigma_u = 0.3442, loglik = -40525.4909
Iter 104: sigma_u = 0.3398, loglik = -41259.1472
Iter 105: sigma_u = 0.3357, loglik = -41976.7143
Iter 106: sigma_u = 0.3317, loglik = -42677.0654
Iter 107: sigma_u = 0.3279, loglik = -43359.2526
Iter 108: sigma_u = 0.3243, loglik = -44022.4445
Iter 109: sigma_u = 0.3209, loglik = -44665.9196
Iter 110: sigma_u = 0.3176, loglik = -45289.1590
Iter 111: sigma_u = 0.3145, loglik = -45891.7342
Iter 112: sigma_u = 0.3115, loglik = -46473.3788
Iter 113: sigma_u = 0.3087, loglik = -47033.9372
Iter 114: sigma_u = 0.3060, loglik = -47573.3444
Iter 115: sigma_u = 0.3034, loglik = -48091.7586
Iter 116: sigma_u = 0.3010, loglik = -48589.2810
Iter 117: sigma_u = 0.2987, loglik = -49066.1792
Iter 118: sigma_u = 0.2965, loglik = -49522.8261
Iter 119: sigma_u = 0.2944, loglik = -49959.5133
Iter 120: sigma_u = 0.2925, loglik = -50376.6987
Iter 121: sigma_u = 0.2906, loglik = -50774.8933
Iter 122: sigma_u = 0.2888, loglik = -51154.6264
Iter 123: sigma_u = 0.2873, loglik = -51516.3987
Iter 124: sigma_u = 0.2857, loglik = -51836.6226
Iter 125: sigma_u = 0.2843, loglik = -52165.3617
Iter 126: sigma_u = 0.2829, loglik = -52455.4499
Iter 127: sigma_u = 0.2817, loglik = -52753.6122
Iter 128: sigma_u = 0.2804, loglik = -53011.8382
Iter 129: sigma_u = 0.2793, loglik = -53281.7717
Iter 130: sigma_u = 0.2781, loglik = -53514.9940
Iter 131: sigma_u = 0.2771, loglik = -53758.9810
Iter 132: sigma_u = 0.2761, loglik = -53969.4214
Iter 133: sigma_u = 0.2752, loglik = -54187.9410
Iter 134: sigma_u = 0.2743, loglik = -54377.6732
Iter 135: sigma_u = 0.2735, loglik = -54574.8176
Iter 136: sigma_u = 0.2728, loglik = -54745.6680
Iter 137: sigma_u = 0.2720, loglik = -54900.0026
Iter 138: sigma_u = 0.2714, loglik = -55068.5968
Iter 139: sigma_u = 0.2708, loglik = -55214.5501
Iter 140: sigma_u = 0.2702, loglik = -55346.8164
Iter 141: sigma_u = 0.2697, loglik = -55469.8255
Iter 142: sigma_u = 0.2692, loglik = -55585.8549
Iter 143: sigma_u = 0.2687, loglik = -55696.0794
Iter 144: sigma_u = 0.2682, loglik = -55800.9822
Iter 145: sigma_u = 0.2678, loglik = -55901.0037
Iter 146: sigma_u = 0.2674, loglik = -55996.3783
Iter 147: sigma_u = 0.2670, loglik = -56087.3543
Iter 148: sigma_u = 0.2666, loglik = -56174.1210
Iter 149: sigma_u = 0.2662, loglik = -56256.8527
Iter 150: sigma_u = 0.2659, loglik = -56335.7168
Iter 151: sigma_u = 0.2656, loglik = -56410.9795
Iter 152: sigma_u = 0.2653, loglik = -56482.7086
Iter 153: sigma_u = 0.2650, loglik = -56551.0977
Iter 154: sigma_u = 0.2647, loglik = -56616.2649
Iter 155: sigma_u = 0.2644, loglik = -56680.9715
Iter 156: sigma_u = 0.2641, loglik = -56742.1968
Iter 157: sigma_u = 0.2639, loglik = -56800.2673
Iter 158: sigma_u = 0.2636, loglik = -56855.3188
Iter 159: sigma_u = 0.2634, loglik = -56907.5457
Iter 160: sigma_u = 0.2632, loglik = -56957.1997
Iter 161: sigma_u = 0.2630, loglik = -57004.3707
Iter 162: sigma_u = 0.2628, loglik = -57049.2307
Iter 163: sigma_u = 0.2626, loglik = -57091.9192
Iter 164: sigma_u = 0.2625, loglik = -57132.5278
Iter 165: sigma_u = 0.2623, loglik = -57171.1501
Iter 166: sigma_u = 0.2621, loglik = -57207.9312
Iter 167: sigma_u = 0.2620, loglik = -57242.9593
Iter 168: sigma_u = 0.2618, loglik = -57276.2790
Iter 169: sigma_u = 0.2617, loglik = -57312.1429
Iter 170: sigma_u = 0.2616, loglik = -57343.3660

Iter 171: sigma_u = 0.2615, loglik = -57368.7503
Iter 172: sigma_u = 0.2614, loglik = -57392.8453
Iter 173: sigma_u = 0.2613, loglik = -57413.9157
Iter 174: sigma_u = 0.2612, loglik = -57435.6292
Iter 175: sigma_u = 0.2611, loglik = -57454.3116
Iteration 175: beta norm = 4.979744279984125, sigma_u = 0.2611
Iter 176: sigma_u = 0.2610, loglik = -57473.9928
Iter 177: sigma_u = 0.2609, loglik = -57490.8665
Iter 178: sigma_u = 0.2609, loglik = -57509.0321
Iter 179: sigma_u = 0.2608, loglik = -57524.5140
Iter 180: sigma_u = 0.2607, loglik = -57541.1424
Iter 181: sigma_u = 0.2607, loglik = -57555.3190
Iter 182: sigma_u = 0.2606, loglik = -57570.6222
Iter 183: sigma_u = 0.2605, loglik = -57583.6735
Iter 184: sigma_u = 0.2605, loglik = -57597.7958
Iter 185: sigma_u = 0.2604, loglik = -57609.8784
Iter 186: sigma_u = 0.2604, loglik = -57622.8956
Iter 187: sigma_u = 0.2603, loglik = -57633.9976
Iter 188: sigma_u = 0.2603, loglik = -57646.0052
Iter 189: sigma_u = 0.2602, loglik = -57656.1627
Iter 190: sigma_u = 0.2602, loglik = -57667.2271
Iter 191: sigma_u = 0.2601, loglik = -57676.7123
Iter 192: sigma_u = 0.2601, loglik = -57686.9369
Iter 193: sigma_u = 0.2601, loglik = -57695.7369
Iter 194: sigma_u = 0.2600, loglik = -57705.1364
Iter 195: sigma_u = 0.2600, loglik = -57713.1437
Iter 196: sigma_u = 0.2599, loglik = -57721.8848
Iter 197: sigma_u = 0.2599, loglik = -57729.2696
Iter 198: sigma_u = 0.2599, loglik = -57737.3475
Iter 199: sigma_u = 0.2598, loglik = -57744.1283
Iter 200: sigma_u = 0.2598, loglik = -57751.5431
Iter 201: sigma_u = 0.2598, loglik = -57757.9400
Iter 202: sigma_u = 0.2598, loglik = -57764.7868
Iter 203: sigma_u = 0.2597, loglik = -57770.5913
Iter 204: sigma_u = 0.2597, loglik = -57776.9156
Iter 205: sigma_u = 0.2597, loglik = -57782.2870
Iter 206: sigma_u = 0.2597, loglik = -57788.1603
Iter 207: sigma_u = 0.2596, loglik = -57793.1251
Iter 208: sigma_u = 0.2596, loglik = -57798.5419
Iter 209: sigma_u = 0.2596, loglik = -57803.0315
Iter 210: sigma_u = 0.2596, loglik = -57807.9649
Iter 211: sigma_u = 0.2596, loglik = -57812.0338
Iter 212: sigma_u = 0.2595, loglik = -57816.5885
Iter 213: sigma_u = 0.2595, loglik = -57820.5880
Iter 214: sigma_u = 0.2595, loglik = -57824.7690
Iter 215: sigma_u = 0.2595, loglik = -57828.3709
Iter 216: sigma_u = 0.2595, loglik = -57832.2851
Iter 217: sigma_u = 0.2595, loglik = -57835.6333
Iter 218: sigma_u = 0.2594, loglik = -57839.2094
Iter 219: sigma_u = 0.2594, loglik = -57842.3593
Iter 220: sigma_u = 0.2594, loglik = -57845.6977
Iter 221: sigma_u = 0.2594, loglik = -57848.4976
Iter 222: sigma_u = 0.2594, loglik = -57851.5641
Iter 223: sigma_u = 0.2594, loglik = -57854.1997
Iter 224: sigma_u = 0.2594, loglik = -57857.0141
Iter 225: sigma_u = 0.2593, loglik = -57859.4865
Iter 226: sigma_u = 0.2593, loglik = -57862.0946
Iter 227: sigma_u = 0.2593, loglik = -57864.4055
Iter 228: sigma_u = 0.2593, loglik = -57866.8089
Iter 229: sigma_u = 0.2593, loglik = -57868.9123
Iter 230: sigma_u = 0.2593, loglik = -57871.1313
Iter 231: sigma_u = 0.2593, loglik = -57872.9757
Iter 232: sigma_u = 0.2593, loglik = -57875.0103
Iter 233: sigma_u = 0.2593, loglik = -57876.6765
Iter 234: sigma_u = 0.2593, loglik = -57878.5087
Iter 235: sigma_u = 0.2593, loglik = -57880.0892
Iter 236: sigma_u = 0.2593, loglik = -57881.9091
Iter 237: sigma_u = 0.2592, loglik = -57883.3987
Iter 238: sigma_u = 0.2592, loglik = -57885.0129
Iter 239: sigma_u = 0.2592, loglik = -57886.4397
Iter 240: sigma_u = 0.2592, loglik = -57887.8922
Iter 241: sigma_u = 0.2592, loglik = -57889.0876
Iter 242: sigma_u = 0.2592, loglik = -57890.4447
Iter 243: sigma_u = 0.2592, loglik = -57891.6564
Iter 244: sigma_u = 0.2592, loglik = -57892.8839
Iter 245: sigma_u = 0.2592, loglik = -57893.9659
Iter 246: sigma_u = 0.2592, loglik = -57895.2033
Iter 247: sigma_u = 0.2592, loglik = -57896.2815
Iter 248: sigma_u = 0.2592, loglik = -57897.3279
Iter 249: sigma_u = 0.2592, loglik = -57898.3129
Iter 250: sigma_u = 0.2592, loglik = -57899.3079
Iter 251: sigma_u = 0.2592, loglik = -57900.2332
✅ Converged at iteration 252
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0           -1.438      -1.407220    -1.407471
1            4.847       4.755697     4.755374
2           -0.444      -0.411510    -0.410933
3            0.800       0.842100     0.259174



Time taken 2.416695702075958 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.7465, loglik = -23866.8940
Iter 1: sigma_u = 0.7048, loglik = -24472.1527
Iter 2: sigma_u = 0.6652, loglik = -25470.7226
Iter 3: sigma_u = 0.6280, loglik = -26619.8573
Iter 4: sigma_u = 0.5931, loglik = -27894.7805
Iter 5: sigma_u = 0.5605, loglik = -29296.2171
Iter 6: sigma_u = 0.5302, loglik = -30831.4761
Iter 7: sigma_u = 0.5019, loglik = -32505.8816
Iter 8: sigma_u = 0.4755, loglik = -34321.5783
Iter 9: sigma_u = 0.4511, loglik = -36276.9478
Iter 10: sigma_u = 0.4284, loglik = -38365.2848
Iter 11: sigma_u = 0.4075, loglik = -40573.5516
Iter 12: sigma_u = 0.3882, loglik = -42881.4921
Iter 13: sigma_u = 0.3706, loglik = -45261.5751
Iter 14: sigma_u = 0.3545, loglik = -47679.7933
Iter 15: sigma_u = 0.3398, loglik = -50097.6112
Iter 16: sigma_u = 0.3266, loglik = -52474.1670
Iter 17: sigma_u = 0.3148, loglik = -54771.6958
Iter 18: sigma_u = 0.3043, loglik = -56956.0500
Iter 19: sigma_u = 0.2950, loglik = -59000.1190
Iter 20: sigma_u = 0.2868, loglik = -60884.9862
Iter 21: sigma_u = 0.2796, loglik = -62600.0643
Iter 22: sigma_u = 0.2734, loglik = -64142.4017
Iter 23: sigma_u = 0.2680, loglik = -65515.2987
Iter 24: sigma_u = 0.2633, loglik = -66726.7811
Iter 25: sigma_u = 0.2593, loglik = -67787.9709
Iter 26: sigma_u = 0.2559, loglik = -68711.8701
Iter 27: sigma_u = 0.2529, loglik = -69512.1654
Iter 28: sigma_u = 0.2504, loglik = -70202.5136
Iter 29: sigma_u = 0.2483, loglik = -70795.2780
Iter 30: sigma_u = 0.2464, loglik = -71304.2056
Iter 31: sigma_u = 0.2449, loglik = -71739.5991
Iter 32: sigma_u = 0.2436, loglik = -72101.2451
Iter 33: sigma_u = 0.2425, loglik = -72417.4001
Iter 34: sigma_u = 0.2416, loglik = -72679.5289
Iter 35: sigma_u = 0.2408, loglik = -72900.2002
Iter 36: sigma_u = 0.2402, loglik = -73087.9500
Iter 37: sigma_u = 0.2396, loglik = -73248.5907
Iter 38: sigma_u = 0.2391, loglik = -73386.3251
Iter 39: sigma_u = 0.2387, loglik = -73501.9727
Iter 40: sigma_u = 0.2383, loglik = -73601.0068
Iter 41: sigma_u = 0.2380, loglik = -73686.2682
Iter 42: sigma_u = 0.2378, loglik = -73759.7115
Iter 43: sigma_u = 0.2376, loglik = -73822.9617
Iter 44: sigma_u = 0.2374, loglik = -73877.3439
Iter 45: sigma_u = 0.2372, loglik = -73926.6405
Iter 46: sigma_u = 0.2370, loglik = -73969.1504
Iter 47: sigma_u = 0.2369, loglik = -74005.1535
Iter 48: sigma_u = 0.2368, loglik = -74035.6452
Iter 49: sigma_u = 0.2367, loglik = -74061.5304
Iter 50: sigma_u = 0.2366, loglik = -74083.4215
Iter 51: sigma_u = 0.2366, loglik = -74100.9345
Iter 52: sigma_u = 0.2365, loglik = -74115.6838
Iter 53: sigma_u = 0.2365, loglik = -74127.2914
Iter 54: sigma_u = 0.2365, loglik = -74137.4897
Iter 55: sigma_u = 0.2364, loglik = -74145.3997
Iter 56: sigma_u = 0.2364, loglik = -74152.5370
Iter 57: sigma_u = 0.2364, loglik = -74158.1526
Iter 58: sigma_u = 0.2364, loglik = -74163.5260
Iter 59: sigma_u = 0.2363, loglik = -74167.8271
Iter 60: sigma_u = 0.2363, loglik = -74171.9787
Iter 61: sigma_u = 0.2363, loglik = -74175.3522
Iter 62: sigma_u = 0.2363, loglik = -74178.6768
Iter 63: sigma_u = 0.2363, loglik = -74181.3344
Iter 64: sigma_u = 0.2363, loglik = -74183.8927
Iter 65: sigma_u = 0.2363, loglik = -74185.9993
Iter 66: sigma_u = 0.2363, loglik = -74188.0580
Iter 67: sigma_u = 0.2363, loglik = -74189.7338
Iter 68: sigma_u = 0.2363, loglik = -74191.3857
Iter 69: sigma_u = 0.2363, loglik = -74192.7232
Iter 70: sigma_u = 0.2362, loglik = -74194.0786
Iter 71: sigma_u = 0.2362, loglik = -74195.1641
Iter 72: sigma_u = 0.2362, loglik = -74196.2155
Iter 73: sigma_u = 0.2362, loglik = -74197.0893
✅ Converged at iteration 74
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            1.476       1.468188     1.467953
1           -0.151      -0.162452    -0.162284
2           -1.735      -1.753776    -1.754425
3            0.800       0.814880     0.236234



Time taken 0.7188204685846965 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.8247, loglik = -18546.0252
Iter 1: sigma_u = 0.7793, loglik = -18706.6659
Iter 2: sigma_u = 0.7341, loglik = -19584.8785
Iter 3: sigma_u = 0.6908, loglik = -20608.9834
Iter 4: sigma_u = 0.6500, loglik = -21745.0835
Iter 5: sigma_u = 0.6119, loglik = -23005.5209
Iter 6: sigma_u = 0.5763, loglik = -24404.4710
Iter 7: sigma_u = 0.5432, loglik = -25950.5816
Iter 8: sigma_u = 0.5123, loglik = -27652.3269
Iter 9: sigma_u = 0.4837, loglik = -29515.4519
Iter 10: sigma_u = 0.4571, loglik = -31541.7497
Iter 11: sigma_u = 0.4325, loglik = -33727.4218
Iter 12: sigma_u = 0.4098, loglik = -36061.1205
Iter 13: sigma_u = 0.3889, loglik = -38522.1608
Iter 14: sigma_u = 0.3698, loglik = -41079.9491
Iter 15: sigma_u = 0.3524, loglik = -43694.7729
Iter 16: sigma_u = 0.3367, loglik = -46319.2099
Iter 17: sigma_u = 0.3225, loglik = -48904.6990
Iter 18: sigma_u = 0.3099, loglik = -51403.9526
Iter 19: sigma_u = 0.2987, loglik = -53776.4261
Iter 20: sigma_u = 0.2887, loglik = -55992.6579
Iter 21: sigma_u = 0.2800, loglik = -58030.4621
Iter 22: sigma_u = 0.2724, loglik = -59880.3100
Iter 23: sigma_u = 0.2658, loglik = -61540.7428
Iter 24: sigma_u = 0.2600, loglik = -63018.9290
Iter 25: sigma_u = 0.2550, loglik = -64325.1085
Iter 26: sigma_u = 0.2507, loglik = -65472.5434
Iter 27: sigma_u = 0.2470, loglik = -66475.8606
Iter 28: sigma_u = 0.2438, loglik = -67339.8678
Iter 29: sigma_u = 0.2410, loglik = -68102.8494
Iter 30: sigma_u = 0.2386, loglik = -68755.0304
Iter 31: sigma_u = 0.2365, loglik = -69328.0670
Iter 32: sigma_u = 0.2348, loglik = -69817.4442
Iter 33: sigma_u = 0.2332, loglik = -70245.4058
Iter 34: sigma_u = 0.2319, loglik = -70611.3066
Iter 35: sigma_u = 0.2308, loglik = -70930.1752
Iter 36: sigma_u = 0.2298, loglik = -71203.0712
Iter 37: sigma_u = 0.2289, loglik = -71439.2646
Iter 38: sigma_u = 0.2283, loglik = -71640.8937
Iter 39: sigma_u = 0.2276, loglik = -71804.8594
Iter 40: sigma_u = 0.2271, loglik = -71957.3246
Iter 41: sigma_u = 0.2267, loglik = -72079.8603
Iter 42: sigma_u = 0.2263, loglik = -72186.0399
Iter 43: sigma_u = 0.2259, loglik = -72284.2849
Iter 44: sigma_u = 0.2256, loglik = -72368.2041
Iter 45: sigma_u = 0.2254, loglik = -72437.1001
Iter 46: sigma_u = 0.2252, loglik = -72497.4544
Iter 47: sigma_u = 0.2250, loglik = -72550.1707
Iter 48: sigma_u = 0.2248, loglik = -72596.1894
Iter 49: sigma_u = 0.2247, loglik = -72636.2505
Iter 50: sigma_u = 0.2245, loglik = -72666.0730
Iter 51: sigma_u = 0.2245, loglik = -72700.8649
Iter 52: sigma_u = 0.2244, loglik = -72711.1626
Iter 53: sigma_u = 0.2243, loglik = -72738.9599
Iter 54: sigma_u = 0.2242, loglik = -72763.8919
Iter 55: sigma_u = 0.2242, loglik = -72775.0367
Iter 56: sigma_u = 0.2242, loglik = -72781.7634
Iter 57: sigma_u = 0.2241, loglik = -72794.9757
Iter 58: sigma_u = 0.2241, loglik = -72800.2289
Iter 59: sigma_u = 0.2241, loglik = -72813.3299
Iter 60: sigma_u = 0.2240, loglik = -72817.6961
Iter 61: sigma_u = 0.2240, loglik = -72828.4076
Iter 62: sigma_u = 0.2240, loglik = -72832.0378
Iter 63: sigma_u = 0.2240, loglik = -72840.9876
Iter 64: sigma_u = 0.2239, loglik = -72843.9885
Iter 65: sigma_u = 0.2239, loglik = -72851.5738
Iter 66: sigma_u = 0.2239, loglik = -72854.0852
Iter 67: sigma_u = 0.2239, loglik = -72860.3379
Iter 68: sigma_u = 0.2239, loglik = -72862.4142
Iter 69: sigma_u = 0.2238, loglik = -72867.6885
Iter 70: sigma_u = 0.2238, loglik = -72869.4297
Iter 71: sigma_u = 0.2238, loglik = -72873.7494
Iter 72: sigma_u = 0.2238, loglik = -72875.1587
Iter 73: sigma_u = 0.2238, loglik = -72878.8447
Iter 74: sigma_u = 0.2238, loglik = -72880.0222
Iter 75: sigma_u = 0.2238, loglik = -72883.1839
Iter 76: sigma_u = 0.2238, loglik = -72884.1860
Iter 77: sigma_u = 0.2238, loglik = -72886.6476
Iter 78: sigma_u = 0.2238, loglik = -72887.4456
Iter 79: sigma_u = 0.2238, loglik = -72889.7412
Iter 80: sigma_u = 0.2238, loglik = -72890.4197
✅ Converged at iteration 81
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             2.50       2.500865     2.503701
1             0.45       0.443395     0.443248
2             0.25       0.236074     0.235250
3            -1.20      -1.217272    -1.218038
4             0.80       0.779917     0.223751



Time taken 0.9444955190022787 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.2975, loglik = -17064.4909
Iter 1: sigma_u = 1.2089, loglik = -17420.2754
Iter 2: sigma_u = 1.1263, loglik = -17852.3071
Iter 3: sigma_u = 1.0495, loglik = -18351.0153
Iter 4: sigma_u = 0.9781, loglik = -18922.9369
Iter 5: sigma_u = 0.9118, loglik = -19577.5102
Iter 6: sigma_u = 0.8502, loglik = -20325.4825
Iter 7: sigma_u = 0.7931, loglik = -21178.6247
Iter 8: sigma_u = 0.7401, loglik = -22149.6642
Iter 9: sigma_u = 0.6910, loglik = -23251.8891
Iter 10: sigma_u = 0.6455, loglik = -24499.9195
Iter 11: sigma_u = 0.6034, loglik = -25908.3303
Iter 12: sigma_u = 0.5644, loglik = -27491.4884
Iter 13: sigma_u = 0.5284, loglik = -29262.7386
Iter 14: sigma_u = 0.4951, loglik = -31233.2405
Iter 15: sigma_u = 0.4645, loglik = -33410.1340
Iter 16: sigma_u = 0.4363, loglik = -35794.7076
Iter 17: sigma_u = 0.4104, loglik = -38376.7314
Iter 18: sigma_u = 0.3868, loglik = -41133.5436
Iter 19: sigma_u = 0.3654, loglik = -44029.1507
Iter 20: sigma_u = 0.3460, loglik = -47012.8262
Iter 21: sigma_u = 0.3285, loglik = -50019.8081
Iter 22: sigma_u = 0.3130, loglik = -52987.6887
Iter 23: sigma_u = 0.2993, loglik = -55848.7347
Iter 24: sigma_u = 0.2872, loglik = -58545.9000
Iter 25: sigma_u = 0.2767, loglik = -61037.7173
Iter 26: sigma_u = 0.2676, loglik = -63298.9505
Iter 27: sigma_u = 0.2598, loglik = -65320.6042
Iter 28: sigma_u = 0.2531, loglik = -67103.4271
Iter 29: sigma_u = 0.2474, loglik = -68659.0530
Iter 30: sigma_u = 0.2425, loglik = -70005.0275
Iter 31: sigma_u = 0.2384, loglik = -71161.8321
Iter 32: sigma_u = 0.2349, loglik = -72150.9486
Iter 33: sigma_u = 0.2319, loglik = -72993.2854
Iter 34: sigma_u = 0.2294, loglik = -73708.4579
Iter 35: sigma_u = 0.2273, loglik = -74316.0101
Iter 36: sigma_u = 0.2256, loglik = -74828.7805
Iter 37: sigma_u = 0.2241, loglik = -75261.8218
Iter 38: sigma_u = 0.2229, loglik = -75626.6757
Iter 39: sigma_u = 0.2218, loglik = -75925.6340
Iter 40: sigma_u = 0.2210, loglik = -76183.4965
Iter 41: sigma_u = 0.2202, loglik = -76396.9073
Iter 42: sigma_u = 0.2196, loglik = -76575.4761
Iter 43: sigma_u = 0.2191, loglik = -76726.2572
Iter 44: sigma_u = 0.2186, loglik = -76853.8743
Iter 45: sigma_u = 0.2183, loglik = -76962.7779
Iter 46: sigma_u = 0.2180, loglik = -77055.0240
Iter 47: sigma_u = 0.2177, loglik = -77133.0723
Iter 48: sigma_u = 0.2175, loglik = -77199.1126
Iter 49: sigma_u = 0.2173, loglik = -77255.0281
Iter 50: sigma_u = 0.2171, loglik = -77302.3316
Iter 51: sigma_u = 0.2170, loglik = -77343.5471
Iter 52: sigma_u = 0.2168, loglik = -77377.4692
Iter 53: sigma_u = 0.2167, loglik = -77406.9011
Iter 54: sigma_u = 0.2167, loglik = -77431.0608
Iter 55: sigma_u = 0.2166, loglik = -77451.2417
Iter 56: sigma_u = 0.2166, loglik = -77464.4011
Iter 57: sigma_u = 0.2165, loglik = -77474.5777
Iter 58: sigma_u = 0.2165, loglik = -77485.1322
Iter 59: sigma_u = 0.2165, loglik = -77492.3895
Iter 60: sigma_u = 0.2164, loglik = -77500.5062
Iter 61: sigma_u = 0.2164, loglik = -77506.1713
Iter 62: sigma_u = 0.2164, loglik = -77512.3684
Iter 63: sigma_u = 0.2164, loglik = -77516.9849
Iter 64: sigma_u = 0.2164, loglik = -77521.7486
Iter 65: sigma_u = 0.2163, loglik = -77525.5615
Iter 66: sigma_u = 0.2163, loglik = -77529.3396
Iter 67: sigma_u = 0.2163, loglik = -77532.5105
Iter 68: sigma_u = 0.2163, loglik = -77535.5597
Iter 69: sigma_u = 0.2163, loglik = -77538.1172
Iter 70: sigma_u = 0.2163, loglik = -77540.5480
Iter 71: sigma_u = 0.2163, loglik = -77542.6485
Iter 72: sigma_u = 0.2163, loglik = -77544.5875
Iter 73: sigma_u = 0.2163, loglik = -77546.2942
Iter 74: sigma_u = 0.2163, loglik = -77547.8340
Iter 75: sigma_u = 0.2163, loglik = -77549.2318
Iter 76: sigma_u = 0.2163, loglik = -77550.5449
Iter 77: sigma_u = 0.2162, loglik = -77551.6584
Iter 78: sigma_u = 0.2162, loglik = -77552.6903
Iter 79: sigma_u = 0.2162, loglik = -77553.6290
Iter 80: sigma_u = 0.2162, loglik = -77554.5297
✅ Converged at iteration 81
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              0.8       0.761322     0.760007
1             -0.9      -0.898281    -0.897903
2              0.5       0.520934     0.520603
3             -1.7      -1.663235    -1.661603
4              0.8       0.774902     0.216239



Time taken 0.949126136302948 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 2.3233, loglik = -11038.4596
Iter 1: sigma_u = 2.2153, loglik = -11077.8779
Iter 2: sigma_u = 2.1172, loglik = -11163.4196
Iter 3: sigma_u = 2.0265, loglik = -11256.6720
Iter 4: sigma_u = 1.9416, loglik = -11355.9168
Iter 5: sigma_u = 1.8615, loglik = -11462.0075
Iter 6: sigma_u = 1.7853, loglik = -11576.1078
Iter 7: sigma_u = 1.7127, loglik = -11699.2316
Iter 8: sigma_u = 1.6434, loglik = -11832.3101
Iter 9: sigma_u = 1.5771, loglik = -11976.2840
Iter 10: sigma_u = 1.5136, loglik = -12132.1209
Iter 11: sigma_u = 1.4528, loglik = -12300.8316
Iter 12: sigma_u = 1.3945, loglik = -12483.4812
Iter 13: sigma_u = 1.3386, loglik = -12681.1995
Iter 14: sigma_u = 1.2851, loglik = -12895.1846
Iter 15: sigma_u = 1.2339, loglik = -13126.7131
Iter 16: sigma_u = 1.1847, loglik = -13377.1392
Iter 17: sigma_u = 1.1376, loglik = -13647.9051
Iter 18: sigma_u = 1.0925, loglik = -13940.5323
Iter 19: sigma_u = 1.0493, loglik = -14256.6334
Iter 20: sigma_u = 1.0079, loglik = -14597.9106
Iter 21: sigma_u = 0.9683, loglik = -14966.1615
Iter 22: sigma_u = 0.9303, loglik = -15363.2611
Iter 23: sigma_u = 0.8939, loglik = -15791.1774
Iter 24: sigma_u = 0.8591, loglik = -16251.9511
Iter 25: sigma_u = 0.8258, loglik = -16747.7062
Iter 26: sigma_u = 0.7939, loglik = -17280.6184
Iter 27: sigma_u = 0.7634, loglik = -17852.9203
Iter 28: sigma_u = 0.7342, loglik = -18466.7975
Iter 29: sigma_u = 0.7063, loglik = -19124.5891
Iter 30: sigma_u = 0.6797, loglik = -19828.5485
Iter 31: sigma_u = 0.6542, loglik = -20580.8615
Iter 32: sigma_u = 0.6298, loglik = -21383.6567
Iter 33: sigma_u = 0.6065, loglik = -22238.8929
Iter 34: sigma_u = 0.5843, loglik = -23148.3556
Iter 35: sigma_u = 0.5632, loglik = -24113.5502
Iter 36: sigma_u = 0.5429, loglik = -25135.6577
Iter 37: sigma_u = 0.5237, loglik = -26215.4121
Iter 38: sigma_u = 0.5054, loglik = -27352.9501
Iter 39: sigma_u = 0.4879, loglik = -28547.7428
Iter 40: sigma_u = 0.4713, loglik = -29798.4332
Iter 41: sigma_u = 0.4555, loglik = -31102.6623
Iter 42: sigma_u = 0.4406, loglik = -32456.9084
Iter 43: sigma_u = 0.4264, loglik = -33856.4338
Iter 44: sigma_u = 0.4130, loglik = -35295.1311
Iter 45: sigma_u = 0.4004, loglik = -36765.6038
Iter 46: sigma_u = 0.3884, loglik = -38259.1920
Iter 47: sigma_u = 0.3772, loglik = -39766.2223
Iter 48: sigma_u = 0.3667, loglik = -41276.1464
Iter 49: sigma_u = 0.3568, loglik = -42777.9997
Iter 50: sigma_u = 0.3476, loglik = -44260.8059
Iter 51: sigma_u = 0.3391, loglik = -45713.9049
Iter 52: sigma_u = 0.3311, loglik = -47127.4679
Iter 53: sigma_u = 0.3238, loglik = -48494.3632
Iter 54: sigma_u = 0.3170, loglik = -49805.7336
Iter 55: sigma_u = 0.3107, loglik = -51055.4844
Iter 56: sigma_u = 0.3050, loglik = -52239.0201
Iter 57: sigma_u = 0.2997, loglik = -53353.2061
Iter 58: sigma_u = 0.2949, loglik = -54396.4544
Iter 59: sigma_u = 0.2905, loglik = -55368.5106
Iter 60: sigma_u = 0.2865, loglik = -56270.2111
Iter 61: sigma_u = 0.2828, loglik = -57105.4484
Iter 62: sigma_u = 0.2795, loglik = -57874.9672
Iter 63: sigma_u = 0.2765, loglik = -58581.6409
Iter 64: sigma_u = 0.2738, loglik = -59228.6858
Iter 65: sigma_u = 0.2714, loglik = -59819.6646
Iter 66: sigma_u = 0.2691, loglik = -60358.2290
Iter 67: sigma_u = 0.2671, loglik = -60848.0935
Iter 68: sigma_u = 0.2653, loglik = -61292.3944
Iter 69: sigma_u = 0.2637, loglik = -61694.9044
Iter 70: sigma_u = 0.2623, loglik = -62057.8888
Iter 71: sigma_u = 0.2609, loglik = -62388.2141
Iter 72: sigma_u = 0.2598, loglik = -62686.4380
Iter 73: sigma_u = 0.2587, loglik = -62949.7789
Iter 74: sigma_u = 0.2578, loglik = -63193.6836
Iter 75: sigma_u = 0.2569, loglik = -63408.5984
Iter 76: sigma_u = 0.2561, loglik = -63602.7689
Iter 77: sigma_u = 0.2554, loglik = -63776.6856
Iter 78: sigma_u = 0.2549, loglik = -63934.7880
Iter 79: sigma_u = 0.2543, loglik = -64069.3330
Iter 80: sigma_u = 0.2539, loglik = -64191.5013
Iter 81: sigma_u = 0.2534, loglik = -64301.6274
Iter 82: sigma_u = 0.2530, loglik = -64401.5589
Iter 83: sigma_u = 0.2527, loglik = -64491.8957
Iter 84: sigma_u = 0.2523, loglik = -64573.9729
Iter 85: sigma_u = 0.2521, loglik = -64648.2227
Iter 86: sigma_u = 0.2518, loglik = -64715.6900
Iter 87: sigma_u = 0.2515, loglik = -64776.7181
Iter 88: sigma_u = 0.2513, loglik = -64832.1866
Iter 89: sigma_u = 0.2511, loglik = -64882.3382
Iter 90: sigma_u = 0.2510, loglik = -64926.4199
Iter 91: sigma_u = 0.2508, loglik = -64967.2503
Iter 92: sigma_u = 0.2507, loglik = -65004.0184
Iter 93: sigma_u = 0.2505, loglik = -65037.5418
Iter 94: sigma_u = 0.2504, loglik = -65068.2211
Iter 95: sigma_u = 0.2503, loglik = -65096.3562
Iter 96: sigma_u = 0.2502, loglik = -65122.0463
Iter 97: sigma_u = 0.2501, loglik = -65144.4006
Iter 98: sigma_u = 0.2501, loglik = -65160.4320
Iter 99: sigma_u = 0.2500, loglik = -65172.9366
Iter 100: sigma_u = 0.2500, loglik = -65185.9436
Iter 101: sigma_u = 0.2499, loglik = -65197.1101
Iter 102: sigma_u = 0.2499, loglik = -65208.0449
Iter 103: sigma_u = 0.2498, loglik = -65217.7841
Iter 104: sigma_u = 0.2498, loglik = -65227.1950
Iter 105: sigma_u = 0.2498, loglik = -65235.6482
Iter 106: sigma_u = 0.2497, loglik = -65243.9016
Iter 107: sigma_u = 0.2497, loglik = -65251.2752
Iter 108: sigma_u = 0.2497, loglik = -65258.5197
Iter 109: sigma_u = 0.2496, loglik = -65264.9707
Iter 110: sigma_u = 0.2496, loglik = -65271.3116
Iter 111: sigma_u = 0.2496, loglik = -65276.9542
Iter 112: sigma_u = 0.2496, loglik = -65282.5998
Iter 113: sigma_u = 0.2496, loglik = -65287.5585
Iter 114: sigma_u = 0.2495, loglik = -65292.3971
Iter 115: sigma_u = 0.2495, loglik = -65296.7591
Iter 116: sigma_u = 0.2495, loglik = -65301.0494
Iter 117: sigma_u = 0.2495, loglik = -65304.8666
Iter 118: sigma_u = 0.2495, loglik = -65308.6887
Iter 119: sigma_u = 0.2495, loglik = -65312.0395
Iter 120: sigma_u = 0.2494, loglik = -65315.4361
Iter 121: sigma_u = 0.2494, loglik = -65318.4181
Iter 122: sigma_u = 0.2494, loglik = -65321.4085
Iter 123: sigma_u = 0.2494, loglik = -65324.0196
Iter 124: sigma_u = 0.2494, loglik = -65326.6247
Iter 125: sigma_u = 0.2494, loglik = -65328.9281
Iter 126: sigma_u = 0.2494, loglik = -65331.2655
Iter 127: sigma_u = 0.2494, loglik = -65333.3108
Iter 128: sigma_u = 0.2494, loglik = -65335.3969
Iter 129: sigma_u = 0.2494, loglik = -65337.1981
Iter 130: sigma_u = 0.2493, loglik = -65338.9660
Iter 131: sigma_u = 0.2493, loglik = -65340.5792
Iter 132: sigma_u = 0.2493, loglik = -65342.2034
Iter 133: sigma_u = 0.2493, loglik = -65343.6199
Iter 134: sigma_u = 0.2493, loglik = -65345.0243
Iter 135: sigma_u = 0.2493, loglik = -65346.2508
Iter 136: sigma_u = 0.2493, loglik = -65347.4580
Iter 137: sigma_u = 0.2493, loglik = -65348.5517
Iter 138: sigma_u = 0.2493, loglik = -65349.6476
Iter 139: sigma_u = 0.2493, loglik = -65350.6394
Iter 140: sigma_u = 0.2493, loglik = -65351.5735
Iter 141: sigma_u = 0.2493, loglik = -65352.4156
Iter 142: sigma_u = 0.2493, loglik = -65353.2978
✅ Converged at iteration 143
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              1.8       1.819847     1.816181
1             -2.1      -2.115470    -2.111817
2             -0.5      -0.466894    -0.465904
3             -1.7      -1.753124    -1.749481
4              0.8       0.835636     0.249287



Time taken 1.7733455856641134 minutes



Initial sigma: 0.8

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.3359, loglik = -15480.0531
Iter 1: sigma_u = 1.2674, loglik = -15694.0525
Iter 2: sigma_u = 1.2019, loglik = -15995.4995
Iter 3: sigma_u = 1.1396, loglik = -16335.2691
Iter 4: sigma_u = 1.0807, loglik = -16711.6777
Iter 5: sigma_u = 1.0249, loglik = -17128.2405
Iter 6: sigma_u = 0.9722, loglik = -17588.9125
Iter 7: sigma_u = 0.9223, loglik = -18098.0139
Iter 8: sigma_u = 0.8752, loglik = -18660.1481
Iter 9: sigma_u = 0.8307, loglik = -19280.0467
Iter 10: sigma_u = 0.7887, loglik = -19962.7856
Iter 11: sigma_u = 0.7490, loglik = -20713.6394
Iter 12: sigma_u = 0.7115, loglik = -21538.0488
Iter 13: sigma_u = 0.6762, loglik = -22441.5436
Iter 14: sigma_u = 0.6428, loglik = -23429.6460
Iter 15: sigma_u = 0.6114, loglik = -24507.7286
Iter 16: sigma_u = 0.5818, loglik = -25680.8563
Iter 17: sigma_u = 0.5540, loglik = -26953.5583
Iter 18: sigma_u = 0.5278, loglik = -28329.5074
Iter 19: sigma_u = 0.5032, loglik = -29811.1701
Iter 20: sigma_u = 0.4801, loglik = -31399.2702
Iter 21: sigma_u = 0.4585, loglik = -33092.2114
Iter 22: sigma_u = 0.4383, loglik = -34885.4003
Iter 23: sigma_u = 0.4194, loglik = -36770.5824
Iter 24: sigma_u = 0.4018, loglik = -38735.3268
Iter 25: sigma_u = 0.3855, loglik = -40762.7911
Iter 26: sigma_u = 0.3704, loglik = -42831.9807
Iter 27: sigma_u = 0.3565, loglik = -44918.4906
Iter 28: sigma_u = 0.3437, loglik = -46995.7568
Iter 29: sigma_u = 0.3321, loglik = -49036.7498
Iter 30: sigma_u = 0.3215, loglik = -51015.6766
Iter 31: sigma_u = 0.3120, loglik = -52909.7387
Iter 32: sigma_u = 0.3034, loglik = -54700.2776
Iter 33: sigma_u = 0.2957, loglik = -56373.5149
Iter 34: sigma_u = 0.2889, loglik = -57920.7603
Iter 35: sigma_u = 0.2828, loglik = -59338.1392
Iter 36: sigma_u = 0.2774, loglik = -60625.9374
Iter 37: sigma_u = 0.2727, loglik = -61787.6711
Iter 38: sigma_u = 0.2685, loglik = -62829.6279
Iter 39: sigma_u = 0.2649, loglik = -63759.1606
Iter 40: sigma_u = 0.2616, loglik = -64584.7393
Iter 41: sigma_u = 0.2588, loglik = -65315.0428
Iter 42: sigma_u = 0.2564, loglik = -65958.8889
Iter 43: sigma_u = 0.2542, loglik = -66524.8765
Iter 44: sigma_u = 0.2524, loglik = -67021.4797
Iter 45: sigma_u = 0.2507, loglik = -67456.1442
Iter 46: sigma_u = 0.2493, loglik = -67835.9745
Iter 47: sigma_u = 0.2481, loglik = -68167.5413
Iter 48: sigma_u = 0.2471, loglik = -68444.9693
Iter 49: sigma_u = 0.2462, loglik = -68698.6290
Iter 50: sigma_u = 0.2454, loglik = -68910.0491
Iter 51: sigma_u = 0.2447, loglik = -69093.9155
Iter 52: sigma_u = 0.2441, loglik = -69255.1689
Iter 53: sigma_u = 0.2436, loglik = -69396.6286
Iter 54: sigma_u = 0.2431, loglik = -69517.9280
Iter 55: sigma_u = 0.2428, loglik = -69624.7602
Iter 56: sigma_u = 0.2424, loglik = -69718.0752
Iter 57: sigma_u = 0.2421, loglik = -69799.7712
Iter 58: sigma_u = 0.2418, loglik = -69871.1336
Iter 59: sigma_u = 0.2416, loglik = -69933.6148
Iter 60: sigma_u = 0.2414, loglik = -69988.1532
Iter 61: sigma_u = 0.2412, loglik = -70035.9105
Iter 62: sigma_u = 0.2411, loglik = -70077.4120
Iter 63: sigma_u = 0.2410, loglik = -70114.7301
Iter 64: sigma_u = 0.2408, loglik = -70145.1815
Iter 65: sigma_u = 0.2408, loglik = -70175.6284
Iter 66: sigma_u = 0.2407, loglik = -70191.2430
Iter 67: sigma_u = 0.2406, loglik = -70206.4517
Iter 68: sigma_u = 0.2406, loglik = -70217.8780
Iter 69: sigma_u = 0.2406, loglik = -70230.6089
Iter 70: sigma_u = 0.2405, loglik = -70240.1648
Iter 71: sigma_u = 0.2405, loglik = -70250.7461
Iter 72: sigma_u = 0.2404, loglik = -70258.8053
Iter 73: sigma_u = 0.2404, loglik = -70267.8381
Iter 74: sigma_u = 0.2404, loglik = -70274.6623
Iter 75: sigma_u = 0.2404, loglik = -70282.3204
Iter 76: sigma_u = 0.2403, loglik = -70288.1564
Iter 77: sigma_u = 0.2403, loglik = -70294.5667
Iter 78: sigma_u = 0.2403, loglik = -70299.5548
Iter 79: sigma_u = 0.2403, loglik = -70305.0573
Iter 80: sigma_u = 0.2402, loglik = -70309.3330
Iter 81: sigma_u = 0.2402, loglik = -70313.9919
Iter 82: sigma_u = 0.2402, loglik = -70317.6095
Iter 83: sigma_u = 0.2402, loglik = -70321.6508
Iter 84: sigma_u = 0.2402, loglik = -70324.7357
Iter 85: sigma_u = 0.2402, loglik = -70328.2282
Iter 86: sigma_u = 0.2402, loglik = -70330.8006
Iter 87: sigma_u = 0.2402, loglik = -70333.7906
Iter 88: sigma_u = 0.2401, loglik = -70335.9711
Iter 89: sigma_u = 0.2401, loglik = -70338.4021
Iter 90: sigma_u = 0.2401, loglik = -70340.3014
Iter 91: sigma_u = 0.2401, loglik = -70342.4303
Iter 92: sigma_u = 0.2401, loglik = -70344.0323
Iter 93: sigma_u = 0.2401, loglik = -70345.8925
Iter 94: sigma_u = 0.2401, loglik = -70347.2548
Iter 95: sigma_u = 0.2401, loglik = -70348.8443
Iter 96: sigma_u = 0.2401, loglik = -70350.0240
Iter 97: sigma_u = 0.2401, loglik = -70351.3688
Iter 98: sigma_u = 0.2401, loglik = -70352.3904
Iter 99: sigma_u = 0.2401, loglik = -70353.5869
Iter 100: sigma_u = 0.2401, loglik = -70354.4444
✅ Converged at iteration 101
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            -1.24      -1.246589    -1.247010
1             1.17       1.156178     1.156315
2            -1.04      -1.030111    -1.030012
3             0.97       0.973267     0.973289
4             0.80       0.815462     0.240070



Time taken 1.1012013673782348 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.7007, loglik = -27928.5627
Iter 1: sigma_u = 0.7461, loglik = -26593.0999
Iter 2: sigma_u = 0.7937, loglik = -25417.0398
Iter 3: sigma_u = 0.8439, loglik = -24384.4294
Iter 4: sigma_u = 0.8970, loglik = -23475.1415
Iter 5: sigma_u = 0.9529, loglik = -22672.8290
Iter 6: sigma_u = 1.0121, loglik = -21964.0040
Iter 7: sigma_u = 1.0746, loglik = -21337.1178
Iter 8: sigma_u = 1.1407, loglik = -20782.2219
Iter 9: sigma_u = 1.2106, loglik = -20290.6870
Iter 10: sigma_u = 1.2845, loglik = -19854.9966
Iter 11: sigma_u = 1.3627, loglik = -19468.5851
Iter 12: sigma_u = 1.4455, loglik = -19125.7158
Iter 13: sigma_u = 1.5330, loglik = -18821.3621
Iter 14: sigma_u = 1.6257, loglik = -18551.1200
Iter 15: sigma_u = 1.7237, loglik = -18311.1143
Iter 16: sigma_u = 1.8273, loglik = -18097.9103
Iter 17: sigma_u = 1.9365, loglik = -17908.4343
Iter 18: sigma_u = 2.0509, loglik = -17739.9315
Iter 19: sigma_u = 2.1691, loglik = -17589.9857
Iter 20: sigma_u = 2.2882, loglik = -17456.6658
Iter 21: sigma_u = 2.4033, loglik = -17338.7188
Iter 22: sigma_u = 2.5084, loglik = -17235.8083
Iter 23: sigma_u = 2.5982, loglik = -17148.4489
Iter 24: sigma_u = 2.6698, loglik = -17077.3339
Iter 25: sigma_u = 2.7235, loglik = -17022.3253
Iter 26: sigma_u = 2.7617, loglik = -16981.8967
Iter 27: sigma_u = 2.7878, loglik = -16953.4621
Iter 28: sigma_u = 2.8053, loglik = -16934.1266
Iter 29: sigma_u = 2.8167, loglik = -16921.2970
Iter 30: sigma_u = 2.8241, loglik = -16912.8890
Iter 31: sigma_u = 2.8288, loglik = -16907.4787
Iter 32: sigma_u = 2.8318, loglik = -16904.1004
Iter 33: sigma_u = 2.8337, loglik = -16901.8676
Iter 34: sigma_u = 2.8349, loglik = -16900.4944
Iter 35: sigma_u = 2.8356, loglik = -16899.6435
Iter 36: sigma_u = 2.8361, loglik = -16899.0947
Iter 37: sigma_u = 2.8364, loglik = -16898.7369
Iter 38: sigma_u = 2.8366, loglik = -16898.5245
Iter 39: sigma_u = 2.8368, loglik = -16898.3451
Iter 40: sigma_u = 2.8369, loglik = -16898.2278
Iter 41: sigma_u = 2.8370, loglik = -16898.1389
Iter 42: sigma_u = 2.8370, loglik = -16898.1003
Iter 43: sigma_u = 2.8370, loglik = -16898.0973
Iter 44: sigma_u = 2.8370, loglik = -16898.0822
✅ Converged at iteration 45
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              0.5       0.523358     0.518958
1              0.5       0.489893     0.482281
2             -1.2      -1.216415    -1.202962
3              1.2       1.174901     2.837015



Time taken 0.547721016407013 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.0257, loglik = -16169.9196
Iter 1: sigma_u = 1.0908, loglik = -15466.2709
Iter 2: sigma_u = 1.1556, loglik = -14968.7095
Iter 3: sigma_u = 1.2226, loglik = -14529.1399
Iter 4: sigma_u = 1.2927, loglik = -14134.7193
Iter 5: sigma_u = 1.3663, loglik = -13781.5726
Iter 6: sigma_u = 1.4440, loglik = -13465.6758
Iter 7: sigma_u = 1.5260, loglik = -13182.9195
Iter 8: sigma_u = 1.6123, loglik = -12929.9410
Iter 9: sigma_u = 1.7034, loglik = -12703.6259
Iter 10: sigma_u = 1.7993, loglik = -12501.1798
Iter 11: sigma_u = 1.9004, loglik = -12320.0944
Iter 12: sigma_u = 2.0069, loglik = -12158.1094
Iter 13: sigma_u = 2.1189, loglik = -12013.1860
Iter 14: sigma_u = 2.2365, loglik = -11883.4664
Iter 15: sigma_u = 2.3594, loglik = -11767.2395
Iter 16: sigma_u = 2.4862, loglik = -11663.0393
Iter 17: sigma_u = 2.6142, loglik = -11569.4903
Iter 18: sigma_u = 2.7387, loglik = -11485.9011
Iter 19: sigma_u = 2.8539, loglik = -11412.1030
Iter 20: sigma_u = 2.9545, loglik = -11348.4346
Iter 21: sigma_u = 3.0377, loglik = -11295.2730
Iter 22: sigma_u = 3.1031, loglik = -11252.5370
Iter 23: sigma_u = 3.1528, loglik = -11219.4258
Iter 24: sigma_u = 3.1894, loglik = -11194.5572
Iter 25: sigma_u = 3.2160, loglik = -11176.3286
Iter 26: sigma_u = 3.2349, loglik = -11163.1938
Iter 27: sigma_u = 3.2483, loglik = -11153.8421
Iter 28: sigma_u = 3.2578, loglik = -11147.2377
Iter 29: sigma_u = 3.2644, loglik = -11142.5983
Iter 30: sigma_u = 3.2690, loglik = -11139.3506
Iter 31: sigma_u = 3.2723, loglik = -11137.0830
Iter 32: sigma_u = 3.2745, loglik = -11135.5005
Iter 33: sigma_u = 3.2761, loglik = -11134.3995
Iter 34: sigma_u = 3.2771, loglik = -11133.6330
Iter 35: sigma_u = 3.2777, loglik = -11133.1238
Iter 36: sigma_u = 3.2782, loglik = -11132.8210
Iter 37: sigma_u = 3.2785, loglik = -11132.5788
Iter 38: sigma_u = 3.2790, loglik = -11132.4170
Iter 39: sigma_u = 3.2792, loglik = -11132.2134
Iter 40: sigma_u = 3.2793, loglik = -11132.1077
Iter 41: sigma_u = 3.2794, loglik = -11132.0717
Iter 42: sigma_u = 3.2794, loglik = -11132.0198
Iter 43: sigma_u = 3.2795, loglik = -11131.9898
Iter 44: sigma_u = 3.2796, loglik = -11131.9645
Iter 45: sigma_u = 3.2796, loglik = -11131.9401
Iter 46: sigma_u = 3.2796, loglik = -11131.9235
Iter 47: sigma_u = 3.2796, loglik = -11131.9157
Iter 48: sigma_u = 3.2796, loglik = -11131.9084
✅ Converged at iteration 49
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              1.5       1.505582     1.510979
1             -0.8      -0.821783    -0.801680
2              1.3       1.324746     1.291714
3              1.2       1.200774     3.279634



Time taken 0.5263460516929627 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 4.0802, loglik = -5511.4419
Iter 1: sigma_u = 3.8011, loglik = -5640.8951
Iter 2: sigma_u = 3.6207, loglik = -5723.2074
Iter 3: sigma_u = 3.4977, loglik = -5779.0890
Iter 4: sigma_u = 3.4102, loglik = -5818.5686
Iter 5: sigma_u = 3.3459, loglik = -5847.3732
Iter 6: sigma_u = 3.2977, loglik = -5868.9645
Iter 7: sigma_u = 3.2610, loglik = -5885.4034
Iter 8: sigma_u = 3.2327, loglik = -5898.0932
Iter 9: sigma_u = 3.2106, loglik = -5907.9878
Iter 10: sigma_u = 3.1932, loglik = -5915.7712
Iter 11: sigma_u = 3.1798, loglik = -5921.9323
Iter 12: sigma_u = 3.1688, loglik = -5926.7199
Iter 13: sigma_u = 3.1601, loglik = -5930.6595
Iter 14: sigma_u = 3.1535, loglik = -5933.8146
Iter 15: sigma_u = 3.1481, loglik = -5936.2030
Iter 16: sigma_u = 3.1437, loglik = -5938.1461
Iter 17: sigma_u = 3.1401, loglik = -5939.7355
Iter 18: sigma_u = 3.1372, loglik = -5941.0358
Iter 19: sigma_u = 3.1351, loglik = -5942.1020
Iter 20: sigma_u = 3.1330, loglik = -5942.8692
Iter 21: sigma_u = 3.1316, loglik = -5943.6282
Iter 22: sigma_u = 3.1305, loglik = -5944.1525
Iter 23: sigma_u = 3.1293, loglik = -5944.5386
Iter 24: sigma_u = 3.1284, loglik = -5944.9916
Iter 25: sigma_u = 3.1278, loglik = -5945.3020
Iter 26: sigma_u = 3.1273, loglik = -5945.5341
Iter 27: sigma_u = 3.1268, loglik = -5945.7223
Iter 28: sigma_u = 3.1264, loglik = -5945.8851
Iter 29: sigma_u = 3.1259, loglik = -5946.0575
Iter 30: sigma_u = 3.1255, loglik = -5946.2295
Iter 31: sigma_u = 3.1254, loglik = -5946.3709
Iter 32: sigma_u = 3.1252, loglik = -5946.4293
Iter 33: sigma_u = 3.1250, loglik = -5946.4874
Iter 34: sigma_u = 3.1249, loglik = -5946.5467
Iter 35: sigma_u = 3.1248, loglik = -5946.5854
Iter 36: sigma_u = 3.1247, loglik = -5946.6453
Iter 37: sigma_u = 3.1245, loglik = -5946.6741
Iter 38: sigma_u = 3.1245, loglik = -5946.7249
Iter 39: sigma_u = 3.1244, loglik = -5946.7469
Iter 40: sigma_u = 3.1243, loglik = -5946.7859
Iter 41: sigma_u = 3.1242, loglik = -5946.8024
Iter 42: sigma_u = 3.1242, loglik = -5946.8324
Iter 43: sigma_u = 3.1242, loglik = -5946.8454
Iter 44: sigma_u = 3.1241, loglik = -5946.8669
Iter 45: sigma_u = 3.1241, loglik = -5946.8766
Iter 46: sigma_u = 3.1241, loglik = -5946.8939
Iter 47: sigma_u = 3.1240, loglik = -5946.9010
Iter 48: sigma_u = 3.1240, loglik = -5946.9132
Iter 49: sigma_u = 3.1240, loglik = -5946.9192
Iter 50: sigma_u = 3.1240, loglik = -5946.9279
Iter 51: sigma_u = 3.1240, loglik = -5946.9323
✅ Converged at iteration 52
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0           -1.438      -1.409804    -1.387146
1            4.847       4.709009     4.624068
2           -0.444      -0.407519    -0.398340
3            1.200       1.193965     3.123954



Time taken 0.4789510210355123 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.7587, loglik = -26093.4776
Iter 1: sigma_u = 0.8169, loglik = -24406.4371
Iter 2: sigma_u = 0.8783, loglik = -23209.6193
Iter 3: sigma_u = 0.9433, loglik = -22210.7496
Iter 4: sigma_u = 1.0125, loglik = -21350.6535
Iter 5: sigma_u = 1.0863, loglik = -20605.6555
Iter 6: sigma_u = 1.1651, loglik = -19959.4308
Iter 7: sigma_u = 1.2492, loglik = -19398.3760
Iter 8: sigma_u = 1.3392, loglik = -18910.9597
Iter 9: sigma_u = 1.4354, loglik = -18487.2676
Iter 10: sigma_u = 1.5383, loglik = -18118.7714
Iter 11: sigma_u = 1.6483, loglik = -17798.1411
Iter 12: sigma_u = 1.7659, loglik = -17519.0883
Iter 13: sigma_u = 1.8914, loglik = -17276.2089
Iter 14: sigma_u = 2.0250, loglik = -17064.7897
Iter 15: sigma_u = 2.1655, loglik = -16880.6301
Iter 16: sigma_u = 2.3100, loglik = -16720.0420
Iter 17: sigma_u = 2.4524, loglik = -16580.0683
Iter 18: sigma_u = 2.5837, loglik = -16459.0371
Iter 19: sigma_u = 2.6951, loglik = -16356.9812
Iter 20: sigma_u = 2.7818, loglik = -16274.9188
Iter 21: sigma_u = 2.8441, loglik = -16212.9714
Iter 22: sigma_u = 2.8864, loglik = -16169.1074
Iter 23: sigma_u = 2.9138, loglik = -16139.6539
Iter 24: sigma_u = 2.9311, loglik = -16120.6280
Iter 25: sigma_u = 2.9419, loglik = -16108.6513
Iter 26: sigma_u = 2.9485, loglik = -16101.2157
Iter 27: sigma_u = 2.9525, loglik = -16096.6676
Iter 28: sigma_u = 2.9548, loglik = -16093.9050
Iter 29: sigma_u = 2.9562, loglik = -16092.3133
Iter 30: sigma_u = 2.9570, loglik = -16091.3912
Iter 31: sigma_u = 2.9575, loglik = -16090.8252
Iter 32: sigma_u = 2.9579, loglik = -16090.4589
Iter 33: sigma_u = 2.9581, loglik = -16090.2072
Iter 34: sigma_u = 2.9584, loglik = -16090.0341
Iter 35: sigma_u = 2.9584, loglik = -16089.8783
Iter 36: sigma_u = 2.9585, loglik = -16089.8303
Iter 37: sigma_u = 2.9585, loglik = -16089.8160
Iter 38: sigma_u = 2.9585, loglik = -16089.7714
Iter 39: sigma_u = 2.9585, loglik = -16089.7623
Iter 40: sigma_u = 2.9586, loglik = -16089.7553
✅ Converged at iteration 41
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            1.476       1.476516     1.444462
1           -0.151      -0.165488    -0.161514
2           -1.735      -1.747356    -1.728607
3            1.200       1.212734     2.958564



Time taken 0.49351595242818197 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.8182, loglik = -21443.5265
Iter 1: sigma_u = 0.8825, loglik = -19615.3125
Iter 2: sigma_u = 0.9474, loglik = -18650.4974
Iter 3: sigma_u = 1.0143, loglik = -17856.2913
Iter 4: sigma_u = 1.0848, loglik = -17161.8000
Iter 5: sigma_u = 1.1596, loglik = -16553.0161
Iter 6: sigma_u = 1.2390, loglik = -16020.2269
Iter 7: sigma_u = 1.3236, loglik = -15553.8162
Iter 8: sigma_u = 1.4138, loglik = -15145.4221
Iter 9: sigma_u = 1.5099, loglik = -14787.6966
Iter 10: sigma_u = 1.6123, loglik = -14474.2423
Iter 11: sigma_u = 1.7215, loglik = -14199.5405
Iter 12: sigma_u = 1.8378, loglik = -13958.8942
Iter 13: sigma_u = 1.9615, loglik = -13748.4363
Iter 14: sigma_u = 2.0924, loglik = -13565.0878
Iter 15: sigma_u = 2.2298, loglik = -13406.3501
Iter 16: sigma_u = 2.3723, loglik = -13269.9150
Iter 17: sigma_u = 2.5162, loglik = -13153.3310
Iter 18: sigma_u = 2.6557, loglik = -13054.0678
Iter 19: sigma_u = 2.7832, loglik = -12970.0216
Iter 20: sigma_u = 2.8917, loglik = -12899.9345
Iter 21: sigma_u = 2.9778, loglik = -12843.3328
Iter 22: sigma_u = 3.0421, loglik = -12799.5981
Iter 23: sigma_u = 3.0879, loglik = -12767.3363
Iter 24: sigma_u = 3.1195, loglik = -12744.4626
Iter 25: sigma_u = 3.1408, loglik = -12728.7451
Iter 26: sigma_u = 3.1550, loglik = -12718.1463
Iter 27: sigma_u = 3.1645, loglik = -12711.0990
Iter 28: sigma_u = 3.1707, loglik = -12706.4238
Iter 29: sigma_u = 3.1748, loglik = -12703.3569
Iter 30: sigma_u = 3.1772, loglik = -12701.3456
Iter 31: sigma_u = 3.1789, loglik = -12700.1315
Iter 32: sigma_u = 3.1801, loglik = -12699.3075
Iter 33: sigma_u = 3.1806, loglik = -12698.7268
Iter 34: sigma_u = 3.1811, loglik = -12698.4628
Iter 35: sigma_u = 3.1813, loglik = -12698.1808
Iter 36: sigma_u = 3.1815, loglik = -12698.1240
Iter 37: sigma_u = 3.1816, loglik = -12698.0095
Iter 38: sigma_u = 3.1817, loglik = -12697.9434
Iter 39: sigma_u = 3.1819, loglik = -12697.8980
Iter 40: sigma_u = 3.1820, loglik = -12697.7843
Iter 41: sigma_u = 3.1820, loglik = -12697.7644
Iter 42: sigma_u = 3.1821, loglik = -12697.7446
Iter 43: sigma_u = 3.1821, loglik = -12697.7000
Iter 44: sigma_u = 3.1822, loglik = -12697.7008
Iter 45: sigma_u = 3.1822, loglik = -12697.6803
Iter 46: sigma_u = 3.1822, loglik = -12697.6797
Iter 47: sigma_u = 3.1822, loglik = -12697.6685
Iter 48: sigma_u = 3.1822, loglik = -12697.6646
Iter 49: sigma_u = 3.1823, loglik = -12697.6584
✅ Converged at iteration 50
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             2.50       2.488176     2.454494
1             0.45       0.430351     0.417265
2             0.25       0.227002     0.216177
3            -1.20      -1.185579    -1.166717
4             1.20       1.218694     3.182253



Time taken 0.7261964639027914 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.3241, loglik = -17800.0685
Iter 1: sigma_u = 1.4062, loglik = -17409.2398
Iter 2: sigma_u = 1.4924, loglik = -17080.5315
Iter 3: sigma_u = 1.5836, loglik = -16792.1943
Iter 4: sigma_u = 1.6802, loglik = -16536.8525
Iter 5: sigma_u = 1.7824, loglik = -16310.2742
Iter 6: sigma_u = 1.8905, loglik = -16109.1482
Iter 7: sigma_u = 2.0046, loglik = -15930.6005
Iter 8: sigma_u = 2.1241, loglik = -15772.1335
Iter 9: sigma_u = 2.2476, loglik = -15631.6453
Iter 10: sigma_u = 2.3718, loglik = -15507.4363
Iter 11: sigma_u = 2.4915, loglik = -15398.3117
Iter 12: sigma_u = 2.6006, loglik = -15303.8140
Iter 13: sigma_u = 2.6936, loglik = -15224.0494
Iter 14: sigma_u = 2.7676, loglik = -15159.3635
Iter 15: sigma_u = 2.8230, loglik = -15109.4004
Iter 16: sigma_u = 2.8627, loglik = -15072.5730
Iter 17: sigma_u = 2.8900, loglik = -15046.5235
Iter 18: sigma_u = 2.9084, loglik = -15028.6661
Iter 19: sigma_u = 2.9206, loglik = -15016.7071
Iter 20: sigma_u = 2.9285, loglik = -15008.8248
Iter 21: sigma_u = 2.9337, loglik = -15003.6816
Iter 22: sigma_u = 2.9369, loglik = -15000.3497
Iter 23: sigma_u = 2.9389, loglik = -14998.2829
Iter 24: sigma_u = 2.9403, loglik = -14996.9532
Iter 25: sigma_u = 2.9411, loglik = -14996.0753
Iter 26: sigma_u = 2.9417, loglik = -14995.5380
Iter 27: sigma_u = 2.9421, loglik = -14995.1598
Iter 28: sigma_u = 2.9424, loglik = -14994.9013
Iter 29: sigma_u = 2.9426, loglik = -14994.7135
Iter 30: sigma_u = 2.9427, loglik = -14994.5780
Iter 31: sigma_u = 2.9428, loglik = -14994.5095
Iter 32: sigma_u = 2.9428, loglik = -14994.4458
Iter 33: sigma_u = 2.9429, loglik = -14994.4237
Iter 34: sigma_u = 2.9429, loglik = -14994.3874
Iter 35: sigma_u = 2.9429, loglik = -14994.3820
Iter 36: sigma_u = 2.9429, loglik = -14994.3739
Iter 37: sigma_u = 2.9429, loglik = -14994.3590
✅ Converged at iteration 38
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              0.8       0.790720     0.769312
1             -0.9      -0.893298    -0.879659
2              0.5       0.497390     0.488140
3             -1.7      -1.684633    -1.653679
4              1.2       1.189074     2.942939



Time taken 0.5283913175264995 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 2.2999, loglik = -11782.7748
Iter 1: sigma_u = 2.4070, loglik = -11638.9205
Iter 2: sigma_u = 2.5123, loglik = -11550.7236
Iter 3: sigma_u = 2.6138, loglik = -11476.0511
Iter 4: sigma_u = 2.7082, loglik = -11410.3891
Iter 5: sigma_u = 2.7923, loglik = -11353.2707
Iter 6: sigma_u = 2.8638, loglik = -11304.7229
Iter 7: sigma_u = 2.9222, loglik = -11264.6628
Iter 8: sigma_u = 2.9681, loglik = -11232.6486
Iter 9: sigma_u = 3.0031, loglik = -11207.8316
Iter 10: sigma_u = 3.0292, loglik = -11189.0724
Iter 11: sigma_u = 3.0483, loglik = -11175.1786
Iter 12: sigma_u = 3.0621, loglik = -11165.0481
Iter 13: sigma_u = 3.0720, loglik = -11157.7460
Iter 14: sigma_u = 3.0790, loglik = -11152.5331
Iter 15: sigma_u = 3.0839, loglik = -11148.8429
Iter 16: sigma_u = 3.0874, loglik = -11146.2571
Iter 17: sigma_u = 3.0899, loglik = -11144.4062
Iter 18: sigma_u = 3.0917, loglik = -11143.0782
Iter 19: sigma_u = 3.0927, loglik = -11142.1483
Iter 20: sigma_u = 3.0934, loglik = -11141.6296
Iter 21: sigma_u = 3.0940, loglik = -11141.2418
Iter 22: sigma_u = 3.0944, loglik = -11140.9445
Iter 23: sigma_u = 3.0947, loglik = -11140.7173
Iter 24: sigma_u = 3.0951, loglik = -11140.5613
Iter 25: sigma_u = 3.0953, loglik = -11140.3796
Iter 26: sigma_u = 3.0955, loglik = -11140.2570
Iter 27: sigma_u = 3.0956, loglik = -11140.1522
Iter 28: sigma_u = 3.0956, loglik = -11140.1205
Iter 29: sigma_u = 3.0957, loglik = -11140.0940
Iter 30: sigma_u = 3.0957, loglik = -11140.0667
Iter 31: sigma_u = 3.0957, loglik = -11140.0510
Iter 32: sigma_u = 3.0958, loglik = -11140.0410
Iter 33: sigma_u = 3.0958, loglik = -11140.0261
✅ Converged at iteration 34
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              1.8       1.784587     1.750471
1             -2.1      -2.076020    -2.043686
2             -0.5      -0.484531    -0.472671
3             -1.7      -1.739061    -1.703288
4              1.2       1.190422     3.095757



Time taken 0.5887140353520711 minutes



Initial sigma: 1.2

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.3491, loglik = -16352.2814
Iter 1: sigma_u = 1.4308, loglik = -15956.7759
Iter 2: sigma_u = 1.5160, loglik = -15650.4549
Iter 3: sigma_u = 1.6057, loglik = -15382.0266
Iter 4: sigma_u = 1.7003, loglik = -15143.1196
Iter 5: sigma_u = 1.8002, loglik = -14930.2897
Iter 6: sigma_u = 1.9056, loglik = -14740.6003
Iter 7: sigma_u = 2.0166, loglik = -14571.5591
Iter 8: sigma_u = 2.1330, loglik = -14420.8125
Iter 9: sigma_u = 2.2540, loglik = -14286.2680
Iter 10: sigma_u = 2.3775, loglik = -14166.1753
Iter 11: sigma_u = 2.4996, loglik = -14059.2111
Iter 12: sigma_u = 2.6149, loglik = -13964.7807
Iter 13: sigma_u = 2.7175, loglik = -13883.0199
Iter 14: sigma_u = 2.8030, loglik = -13814.5120
Iter 15: sigma_u = 2.8700, loglik = -13759.5604
Iter 16: sigma_u = 2.9198, loglik = -13717.4972
Iter 17: sigma_u = 2.9554, loglik = -13686.6670
Iter 18: sigma_u = 2.9800, loglik = -13664.8569
Iter 19: sigma_u = 2.9967, loglik = -13649.8319
Iter 20: sigma_u = 3.0081, loglik = -13639.6676
Iter 21: sigma_u = 3.0155, loglik = -13632.8153
Iter 22: sigma_u = 3.0204, loglik = -13628.2975
Iter 23: sigma_u = 3.0234, loglik = -13625.3421
Iter 24: sigma_u = 3.0253, loglik = -13623.5005
Iter 25: sigma_u = 3.0265, loglik = -13622.3844
Iter 26: sigma_u = 3.0274, loglik = -13621.6335
Iter 27: sigma_u = 3.0280, loglik = -13621.1154
Iter 28: sigma_u = 3.0284, loglik = -13620.7625
Iter 29: sigma_u = 3.0288, loglik = -13620.4994
Iter 30: sigma_u = 3.0290, loglik = -13620.2874
Iter 31: sigma_u = 3.0291, loglik = -13620.1680
Iter 32: sigma_u = 3.0292, loglik = -13620.1041
Iter 33: sigma_u = 3.0292, loglik = -13620.0347
Iter 34: sigma_u = 3.0293, loglik = -13620.0052
Iter 35: sigma_u = 3.0293, loglik = -13619.9749
Iter 36: sigma_u = 3.0293, loglik = -13619.9584
Iter 37: sigma_u = 3.0293, loglik = -13619.9413
Iter 38: sigma_u = 3.0294, loglik = -13619.9317
✅ Converged at iteration 39
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            -1.24      -1.205926    -1.181565
1             1.17       1.154209     1.134927
2            -1.04      -1.072491    -1.052914
3             0.97       0.959146     0.945406
4             1.20       1.194669     3.029366



Time taken 0.7106805682182312 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.6300, loglik = -43486.4136
Iter 1: sigma_u = 0.9041, loglik = -29208.9552
Iter 2: sigma_u = 1.2919, loglik = -21934.3746
Iter 3: sigma_u = 1.8427, loglik = -18322.9506
Iter 4: sigma_u = 2.6341, loglik = -16537.5767
Iter 5: sigma_u = 3.7103, loglik = -15469.7247
Iter 6: sigma_u = 4.4457, loglik = -14397.0915
Iter 7: sigma_u = 4.7032, loglik = -13890.9195
Iter 8: sigma_u = 4.7746, loglik = -13752.5532
Iter 9: sigma_u = 4.7933, loglik = -13717.3163
Iter 10: sigma_u = 4.7982, loglik = -13708.3509
Iter 11: sigma_u = 4.7993, loglik = -13705.9875
Iter 12: sigma_u = 4.7995, loglik = -13705.4407
Iter 13: sigma_u = 4.7996, loglik = -13705.3424
Iter 14: sigma_u = 4.7995, loglik = -13705.2891
Iter 15: sigma_u = 4.7996, loglik = -13705.3373
Iter 16: sigma_u = 4.7995, loglik = -13705.2856
Iter 17: sigma_u = 4.7996, loglik = -13705.3348
Iter 18: sigma_u = 4.7995, loglik = -13705.2910
Iter 19: sigma_u = 4.7996, loglik = -13705.3307
Iter 20: sigma_u = 4.7996, loglik = -13705.2972
Iter 21: sigma_u = 4.7997, loglik = -13705.2903
Iter 22: sigma_u = 4.7997, loglik = -13705.2778
Iter 23: sigma_u = 4.7997, loglik = -13705.2604
Iter 24: sigma_u = 4.7997, loglik = -13705.2713
Iter 25: sigma_u = 4.7997, loglik = -13705.2618
Iter 26: sigma_u = 4.7997, loglik = -13705.2675
✅ Converged at iteration 27
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              0.5       0.519852     0.499466
1              0.5       0.477102     0.440624
2             -1.2      -1.178199    -1.105018
3              2.5       2.417661     4.799693



Time taken 0.3802985986073812 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.8793, loglik = -26782.7982
Iter 1: sigma_u = 1.2659, loglik = -19077.1379
Iter 2: sigma_u = 1.8066, loglik = -15412.8160
Iter 3: sigma_u = 2.5633, loglik = -13597.6488
Iter 4: sigma_u = 3.5319, loglik = -12733.5090
Iter 5: sigma_u = 4.4198, loglik = -12300.8061
Iter 6: sigma_u = 4.9105, loglik = -11677.8769
Iter 7: sigma_u = 5.1099, loglik = -11350.9639
Iter 8: sigma_u = 5.1765, loglik = -11228.3911
Iter 9: sigma_u = 5.1945, loglik = -11184.3478
Iter 10: sigma_u = 5.1969, loglik = -11168.5326
Iter 11: sigma_u = 5.1953, loglik = -11162.7740
Iter 12: sigma_u = 5.1931, loglik = -11160.5958
Iter 13: sigma_u = 5.1914, loglik = -11159.7083
Iter 14: sigma_u = 5.1901, loglik = -11159.3163
Iter 15: sigma_u = 5.1891, loglik = -11159.1481
Iter 16: sigma_u = 5.1885, loglik = -11159.0937
Iter 17: sigma_u = 5.1881, loglik = -11159.0468
Iter 18: sigma_u = 5.1882, loglik = -11159.0142
Iter 19: sigma_u = 5.1880, loglik = -11158.8823
Iter 20: sigma_u = 5.1881, loglik = -11158.9133
Iter 21: sigma_u = 5.1878, loglik = -11158.8311
Iter 22: sigma_u = 5.1879, loglik = -11158.9667
Iter 23: sigma_u = 5.1879, loglik = -11158.9010
Iter 24: sigma_u = 5.1877, loglik = -11158.8442
Iter 25: sigma_u = 5.1878, loglik = -11158.9240
Iter 26: sigma_u = 5.1876, loglik = -11158.8780
Iter 27: sigma_u = 5.1877, loglik = -11158.9475
Iter 28: sigma_u = 5.1877, loglik = -11158.9117
Iter 29: sigma_u = 5.1877, loglik = -11158.8757
Iter 30: sigma_u = 5.1877, loglik = -11158.9195
Iter 31: sigma_u = 5.1876, loglik = -11158.8942
Iter 32: sigma_u = 5.1877, loglik = -11158.9058
Iter 33: sigma_u = 5.1876, loglik = -11158.8929
✅ Converged at iteration 34
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              1.5       1.526887     1.146008
1             -0.8      -0.774911    -0.634924
2              1.3       1.280483     1.045416
3              2.5       2.559852     5.187636



Time taken 0.49364026784896853 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 3.7921, loglik = -7603.8125
Iter 1: sigma_u = 4.2932, loglik = -7319.2808
Iter 2: sigma_u = 4.6292, loglik = -7114.6702
Iter 3: sigma_u = 4.8349, loglik = -6987.1261
Iter 4: sigma_u = 4.9537, loglik = -6913.6907
Iter 5: sigma_u = 5.0199, loglik = -6872.9551
Iter 6: sigma_u = 5.0561, loglik = -6850.7879
Iter 7: sigma_u = 5.0756, loglik = -6838.8447
Iter 8: sigma_u = 5.0860, loglik = -6832.4587
Iter 9: sigma_u = 5.0916, loglik = -6829.0510
Iter 10: sigma_u = 5.0946, loglik = -6827.2353
Iter 11: sigma_u = 5.0962, loglik = -6826.2691
Iter 12: sigma_u = 5.0968, loglik = -6825.7332
Iter 13: sigma_u = 5.0970, loglik = -6825.5326
Iter 14: sigma_u = 5.0975, loglik = -6825.4569
Iter 15: sigma_u = 5.0974, loglik = -6825.3199
Iter 16: sigma_u = 5.0976, loglik = -6825.3597
Iter 17: sigma_u = 5.0975, loglik = -6825.2875
Iter 18: sigma_u = 5.0976, loglik = -6825.3215
Iter 19: sigma_u = 5.0976, loglik = -6825.2691
Iter 20: sigma_u = 5.0977, loglik = -6825.2940
Iter 21: sigma_u = 5.0977, loglik = -6825.2415
Iter 22: sigma_u = 5.0977, loglik = -6825.2661
Iter 23: sigma_u = 5.0977, loglik = -6825.2345
Iter 24: sigma_u = 5.0978, loglik = -6825.2495
Iter 25: sigma_u = 5.0978, loglik = -6825.2319
Iter 26: sigma_u = 5.0978, loglik = -6825.2363
Iter 27: sigma_u = 5.0979, loglik = -6825.2202
Iter 28: sigma_u = 5.0978, loglik = -6825.1991
Iter 29: sigma_u = 5.0979, loglik = -6825.2090
Iter 30: sigma_u = 5.0979, loglik = -6825.1967
Iter 31: sigma_u = 5.0979, loglik = -6825.2026
Iter 32: sigma_u = 5.0979, loglik = -6825.1954
Iter 33: sigma_u = 5.0979, loglik = -6825.1975
Iter 34: sigma_u = 5.0979, loglik = -6825.1910
✅ Converged at iteration 35
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0           -1.438      -1.358913    -1.117127
1            4.847       4.710092     3.838733
2           -0.444      -0.504660    -0.396509
3            2.500       2.478351     5.097914



Time taken 0.3630268017450968 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.6845, loglik = -39675.3423
Iter 1: sigma_u = 0.9896, loglik = -26677.1631
Iter 2: sigma_u = 1.4239, loglik = -20374.8064
Iter 3: sigma_u = 2.0444, loglik = -17312.8994
Iter 4: sigma_u = 2.9441, loglik = -15807.2070
Iter 5: sigma_u = 4.0460, loglik = -14781.0033
Iter 6: sigma_u = 4.6628, loglik = -13789.9868
Iter 7: sigma_u = 4.8658, loglik = -13401.4372
Iter 8: sigma_u = 4.9216, loglik = -13296.0225
Iter 9: sigma_u = 4.9362, loglik = -13268.0736
Iter 10: sigma_u = 4.9398, loglik = -13260.4088
Iter 11: sigma_u = 4.9406, loglik = -13258.1250
Iter 12: sigma_u = 4.9408, loglik = -13257.4302
Iter 13: sigma_u = 4.9405, loglik = -13257.1354
Iter 14: sigma_u = 4.9407, loglik = -13257.1655
Iter 15: sigma_u = 4.9406, loglik = -13256.9751
Iter 16: sigma_u = 4.9407, loglik = -13256.9556
Iter 17: sigma_u = 4.9408, loglik = -13256.8956
Iter 18: sigma_u = 4.9407, loglik = -13256.8390
Iter 19: sigma_u = 4.9407, loglik = -13256.8787
Iter 20: sigma_u = 4.9406, loglik = -13256.8462
Iter 21: sigma_u = 4.9407, loglik = -13256.8929
Iter 22: sigma_u = 4.9406, loglik = -13256.8620
Iter 23: sigma_u = 4.9406, loglik = -13256.9096
Iter 24: sigma_u = 4.9406, loglik = -13256.8844
Iter 25: sigma_u = 4.9406, loglik = -13256.8866
Iter 26: sigma_u = 4.9405, loglik = -13256.9108
Iter 27: sigma_u = 4.9405, loglik = -13256.9127
✅ Converged at iteration 28
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            1.476       1.455275     1.258975
1           -0.151      -0.158543    -0.138383
2           -1.735      -1.699954    -1.597066
3            2.500       2.478714     4.940528



Time taken 0.3408284505208333 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 0.7482, loglik = -34652.3292
Iter 1: sigma_u = 1.1000, loglik = -22703.3426
Iter 2: sigma_u = 1.6028, loglik = -17404.4864
Iter 3: sigma_u = 2.3219, loglik = -14899.0107
Iter 4: sigma_u = 3.2967, loglik = -13728.9544
Iter 5: sigma_u = 4.3560, loglik = -13171.7098
Iter 6: sigma_u = 4.9670, loglik = -12351.4759
Iter 7: sigma_u = 5.1958, loglik = -11939.4020
Iter 8: sigma_u = 5.2627, loglik = -11799.0027
Iter 9: sigma_u = 5.2775, loglik = -11751.9918
Iter 10: sigma_u = 5.2780, loglik = -11735.4884
Iter 11: sigma_u = 5.2755, loglik = -11729.2183
Iter 12: sigma_u = 5.2731, loglik = -11726.5873
Iter 13: sigma_u = 5.2714, loglik = -11725.3393
Iter 14: sigma_u = 5.2703, loglik = -11724.6845
Iter 15: sigma_u = 5.2698, loglik = -11724.3156
Iter 16: sigma_u = 5.2692, loglik = -11724.0405
Iter 17: sigma_u = 5.2691, loglik = -11723.9384
Iter 18: sigma_u = 5.2691, loglik = -11723.8277
Iter 19: sigma_u = 5.2692, loglik = -11723.7114
Iter 20: sigma_u = 5.2690, loglik = -11723.6295
Iter 21: sigma_u = 5.2690, loglik = -11723.6748
Iter 22: sigma_u = 5.2687, loglik = -11723.6176
Iter 23: sigma_u = 5.2688, loglik = -11723.7275
Iter 24: sigma_u = 5.2685, loglik = -11723.6691
Iter 25: sigma_u = 5.2686, loglik = -11723.7980
Iter 26: sigma_u = 5.2686, loglik = -11723.7517
Iter 27: sigma_u = 5.2685, loglik = -11723.7203
Iter 28: sigma_u = 5.2685, loglik = -11723.7306
Iter 29: sigma_u = 5.2685, loglik = -11723.7518
Iter 30: sigma_u = 5.2684, loglik = -11723.7408
Iter 31: sigma_u = 5.2684, loglik = -11723.7605
Iter 32: sigma_u = 5.2685, loglik = -11723.7510
Iter 33: sigma_u = 5.2684, loglik = -11723.7407
Iter 34: sigma_u = 5.2684, loglik = -11723.7529
Iter 35: sigma_u = 5.2684, loglik = -11723.7450
✅ Converged at iteration 36
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0             2.50       2.535221     2.012771
1             0.45       0.437287     0.370502
2             0.25       0.285192     0.239046
3            -1.20      -1.222261    -1.084175
4             2.50       2.626842     5.268425



Time taken 0.6455079833666484 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.1977, loglik = -22024.5954
Iter 1: sigma_u = 1.7037, loglik = -17942.4495
Iter 2: sigma_u = 2.4186, loglik = -15893.2071
Iter 3: sigma_u = 3.4374, loglik = -14823.8873
Iter 4: sigma_u = 4.3826, loglik = -13849.4648
Iter 5: sigma_u = 4.8089, loglik = -13148.3840
Iter 6: sigma_u = 4.9482, loglik = -12916.7695
Iter 7: sigma_u = 4.9891, loglik = -12850.8232
Iter 8: sigma_u = 5.0007, loglik = -12832.3488
Iter 9: sigma_u = 5.0042, loglik = -12827.2012
Iter 10: sigma_u = 5.0048, loglik = -12825.6593
Iter 11: sigma_u = 5.0050, loglik = -12825.3728
Iter 12: sigma_u = 5.0052, loglik = -12825.2997
Iter 13: sigma_u = 5.0051, loglik = -12825.2244
Iter 14: sigma_u = 5.0052, loglik = -12825.2898
Iter 15: sigma_u = 5.0051, loglik = -12825.2287
Iter 16: sigma_u = 5.0052, loglik = -12825.2746
Iter 17: sigma_u = 5.0053, loglik = -12825.2236
Iter 18: sigma_u = 5.0052, loglik = -12825.1877
Iter 19: sigma_u = 5.0053, loglik = -12825.2222
Iter 20: sigma_u = 5.0054, loglik = -12825.1938
Iter 21: sigma_u = 5.0053, loglik = -12825.1527
Iter 22: sigma_u = 5.0054, loglik = -12825.1738
Iter 23: sigma_u = 5.0053, loglik = -12825.1552
Iter 24: sigma_u = 5.0054, loglik = -12825.1681
✅ Converged at iteration 25
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              0.8       0.824088     0.709647
1             -0.9      -0.902246    -0.810154
2              0.5       0.427695     0.368811
3             -1.7      -1.664422    -1.434758
4              2.5       2.501432     5.005354



Time taken 0.49281193415323893 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 2.0317, loglik = -14471.5337
Iter 1: sigma_u = 2.7869, loglik = -13190.4788
Iter 2: sigma_u = 3.7505, loglik = -12505.2618
Iter 3: sigma_u = 4.5391, loglik = -11855.9586
Iter 4: sigma_u = 4.9519, loglik = -11372.4632
Iter 5: sigma_u = 5.1267, loglik = -11170.2154
Iter 6: sigma_u = 5.1939, loglik = -11094.3930
Iter 7: sigma_u = 5.2187, loglik = -11066.6458
Iter 8: sigma_u = 5.2278, loglik = -11056.5747
Iter 9: sigma_u = 5.2311, loglik = -11052.9313
Iter 10: sigma_u = 5.2318, loglik = -11051.6153
Iter 11: sigma_u = 5.2323, loglik = -11051.3037
Iter 12: sigma_u = 5.2325, loglik = -11051.1078
Iter 13: sigma_u = 5.2324, loglik = -11051.0319
Iter 14: sigma_u = 5.2326, loglik = -11051.0560
Iter 15: sigma_u = 5.2327, loglik = -11051.0034
Iter 16: sigma_u = 5.2326, loglik = -11050.9405
Iter 17: sigma_u = 5.2327, loglik = -11050.9799
Iter 18: sigma_u = 5.2327, loglik = -11050.9402
Iter 19: sigma_u = 5.2327, loglik = -11050.9707
Iter 20: sigma_u = 5.2328, loglik = -11050.9409
Iter 21: sigma_u = 5.2328, loglik = -11050.9277
Iter 22: sigma_u = 5.2329, loglik = -11050.9042
Iter 23: sigma_u = 5.2329, loglik = -11050.8927
Iter 24: sigma_u = 5.2329, loglik = -11050.8752
Iter 25: sigma_u = 5.2329, loglik = -11050.8890
Iter 26: sigma_u = 5.2329, loglik = -11050.8778
Iter 27: sigma_u = 5.2329, loglik = -11050.8863
Iter 28: sigma_u = 5.2329, loglik = -11050.8788
Iter 29: sigma_u = 5.2329, loglik = -11050.8849
Iter 30: sigma_u = 5.2329, loglik = -11050.8795
✅ Converged at iteration 31
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0              1.8       1.784960     1.471855
1             -2.1      -2.087634    -1.780872
2             -0.5      -0.505121    -0.430353
3             -1.7      -1.673595    -1.386824
4              2.5       2.525109     5.232879



Time taken 0.5352632999420166 minutes



Initial sigma: 2.5

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3121810126.py:139: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_better, args=(X, y, groups, n_individuals),
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/2261307601.py:79: OptimizeWarning: Unknown solver options: verbose
  res = minimize(

Iter 0: sigma_u = 1.2183, loglik = -20935.1377
Iter 1: sigma_u = 1.7206, loglik = -17141.3292
Iter 2: sigma_u = 2.4220, loglik = -15212.9857
Iter 3: sigma_u = 3.3878, loglik = -14213.7177
Iter 4: sigma_u = 4.3228, loglik = -13443.5205
Iter 5: sigma_u = 4.7975, loglik = -12752.8224
Iter 6: sigma_u = 4.9740, loglik = -12476.3207
Iter 7: sigma_u = 5.0326, loglik = -12385.1915
Iter 8: sigma_u = 5.0514, loglik = -12355.0518
Iter 9: sigma_u = 5.0574, loglik = -12344.6670
Iter 10: sigma_u = 5.0594, loglik = -12340.8489
Iter 11: sigma_u = 5.0600, loglik = -12339.3191
Iter 12: sigma_u = 5.0603, loglik = -12338.6491
Iter 13: sigma_u = 5.0604, loglik = -12338.3143
Iter 14: sigma_u = 5.0603, loglik = -12338.1531
Iter 15: sigma_u = 5.0604, loglik = -12338.0977
Iter 16: sigma_u = 5.0605, loglik = -12338.0452
Iter 17: sigma_u = 5.0605, loglik = -12337.9666
Iter 18: sigma_u = 5.0606, loglik = -12337.9681
Iter 19: sigma_u = 5.0605, loglik = -12337.9199
Iter 20: sigma_u = 5.0605, loglik = -12337.9676
Iter 21: sigma_u = 5.0604, loglik = -12337.9338
Iter 22: sigma_u = 5.0605, loglik = -12337.9831
Iter 23: sigma_u = 5.0605, loglik = -12337.9548
Iter 24: sigma_u = 5.0605, loglik = -12337.9324
Iter 25: sigma_u = 5.0605, loglik = -12337.9580
Iter 26: sigma_u = 5.0604, loglik = -12337.9405
Iter 27: sigma_u = 5.0605, loglik = -12337.9632
Iter 28: sigma_u = 5.0605, loglik = -12337.9490
Iter 29: sigma_u = 5.0605, loglik = -12337.9422
Iter 30: sigma_u = 5.0605, loglik = -12337.9517
Iter 31: sigma_u = 5.0605, loglik = -12337.9446
✅ Converged at iteration 32
Final Parameter estimates GHQ vs EM (i.e., for round of set of true parameters):

   True parameters  Estimates GHQ  Estimate EM
0            -1.24      -1.149517    -0.865695
1             1.17       1.159480     1.020438
2            -1.04      -1.117443    -0.967475
3             0.97       0.950702     0.832605
4             2.50       2.485806     5.060457



Time taken 0.5661248207092285 minutes

In [6]:
# Saving the rsults of each simulation and benchmark above to a list

try:
    vec_update_tp_list_dat
except:
    vec_update_tp_list_dat = []

for j in range(len(B_Res_simul_synth3)):

    update_tp_list_dat = []
    tp_list_dat =[B_Res_simul_synth3[j][i][0] for i in range(len(B_Res_simul_synth3[j]))]

    for dat in tp_list_dat:

        if dat.shape[0] == 4:
            dat.index = ['beta_0', 'beta_1', 'beta_2', 'sigma_u']
        else:
            dat.index = ['beta_0', 'beta_1', 'beta_2', 'beta_3', 'sigma_u']

        update_tp_list_dat.append(dat)
        
    vec_update_tp_list_dat.append(update_tp_list_dat)

In [7]:
'kokokaka'
vec_update_tp_list_dat[1]

[         True parameters  Estimates GHQ  Estimate EM
 beta_0               0.5       0.518098     0.518666
 beta_1               0.5       0.495437     0.495259
 beta_2              -1.2      -1.216457    -1.216541
 sigma_u              0.8       0.772839     0.213941,
          True parameters  Estimates GHQ  Estimate EM
 beta_0               1.5       1.464638     1.469740
 beta_1              -0.8      -0.822129    -0.823051
 beta_2               1.3       1.339157     1.341286
 sigma_u              0.8       0.788510     0.233045,
          True parameters  Estimates GHQ  Estimate EM
 beta_0            -1.438      -1.407220    -1.407471
 beta_1             4.847       4.755697     4.755374
 beta_2            -0.444      -0.411510    -0.410933
 sigma_u            0.800       0.842100     0.259174,
          True parameters  Estimates GHQ  Estimate EM
 beta_0             1.476       1.468188     1.467953
 beta_1            -0.151      -0.162452    -0.162284
 beta_2            -1.735      -1.753776    -1.754425
 sigma_u            0.800       0.814880     0.236234,
          True parameters  Estimates GHQ  Estimate EM
 beta_0              2.50       2.500865     2.503701
 beta_1              0.45       0.443395     0.443248
 beta_2              0.25       0.236074     0.235250
 beta_3             -1.20      -1.217272    -1.218038
 sigma_u             0.80       0.779917     0.223751,
          True parameters  Estimates GHQ  Estimate EM
 beta_0               0.8       0.761322     0.760007
 beta_1              -0.9      -0.898281    -0.897903
 beta_2               0.5       0.520934     0.520603
 beta_3              -1.7      -1.663235    -1.661603
 sigma_u              0.8       0.774902     0.216239,
          True parameters  Estimates GHQ  Estimate EM
 beta_0               1.8       1.819847     1.816181
 beta_1              -2.1      -2.115470    -2.111817
 beta_2              -0.5      -0.466894    -0.465904
 beta_3              -1.7      -1.753124    -1.749481
 sigma_u              0.8       0.835636     0.249287,
          True parameters  Estimates GHQ  Estimate EM
 beta_0             -1.24      -1.246589    -1.247010
 beta_1              1.17       1.156178     1.156315
 beta_2             -1.04      -1.030111    -1.030012
 beta_3              0.97       0.973267     0.973289
 sigma_u             0.80       0.815462     0.240070]

#### Transforming the list above into a table (This is TABLE 2.12 in my Thesis)

In [12]:
final_dat_compar_EM_GHQ =\
pd.concat([pd.concat(vec_update_tp_list_dat[0]),
           pd.concat(vec_update_tp_list_dat[1]),\
pd.concat(vec_update_tp_list_dat[2]), pd.concat(vec_update_tp_list_dat[3])], axis=1)


final_dat_compar_EM_GHQ.columns = ['TP', 'Est. GHQ', 'Est. EM', 'TP', 'Est. GHQ', 'Est. EM',
                                   'TP', 'Est. GHQ', 'Est. EM','TP', 'Est. GHQ', 'Est. EM']
final_dat_compar_EM_GHQ.index = ['$beta_0$', '$beta_1$', '$beta_2$', '$sigma_u$', '$beta_0$',
                                 '$beta_1$', '$beta_2$',
       '$sigma_u$', '$beta_0$', '$beta_1$', '$beta_2$', '$sigma_u$', '$beta_0$', '$beta_1$',
       '$beta_2$', '$sigma_u$', '$beta_0$', '$beta_1$', '$beta_2$', '$beta_3$', '$sigma_u$',
       '$beta_0$', '$beta_1$', '$beta_2$', '$beta_3$', '$sigma_u$', '$beta_0$', '$beta_1$',
       '$beta_2$', '$beta_3$', '$sigma_u$', '$beta_0$', '$beta_1$', '$beta_2$', '$beta_3$',
       '$sigma_u$']

print(final_dat_compar_EM_GHQ.to_latex(float_format='%.3f'))

\begin{tabular}{lrrrrrrrrrrrr}
\toprule
 & TP & Est. GHQ & Est. EM & TP & Est. GHQ & Est. EM & TP & Est. GHQ & Est. EM & TP & Est. GHQ & Est. EM \\
\midrule
$beta_0$ & 0.500 & 0.484 & 0.484 & 0.500 & 0.518 & 0.519 & 0.500 & 0.523 & 0.519 & 0.500 & 0.520 & 0.499 \\
$beta_1$ & 0.500 & 0.480 & 0.480 & 0.500 & 0.495 & 0.495 & 0.500 & 0.490 & 0.482 & 0.500 & 0.477 & 0.441 \\
$beta_2$ & -1.200 & -1.200 & -1.200 & -1.200 & -1.216 & -1.217 & -1.200 & -1.216 & -1.203 & -1.200 & -1.178 & -1.105 \\
$sigma_u$ & 0.250 & 0.284 & 0.066 & 0.800 & 0.773 & 0.214 & 1.200 & 1.175 & 2.837 & 2.500 & 2.418 & 4.800 \\
$beta_0$ & 1.500 & 1.446 & 1.449 & 1.500 & 1.465 & 1.470 & 1.500 & 1.506 & 1.511 & 1.500 & 1.527 & 1.146 \\
$beta_1$ & -0.800 & -0.816 & -0.817 & -0.800 & -0.822 & -0.823 & -0.800 & -0.822 & -0.802 & -0.800 & -0.775 & -0.635 \\
$beta_2$ & 1.300 & 1.400 & 1.402 & 1.300 & 1.339 & 1.341 & 1.300 & 1.325 & 1.292 & 1.300 & 1.280 & 1.045 \\
$sigma_u$ & 0.250 & 0.067 & 0.028 & 0.800 & 0.789 & 0.233 & 1.200 & 1.201 & 3.280 & 2.500 & 2.560 & 5.188 \\
$beta_0$ & -1.438 & -1.427 & -1.426 & -1.438 & -1.407 & -1.407 & -1.438 & -1.410 & -1.387 & -1.438 & -1.359 & -1.117 \\
$beta_1$ & 4.847 & 4.833 & 4.831 & 4.847 & 4.756 & 4.755 & 4.847 & 4.709 & 4.624 & 4.847 & 4.710 & 3.839 \\
$beta_2$ & -0.444 & -0.434 & -0.434 & -0.444 & -0.412 & -0.411 & -0.444 & -0.408 & -0.398 & -0.444 & -0.505 & -0.397 \\
$sigma_u$ & 0.250 & 0.411 & 0.097 & 0.800 & 0.842 & 0.259 & 1.200 & 1.194 & 3.124 & 2.500 & 2.478 & 5.098 \\
$beta_0$ & 1.476 & 1.462 & 1.462 & 1.476 & 1.468 & 1.468 & 1.476 & 1.477 & 1.444 & 1.476 & 1.455 & 1.259 \\
$beta_1$ & -0.151 & -0.164 & -0.164 & -0.151 & -0.162 & -0.162 & -0.151 & -0.165 & -0.162 & -0.151 & -0.159 & -0.138 \\
$beta_2$ & -1.735 & -1.758 & -1.758 & -1.735 & -1.754 & -1.754 & -1.735 & -1.747 & -1.729 & -1.735 & -1.700 & -1.597 \\
$sigma_u$ & 0.250 & 0.231 & 0.054 & 0.800 & 0.815 & 0.236 & 1.200 & 1.213 & 2.959 & 2.500 & 2.479 & 4.941 \\
$beta_0$ & 2.500 & 2.484 & 2.489 & 2.500 & 2.501 & 2.504 & 2.500 & 2.488 & 2.454 & 2.500 & 2.535 & 2.013 \\
$beta_1$ & 0.450 & 0.437 & 0.438 & 0.450 & 0.443 & 0.443 & 0.450 & 0.430 & 0.417 & 0.450 & 0.437 & 0.371 \\
$beta_2$ & 0.250 & 0.226 & 0.226 & 0.250 & 0.236 & 0.235 & 0.250 & 0.227 & 0.216 & 0.250 & 0.285 & 0.239 \\
$beta_3$ & -1.200 & -1.193 & -1.195 & -1.200 & -1.217 & -1.218 & -1.200 & -1.186 & -1.167 & -1.200 & -1.222 & -1.084 \\
$sigma_u$ & 0.250 & 0.068 & 0.027 & 0.800 & 0.780 & 0.224 & 1.200 & 1.219 & 3.182 & 2.500 & 2.627 & 5.268 \\
$beta_0$ & 0.800 & 0.761 & 0.762 & 0.800 & 0.761 & 0.760 & 0.800 & 0.791 & 0.769 & 0.800 & 0.824 & 0.710 \\
$beta_1$ & -0.900 & -0.889 & -0.890 & -0.900 & -0.898 & -0.898 & -0.900 & -0.893 & -0.880 & -0.900 & -0.902 & -0.810 \\
$beta_2$ & 0.500 & 0.499 & 0.499 & 0.500 & 0.521 & 0.521 & 0.500 & 0.497 & 0.488 & 0.500 & 0.428 & 0.369 \\
$beta_3$ & -1.700 & -1.642 & -1.642 & -1.700 & -1.663 & -1.662 & -1.700 & -1.685 & -1.654 & -1.700 & -1.664 & -1.435 \\
$sigma_u$ & 0.250 & 0.138 & 0.033 & 0.800 & 0.775 & 0.216 & 1.200 & 1.189 & 2.943 & 2.500 & 2.501 & 5.005 \\
$beta_0$ & 1.800 & 1.770 & 1.773 & 1.800 & 1.820 & 1.816 & 1.800 & 1.785 & 1.750 & 1.800 & 1.785 & 1.472 \\
$beta_1$ & -2.100 & -2.073 & -2.076 & -2.100 & -2.115 & -2.112 & -2.100 & -2.076 & -2.044 & -2.100 & -2.088 & -1.781 \\
$beta_2$ & -0.500 & -0.484 & -0.484 & -0.500 & -0.467 & -0.466 & -0.500 & -0.485 & -0.473 & -0.500 & -0.505 & -0.430 \\
$beta_3$ & -1.700 & -1.701 & -1.704 & -1.700 & -1.753 & -1.749 & -1.700 & -1.739 & -1.703 & -1.700 & -1.674 & -1.387 \\
$sigma_u$ & 0.250 & 0.083 & 0.030 & 0.800 & 0.836 & 0.249 & 1.200 & 1.190 & 3.096 & 2.500 & 2.525 & 5.233 \\
$beta_0$ & -1.240 & -1.216 & -1.216 & -1.240 & -1.247 & -1.247 & -1.240 & -1.206 & -1.182 & -1.240 & -1.150 & -0.866 \\
$beta_1$ & 1.170 & 1.161 & 1.161 & 1.170 & 1.156 & 1.156 & 1.170 & 1.154 & 1.135 & 1.170 & 1.159 & 1.020 \\
$beta_2$ & -1.040 & -1.059 & -1.059 & -1.040 & -1.030 & -1.030 & -1.040 & -1.072 & -1.053 & -1.040 & -1.117 & -0.967 \\
$beta_3$ & 0.970 & 0.969 & 0.969 & 0.970 & 0.973 & 0.973 & 0.970 & 0.959 & 0.945 & 0.970 & 0.951 & 0.833 \\
$sigma_u$ & 0.250 & 0.227 & 0.053 & 0.800 & 0.815 & 0.240 & 1.200 & 1.195 & 3.029 & 2.500 & 2.486 & 5.060 \\
\bottomrule
\end{tabular}

# 2. Other functions in the Thesis

- Due to a NDA with the company that provided the data. We are not allowed to provide but these functions can be easily extended to the simulated data above (constructed in the same format as the original data).
- **All numerical results provided below are to assist in testing the functinality of the codes, and make exploration easier and more intuitive; therefore they are not part of the thesis.**

- Below, we fix the simulation data to be the last one generated in the simulation study

- We need to add the unique event time per individual as well be able to track, therefore we complete the simulation data as follows:

In [14]:
#  Contenating corresponding individuals and response variable
tp_dat_X = pd.concat([pd.DataFrame(individual_ids), X, pd.DataFrame(y)],axis=1)

tp_dat_X.columns = ['sample_id', 'cons', 'X1', 'X2', 'X3','y']

# Adding unqiue time per event per individual 
tp_dat_X['times'] = tp_dat_X.groupby(['sample_id'])['cons'].cumcount()+1

In [15]:
tp_dat_X

       sample_id  cons        X1  X2        X3  y  times
0              0   1.0 -1.853012   1  0.862900  0      1
1              0   1.0 -0.958259   1  0.448140  0      2
2              0   1.0 -1.147509   0  0.131308  0      3
3              0   1.0  1.469742   1  0.244961  1      4
4              1   1.0  0.395480   1  0.722274  1      1
...          ...   ...       ...  ..       ... ..    ...
29898       9998   1.0 -0.692278   1  0.533335  0      3
29899       9998   1.0 -1.740829   0  1.259163  0      4
29900       9999   1.0  0.879946   0  0.548936  1      1
29901       9999   1.0  1.958406   0  0.318894  1      2
29902       9999   1.0  0.263911   1  1.388153  1      3

[29903 rows x 7 columns]

### 2.1.  Implementation of the objective function (negative marginal log-likelihood) using GHQ integration: Case of time-dependent linear frailties
- see section 2.5.2.4

In [16]:
def loglik_glmm_2d_ghq_vectorized(params, X, y, groups, n_individuals, times, n_quad=10):

    beta = params[:-2]  # Fixed effects
    log_sigma_a = params[-2]  # Log of sqrt(variance) for slope frailty
    log_sigma_b = params[-1]  # Log of sqrt(variance) for intercept frailty

    sigma_a = np.exp(log_sigma_a)
    sigma_b = np.exp(log_sigma_b)

    n_obs = X.shape[0]

    # Gauss-Hermite quadrature nodes and weights
    ghq_points_a, ghq_weights_a = hermgauss(n_quad)
    ghq_points_b, ghq_weights_b = hermgauss(n_quad)

    ghq_weights_a /= np.sqrt(np.pi)
    ghq_weights_b /= np.sqrt(np.pi)

    # Rescale nodes
    a_nodes = ghq_points_a * np.sqrt(2) * sigma_a
    b_nodes = ghq_points_b * np.sqrt(2) * sigma_b

    # Fixed effects
    eta_fixed = np.asarray(X @ beta)  # shape (n_obs,)

    # Expand a_nodes and b_nodes into full 2D grid
    A, B = np.meshgrid(a_nodes, b_nodes, indexing='ij')  # both (n_quad, n_quad)

    # Expand to observations: broadcasting
    A_obs = A[None, :, :]  # shape (1, n_quad, n_quad)
    B_obs = B[None, :, :]  # shape (1, n_quad, n_quad)
    times_obs = times[:, None, None]  # (n_obs, 1, 1)
    eta_fixed_obs = eta_fixed[:, None, None]  # (n_obs, 1, 1)

    # Compute full eta (linear predictor)
    eta_random = A_obs * times_obs + B_obs  # shape (n_obs, n_quad, n_quad)
    eta_all = eta_fixed_obs + eta_random

    # Logistic link
    p_all = 1 / (1 + np.exp(-np.clip(eta_all, -30, 30)))

    # Log-likelihoods per observation and quadrature pair
    y_obs = y[:, None, None]
    log_likelihoods = y_obs * np.log(p_all + 1e-8) + (1 - y_obs) * np.log(1 - p_all + 1e-8)  # (n_obs, n_quad, n_quad)

    # Now sum over observations by groups (individuals)
    loglik_per_observation = np.zeros((n_individuals, n_quad, n_quad))
    np.add.at(loglik_per_observation, groups, log_likelihoods)  # (n_individuals, n_quad, n_quad)

    # Now do 2D weighted logsumexp per individual
    weights_2d = np.outer(ghq_weights_a, ghq_weights_b)  # (n_quad, n_quad)

    loglik_per_individual = logsumexp(
        loglik_per_observation.reshape(n_individuals, -1),
        b=weights_2d.flatten(),
        axis=1
    ) + np.log(1/np.pi)  # ⚡ Remember 1/pi correction

    total_loglik = np.sum(loglik_per_individual)

    return -total_loglik  # Negative log-likelihood for minimization

#### 2.2.1 Example use case (Linear-time dependent frailties)

In [17]:
# Selecting only the covariates

X = copy.deepcopy(tp_dat_X.iloc[:,1:-2])

print('shape of X', X.shape)
print('shape of X', X.columns,'\n')

shape of X (29903, 4)
shape of X Index(['cons', 'X1', 'X2', 'X3'], dtype='object')

In [19]:
# Extracting times
times = tp_dat_X['times'].values

In [20]:
# ------------------------------------------------

# Ensure individual IDs are mapped to sequential indices
unique_ids, groups = np.unique(tp_dat_X['sample_id'].values, return_inverse=True)

# Update n_individuals based on unique IDs
n_individuals = len(unique_ids)

# ------------------------------------------------
# Making a copy 
groups_encoded = copy.deepcopy(groups)


# ---------------------------------------
model_logis_td = LogisticRegression(penalty="none")
model_logis_td.fit(X.values,y)

# Predicting probabilities on the train set to generate some statistics 
predicted_probs_td = model_logis_td.predict_proba(X)[:,1]

# Log-likelihood
loglik_reduced_td = np.sum(y * np.log(predicted_probs_td + 1e-8) +\
                           (1 - y) * np.log(1 - predicted_probs_td + 1e-8))


# Extract initial estimates for fixed effects
beta_init_td = model_logis_td.coef_[0]

# Residuals for starting point
residuals_td = y - predicted_probs_td
sigma_u_init_td = np.std(residuals_td)
log_sigma_u_init_td = np.log(sigma_u_init_td + 1e-4)


# --------------------------------------------

log_sigma_a_init = log_sigma_u_init_td
log_sigma_b_init = log_sigma_u_init_td


# Build full initial parameter vector
init_params_better = np.concatenate([beta_init_td, [log_sigma_a_init, log_sigma_b_init]])

# Fit the full model

result_line = minimize(loglik_glmm_2d_ghq_vectorized, init_params_better,
                       args=(X, y, groups_encoded, n_individuals, times), 
                        method="L-BFGS-B", options={'maxiter': 1000, 'disp': True}, jac='2-point')


loglik_line = -result_line.fun  # Extract log-likelihood from full model

# Compute p-values for fixed effects
num_fixed_params = len(result_line.x) - 2  # Now two variance components

p_values_fixed = np.full(num_fixed_params + 2, np.nan)  # Include variances

# --------------------------------------------------------------------------------------


if n_individuals > 100:
    se_glmm = np.sqrt(np.diag(
        pinv(sm.tools.numdiff.approx_hess(result_line.x, loglik_glmm_2d_ghq_vectorized,
                                          args=(X, y, groups_encoded, n_individuals, times)))
    ))[:-2]
    p_values_fixed[:-2] = 2 * (1 - norm.cdf(np.abs(result_line.x[:-2] / se_glmm)))
else:
    pass
# -------------------------------------------------------------------------------


#  Display results
tp_dataframe_line = pd.DataFrame({
    'Parameter': list(X.columns) + ['Sigma_a (slope)', 'Sigma_b (intercept)'],
    'True parameters': np.concatenate([beta_true, [np.nan, sigmm]]),
    'Parameter Estimate (GHQ)': np.concatenate([result_line.x[:-2], np.exp(result_line.x[-2:])]),
    'p-value (Fixed effects)': p_values_fixed
})

tp_dataframe_line

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/1584080852.py:46: DeprecationWarning: scipy.optimize: The `disp` and `iprint` options of the L-BFGS-B solver are deprecated and will be removed in SciPy 1.18.0.
  result_line = minimize(loglik_glmm_2d_ghq_vectorized, init_params_better,

,Parameter,True parameters,Parameter Estimate (GHQ),p-value (Fixed effects)
0,cons,-1.24,-1.148291,0.0
1,X1,1.17,1.159556,0.0
2,X2,-1.04,-1.118424,0.0
3,X3,0.97,0.953097,0.0
4,Sigma_a (slope),NaN,0.127494,NaN
5,Sigma_b (intercept),2.50,2.458066,NaN

### 2.3. Implementation of the objective function (negative marginal log-likelihood) using GHQ integration: Case of time-dependent piecewise frailties
- See section 2.5.2.5

In [21]:
def loglik_glmm_piecewise_frailty(params, X, y, groups, n_individuals, times, tau=[3, 5, 10], n_quad=20):
    """
    Piecewise time-dependent frailty model using Gauss-Hermite quadrature.
    """
    n_obs = len(y)
    n_segments = len(tau)

    # Extract parameters
    beta = params[:-n_segments]
    log_sigmas = params[-n_segments:]
    sigmas = np.exp(log_sigmas)  # Convert to positive scale

    # Gauss-Hermite nodes/weights (shared)
    gh_x, gh_w = hermgauss(n_quad)
    gh_w = gh_w / np.sqrt(np.pi)

    # Precompute fixed part of eta
    eta_fixed = X @ beta
    loglik_total = 0

    for k in range(n_segments): # For each time interval tau_k \in {tau_1, tau_2, tau_3}
        

        # Identifying relevant intervals
        t_low = 0 if k == 0 else tau[k - 1]
        t_high = tau[k]

        # Selecting observations in this time segment
        idx_k = np.where((times > t_low) & (times <= t_high))[0]
        if len(idx_k) == 0:
            continue  # No data in this segment

        X_k = X.values[idx_k] if isinstance(X, pd.DataFrame) else X[idx_k]
        y_k = y[idx_k]
        
        eta_k = eta_fixed[idx_k]
        eta_k = np.asarray(eta_k)
        
        groups_k = groups[idx_k]

        # Rescaling nodes for this sigma
        u_k = np.sqrt(2) * sigmas[k] * gh_x
        eta_all = eta_k[:, None] + u_k[None, :]  # shape (n_obs_k, n_quad)
        p_all = 1 / (1 + np.exp(-np.clip(eta_all, -30, 30)))

        # Computing log-likelihoods
        logliks = y_k[:, None] * np.log(p_all + 1e-8) + (1 - y_k[:, None]) * np.log(1 - p_all + 1e-8)

        
#         print(f"Segment {k+1} | sigma: {sigmas[k]:.4f} | u_k range: {u_k.min():.2f} to {u_k.max():.2f}")

        # Groupwise summation
        loglik_per_obs = np.zeros((n_individuals, n_quad))
        np.add.at(loglik_per_obs, groups_k, logliks)

        # Integrate over quadrature points
        loglik_per_indiv = logsumexp(loglik_per_obs, b=gh_w, axis=1)
        loglik_total += np.sum(loglik_per_indiv)

    return -loglik_total  # for minimization

#### 2.3.1 Example use case (Linear-time dependent frailties)

In [22]:

# ------------------------------------------------

# Ensure individual IDs are mapped to sequential indices
unique_ids, groups = np.unique(tp_dat_X['sample_id'].values, return_inverse=True)

# Update n_individuals based on unique IDs
n_individuals = len(unique_ids)

groups_encoded = copy.deepcopy(groups)


#  Reduced model (no frailty)
logit_model = sm.Logit(y, X)
logit_result = logit_model.fit(disp=0)
loglik_reduced = logit_result.llf

#  Initialising frailty std devs for 3 segments
predicted_probs = logit_result.predict(X)
residuals = y - predicted_probs
sigma_resid = np.std(residuals)

#  Setting frailties initial values from residuals standard deviation
log_sigma_1 = np.log(sigma_resid + 1e-4)
log_sigma_2 = np.log(sigma_resid + 1e-4)
log_sigma_3 = np.log(sigma_resid + 1e-4)

# Initial parameter vector
beta_init = logit_result.params.values
init_params_piecewise = np.concatenate([beta_init, [log_sigma_1, log_sigma_2, log_sigma_3]])
# print('len(beta_init):',len(beta_init))

#  Fit the full piecewise model
result_piecewise = minimize(loglik_glmm_piecewise_frailty, init_params_piecewise,
                       args=(X, y, groups_encoded, n_individuals, times), 
                        method="L-BFGS-B", options={'maxiter': 1000, 'disp': True}, jac='2-point')




loglik_piecewise = -result_piecewise.fun
num_fixed_params = len(result_piecewise.x) - 3

# P-values for fixed effects
p_values_fixed = np.full(num_fixed_params + 3, np.nan)

if n_individuals > 100:
    se_glmm = np.sqrt(np.diag(
        pinv(sm.tools.numdiff.approx_hess(result_piecewise.x, loglik_glmm_piecewise_frailty,
                                          args=(X, y, groups_encoded, n_individuals, times)))
    ))[:-3]
    p_values_fixed[:-3] = 2 * (1 - norm.cdf(np.abs(result_piecewise.x[:-3] / se_glmm)))
else:
    pass


# Results in. a table
tp_dataframe_piecewise = pd.DataFrame({
    'Parameter': list(X.columns) + ['Sigma_1 (early)', 'Sigma_2 (mid)', 'Sigma_3 (late)'],
    'True parameters': np.concatenate([beta_true, [sigmm, sigmm, sigmm]]),
    'Parameter Estimate (GHQ)': np.concatenate([result_piecewise.x[:-3], np.exp(result_piecewise.x[-3:])]),
    'p-value (Fixed)': p_values_fixed
})

tp_dataframe_piecewise

/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/996050598.py:33: DeprecationWarning: scipy.optimize: The `disp` and `iprint` options of the L-BFGS-B solver are deprecated and will be removed in SciPy 1.18.0.
  result_piecewise = minimize(loglik_glmm_piecewise_frailty, init_params_piecewise,

         Parameter  True parameters  Parameter Estimate (GHQ)  p-value (Fixed)
0             cons            -1.24                 -1.142947              0.0
1               X1             1.17                  1.142291              0.0
2               X2            -1.04                 -1.099285              0.0
3               X3             0.97                  0.953337              0.0
4  Sigma_1 (early)             2.50                  2.437360              NaN
5    Sigma_2 (mid)             2.50                  2.563610              NaN
6   Sigma_3 (late)             2.50                  0.451681              NaN

In [23]:
'poplo'

'poplo'

# 3. Parametric bootsrap LRT (PB-LR) functions

- The parametric bootstrap LRT approach helps to compute the statistical significance (p-value) of the frailty variance (s). See section 2.5.5 of my thesis.

### 3.1 Implementation (T1) : Fixed-effects vs. time-independent frailty (random intercept)

In [25]:
# Simulate under H0: σ² = 0 (no frailty)
# # -----------------------------

# Function to simulate response variables y from fixed effects model
def simulate_null_data(X, beta, rng=None):
    eta = X @ beta
    eta = np.clip(eta, -30, 30)
#     eta = np.clip(eta, -10, 10)
    p = 1 / (1 + np.exp(-eta))
    if rng is None:
        rng = np.random.default_rng()
    return rng.binomial(1, p, size=len(p))

#  Parametric bootstrap LRT function (implemented to run in parallel over the bootstrap replicates)
def wrap_parametric_bootstrap_rlrt_with_tracking(X, groups, beta_null, n_individuals,
                                                 compute_full_loglik_fn,
                                                 B: int = 100, n_quad: int = 20,
                                                 n_jobs: int = -1, seed: int = 42):
    def single_bootstrap_run(b):
#         Setting seed at each bootstrap for reproducibility
        rng = np.random.default_rng(seed + b)

#         Simulating the response variables from the reduced model (model with no frailty in this case)
        y_sim = simulate_null_data(X, beta_null, rng=rng)

#         Fitting Simple LLink model
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", ConvergenceWarning)
            model_red = LogisticRegression(penalty=None, solver='lbfgs', max_iter=1000)
            model_red.fit(X, y_sim)
            if model_red.n_iter_[0] >= model_red.max_iter:
                return (None, 'no_converge_reduced', None, None)

        beta_red_sim = model_red.coef_.flatten()
        model_logis_red_paraams = model_red.coef_[0]
        predicted_probs = model_red.predict_proba(X)[:, 1]
        
#         Extracting reduced model loglikelihood
        loglik_red_sim = np.sum(y_sim * np.log(predicted_probs + 1e-8) +
                                (1 - y_sim) * np.log(1 - predicted_probs + 1e-8))
        

        try:
            def neg_loglik_full(params):
                return compute_full_loglik_fn(params, X, y_sim, groups, n_individuals, n_quad=n_quad)
            
#             Extracting residuals from fixed effects model to setup initial value of frailty variance
            residuals = y_sim - predicted_probs
            sigma_u_init = np.std(residuals) # Initial value for time-independent frailties
                 
#             Setting initial paramters
            init_params = np.concatenate([np.array(model_logis_red_paraams), np.log([sigma_u_init])])

        except:
            return (None, 'no_converge_reduced', None, None)

        res = minimize(neg_loglik_full, init_params, method="L-BFGS-B", options={'maxiter': 1000})
        if not res.success:
            return (None, 'no_converge_reduced', None, None)

        loglik_full_sim = -res.fun
        stat = 2 * (loglik_full_sim - loglik_red_sim)
        return (stat, None, loglik_full_sim, loglik_red_sim)

#     Running in parallel over B boostrap replicates 
    results = Parallel(n_jobs=n_jobs)(delayed(single_bootstrap_run)(b) for b in range(B))

#     Savinf the some relevant results and relevant statistics into lists
    valid_stats = [r[0] for r in results if r[0] is not None] # Here is the list of parametric bootstrap LRT statistics
    failures = [r[1] for r in results if r[0] is None] # Failed bootstrap (i.e. no convergence can be identified here)
    loglik_full_list = [r[2] for r in results if r[0] is not None]# List of parametric bootstrap MLE values for the full model at corresponding bootstrap resamples
    loglik_red_list = [r[3] for r in results if r[0] is not None] # List of parametric bootstrap MLE values for the reduced model at corresponding bootstrap resamples
    failure_counts = dict(Counter(failures))

    return np.array(valid_stats), failure_counts, results, loglik_full_list, loglik_red_list

#### 3.1.1. Example use case for the above function

In [26]:
# Fixed effects model
model_logis_reduced = LogisticRegression(penalty="none") # Setting instance
model_logis_reduced.fit(X.values,y)# Fitting
model_logis_reduced_paraams = model_logis_reduced.coef_[0] # Extrating fixed effects vector of estimates

# Extracting predicted probabilities on same data 
predicted_probs_reduced_model = model_logis_reduced.predict_proba(X)[:,1]

loglik_reduced_model = np.sum(y * np.log(predicted_probs_reduced_model + 1e-8) +\
                           (1 - y) * np.log(1 - predicted_probs_reduced_model + 1e-8))


residuals = y - predicted_probs_reduced_model
sigma_u_init = np.std(residuals) # Initial value for time-independent frailties
log_sigma_u_init = np.log(sigma_u_init + 1e-4) # Making sure log of initial values does not blow up by adding a
# small epsilon
init_params_time_indep = np.append(model_logis_reduced_paraams, log_sigma_u_init)  # setting up vector of full
# initial parameters

    
# ---------------------- Full model (observed) ---------------------

result_full = minimize(loglik_glmm_ghq_vectorized, init_params_time_indep, args=(X, y, groups, n_individuals), 
                        method="L-BFGS-B", options={'maxiter': 1000,  'verbose': 1},
                       jac='2-point')

loglik_full_model_obs = -result_full.fun  


# ----------------- Parametric bootstrap LRT : Case of time-independent frailty ---------------------------
tstart = time.time()


B=100 # we set the number of bootstrap B to be low so that one can judge how long it may take to finish.
# The number can then be increased after this has been tested

ressss_0 =\
    wrap_parametric_bootstrap_rlrt_with_tracking(
    X=X,
    groups=groups,
    beta_null=model_logis_reduced_paraams,
    n_individuals=n_individuals,
    compute_full_loglik_fn=loglik_glmm_ghq_vectorized,
    B=B,
    n_quad=20,
    n_jobs=-1,
    seed=42
)

tstop = time.time()

print('Time taken', (tstop-tstart)/60., 'minutes')

# ----------------------------------------------------

# Compute log-likelihood from your actual full piecewise model

# Negating the full model the maximum likelihood estimate obtained original training set (i.e.  minus the
# minimize loglikelihod)
max_log_lik_full_time_indep_case = loglik_full_model_obs
max_log_lik_freduced_time_indep_case = loglik_reduced_model # loglik_reduced_model should be the loglikelihood
# estimate from the last simulation study in section 1.3 of this notebook

# Making sure the statistics (i.e. the LRT test statistics) is not negative
tp_lrt_observed_time_indep_case = max(2 * ( max_log_lik_full_time_indep_case - max_log_lik_freduced_time_indep_case), 0)
resss_boot_time_indep_case_LRT = np.where(ressss_0[0]<0,0,ressss_0[0])

tp_pval_rlr_time_indep_case = np.mean(resss_boot_time_indep_case_LRT >= tp_lrt_observed_time_indep_case)


print(f"RLRT p-value for frailty variance(s): {tp_pval_rlr_time_indep_case:.4f}")

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/4088397381.py:23: OptimizeWarning: Unknown solver options: verbose
  result_full = minimize(loglik_glmm_ghq_vectorized, init_params_time_indep, args=(X, y, groups, n_individuals),

Time taken 0.8973313848177592 minutes
RLRT p-value for frailty variance(s): 0.0000

**N.B. The PB-LRT remaining functions presented below can be explored in a similar procedures**

### 3.2 Implementation of (T2) : Linear time-dependent frailty: test of slope variance (conditional on intercept variance)

In [28]:
def wrap_parametric_bootstrap_rlrt_sigma_a_only(
    X, times, groups, n_individuals,
    compute_loglik_full,  # full model: uses both a_i and b_i
    compute_loglik_reduced,  # reduced model: uses only b_i
    beta_null, sigma_b_null,
    B=100, n_quad=20, n_jobs=-1, seed=42
):
    def simulate_from_reduced_model(rng):
        b_i = rng.normal(loc=0.0, scale=sigma_b_null, size=n_individuals)
        eta = (X @ beta_null) + b_i[groups]
        p = 1 / (1 + np.exp(-np.clip(eta, -30, 30)))
        return rng.binomial(1, p)

    def single_bootstrap_run(b):
        rng = np.random.default_rng(seed + b)
#         try:
        y_sim = simulate_from_reduced_model(rng)

        # Fit reduced model (b_i only)
        def neg_loglik_red(params):
            return compute_loglik_reduced(params, X, y_sim, groups, n_individuals, n_quad=n_quad)

        init_red = np.concatenate([beta_null, [np.log(sigma_b_null)]])
        res_red = minimize(neg_loglik_red, init_red, method="L-BFGS-B", options={"maxiter": 1000})
        if not res_red.success:
            return (None, 'no_converge_reduced', None, None)
        loglik_red = -res_red.fun
        beta_est_red = res_red.x[:-1]
        log_sigma_b_est = res_red.x[-1]
        
#         -----------------------------------------------
        
        tp_eta = X @ beta_null
        prob_red =  1 / (1 + np.exp(-np.clip(tp_eta, -30, 30)))
        
        tp_residuals = y_sim - prob_red
        tp_sigma_resid = np.std(tp_residuals)
        
#         -----------------------------------------------
        

        # Fit full model (a_i and b_i)
        def neg_loglik_full(params):
            return compute_loglik_full(params, X, y_sim, groups, n_individuals, times, n_quad=n_quad)

#         init_full = np.concatenate([beta_est_red, np.log([1e-1, sigma_b_null])])
        init_full = np.concatenate([beta_est_red, [np.log(1e-1), log_sigma_b_est]])
#         init_full = np.concatenate([beta_est_red, [np.log(tp_sigma_resid), log_sigma_b_est]])
        res_full = minimize(neg_loglik_full, init_full, method="L-BFGS-B", options={"maxiter": 1000})
        if not res_full.success:
            return (None, 'no_converge_full', None, None)

        loglik_full = -res_full.fun
        stat = 2 * (loglik_full-loglik_red)
        return (stat, None, loglik_full, loglik_red)

#         except Exception:
#             return (None, 'exception', None, None)

    results = Parallel(n_jobs=n_jobs)(
        delayed(single_bootstrap_run)(b) for b in range(B)
    )

    valid_stats = [r[0] for r in results if r[0] is not None]
    failures = [r[1] for r in results if r[0] is None]
    loglik_full_list = [r[2] for r in results if r[0] is not None]
    loglik_red_list = [r[3] for r in results if r[0] is not None]
    failure_counts = dict(Counter(failures))

    return np.array(valid_stats), failure_counts, results, loglik_full_list, loglik_red_list

In [29]:
# Computing p-values for the time-independent case based for the time-independent case


model_logis_fix_effects = LogisticRegression(penalty="none")
model_logis_fix_effects.fit(X.values,y)
model_logis_params_fix_effects = model_logis_fix_effects.coef_[0]

# Predicting probabilities on the train set to generate some statistics 
predicted_probs_fix_effects = model_logis_fix_effects.predict_proba(X)[:,1]

loglik_reduced_fix_effects = np.sum(y * np.log(predicted_probs_fix_effects + 1e-8) +\
                           (1 - y) * np.log(1 - predicted_probs_fix_effects + 1e-8))


residuals = y - predicted_probs_fix_effects
sigma_u_init = np.std(residuals) # Initial value for time-independent frailties
log_sigma_u_init = np.log(sigma_u_init + 1e-4) # Making sure log of initial values does not blow up by adding a
# small epsilon
init_params_time_indep = np.append(model_logis_params_fix_effects, log_sigma_u_init)  # setting up vector of full
# initial parameters


result_reduced_time_indep = minimize(loglik_glmm_ghq_vectorized, init_params_time_indep, args=(X, y, groups,
                                                                            n_individuals), 
                        method="L-BFGS-B", options={'maxiter': 1000, 'disp': True}, jac='2-point')



tstart= time.time()

resss_a_case = wrap_parametric_bootstrap_rlrt_sigma_a_only(
    X, times, groups, n_individuals,
    loglik_glmm_2d_ghq_vectorized,  # full model: uses both a_i and b_i
    loglik_glmm_ghq_vectorized,  # reduced model: uses only b_i
    result_reduced_time_indep.x[:-1],
    np.exp(result_reduced_time_indep.x[-1]),
    B=25, n_quad=20, n_jobs=-1, seed=42)  # Try with a small B first to see how long it takes, the increase

tstop= time.time()

print('Time taken is',(tstop-tstart)/60.,'minutes')

# Negating the full model the maximum likelihood estimate obtained original training set (i.e.  minus the
# minimize loglikelihod)
max_log_lik_full_linear_case = loglik_line
max_log_lik_freduced_linear_case = -result_reduced_time_indep.fun

# Making sure the statistics (i.e. the LRT test statistics) is not negative
tp_lrt_observed_line_case = max(2 * ( max_log_lik_full_linear_case - max_log_lik_freduced_linear_case), 0)
resss_boot_line_case_LRT = np.where(resss_a_case[0]<0,0,resss_a_case[0])


# Computing bootstrap parametric LRT p-value
tp_pval_rlrt_case_line = np.mean(resss_boot_line_case_LRT >= tp_lrt_observed_line_case)


print(f"RLRT p-value for frailty variance(s): {tp_pval_rlrt_case_line:.4f}")

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_59340/3669965178.py:23: DeprecationWarning: scipy.optimize: The `disp` and `iprint` options of the L-BFGS-B solver are deprecated and will be removed in SciPy 1.18.0.
  result_reduced_time_indep = minimize(loglik_glmm_ghq_vectorized, init_params_time_indep, args=(X, y, groups,
/Users/ced001/anaconda3/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Time taken is 5.83971730073293 minutes
RLRT p-value for frailty variance(s): 1.0000

### 3.3 Implementation of (T3) : Linear time-dependent frailty: test of intercept variance (conditional on slope variance)

In [36]:
def wrap_parametric_bootstrap_rlrt_sigma_b_only(
    X, times, groups, n_individuals,
    compute_loglik_full,  # full model: uses both a_i and b_i
    compute_loglik_reduced,  # reduced model: uses only b_i
    beta_null, sigma_a_null,
    B=100, n_quad=20, n_jobs=-1, seed=42
):
    def simulate_from_reduced_model(rng):
        a_i = rng.normal(loc=0.0, scale=sigma_a_null, size=n_individuals)
        eta = (X @ beta_null) + a_i[groups]*times
        p = 1 / (1 + np.exp(-np.clip(eta, -30, 30)))
        return rng.binomial(1, p)

    def single_bootstrap_run(b):
        rng = np.random.default_rng(seed + b)
#         try:
        y_sim = simulate_from_reduced_model(rng)

        # Fit reduced model (b_i only)
        def neg_loglik_red(params):
            return compute_loglik_reduced(params, X, y_sim, groups, n_individuals, times, n_quad=n_quad)

        init_red = np.concatenate([beta_null, [np.log(sigma_a_null)]])
        res_red = minimize(neg_loglik_red, init_red, method="L-BFGS-B", options={"maxiter": 1000})
        if not res_red.success:
            return (None, 'no_converge_reduced', None, None)
        loglik_red = -res_red.fun
        beta_est_red = res_red.x[:-1]
        log_sigma_a_est = res_red.x[-1]
        
#         -----------------------------------------------
        
        tp_eta = X @ beta_null
        prob_red =  1 / (1 + np.exp(-np.clip(tp_eta, -30, 30)))
        
        tp_residuals = y_sim - prob_red
        tp_sigma_resid = np.std(tp_residuals)
        
#         -----------------------------------------------
        

        # Fit full model (a_i and b_i)
        def neg_loglik_full(params):
            return compute_loglik_full(params, X, y_sim, groups, n_individuals, times, n_quad=n_quad)

#         init_full = np.concatenate([beta_est_red, np.log([sigma_a_null, 1e-1])])
        init_full = np.concatenate([beta_est_red, [log_sigma_a_est, np.log(1e-1)]])
#         init_full = np.concatenate([beta_est_red, [log_sigma_b_est, np.log(tp_sigma_resid)]])
        res_full = minimize(neg_loglik_full, init_full, method="L-BFGS-B", options={"maxiter": 1000})
        if not res_full.success:
            return (None, 'no_converge_full', None, None)

        loglik_full = -res_full.fun
        stat = -2 * (loglik_red - loglik_full)
        return (stat, None, loglik_full, loglik_red)

#         except Exception:
#             return (None, 'exception', None, None)

    results = Parallel(n_jobs=n_jobs)(
        delayed(single_bootstrap_run)(b) for b in range(B)
    )

    valid_stats = [r[0] for r in results if r[0] is not None]
    failures = [r[1] for r in results if r[0] is None]
    loglik_full_list = [r[2] for r in results if r[0] is not None]
    loglik_red_list = [r[3] for r in results if r[0] is not None]
    failure_counts = dict(Counter(failures))

    return np.array(valid_stats), failure_counts, results, loglik_full_list, loglik_red_list

### 3.4 Implementation of (T4) : Piecewise time-dependent frailty - global test

In [37]:
def wrap_parametric_bootstrap_rlrt_piecewise_any(
    X, times, groups, n_individuals,
    compute_loglik_full,  # e.g., loglik_glmm_piecewise_frailty
    beta_null,
    B=100, n_quad=20, tau=None, n_jobs=-1, seed=42
):

    def simulate_from_null(rng):
        eta = X @ beta_null
        p = 1 / (1 + np.exp(-np.clip(eta, -30, 30)))
        return rng.binomial(1, p)

    def single_bootstrap_run(b):
        rng = np.random.default_rng(seed + b)

        y_sim = simulate_from_null(rng)

        # Reduced model: fixed effects only
        model_red = LogisticRegression(penalty=None, solver='lbfgs', max_iter=1000)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", ConvergenceWarning)
            model_red.fit(X, y_sim)
            if model_red.n_iter_[0] >= model_red.max_iter:
                return (None, 'no_converge_reduced', None, None)
        beta_red_sim = model_red.coef_.flatten()
        prob_red = model_red.predict_proba(X)[:, 1]
        loglik_red_sim = np.sum(
            y_sim * np.log(prob_red + 1e-8) +
            (1 - y_sim) * np.log(1 - prob_red + 1e-8)
        )
        
        
        

        tp_residuals = y_sim - prob_red
        tp_sigma_resid = np.std(tp_residuals)

        # Full model: piecewise frailty
        def neg_loglik_full(params):
            return compute_loglik_full(params, X, y_sim, groups, n_individuals, times, tau=tau, n_quad=n_quad)

        n_segments = len(tau)
#         init_params = np.concatenate([beta_red_sim, np.log([tp_sigma_resid] * n_segments)])
        init_params = np.concatenate([beta_red_sim, np.log([1e-1] * n_segments)])
        res_full = minimize(neg_loglik_full, init_params, method="L-BFGS-B", options={'maxiter': 1000})
        if not res_full.success:
            return (None, 'no_converge_full', None, None)

        loglik_full_sim = -res_full.fun
        stat = -2 * (loglik_red_sim - loglik_full_sim)
        return (stat, None, loglik_full_sim, loglik_red_sim)



    results = Parallel(n_jobs=n_jobs)(
        delayed(single_bootstrap_run)(b) for b in range(B)
    )

    valid_stats = [r[0] for r in results if r[0] is not None]
    failures = [r[1] for r in results if r[0] is None]
    loglik_full_list = [r[2] for r in results if r[0] is not None]
    loglik_red_list = [r[3] for r in results if r[0] is not None]
    failure_counts = dict(Counter(failures))

    return np.array(valid_stats), failure_counts, results, loglik_full_list, loglik_red_list

### 3.5 Implementation of (T5) : Piecewise time-dependent frailty: component-wise tests.

- The function **wrap_parametric_bootstrap_rlrt_piecewise_component** generate the PB-LRT statistics from the function **loglik_glmm_piecewise_frailty** (which should be used **as the full model** in this case) and the **reduced model** (in this case the function **loglik_glmm_piecewise_frailty_exclude_k**, which sets the k^th frailty variance to 0)

In [38]:
def wrap_parametric_bootstrap_rlrt_piecewise_component(
    X, times, groups, n_individuals,
    compute_loglik_full,  # e.g., loglik_glmm_piecewise_frailty
    compute_loglik_reduced,  # e.g., loglik_glmm_piecewise_frailty_exclude_k
    beta_null,
    sigma_nulls_reduced,  # log sigmas with the tested component excluded
    component_index,  # index of the variance component being tested (0-based)
    B=100, n_quad=20, tau=None, n_jobs=-1, seed=42
):

    if tau is None:
        raise ValueError("tau must be provided.")

    def simulate_from_reduced_model(rng):
        n_segments = len(tau)
        sigmas = np.exp(np.array(sigma_nulls_reduced))
        u = np.zeros((n_individuals, n_segments))
        sigma_idx = 0
        for k in range(n_segments):
            if k == component_index:
                continue
            u[:, k] = rng.normal(loc=0.0, scale=sigmas[sigma_idx], size=n_individuals)
            sigma_idx += 1
        t_mask = [(times > (0 if k == 0 else tau[k - 1])) & (times <= tau[k]) for k in range(n_segments)]
        eta = X @ beta_null
        for k in range(n_segments):
            eta += u[groups, k] * t_mask[k]
        p = 1 / (1 + np.exp(-np.clip(eta, -30, 30)))
        return rng.binomial(1, p)

    def single_bootstrap_run(b):
        rng = np.random.default_rng(seed + b)
        y_sim = simulate_from_reduced_model(rng)

        # Reduced model
        def neg_loglik_reduced(params):
            return compute_loglik_reduced(params, X, y_sim, groups, n_individuals,
                                          times, tau=tau, component_index=component_index, n_quad=n_quad)

        init_red = np.concatenate([beta_null, sigma_nulls_reduced])
        res_red = minimize(neg_loglik_reduced, init_red, method="L-BFGS-B", options={"maxiter": 1000})
        if not res_red.success:
            return (None, 'no_converge_reduced', None, None)
        loglik_red = -res_red.fun
        beta_est = res_red.x[:len(beta_null)]
        

        # Full model
        n_segments = len(tau)
        sigma_idx = 0
        log_sigmas_full = []
        for i in range(n_segments):
            if i == component_index:
                log_sigmas_full.append(np.log(5e-1))  # inserting small init for omitted one
            else:
                log_sigmas_full.append(sigma_nulls_reduced[sigma_idx])
                sigma_idx += 1
        init_full = np.concatenate([beta_est, log_sigmas_full])

        def neg_loglik_full(params):
            return compute_loglik_full(params, X, y_sim, groups, n_individuals, times, tau=tau, n_quad=n_quad)

        res_full = minimize(neg_loglik_full, init_full, method="L-BFGS-B", options={"maxiter": 1000})
        if not res_full.success:
            return (None, 'no_converge_full', None, None)

        loglik_full = -res_full.fun
        stat = -2 * (loglik_red - loglik_full)
        return (stat, None, loglik_full, loglik_red)

    results = Parallel(n_jobs=n_jobs)(
        delayed(single_bootstrap_run)(b) for b in range(B)
    )

    valid_stats = [r[0] for r in results if r[0] is not None]
    failures = [r[1] for r in results if r[0] is None]
    loglik_full_list = [r[2] for r in results if r[0] is not None]
    loglik_red_list = [r[3] for r in results if r[0] is not None]
    failure_counts = dict(Counter(failures))

    return np.array(valid_stats), failure_counts, results, loglik_full_list, loglik_red_list

In [39]:
def loglik_glmm_piecewise_frailty_exclude_k(
    params, X, y, groups, n_individuals, times, tau=[3, 5, 10],
    component_index=None, n_quad=20
):

    n_segments = len(tau)
    assert component_index is not None and 0 <= component_index < n_segments, "Invalid component_index"

    beta = params[:- (n_segments - 1)]
    log_sigmas = params[- (n_segments - 1):]
    sigmas = np.exp(log_sigmas)
    
#     print('len(beta):',len(beta))

    gh_x, gh_w = hermgauss(n_quad)
    gh_w = gh_w / np.sqrt(np.pi)

    eta_fixed = X @ beta
    loglik_total = 0
    sigma_idx = 0

    for k in range(n_segments):
        if k == component_index:
            continue  # Skip this segment (variance = 0)

        t_low = 0 if k == 0 else tau[k - 1]
        t_high = tau[k]
        idx_k = np.where((times > t_low) & (times <= t_high))[0]
        if len(idx_k) == 0:
            continue

        X_k = X.iloc[idx_k] if hasattr(X, "iloc") else X[idx_k]
        y_k = y[idx_k]
        eta_k = eta_fixed.iloc[idx_k] if hasattr(eta_fixed, "iloc") else eta_fixed[idx_k]
        eta_k = np.asarray(eta_k)
        groups_k = groups[idx_k]

        u_k = np.sqrt(2) * sigmas[sigma_idx] * gh_x
        sigma_idx += 1

        eta_all = eta_k[:, None] + u_k[None, :]
        p_all = 1 / (1 + np.exp(-np.clip(eta_all, -30, 30)))

        logliks = y_k[:, None] * np.log(p_all + 1e-8) + (1 - y_k[:, None]) * np.log(1 - p_all + 1e-8)

        loglik_per_obs = np.zeros((n_individuals, n_quad))
        np.add.at(loglik_per_obs, groups_k, logliks)
        loglik_per_indiv = logsumexp(loglik_per_obs, b=gh_w, axis=1)
        loglik_total += np.sum(loglik_per_indiv)

    return -loglik_total

# 4. Optimised Matthews Correlation Coefficient

### 4.1 The multistate classification functions are given as follows
- The functions have not been streamlined to automatically handle any number of states yet
- They have been written specifically for multistate classification when the number of states is 3 but can easily be extented:
    - This implies modifying ['Prob_land_state_1', 'Prob_land_state_2', 'Prob_land_state_3'] to an the exact  landing states one whishes to predict to 
    - For instance, for 4 states, one can set : ['Prob_land_state_1', 'Prob_land_state_2', 'Prob_land_state_3', 'Prob_land_state_4'] or whatever the columns of predicted probabilities in the input data to the function (i.e., Pred_data_0) have been named
    - Given an initial state h, The column "Prob_land_state_1" is the column of predicted probabilities for transition-type (h,1). "Prob_land_state_2" is the column of predicted probabilities for transition-type (h,2), and so on

In [4]:

# This function corresponds to the D&C methods for multitate classification
def vectorized_discrepancy_model(c_vec, Pred_data_0):
    
    # c_vec is the initial value of the vector of cut-off poins
    # Pred_data_0 is the training data containing appropriately named columns for the predicted transition 
    # probabilities 
    
    Pred_data = Pred_data_0.copy().reset_index(drop=True)

    # Extracting probability matrix and implementing discrepancy criteria
    probs = Pred_data[['Prob_land_state_1', 'Prob_land_state_2', 'Prob_land_state_3']].values
    adjusted_probs = probs - c_vec

    # prediction of next state
    pred_states = np.argmax(adjusted_probs, axis=1) + 1
    true_states = Pred_data['Observed_state'].values

    # Evaluation of accuracy of preditions
    correct = (pred_states == true_states).sum()
    accuracy = correct / len(true_states)

    return -accuracy




# This function corresponds to the D&C method for multitate classification but rescaled with the standard
# deviation of the predicted probabilities (from the training set)
def vectorized_discrepancy_model_std(c_vec, Pred_data_0):
    Pred_data = Pred_data_0.copy().reset_index(drop=True)

    # Extracting probability matrix 
    probs = Pred_data[['Prob_land_state_1', 'Prob_land_state_2', 'Prob_land_state_3']].values
    
    # Computing standard deviations and making sure to avoid division by zero
    stds = np.std(probs, axis=0)
    stds[stds == 0] = 1e-12

    # Standardisation + discrepancy criteria
    adjusted_scores = (probs - c_vec) / stds

    # Prediction and evaluation of accuracy of preditions
    pred_states = np.argmax(adjusted_scores, axis=1) + 1
    true_states = Pred_data['Observed_state'].values

    correct = (pred_states == true_states).sum()
    accuracy = correct / len(true_states)

    return -accuracy






# This function corresponds to the proposed OMCC for multitate classification

def vectorized_discrepancy_model_MCC(c_vec, Pred_data_0):
    Pred_data = Pred_data_0.copy().reset_index(drop=True)
    
    # Applying discrepancy criteria and get predicted class (1-based)
    adjusted_probs = np.stack([
        Pred_data['Prob_land_state_1'].values - c_vec[0],
        Pred_data['Prob_land_state_2'].values - c_vec[1],
        Pred_data['Prob_land_state_3'].values - c_vec[2]
    ], axis=1)
    
    pred_states = np.argmax(adjusted_probs, axis=1) + 1
    true_states = Pred_data['Observed_state'].values
    
    # Building a 3x3 confusion matrix
    confusion_matrix = np.zeros((3, 3), dtype=int)
    for t, p in zip(true_states, pred_states):
        confusion_matrix[t-1, p-1] += 1

    n = confusion_matrix.sum()
    sum_diag = np.trace(confusion_matrix)
    row_sums = confusion_matrix.sum(axis=1)
    col_sums = confusion_matrix.sum(axis=0)

    numerator = n * sum_diag - np.dot(row_sums, col_sums)
    denom_part1 = n**2 - np.sum(row_sums**2)
    denom_part2 = n**2 - np.sum(col_sums**2)
    denominator = np.sqrt(denom_part1 * denom_part2)

    # MCC function 
    MCC = numerator / (denominator + 1e-12)  # MCC function to avoid divide by zero

    return -MCC




# This function corresponds to the proposed OMCC for multitate classification but rescaled with the standard
# deviation of the predicted probabilities (from the training set)

def vectorized_discrepancy_model_MCC_std(c_vec, Pred_data_0):
    Pred_data = Pred_data_0.copy().reset_index(drop=True)
    
    # Computing standard deviations of predicted probabilities (from training set)
    stds = np.array([
        Pred_data['Prob_land_state_1'].std(),
        Pred_data['Prob_land_state_2'].std(),
        Pred_data['Prob_land_state_3'].std()
    ])
    
    # To avoid division by zero in standardisation
    stds[stds == 0] = 1e-12
    
    # Standardising and apply discrepancy criteria
    adjusted_scores = np.stack([
        (Pred_data['Prob_land_state_1'].values - c_vec[0]) / stds[0],
        (Pred_data['Prob_land_state_2'].values - c_vec[1]) / stds[1],
        (Pred_data['Prob_land_state_3'].values - c_vec[2]) / stds[2]
    ], axis=1)
    
    pred_states = np.argmax(adjusted_scores, axis=1) + 1
    true_states = Pred_data['Observed_state'].values

    # Building confusion matrix (3x3)
    confusion_matrix = np.zeros((3, 3), dtype=int)
    for t, p in zip(true_states, pred_states):
        confusion_matrix[t-1, p-1] += 1

    n = confusion_matrix.sum()
    sum_diag = np.trace(confusion_matrix)
    row_sums = confusion_matrix.sum(axis=1)
    col_sums = confusion_matrix.sum(axis=0)

    numerator = n * sum_diag - np.dot(row_sums, col_sums) 
    denom_part1 = n**2 - np.sum(row_sums**2)
    denom_part2 = n**2 - np.sum(col_sums**2)

    # To handle issue in the denominator handling
    if denom_part1 == 0 and denom_part2 == 0:
        denominator = 1
    elif denom_part1 == 0:
        denominator = np.sqrt(1 * denom_part2)
    elif denom_part2 == 0:
        denominator = np.sqrt(denom_part1 * 1)
    else:
        denominator = np.sqrt(denom_part1 * denom_part2)

    # MCC function 
    MCC = numerator / (denominator + 1e-12)
    return -MCC

#### Example use case

- We first simulate a data where the response variable has 3 states (1,2,3) and provide an illustration of the multistate classification algorithm
- The number of states can be made arbitrary (but has to be finite number of states)

In [39]:
np.random.seed(42)

n_individuals_new = 10000
obs_per_individual_new = np.random.randint(1, 6, size=n_individuals_new)
n_obs = obs_per_individual_new.sum()

# covariates (same as before)
X1 = np.random.uniform(-2, 2, size=n_obs)
X2 = np.random.choice([0, 1], size=n_obs)

individual_ids_new = np.repeat(np.arange(n_individuals_new), obs_per_individual_new)

df = pd.DataFrame({"X1": X1, "X2": X2, "sample_id": individual_ids_new})
X_new = sm.add_constant(df[["X1", "X2"]]).to_numpy()  # (n_obs, p)


# Selecting true coefficients
W = np.array([
    [0.5, 0.5, -1.2],   # intercepts effects for classes 1,2,3
    [1.5, -0.8, 1.3],   # covariate X1 effects
    [-1.438,  4.847, -0.444],   # covariates X2 effects
])  

# # ----------------------------------------------
# # if you wanted 4 classes with 2 covariates (for example, one intercept with covariates X1 and X2),
# # you may set:

# W = np.array([
#     [0.5, 0.5, -1.2, 2.5],   # intercepts effects for classes 1,2,3,4
#     [1.5, -0.8, 1.3, -0.9],   # covariate X1 effects
#     [-1.438,  4.847, -0.444, 1.1],   # covariates X2 effects
# ])  


# # ----------------------------------------------


# linear predictors in a data of shape (n_obs, 3)
scores = X_new @ W                    

# On each row, we substrack the maximum value for numeric stability
scores = scores - scores.max(1, keepdims=True)  # we can do this since for softmax function e^{x_i-c}/(sum_j e^{x_j-c}) = e^{x_i}/(sum_j e^{x_j})

# Exponential of scores
P = np.exp(scores)

# Normalising to generate probabilities
P = P / P.sum(1, keepdims=True)   # to make sure each row sums up to 1

# Simulate the states based on P and the number of states (corresponding to len(W))
y = np.array([np.random.choice(len(W), p=p) for p in P])+1  # state \in {1,2,3}

# Setting the response variable column
df["Observed_state"] = y

# Extracting IDs and unique count of IDs
unique_ids_new, groups_new = np.unique(df["sample_id"].values, return_inverse=True) # helps to assign unique
# correct unique to individual with multiple events

n_individuals_new = len(unique_ids_new)


# Adding column of ones
dff = pd.DataFrame(sm.add_constant(df))

dff.columns = ['const' ,'X1', 'X2', 'sample_id', 'Observed_state']

# Reordering columns

dff = dff[['sample_id', 'const', 'X1', 'X2','Observed_state']]

dff

# Setting up indicators (i.e. Binary response variables)
dff['to_state_1'] = (dff['Observed_state']==1).astype('int')
dff['to_state_2'] = (dff['Observed_state']==2).astype('int')
dff['to_state_3'] = (dff['Observed_state']==3).astype('int')


unique_custs = dff['sample_id'].unique()
tp_cust = np.random.choice(unique_custs, int(.75*len(unique_custs))) # selecting 75% of customer as part of
# the training set

# Setting up training and test set (for the puropse of illustration)
tp_train_dat = dff[dff['sample_id'].isin(tp_cust)]
tp_test_dat = dff[~dff['sample_id'].isin(tp_cust)]

# Making temporary copy of y in the training set and tet set
tp_y_observed_train = tp_train_dat['Observed_state'].values
tp_y_observed_test = tp_test_dat['Observed_state'].values

# Only training and test covariates
X_train_dat = tp_train_dat[['const', 'X1','X2']]
X_test_dat = tp_test_dat[['const', 'X1','X2']]

In [40]:
df.columns

Index(['X1', 'X2', 'sample_id', 'Observed_state'], dtype='object')

In [44]:
# Setting instances of the LLink
model_logis_td_state_1 = LogisticRegression(penalty="none")
model_logis_td_state_2 = LogisticRegression(penalty="none")
model_logis_td_state_3 = LogisticRegression(penalty="none")


# Extracting response vars
y_train_to_1 = tp_train_dat['to_state_1'].values
y_train_to_2 = tp_train_dat['to_state_2'].values
y_train_to_3 = tp_train_dat['to_state_3'].values

# Fitting LLink model to each transition-type
model_logis_td_state_1.fit(X_train_dat.values,y_train_to_1)
model_logis_td_state_2.fit(X_train_dat.values,y_train_to_2)
model_logis_td_state_3.fit(X_train_dat.values,y_train_to_3)

# Extracting predicted probabilities on the train set

predicted_probs_to_state_1_train = model_logis_td_state_1.predict_proba(X_train_dat.values)[:,1]
predicted_probs_to_state_2_train = model_logis_td_state_2.predict_proba(X_train_dat.values)[:,1]
predicted_probs_to_state_3_train = model_logis_td_state_3.predict_proba(X_train_dat.values)[:,1]

# Extracting predicted probabilities on the test set
predicted_probs_to_state_1_test = model_logis_td_state_1.predict_proba(X_test_dat.values)[:,1]
predicted_probs_to_state_2_test = model_logis_td_state_2.predict_proba(X_test_dat.values)[:,1]
predicted_probs_to_state_3_test = model_logis_td_state_3.predict_proba(X_test_dat.values)[:,1]

# Concatenating predicted probabilities to relevant data and NAMING APPROPRIATELY SO THAT IT MATCHES THE 
# COLUMN NAMES AND NUMBER OF STATES IN THE MULTISTATE CLASSIFICATION FUNCTIONS

X_train_dat['Prob_land_state_1'] = predicted_probs_to_state_1_train
X_train_dat['Prob_land_state_2'] = predicted_probs_to_state_2_train
X_train_dat['Prob_land_state_3'] = predicted_probs_to_state_3_train


X_test_dat['Prob_land_state_1'] = predicted_probs_to_state_1_test
X_test_dat['Prob_land_state_2'] = predicted_probs_to_state_2_test
X_test_dat['Prob_land_state_3'] = predicted_probs_to_state_3_test


# Concatenating back the response variabls

X_train_dat['Observed_state'] = tp_y_observed_train
X_test_dat['Observed_state'] = tp_y_observed_test

/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/Users/ced001/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1182: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train_dat['Prob_land_state_1'] = predicted_probs_to_state_1_train
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train_dat['Prob_land_state_2'] = predicted_probs_to_state_2_train
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train_dat['Prob_land_state_3'] = predicted_probs_to_state_3_train
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test_dat['Prob_land_state_1'] = predicted_probs_to_state_1_test
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test_dat['Prob_land_state_2'] = predicted_probs_to_state_2_test
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test_dat['Prob_land_state_3'] = predicted_probs_to_state_3_test
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train_dat['Observed_state'] = tp_y_observed_train
/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/2966332807.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test_dat['Observed_state'] = tp_y_observed_test

**Below I print the proportion of each observed state in the training set and test set**

In [128]:
print('Proportion of events in each class observed in training set:\n')

X_train_dat['Observed_state'].value_counts(normalize=True)

Proportion of events in each class observed in training set:

Observed_state
2    0.725997
1    0.233934
3    0.040069
Name: proportion, dtype: float64

In [129]:
print('Proportion of events in each class observed in test set:\n')

X_test_dat['Observed_state'].value_counts(normalize=True)

Proportion of events in each class observed in test set:

Observed_state
2    0.726174
1    0.233981
3    0.039845
Name: proportion, dtype: float64


- We use a **diffential evolution optimisation algorithm** for the estimation of the thresholds vector
- This is an efficient algorithm to find global solutions

In [51]:
from scipy.optimize import differential_evolution

### 4.2. Working example for multistate classification using D&C approach

**The optimisation below is equivalent to the discrepancy decision rule (2.25) for D&C in my thesis**

In [121]:
# Selecting relevant columns
Pred_data0_train = X_train_dat[['Prob_land_state_1','Prob_land_state_2','Prob_land_state_3','Observed_state']]


# Running optimisation
result_train = differential_evolution(
    vectorized_discrepancy_model, # Put the selected multiclass approach (function) here
    bounds=[(0,1)]*3,# to make sure the optimal threshold remain within (0,1)
    args=(Pred_data0_train,),# Input money
    maxiter=500, popsize=15, polish=True, seed=42, disp = True
)

best_DC = -result_train.fun
best_thresholds_DC = result_train.x

differential_evolution step 1: f(x)= -0.8785242570485141
differential_evolution step 2: f(x)= -0.8785877571755144
Polishing solution with 'L-BFGS-B'

In [122]:
print('Accuracy of the training set is:', np.round(100*best_DC,3),'%.')

Accuracy of the training set is: 87.859 %.

In [123]:
print('The optimal vector of thresholds is:',best_thresholds_DC)

The optimal vector of thresholds is: [0.51947368 0.73030717 0.63974526]

**Using the above optimal thresholds, we can evaluate the accuracy on the test set**
- N.B. Since we used the D&C (without rescaling) multistate approach, we apply the same the corresponding discrepancy measure (this is equivalent to equation (2.23) in the thesis)

In [124]:
# Setting up data
Pred_data0_test = X_test_dat[['Prob_land_state_1','Prob_land_state_2','Prob_land_state_3','Observed_state']]

# Comupting the discrepancy scores for D&C 
adjusted = Pred_data0_test.iloc[:, :-1].to_numpy() - best_thresholds_DC

# Predicting next landing state
pred_states_test_set = np.argmax(adjusted, axis=1) + 1


#-------------- Measuring overall accuracy of predictions (i.e. to all states)

# Adding the predicted state as column to the test set
Pred_data0_test['Predicted_state'] = pred_states_test_set

# Measuring the accuracy of predictions
print('Overall accuracy of prediction to next state on test set using D&C is:',
      np.round(100*(Pred_data0_test['Observed_state']==Pred_data0_test['Predicted_state']).mean(),3),'%')
print('\n')

#-------------- Measuring accuracyof predictions to state 1

# Selecting rows event where the observed state is 1
tp_Pred_data0_test = Pred_data0_test[Pred_data0_test['Observed_state']==1] 

print('Accuracy of prediction to state 1 on test set using  D&C is:',
      np.round(100*(tp_Pred_data0_test['Observed_state']==tp_Pred_data0_test['Predicted_state']).mean(),3),'%')
print('\n')

#-------------- Measuring accuracyof predictions to state 2

# Selecting rows event where the observed state is 2
tp_Pred_data0_test = Pred_data0_test[Pred_data0_test['Observed_state']==2] 

print('Accuracy of prediction to state 2 on test set using D&C is:',
      np.round(100*(tp_Pred_data0_test['Observed_state']==tp_Pred_data0_test['Predicted_state']).mean(),3),'%')
print('\n')

#-------------- Measuring accuracyof predictions to state 3

# Selecting rows event where the observed state is 3
tp_Pred_data0_test = Pred_data0_test[Pred_data0_test['Observed_state']==3] 

print('Accuracy of prediction to state 3 on test set is:',
      np.round(100*(tp_Pred_data0_test['Observed_state']==tp_Pred_data0_test['Predicted_state']).mean(),3),'%')

Overall accuracy of prediction to next state on test set using D&C is: 87.828 %


Accuracy of prediction to state 1 on test set using  D&C is: 84.179 %


Accuracy of prediction to state 2 on test set using D&C is: 93.822 %


Accuracy of prediction to state 3 on test set is: 0.0 %

/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/1235245185.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Pred_data0_test['Predicted_state'] = pred_states_test_set

### 4.3. Working example for multistate classification using our approach (OMCC)

**We now estimate the optimal thresholds using the multistate classification approach we proposed in the thesis (i.e. the OMCC)**

In [116]:
# Selecting relevant columns
Pred_data0_train = X_train_dat[['Prob_land_state_1','Prob_land_state_2','Prob_land_state_3','Observed_state']]


# Running optimisation
result_train = differential_evolution(
    vectorized_discrepancy_model_MCC, # Put the selected multiclass approach (function) here
    bounds=[(0,1)]*3,# to make sure the optimal threshold remain within (0,1)
    args=(Pred_data0_train,),# Input money
    maxiter=500, popsize=15, polish=True, seed=42, disp = True
)

best_OMCC = -result_train.fun
best_thresholds_OMCC = result_train.x

differential_evolution step 1: f(x)= -0.7061168270542098
differential_evolution step 2: f(x)= -0.7061168270542098
differential_evolution step 3: f(x)= -0.7061168270542098
differential_evolution step 4: f(x)= -0.7062384440472144
Polishing solution with 'L-BFGS-B'

In [117]:
print('MCC **SCORE** on the training set is:', np.round(100*best_OMCC,3),'%.')

MCC **SCORE** on the training set is: 70.624 %.

In [118]:
print('The optimal vector of thresholds is: on the training set is:', best_thresholds_OMCC)

The optimal vector of thresholds is: on the training set is: [0.18376418 0.56258003 0.32031983]

In [120]:
# Setting up data
Pred_data0_test = X_test_dat[['Prob_land_state_1','Prob_land_state_2','Prob_land_state_3','Observed_state']]

# Comupting the discrepancy scores for D&C 
adjusted = Pred_data0_test.iloc[:, :-1].to_numpy() - best_thresholds_OMCC

# Predicting next landing state
pred_states_test_set = np.argmax(adjusted, axis=1) + 1


#-------------- Measuring overall accuracy of predictions (i.e. to all states)

# Adding the predicted state as column to the test set
Pred_data0_test['Predicted_state'] = pred_states_test_set

# Measuring the accuracy of predictions
print('Overall accuracy of prediction to next state on test set using the OMCC is:',
      np.round(100*(Pred_data0_test['Observed_state']==Pred_data0_test['Predicted_state']).mean(),3),'%')
print('\n')

#-------------- Measuring accuracyof predictions to state 1

# Selecting rows event where the observed state is 1
tp_Pred_data0_test = Pred_data0_test[Pred_data0_test['Observed_state']==1] 

print('Accuracy of prediction to state 1 on test set using the OMCC  is:',
      np.round(100*(tp_Pred_data0_test['Observed_state']==tp_Pred_data0_test['Predicted_state']).mean(),3),'%')
print('\n')

#-------------- Measuring accuracyof predictions to state 2

# Selecting rows event where the observed state is 2
tp_Pred_data0_test = Pred_data0_test[Pred_data0_test['Observed_state']==2] 

print('Accuracy of prediction to state 2 on test set using the OMCC  is:',
      np.round(100*(tp_Pred_data0_test['Observed_state']==tp_Pred_data0_test['Predicted_state']).mean(),3),'%')
print('\n')

#-------------- Measuring accuracyof predictions to state 3

# Selecting rows event where the observed state is 3
tp_Pred_data0_test = Pred_data0_test[Pred_data0_test['Observed_state']==3] 

print('Accuracy of prediction to state 3 on test set using the OMCC is:',
      np.round(100*(tp_Pred_data0_test['Observed_state']==tp_Pred_data0_test['Predicted_state']).mean(),3),'%')

Overall accuracy of prediction to next state on test set using the OMCC is: 87.171 %


Accuracy of prediction to state 1 on test set using the OMCC  is: 87.017 %


Accuracy of prediction to state 2 on test set using the OMCC  is: 92.003 %


Accuracy of prediction to state 3 on test set using the OMCC is: 0.0 %

/var/folders/2w/qgtm8nnx5k992f8ws4bm58940000gn/T/ipykernel_80792/1813275817.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Pred_data0_test['Predicted_state'] = pred_states_test_set